### ISSUE TITLE
Sharing lyrics with chords (multiline monospaced messages) in the Chat

### ISSUE THREAD

**Issue by passing** [jamulussoftware/jamulus#1020]
**Problem**

The chat only allows for single text lines to be sent. Being able to paste multi-line text would allow for sharing lyrics with chords that you have stored on your computer. You could make them directly available to everybody in the current session without having to upload them somewhere.

**Describe the solution you'd like**

The chat window could have a button somewhere that switches to 'multi-line' mode. In that mode, the input box would need to turn into a multi-line box. Text written in that box should have monospaced font and the message should also be displayed that way after it got sent

Technically, I could imaging that any message with newlines (`\n`) could just be treated that way on the clients receiving it.

**Describe alternatives you've considered**

The multi-line mode could also open another window in case the single-line input box cannot be replaced with a multi-line input.

**Additional context**

Sharing multi-line / monospaced content was possible before #939, which lets the server escape html in chat messages.
But making use of that also required some way of creating html with specific tags as mentioned here: https://github.com/jamulussoftware/jamulus/issues/890#issuecomment-771754260

**Comment by gilgongo** [comment]
Great idea! 

I think it may need some discussion to firm up I think though before we add it to the backlog, so I'm migrating this to a Discussion if that's OK.
