### ISSUE TITLE
Translation typos

### ISSUE THREAD

**Issue by kwetal** [jamulussoftware/jamulus#1069]
**Describe the bug**
The Dutch translation of Jamulus has some typos.

**To Reproduce**
- `Welkomsbericht` in 2 places must be `Welkomstbericht`
- `Vaardigheidssniveau` must be `Vaardigheidsniveau`

**Operating system**
all

**Version of Jamulus**
Jamulus, Version 3.6.2dev-373e1f48

**Additional context**
N/A

**Comment by pgScorpio** [comment]
There are a lot of missing or wrong translations in the Dutch language:

"Custom" translated as "Aangepast" in serverlist and as "Eigen" on the settings page, (Very confusing for many users!)
"Connect" not translated on the main screen, but is translated "Verbinden" on the connections page.
"Settings" not translated in menu, but is translated "Instellingen" on the main page.
"Exit" not translated in menu.
"Audio Stream Rate" not translated on the settings page.
"Pan" not translated on the main page.

**Comment by jerogee** [comment]
@pgScorpio, thanks! I will include your suggestions and corrections in the upcoming release. I am only not sure about "Pan". I believe it is quite common in Dutch audio context and there is little space for the word on the main window. Do you have anything in mind?

**Comment by pgScorpio** [comment]
Pan is normally called "Balans" in dutch. (Abbreviated "Bal.")
Exit (program) is (Programma) "Afsluiten" en Audio Stream Rate is "Audio bitstream snelheid" (Strange mix of dutch and english)

**Comment by kwetal** [comment]
A possible Dutch translation for "pan" might be "balans".

**Comment by jerogee** [comment]
@pgScorpio, @kwetal, thanks. "Balans" it is!
