### ISSUE TITLE
UI: Server recording highlight isn't always properly cleared

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1089]
**Describe the bug**
The "enhanced" server recording highlight isn't always properly cleared.

**To Reproduce**
1. Connect to a server with recording enabled an a licence agreement request prompt (e.g. Any Genre 2 / jamulus.drealm.info).
2. Decline the licence.

**Expected behavior**
3. Window returns to pre-connect

**Screenshots**
Client main window before connecting
![image](https://user-images.githubusercontent.com/1549463/108609392-7e523380-73c5-11eb-9589-6d85adb2a577.png)
Client main window on connection, whilst waiting for agreement
![image](https://user-images.githubusercontent.com/1549463/108609324-1865ac00-73c5-11eb-9d1e-5530506f8d68.png)
Waiting for agreement
![image](https://user-images.githubusercontent.com/1549463/108609355-33382080-73c5-11eb-96b1-7db68276f7fd.png)
Client main window after declining
![image](https://user-images.githubusercontent.com/1549463/108609372-5793fd00-73c5-11eb-9c03-f29288d4c1c2.png)

**Operating system**
![image](https://user-images.githubusercontent.com/1549463/108609210-6a5a0200-73c4-11eb-953c-160a7890c52a.png)
**Version of Jamulus**
![image](https://user-images.githubusercontent.com/1549463/108609227-8eb5de80-73c4-11eb-96a2-c3b861662c91.png)

**Additional context**

*(Initial issue by @pljones, I just split it from https://github.com/jamulussoftware/jamulus/issues/1076)*

**Comment by hoffie** [comment]
@dcorson-ticino-com You worked on that feature in #968, could you have a look here as well and assign this to yourself if you are working on it? Thanks!

**Comment by dcorson-ticino-com** [comment]
Will do!

**Comment by pljones** [comment]
Yeah, Github doesn't seem to like people assigning themselves to things unless they're running the project, I think - we're still learning the ropes :).

**Comment by pljones** [comment]
As a hint - I think you need to do all of the work in ` CAudioMixerBoard::UpdateTitle()` for the recording indicator.  It took me a while to get it updating correctly.  So by default clear the style.  Then set the style in the same if-block as the indicator.

**Comment by dcorson-ticino-com** [comment]
As my Qt and C++ programming skills are improving I guess that might be the better way.
I did it as I did because I wanted to set the style there where the current style is known.
I'll take another look tomorrow.
D

**Comment by pljones** [comment]
Qt takes a fair bit of getting used to - the signals and slots stuff is a bit weird.  Fortunately, I'd just played with UI development in Scala before getting into Jamulus coding and that had some vaguely similar concepts.

**Comment by softins** [comment]
Fixed in #1093
