### ISSUE TITLE
Wrong include file in /jamulus/src/util.h

### ISSUE THREAD

**Issue by DavidSavinkoff** [jamulussoftware/jamulus#1091]
**Describe the bug**

Note that these Windows(tm) #includes are used in /jamulus/src/util.h
There is a potential BUG in /jamulus/src/util.h according to the following information.

Within the /jamulus/src/util.h file:
'# include <ws2ipdef.h>'
Should be replaced with:
'# include <ws2tcpip.h>'

See these Remarks at the end of the web page:
"The Ws2def.h, Ws2ipdef.h, and Wsipv6ok.h header files should never be used directly."
[https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options](https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system** MSFT Windows

**Version of Jamulus**

**Additional context**

**Comment by ann0see** [comment]
Sorry for the late reply. We‘re currently quite busy with the release process. Do you think this is severe?

**Comment by DavidSavinkoff** [comment]
The bug can probably wait because it is not new. Probably low severity. I only have Linux computers so I cannot test any Windows code. I discovered the bug because I have been doing thorough Windows programming with my mind and a text editor.

**Comment by ann0see** [comment]
Ok. You could open a PR after this release is out and then we could discuss/test things there.

**Comment by DavidSavinkoff** [comment]
> Ok. You could open a PR after this release is out and then we could discuss/test things there.

I will do that.

**Comment by ann0see** [comment]
Great!

**Comment by DavidSavinkoff** [comment]
See PR #1145

**Comment by softins** [comment]
Fixed in #1310
