### ISSUE TITLE
Translations: Use substitutions instead of concatenations

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1114]
**Describe the improvement**

Some strings currently use concatenations. Example: https://github.com/jamulussoftware/jamulus/blob/41be42dc72273304afa0086156fae67af6fd0979/src/clientsettingsdlg.cpp#L183

**To Reproduce**

Could probably use something like `grep -Po 'tr\s*\(.*\).*\+.*' src/*` to find other places (this will still yield false positives such as HTML concatenation, which should be OK I think).

**Expected behavior**

This was suggested by @pljones in https://github.com/jamulussoftware/jamulus/pull/1097#discussion_r581275143:
> Would it not be easier for a translator to have the full text with substitutions (so, `QString ( tr ( "Hello, %1" ) ).arg( getName() )...`, giving the context)?  Here there are three pieces, one starting with a measurement unit.

**Additional context**
Must only be changed after 3.7.0 is completed.

**Comment by hoffie** [comment]
Hmm, even HTML concatenations may lead to inconsistent spacing: https://github.com/jamulussoftware/jamulus/blob/master/src/clientsettingsdlg.cpp#L223

In this case, it's a double space and will most like not matter in practice as I assume it will be condensed to one as it would be in ordinary HTML. But still...

**Comment by pljones** [comment]
Which would have to become something like...
```
QString ( tr ( "%1Enabling %2Stereo%3 mode%4" ) ).arg ( "<li>" ).arg ( "<b>" ).arg ( "</b>" ).arg ( "</li>" );
```
... I think...  And the the translator sees `"%1Enabling %2Stereo%3 mode%4"` without the args... does that help?  Hm.

**Comment by hoffie** [comment]
> And the the translator sees `"%1Enabling %2Stereo%3 mode%4"` without the args... does that help? Hm.

I don't think so. :(

> Would providing `tr( "Enabling <b>Stereo</b> mode" )` be easier? If more complex translations (this seems like it's not one...) are needed, then having the flexibility to adjust where the formatting occurs might be useful.

As long as we stick to simple HTML (I guess bold formatting and line breaks are the most common reason for using it?), this would be way more readable (although we would have to check translation PRs thoroughly for them not to break HTML).

> But does the XML support embedded HTML?

Don't know / haven't tried.

I'm not currently working on this and I'm therefore removing myself as the assignee.

**Comment by ann0see** [comment]
@BLumia since you we’re the last person doing a full translation of the software. How many places do need to be updated in order not to have split out tr()?

I think this issue should also be documented in the style guide in CONTRIBUTING.md

**Comment by pljones** [comment]
> I think this issue should also be documented in the style guide in CONTRIBUTING.md

I think _that_ is probably the best idea in this issue :).

**Comment by BLumia** [comment]
> this will still yield false positives such as HTML concatenation, which should be OK I think

https://github.com/jamulussoftware/jamulus/blob/41be42dc72273304afa0086156fae67af6fd0979/src/clientsettingsdlg.cpp#L223

This should also be avoided. If using HTML markup is a must, just also include HTML tags in the source strings. Letting translators see these markup tags is not a bad thing.

e.g. `tr("Enabling <b>Stereo</b> mode")` is better than `tr("Enabling %1 mode").args("<b>"+tr("Stereo")+"</b>")` IMO. Translator will know the word Stereo is emphasized and all they need to know is keep the HTML tag in their translated string. Programmer also won't need to write a lot of `args()` only because of there are HTML tags in the source string.

> How many places do need to be updated in order not to have split out tr()?

I already updated those I can find that have this issue, there might still be some strings that need to be corrected but I'm not sure about the amount.

> I think this issue should also be documented in the style guide in CONTRIBUTING.md

Totally agree since there are some strings with this issue introduced in new commits, contributors should be aware this can be an issue when they want to add new strings to the program.

**Comment by BLumia** [comment]
Additionally, if the place we need to display rich text is a QLabel or QMessageBox, and we are on Qt version >= 5.14, we can also use markdown :)

``` cpp
QLabel* label = new QLabel("test *markdown*");
label->setTextFormat(Qt::MarkdownText);
label->show();
```

![image](https://user-images.githubusercontent.com/10095765/155830040-3bc164ed-66f7-4464-996b-1dd1984ea318.png)

**Comment by hoffie** [comment]
> Additionally, if the place we need to display rich text is a QLabel or QMessageBox, and we are on Qt version >= 5.14, we can also use markdown :)

That's certainly good to know. Currently we still support older Qt versions though.

**Comment by softins** [comment]
> > this will still yield false positives such as HTML concatenation, which should be OK I think
> 
> https://github.com/jamulussoftware/jamulus/blob/41be42dc72273304afa0086156fae67af6fd0979/src/clientsettingsdlg.cpp#L223
> 
> This should also be avoided. If using HTML markup is a must, just also include HTML tags in the source strings. Letting translators see these markup tags is not a bad thing.
> 
> e.g. `tr("Enabling <b>Stereo</b> mode")` is better than `tr("Enabling %1 mode").args("<b>"+tr("Stereo")+"</b>")` IMO. Translator will know the word Stereo is emphasized and all they need to know is keep the HTML tag in their translated string. Programmer also won't need to write a lot of `args()` only because of there are HTML tags in the source string.

Yes, agree 100%, and Qt Linguist fully supports this too. It recognises and highlights embedded HTML:

![image](https://user-images.githubusercontent.com/3224952/156030897-87d46414-1ae8-48f0-bdd0-dd7d4d931a45.png)

Although it doesn't appear to warn the user if the translated string differs in the HTML markup.

It might be quite an undertaking to change this project-wide though (although probably worthwhile). It would need to be done while other activity is fairly quiet and then included without delay, or rebasing could be very arduous!

**Comment by pljones** [comment]
> Although it doesn't appear to warn the user if the translated string differs in the HTML markup.

That's not necessarily bad -- if, say, there was a German translation of the qJackCtl documentation, changing the `href` of the link might be appropriate.

**Comment by ann0see** [comment]
Ok: See https://github.com/jamulussoftware/jamulus/pull/2561 which added a style note related to this issue.

**Comment by ann0see** [comment]
Since I think we have it documented, can we close this? I think 

> Could probably use something like grep -Po 'tr\s*\(.*\).*\+.*' src/* to find other places (this will still yield false positives such as HTML concatenation, which should be OK I think).

Could be run by someone.

**Comment by ann0see** [comment]
Files to be checked:
- [ ] Audiomixerboard.cpp: Personal Mix at:
- [ ] clientsettingsdlg: L - x (investigate)
- [ ] util.cpp Version: 
- [ ] sound/asio/sound.cpp No ASIO audio device driver found (investigate)
