### ISSUE TITLE
Windows installer considered threat by windows defender

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulus#1129]
**Describe the bug**
Currently windows installers are considered a severe thread  "Trojan:Script/Wacatac.B!ml" by windows defencer.

**To Reproduce**
Download windows installer and perform scan (or try to unzip), e.g.
https://github.com/jamulussoftware/jamulus/actions/runs/603986607
https://github.com/jamulussoftware/jamulus/actions/runs/603958205

**Expected behavior**
considered no thread by scan

**Operating system**
Windows 10 Pro
1909
18363.1379

**Version of Jamulus**
artifact from build run

**Comment by nefarius2001** [comment]
> annosee: Yes, I could download and install it. Not sure what this warning you got means? Is it SmartScreen?

Its called "windows defender scan" in my dialogs, but seems to be the same on first glance

**Comment by npostavs** [comment]
I only got the usual Smart Screen thing, which you can go past by clicking "More info" and then "Run anyway". I might have Windows Defender turned lower so that it doesn't get to scan as much, but even when I click "Scan with Microsoft Defenders..." from the right click menu on the zip file it says it finds 0 threats.

Windows 10 Home
Version	20H2
OS build	19042.804

![smart-screen](https://user-images.githubusercontent.com/287742/109387020-a7def380-78cc-11eb-8de9-0bc4abb89dd4.png)

**Comment by nefarius2001** [comment]
![grafik](https://user-images.githubusercontent.com/6545169/109388456-6fa8d680-7907-11eb-9255-1b4f9fb9c4e4.png)

![grafik](https://user-images.githubusercontent.com/6545169/109388468-8a7b4b00-7907-11eb-836c-4c8bc6b12889.png)

![grafik](https://user-images.githubusercontent.com/6545169/109388489-a8e14680-7907-11eb-9e18-9f3bfdf90dd1.png)

**Comment by nefarius2001** [comment]
when I download artifacts, they are *.zip files. Is that the same for you?

**Comment by hoffie** [comment]
> when I download artifacts, they are *.zip files. Is that the same for you?

Should be the same for everyone.

Virustotal lists the [zip file](https://www.virustotal.com/gui/file/53c20faa52fc0c93d8aae8d0c5542cfc9e1a9c03b5f390d6db7b31216054d8c2/detection) as clean by all scanners. I assume that the zip file is extracted by the scanners, but I'm running another test with the exe just now.

**Comment by npostavs** [comment]
I had downloaded aea92e0 before, but `jamulus_3.6.2dev-f9b8973_win.exe.zip` also shows 0 threats with Windows Defender here.

**Comment by hoffie** [comment]
@nefarius2001 Can you share checksums of the zip or exe?

```
427ba9ff40c506995541bf7738b414f2  jamulus_3.6.2dev-aea92e0_win.exe.zip
404848f1dfdc066361b5e8b0ab876c8f  jamulus_3.6.2dev-aea92e0_win.exe
```

**Comment by hoffie** [comment]
@nefarius2001 As we are heading towards a final beta release, it would be cool if you could verify the checksums in order to find out if this is a blocker for a final release or not. I'm adding this issue to the 3.7.0 milestone until we can confirm that it is *not* a blocker.

**Comment by ann0see** [comment]
Tested the windows rc asset and it seems to be ok. So I'll close this
