### ISSUE TITLE
Why is "Mute Myself" still sending data?

### ISSUE THREAD

**Issue by 38github** [jamulussoftware/jamulus#1156]
I would just like to ask why "mute myself" is sending full stream data to the server? Is it possible to minimize this? Would this be possible with variable bitrate or is opus lack of "quality setting" making this problematic? With quality setting I am refering to how ogg vorbis' -q and LAME's -V commands do not try to follow a defined bitrate but instead quality.

**Comment by 38github** [comment]
I am sorry for posting this in Issues. Please move this thread to Discussion, please.

**Comment by dcorson-ticino-com** [comment]
With mute myself all the others can't hear you, but you can hear yourself, through the server.
This is so you can test the quality of the sound channel, do setup, tuning, without disturbing others.

**Comment by 38github** [comment]
> With mute myself all the others can't hear you, but you can hear yourself, through the server.
> This is so you can test the quality of the sound channel, do setup, tuning, without disturbing others.

I know but why does Jamulus use network bandwidth when the sound is local?

**Comment by 38github** [comment]
> through the server.

Oh, so the sound is actually sent to the server. But is it really? That would mean that I would get the same latency using Mute Myself as I do when I am not and that is not the case. Isn't it a waste of bandwidth to send ~900kbps to the server even though I don't want to transmit anything to anyone?

**Comment by chrisrimple** [comment]
@38github there are many good reasons to listen to the sound from the server rather than local sound when muted. The most important is to be able to hear what others are hearing from you, via the server, while not simultaneously interrupting the other musicians on the server. And yes, you will get the same latency when muted - you can test this by connecting to a server with a very high ping and then muting yourself.

**Comment by 38github** [comment]
Either I am not explaining myself well or you are missing something. When I have Mute Myself the sound can not possibly be sent to the server and back. I have connected to a server half way around the globe and with Mute Myself unchecked I get at least 250ms delay. With Mute Myself the sound is immediate. Therefore the sound can not be sent to the server and back. Therefore, why is ~900kbps still being sent to the server?

**Comment by ann0see** [comment]
> but you can hear yourself, through the server.

As far as I know, that's **not** true. Jamulus just sends silence to stay connected to the server.
