### ISSUE TITLE
Check for duplicated accelerator keys in translations

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#1161]
Just making sure this activity is tracked for the release. I'm on the case.

**Comment by softins** [comment]
Quite a few conflicts to resolve: https://gist.github.com/softins/d0587ae7e1ea44e9e0eeb352bc0eb8a0

**Comment by softins** [comment]
I'll leave this open for now as a reminder to revisit it when we receive pt_PT and sk_SK translations.

**Comment by Snayler** [comment]
> I'll leave this open for now as a reminder to revisit it when we receive pt_PT and sk_SK translations.

Did you mean pt_BR? I checked all the duplicates on pt_PT and they don't seem to interfere with each other, as they don't overlap in the different menus or on the main window.

**Comment by Snayler** [comment]
> I'll leave this open for now as a reminder to revisit it when we receive pt_PT and sk_SK translations.

Just created a pull request with the updated translation. I'm using a notebook where I'm writting all the accelerator keys I'm using to make sure they don't overlap on the same menu or in the main window, so there should be no problems there.

**Comment by softins** [comment]
pt_PT checked and merged. Thank you very much @Snayler!

**Comment by hoffie** [comment]
@softins Would that script be something for the `tools/` folder?

**Comment by softins** [comment]
Certainly, if it would be useful. It is not automated, it just lists potential clashes for human checking. It isn't possible, for example to distinguish between the same character used in entries down different menus.

**Comment by softins** [comment]
Now that we have no more translation needed for 3.7.0, I'll move this issue to 3.7.1 as a reminder for the next release.

**Comment by hoffie** [comment]
A checklist item for doing this check for each release has now been added to #1594. The 3.8.0 preparation Issue (#1595) has been updated as well. So this ticket could be closed?

**Comment by ann0see** [comment]
Closing since it's part of the preparation issue.
