### ISSUE TITLE
Server rejects connections if the recording location is full

### ISSUE THREAD

**Issue by genesisproject2020** [jamulussoftware/jamulus#1163]
Bug:
If recording is enabled and the storage location for the recordings is full or for some other reason not able to store the recordings at the location provided the server will reject or just not create a connection to a connecting client. 

Replicate:
Start a server with recording enabled and point the storage location to a place where there is no space available.

Expected:
A connection is made but an information message saying that the storage of recordings not possible.

Environment:
Ubuntu 20.04 LTS
Jamulus Version 3.6.2dev-86143479
A separate hard drive for recordings.

**Comment by ann0see** [comment]
Not sure if detecting a full hdd is easy. I remember that Peter wrote in another ticket that detecting a full disk is not easy to implement. 

I think the server even crashes?

**Comment by drummer1154** [comment]
See #1289

**Comment by hoffie** [comment]
@genesisproject2020 Can you please also test if #1463 fixes this issue?

**Comment by hoffie** [comment]
@genesisproject2020 #1463 has been merged now which should make error handling more user-friendly. It does not change pre-checks on start up though. If you still think something should be changed, please reopen. :)
