### ISSUE TITLE
Do not show IP on the mixing board of a private server

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1164]
For a private server, the (WAN) IP address of that server is displayed (twice) at every client Jamulus screen. If one is making e.g. screenshots for educational purposes etc, or just to advertise how great Jamulus is on e.g. social media, they are exposing this IP number in public!  Why not displaying the _name_ as provided via the _-o_ (--serverinfo) command line parameter?

_Originally posted by @DemiWork in https://github.com/jamulussoftware/jamulus/discussions/916#discussioncomment-421647_

**Comment by ann0see** [comment]
>  Why not displaying the name as provided via the -o (--serverinfo) command line parameter?

This doesn't necessarily have to be set, on a private server, I think.

**Comment by hoffie** [comment]
> > Why not displaying the name as provided via the -o (--serverinfo) command line parameter?
> 
> This doesn't necessarily have to be set, on a private server, I think.

As far as I can see, there is no serverinfo at all for standalone servers. This is solely used for server list entries when registering at a dictionary server.

As to the issue in general: I understand that this can be a problem in some environments, especially considering that Jamulus does not have any other way of access control. If we just removed the IP address, we should consider if this breaks someone's use case. There have been discussions about window titles before (#789), although related to `clientname`.

**Comment by DemiWork** [comment]
Indeed currently the _-o_ option is not executed when applying private server mode.  Instead, the WAN IP address is displayed. But why not displaying a _server name_ if one explicitly is using the _-o_ parameter? And let the server default displaying the WAN IP if no _-o_ is provided upon starting a private server to remain backwards compatibility with existing use cases? (although still I feel we should avoid displaying a WAN IP as much as we can, just to reduce chances of misuse!)..

**Comment by ann0see** [comment]
What about just showing "Server" as server name and if somebody hovers over it, we show the IP?

**Comment by hoffie** [comment]
> But why not displaying a server name if one explicitly is using the -o parameter?

If you are referring to a standalone server's UI, then we could do that, yep.
However, I suspect that you are rather talking about clients which are connected to such a server. Can you confirm?
In the latter case, the servername is simply not available to the client because it is not part of any protocol message between server and client. This could be added, of course, but we should be sure it's worth it. Maybe a client-only solution (e.g. what @ann0see suggested) may be easier. :)

**Comment by DemiWork** [comment]
Confirmed: The issue relates the Clients. These are displaying the WAN IP of a private server upon connecting. IMHO the solution @ann0see is proposing, at least prevents displaying the WAN IP during regular usage (but existing uses cases should be evaluated still. It's about trade-off of a potential vulnerability by exposing accidentally the WAN IP of the operator of the private server).

**Comment by softins** [comment]
This doesn't srike me as a problem. The IP address of the connected private server is known to the person running the client.

If someone wants to take screenshots for documentation, it is their responsibility to blur or mask the IP address in the same way as they would need to do with any other personal information on example forms in any application, not just Jamulus.

**Comment by dakhubgit** [comment]
Well, for creating educational videos, it's often feasible to have `localhost` as a server name.  Other options probably are putting a fantasy name into `/etc/hosts` or wherever you can shortcircuit name resolution.

What I'd consider useful is to replace the server name with "default" as long as it corresponds to that given with a `-c` command option.  That way you'd have an easy way to omit it without relevant information loss, though one would want to do the same in the Connect dialog preset.

**Comment by gilgongo** [comment]
As per https://github.com/jamulussoftware/jamulus/issues/1164#issuecomment-792378751 - closing.
