### ISSUE TITLE
Android - "Back" Gesture not recognised in Chat and Settings

### ISSUE THREAD

**Issue by Andrew999999** [jamulussoftware/jamulus#1172]
**Describe the bug**

For a device that uses gesture control (no traditional home/back/menu buttons) the gesture for "back" is not recognised when the Settings or Chat windows are active.  Furthermore there is no close or cancel button visible, so there is no way to return to the main Jamulus window.

**To Reproduce**

Launch jamulus.  Click on Settings or Chat.

**Expected behavior**

The Settings or Chat window would close, returning the user to the main Jamulus window.

**Screenshots**

**Operating system**

Android 10.

**Version of Jamulus**

r3_7_0beta3/jamulus_3.6.2dev-6e630f4

**Additional context**

Only affects phones/tablets with gesture navigation.  Does not appear where traditional Android navigation buttons are enabled.

**Comment by ann0see** [comment]
I could reproduce this issue. Somebody knowing Android should have a look at this.

**Comment by lebaston100** [comment]
Can reproduce too.
Device: Xiaomi Redmi Note 8T

**Comment by pljones** [comment]
Each window currently acts like a new application, which could have something to do with it.  If you open Firefox from Whatsapp, for example, back wouldn't take you from Firefox to Whatsapp.  And that's what's happening here, I think.

**Comment by ann0see** [comment]
@Andrew999999 @lebaston100: @ngocdh worked on some improvements. Does this still occur on Jamulus 3.8.2? If not, please close this issue.

Note: I will unsubscribe from this issue and won’t receive responses from any new comments. If you have any questions concerning maintenance, feel free to ping me.

**Comment by Andrew999999** [comment]
Fixed in 3.8.2
