### ISSUE TITLE
Packages not installable on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1175]
**Describe the bug**

Release packages (e.g. betas and final releases) do not install on Ubuntu 18.04 LTS.
*Spotted by @softins' quality testing :)*

**To Reproduce**

`dpkg -i jamulus*.deb && systemctl start jamulus-headless`

**Expected behavior**

Clean install.

**Screenshots**

```
Mar 05 12:47:28 ubuntu18 jamulus[19877]: /usr/bin/jamulus-headless: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/jamulus-headless)
Mar 05 12:47:28 ubuntu18 jamulus[19877]: /usr/bin/jamulus-headless: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/bin/jamulus-headless)
Mar 05 12:47:28 ubuntu18 systemd[1]: jamulus-headless.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 12:47:28 ubuntu18 systemd[1]: jamulus-headless.service: Failed with result 'exit-code'.
```

**Operating system**

Ubuntu 18.04 LTS

**Version of Jamulus**

Jamulus 3.7.0beta3

It is known that we need to build on Ubuntu 18.04 to be compatible with this release. This was fixed in #1100. ~~However, this only [fixed it](https://github.com/jamulussoftware/jamulus/blob/master/.github/workflows/autobuild.yml#L105) for CI assets (e.g. PRs), but [not for releases](https://github.com/jamulussoftware/jamulus/blob/master/.github/workflows/autobuild.yml#L38).~~

~~I'll send a PR shortly.~~

**Comment by softins** [comment]
For clarity, `dpkg -i` gives no errors. The step that doesn't work is `systemctl start jamulus-headless`.

**Comment by hoffie** [comment]
My initial analysis is wrong. #1100 was correct. PR assets and release assets are built by the same autobuild logic (which is good!). The place I found was about the Github release publishing step, which runs on ubuntu-20.04 and which should be totally fine.

The reason for @softins's test failure is most likely that beta3 was created 14 days ago, while #1100 was only merged 10 days ago, so it was simply not included.

Sorry for the noise, nothing to see here. :)
