### ISSUE TITLE
A message to switch to the new used DNS entries for central servers

### ISSUE THREAD

**Issue by genesisproject2020** [jamulussoftware/jamulus#1185]
Now when the new DNS entries for the central servers are implemented it would be good to present a message when starting the server with an old DNS entry.

Any Genre 1: anygenre1.jamulus.io:22124 old jamulus.fischvolk.de:22124
Any Genre 2: anygenre2.jamulus.io:22224 old jamulusallgenres.fischvolk.de:22224
Genre Rock: rock.jamulus.io:22424 old jamulusrock.fischvolk.de:22424
Genre Jazz: jazz.jamulus.io:22324 old jamulusjazz.fischvolk.de:22324
Genre Classical/Folk: classical.jamulus.io:22524 old jamulusclassical.fischvolk.de:22524
Genre Choral/Barbershop: choral.jamulus.io:22724 old jamuluschoral.fischvolk.de:22724

(The reference at https://jamulus.io/wiki/Central-Servers should be updates as well.)

**Comment by genesisproject2020** [comment]
Ref: https://github.com/jamulussoftware/jamulus/issues/919

**Comment by ann0see** [comment]
> (The reference at https://jamulus.io/wiki/Central-Servers should be updates as well.)

this should be part of the next documentation release

**Comment by gilgongo** [comment]
> this should be part of the next documentation release

It is.

**Comment by gene96817** [comment]
What will we recommend to groups with users with old client releases?
I am guessing that when I register my servers to a new genre (e.g. Choral/Barbershop) it will go invisible for users looking for servers as Classical/Choral/Barbershop.

**Comment by dcorson-ticino-com** [comment]
We had the same problem that last time new servers were added.
We had a lot of forum topics about people not finding servers.
The answer was to update.

**Comment by gene96817** [comment]
Should we make updating clients to be a key part of the next release? If so, we need to plan how we will message this. A lot of people choose to wait some weeks after a release before installing an update. We need to advise server owners about how to manage this transition.

**Comment by hoffie** [comment]
> Should we make updating clients to be a key part of the next release?

I think it would be a good idea to add an emphasis on this in the release announcement. I have added a reminder to our checklist in #1086.
Using one of the new lists would still be a deliberate¹ choice by the server operator, so at least in case of semi-private servers they can tell their users beforehand.

¹ Unless they are forced to because the older lists are full. But they'd be a problem right now as well.

**Comment by DavidSavinkoff** [comment]
> Should we make updating clients to be a key part of the next release?

What about the jamulus 3.6.2 debian package?
It must be maintained at version 3.6.2 for updates.
You don't want it to loose access to the servers.
See #896

**Comment by gene96817** [comment]
Perhaps this is a bad idea....
Is it possible to hack a pseudo server entry at the directory (example under Genre Classical/Folk) to say "some servers have been moved to Genre Choral/Barbershop". We need this where old genres have been redefined or split. In this way, users would have a clue that they need to update their client.

**Comment by gilgongo** [comment]
In the interests of keeping issues to actionable specs for work, moving to discussion.
