### ISSUE TITLE
Test 2 new - ignore

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#1192]
**Has this feature been discussed and generally agreed?**

**Describe the solution you'd like**

 

**Describe alternatives that have been considered**

**Comment by ann0see** [comment]
@gilgongo I think it would be better if   you did your tests on a forked/new repo (if that’s possible).  

(Create a new repo in the organisation and do your tests there).

Here it just causes noise ;-).

**Comment by gilgongo** [comment]
Sorry, it's because it needs org access so I can't just fork the repo (I've run tests on my own repos for that). If anyone knows how to use a PAT in an action that would be good.

**Comment by ann0see** [comment]
No problem. Can‘t you create a new repo in the organisation?

**Comment by gilgongo** [comment]
I can, but that wouldn't help I don't think because the Project is at Org level. I'd need to a create a whole new Org. Is that possible?

**Comment by ann0see** [comment]
You could create a new org, but I don’t think that’s needed. I‘m only a bit concerned about the issues/failed GH actions runs on this repo.

**Comment by gilgongo** [comment]
> a bit concerned about the issues/failed GH actions

That makes two of us :-)

I'm not sure how to test this then other than just wait for Issues and PRs to be raised. Might take a while...
