### ISSUE TITLE
Vertaling

### ISSUE THREAD

**Issue by nicowitteman** [jamulussoftware/jamulus#1207]
Fijn, zo'n Nederlandse versie!
Op het instellingenscherm lees ik onder onder geluidskaart "Invoerkanaal Mapping" en "Uitgangskanaal in kaart brengen". Dat is voor leken verwarrend. Beter zou het denk ik zijn om ze gelijk te trekken. En dan is "toewijzen" misschien een alternatief?

**Comment by ann0see** [comment]
Hi! I‘m not sure if I understand you correctly (I only speak German) but I think that you’re referring to a wrong translation? Not sure, but as far as I know this has been fixed and will be part of the next release.

**Comment by softins** [comment]
From Google Translate:
> Great, such a Dutch version! On the settings screen I read under sound card "Input channel Mapping" and "Output channel Mapping". That is confusing for laymen. I think it would be better to equalize them. And then "allocate" might be an alternative?

Question for @jerogee ?

**Comment by jerogee** [comment]
@nicowitteman, bedankt! Er zijn aardig wat verbeteringen gepland voor de komende release, dankzij jouw feedback en dat van anderen. Voor die release we het volgende staan:

```xml
        <source>Input Channel Mapping</source>
        <translation>Invoerkanaaltoewijzing</translation>
--
        <source>Output Channel Mapping</source>
        <translation>Uitvoerkanaaltoewijzing</translation>
```

Is dat duidelijker?

**Comment by nicowitteman** [comment]
Prima!

Hartelijke groet,
Nico Witteman

Van: Jeroen Geertzen
Verzonden: maandag 8 maart 2021 18:37
Aan: jamulussoftware/jamulus
CC: nicowitteman; Mention
Onderwerp: Re: [jamulussoftware/jamulus] Vertaling (#1207)

@nicowitteman, bedankt! Er zijn aardig wat verbeteringen gepland voor de komende release, dankzij jouw feedback en dat van anderen. Voor die release we het volgende staan:
        <source>Input Channel Mapping</source>
        <translation>Invoerkanaaltoewijzing</translation>
--
        <source>Output Channel Mapping</source>
        <translation>Uitvoerkanaaltoewijzing</translation>
Is dat duidelijker?

**Comment by jerogee** [comment]
Great. @ann0see , @softins, Nico agrees with the translation we already have ready for 3.7.0.

**Comment by ann0see** [comment]
Great.

**Comment by ann0see** [comment]
Can we close this then?

**Comment by jerogee** [comment]
Yes, please do. Cannot do that myself.

**Comment by ann0see** [comment]
Ok. I'll close this
