### ISSUE TITLE
Switching between skins causes mixing board to stay white

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1238]
Seems as if I can trace down a bug to https://github.com/jamulussoftware/jamulus/commit/f5a58a0d2db7f38d8f6cdc5243b276062c9b2b8b

On Linux: Debian 10 Gnome after this commit the mixing board seems not to change back to fancy, normal, compact mode if I switch it during runtime.

See
https://github.com/jamulussoftware/jamulus/discussions/1217#discussioncomment-464967

Steps to reproduce:

Now I could reproduce it like that:

1. Start Jamulus with fancy mode enabled
1. Switch to normal mode while settings is open
1. Switch back to fancy mode (maybe you'll need to switch back and forth between the different modes).

Note: I'm not connected to a server.

I seen the only one who can reproduce this bug

**Comment by hoffie** [comment]
As I cannot reproduce, I sadly think it would be up to you to try to find the exact cause. I would suggest starting to comment out code and trying if the problem goes away.

I guess this line could be a starting point:
https://github.com/jamulussoftware/jamulus/commit/f5a58a0d2db7f38d8f6cdc5243b276062c9b2b8b#diff-e66f0278a23ad2aef9ee2d631e022364d2d6e27a1c756e79c79e9b332b3b3034R1370

**Comment by ann0see** [comment]
Probably true.

**Comment by ann0see** [comment]
@dcorson-ticino-com how important is this feature? Maybe we should revert the related commits, publish the release and in the meantime I do some further investigation?

**Comment by ann0see** [comment]
See: https://user-images.githubusercontent.com/20726856/111026110-dee2f800-83e8-11eb-9a0d-f7c7202c93f2.MOV

**Comment by dcorson-ticino-com** [comment]
Hi Ann0see,
I had some time to look at the code this morning.  I do not see anything that I would suspect causing the bad display, but I do see that both solutions to the recording indication are in the code.  This is redundant.
Please try putting a return as the first line of the SetMixerBoardDeco routine so that it does nothing and then check that the red recording indication still works and if, maybe, that causes the other problem to go away.
If that helps I will make a new PR to remove the routine and associated variables.

**Comment by ann0see** [comment]
Ok. Just commented added a return statement there with these results:

1. Not connected: UI changes as expected
2. Recording disabled: UI changes as expected
3. Recording enabled (and in compact skin; switching to fancy): Bug is reproducible; there are also glitches if you start in fancy skin and switch back to compact: The Group/Mute/... buttons stay fancy
4. If I enable recording during connection the red indicator seems to work; If the glitch occurs, it can be reset by disabling recording (probably you reset the mixer then)

I assume it is related to a missing reset in the mixer board somewhere.

**Comment by dcorson-ticino-com** [comment]
Good, it looks like the windows manager of your Linux is not correctly resetting the style sheet to that inherited from the class above.
Please try this new test:
..Take out the return you just added in clientdlg line 1411 so that the routine is completely executed.
.. Comment out the lines 1105 and 1109 in audiomixerboard.cpp to remove the calls to setStyleSheet.
Please then test as you did above.
I think the problem is that the line 1109 is not being executed correctly in that Linux version.
I hope my assumption is correct.
Sorry I need to send you debugging for me, but as you are the only person with this error....  :)

**Comment by ann0see** [comment]
> Good, it looks like the windows manager of your Linux is not correctly resetting the style sheet to that inherited from the class above.

Not sure if that's important, but I do also have openbox installed, tested it in an openbox session and could reproduce the same glitch?

I'll do your debugging very soon.

**Comment by ann0see** [comment]
Ok:
1. Not connected: Bug reproducible
2. Recording disabled: Bug reproducible
3. Recording enabled: Bug is reproducible
If the glitch occurs, it can no longer be be reset by disabling recording.

**Comment by dcorson-ticino-com** [comment]
Thanks for the results ann0see.
I don't know what openbox is, so I can't comment on that.
It seems that the second try elicited worse behaviour, so going back to the first with SetMixerBoardDeco disabled.
From what we have tried and rereading carefully it looks like the the bug happens only when going from one UI to another when recording. But not when going back to the original UI after having changed.  Is that correct ?
I that case it could be that something in the styleSheet string I'm sending is bothering the window manager.
So let's uncomment the lines 1105 and 1109 in audiomixerboard.cpp so they are active again.
Put the return back in clientdlg line 1411 so SetMixerBoardDeco does nothing.
Then let's go through the string AM_RECORDING_STYLE, audiomixerboard.h line 187.  
One after the other remove:
.. subcontrol-origin: margin;
.. subcontrol-position: left top;
.. left: 7px;
.. color: rgb(255,255,255);
.. background-color: rgb(255,0,0);
and then test.
One of those things has to be throwing the window manager into a tizzy. 
Don

**Comment by softins** [comment]
It doesn't relate to recording for me. I can reproduce it 100% with just this:
1. Open Jamulus (in fancy mode, left from previous run)
2. Switch to Normal
3. Switch back to Fancy. White box is shown.
4. Exit Jamulus.

**Comment by dcorson-ticino-com** [comment]
>It doesn't relate to recording for me. I can reproduce it 100% with just this

Thanks Tony,  is that happening using the rc1 as is?
Please try putting a return in clientdlg line 1411 so SetMixerBoardDeco does nothing.
That should reduce the problems to only with recording.
I think there is something in the style sheet that is causing the windows manager of this Linux version to flip out.

**Comment by dcorson-ticino-com** [comment]
Does anyone have visibility if this is working or not on a MAC ?

**Comment by softins** [comment]
> > It doesn't relate to recording for me. I can reproduce it 100% with just this
> 
> Thanks Tony, is that happening using the rc1 as is?

Yes, in fact with any compiled version from f5a58a0d2db7f38d8f6cdc5243b276062c9b2b8b onwards.

I'll try your suggestions.

> Does anyone have visibility if this is working or not on a MAC ?

Switching skins in 3.7.0rc1 works fine on my Mac running Mojave.

**Comment by softins** [comment]
Yes, I can confirm the following behaviour with the `return;` at the start of `SetMixerBoardDeco`:
1. Switching between skins while disconnected is ok.
2. Switching between skins while connected to a server that is NOT recording is ok.
3. Switching between skins while connected to a server that IS recording:
   - Switching to Fancy is ok
   - Switching to Normal leaves fancy buttons for Grp, Mute and Solo.

**Comment by ann0see** [comment]
Removing subcontrol-origin: margin; from AM_RECORDING_STYLE

seemed to fix the error for me.

**Comment by ann0see** [comment]
> Switching between skins while connected to a server that IS recording: 

I could also see this appear. What happens if you start in normal mode vs. if you start in fancy mode? For me the bug seemed to be different based on which mode you were on initially.

**Comment by softins** [comment]
> > Switching between skins while connected to a server that IS recording:
> 
> I could also see this appear. What happens if you start in normal mode vs. if you start in fancy mode? For me the bug seemed to be different based on which mode you were on initially.

Didn't check that. I need to pause now - will try it later if the bug isn't solved.

**Comment by softins** [comment]
If I switch to Normal skin, then connect to a recording server, Normal Display is ok. Switching to Fancy gives a white background and the buttons are still normal style, not fancy style. This is still with the `return;` at the start of `SetmixerBoardDeco`.

**Comment by ann0see** [comment]
Not sure, but might it be related to version of Qt which is shipped with Debian 10?

**Comment by ann0see** [comment]
@dcorson-ticino-com I now deleted line by line, and the bug still seems to be appearing.

**Comment by dcorson-ticino-com** [comment]
>I now deleted line by line, and the bug still seems to be appearing.

Thanks ann0see, but bad news.  I don't have any other ideas what this might be caused by.
Of course it could be Qt library versions or something of that effect, but that is hard to diagnose.

**Comment by softins** [comment]
I can do some more investigation tomorrow afternoon to see if I can find anything. I would like to try and understand the mechanism that causes the issue.

**Comment by ann0see** [comment]
Thank you!

**Comment by hoffie** [comment]
I tried playing around with different QT_QPA_PLATFORM values, but didn't see a difference.
Are you using wayland or X11? Would it make sense to share `qtdiag` data?

<summary>qtdiag
<details>

```
$ qtdiag
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0) on "wayland" 
OS: Arch Linux [linux version 5.11.1-arch1-1]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr
  DocumentationPath: /usr/share/doc/qt
  HeadersPath: /usr/include/qt
  LibrariesPath: /usr/lib
  LibraryExecutablesPath: /usr/lib/qt/libexec
  BinariesPath: /usr/bin
  PluginsPath: /usr/lib/qt/plugins
  ImportsPath: /usr/lib/qt/imports
  Qml2ImportsPath: /usr/lib/qt/qml
  ArchDataPath: /usr/lib/qt
  DataPath: /usr/share/qt
  TranslationsPath: /usr/share/qt/translations
  ExamplesPath: /usr/share/doc/qt/examples
  TestsPath: /usr/tests
  SettingsPath: /etc/xdg

Standard paths [*...* denote writable entry]:
  DesktopLocation: "Desktop" */home/christian/Desktop*
  DocumentsLocation: "Documents" */home/christian/Dokumente*
  FontsLocation: "Fonts" */home/christian/.local/share/fonts* /home/christian/.fonts /usr/local/share/fonts /usr/share/fonts
  ApplicationsLocation: "Applications" */home/christian/.local/share/applications* /usr/local/share/applications /usr/share/applications
  MusicLocation: "Music" */home/christian*
  MoviesLocation: "Movies" */home/christian*
  PicturesLocation: "Pictures" */home/christian*
  TempLocation: "Temporary Directory" */tmp*
  HomeLocation: "Home" */home/christian*
  AppLocalDataLocation: "Application Data" */home/christian/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  CacheLocation: "Cache" */home/christian/.cache/QtProject/qtdiag*
  GenericDataLocation: "Shared Data" */home/christian/.local/share* /usr/local/share /usr/share
  RuntimeLocation: "Runtime" */run/user/1000*
  ConfigLocation: "Configuration" */home/christian/.config* /etc/xdg
  DownloadLocation: "Download" */home/christian/Downloads*
  GenericCacheLocation: "Shared Cache" */home/christian/.cache*
  GenericConfigLocation: "Shared Configuration" */home/christian/.config* /etc/xdg
  AppDataLocation: "Application Data" */home/christian/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  AppConfigLocation: "Application Configuration" */home/christian/.config/QtProject/qtdiag* /etc/xdg/QtProject/qtdiag

File selectors (increasing order of precedence):
  de_DE unix linux arch

Network:
  Using "OpenSSL 1.1.1j  16 Feb 2021", version: 0x101010af

Platform capabilities: ThreadedPixmaps OpenGL ThreadedOpenGL BufferQueueingOpenGL MultipleWindows NonFullScreenWindows NativeWidgets WindowManagement RasterGLSurface

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 800
  startDragDistance: 10
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1000
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+25CF
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 0
  tabFocusBehavior: Qt::TabFocusAllControls 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 1

Theme:
  Platforms requested : unknown,generic
            available : gtk3,snap,flatpak,xdgdesktopportal
  Styles requested    : Fusion,Windows
         available    : Windows,Fusion
  System font         : "Sans Serif" 9

Fonts:
  General font : "Sans Serif" 9
  Fixed font   : "monospace" 9
  Title font   : "DejaVu LGC Sans" 12
  Smallest font: "DejaVu LGC Sans" 12

Palette:
  QPalette::WindowText: #ff000000
  QPalette::Button: #ffefefef
  QPalette::Light: #ffffffff
  QPalette::Midlight: #ffcacaca
  QPalette::Dark: #ff9f9f9f
  QPalette::Mid: #ffb8b8b8
  QPalette::Text: #ff000000
  QPalette::BrightText: #ffffffff
  QPalette::ButtonText: #ff000000
  QPalette::Base: #ffffffff
  QPalette::Window: #ffefefef
  QPalette::Shadow: #ff767676
  QPalette::Highlight: #ff308cc6
  QPalette::HighlightedText: #ffffffff
  QPalette::Link: #ff0000ff
  QPalette::LinkVisited: #ffff00ff
  QPalette::AlternateBase: #fff7f7f7
  QPalette::NoRole: #ff000000
  QPalette::ToolTipBase: #ffffffdc
  QPalette::ToolTipText: #ff000000
  QPalette::PlaceholderText: #80000000

Screens: 2, High DPI scaling: inactive
# 0 "HDMI-A-1" Depth: 32 Primary: yes
  Manufacturer: Samsung Electric Company
  Model: SyncMaster
  Serial number: 
  Geometry: 1280x1024+1920+0 Available: 1280x1024+1920+0
  Virtual geometry: 3200x1080+0+0 Available: 3200x1080+0+0
  2 virtual siblings
  Physical size: 380x300 mm  Refresh: 60.02 Hz Power state: 0
  Physical DPI: 85.5579,86.6987 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "DVI-D-1" Depth: 32 Primary: no
  Manufacturer: BenQ Corporation
  Model: G2420HDBL
  Serial number: 
  Geometry: 1920x1080+0+0 Available: 1920x1080+0+0
  Virtual geometry: 3200x1080+0+0 Available: 3200x1080+0+0
  2 virtual siblings
  Physical size: 530x290 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 92.0151,94.5931 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: AMD
Renderer: AMD Radeon(TM) Vega 11 Graphics (RAVEN, DRM 3.40.0, 5.11.1-arch1-1, LLVM 11.1.0)
Version: 4.6 (Compatibility Profile) Mesa 20.3.4
Shading language: 4.60
Format: Version: 4.6 Profile: 2 Swap behavior: 0 Buffer size (RGBA): 8,8,8,8
Profile: None (QOpenGLFunctions_4_6)

Vulkan instance available
Supported instance extensions:
  VK_KHR_device_group_creation, version 1
  VK_KHR_display, version 23
  VK_KHR_external_fence_capabilities, version 1
  VK_KHR_external_memory_capabilities, version 1
  VK_KHR_external_semaphore_capabilities, version 1
  VK_KHR_get_display_properties2, version 1
  VK_KHR_get_physical_device_properties2, version 2
  VK_KHR_get_surface_capabilities2, version 1
  VK_KHR_surface, version 25
  VK_KHR_wayland_surface, version 6
  VK_KHR_xcb_surface, version 6
  VK_KHR_xlib_surface, version 6
  VK_EXT_acquire_xlib_display, version 1
  VK_EXT_debug_report, version 9
  VK_EXT_debug_utils, version 2
  VK_EXT_direct_mode_display, version 1
  VK_EXT_display_surface_counter, version 1
Supported layers:
  VK_LAYER_VALVE_steam_fossilize_64, version 1, spec version 1.2.136, Steam Pipeline Caching Layer
  VK_LAYER_VALVE_steam_overlay_64, version 1, spec version 1.2.136, Steam Overlay Layer
  VK_LAYER_VALVE_steam_fossilize_32, version 1, spec version 1.2.136, Steam Pipeline Caching Layer
  VK_LAYER_VALVE_steam_overlay_32, version 1, spec version 1.2.136, Steam Overlay Layer
Available physical devices:
  API version 1.2.169, vendor 0x1002, device 0x15D8, AMD Radeon(TM) Vega 11 Graphics, type 1, driver version 2.0.177

Qt Rendering Hardware Interface supported backends:
OpenGL (with default QSurfaceFormat):
  Min Texture Size: 1
  Max Texture Size: 16384
  Max Color Attachments: 8
  Frames in Flight: 1
  Uniform Buffer Alignment: 1
  Supported MSAA sample counts: 1,2,4,8
  Features:
    - MultisampleTexture
    v MultisampleRenderBuffer
    - DebugMarkers
    - Timestamps
    v Instancing
    - CustomInstanceStepRate
    v PrimitiveRestart
    v NonDynamicUniformBuffers
    v NonFourAlignedEffectiveIndexBufferOffset
    v NPOTTextureRepeat
    - RedOrAlpha8IsRed
    v ElementIndexUint
    v Compute
    v WideLines
    v VertexShaderPointSize
    v BaseVertex
    - BaseInstance
    v TriangleFanTopology
    v ReadBackNonUniformBuffer
    v ReadBackNonBaseMipLevel
  Texture formats: RGBA8 BGRA8 R8 R16 RED_OR_ALPHA8 RGBA16F RGBA32F R16F R32F D16 D32F BC1 BC2 BC3 ETC2_RGB8 ETC2_RGB8A1 ETC2_RGBA8
Vulkan:
  Min Texture Size: 1
  Max Texture Size: 16384
  Max Color Attachments: 8
  Frames in Flight: 2
  Uniform Buffer Alignment: 16
  Supported MSAA sample counts: 1,2,4,8
  Features:
    v MultisampleTexture
    v MultisampleRenderBuffer
    - DebugMarkers
    v Timestamps
    v Instancing
    - CustomInstanceStepRate
    v PrimitiveRestart
    v NonDynamicUniformBuffers
    v NonFourAlignedEffectiveIndexBufferOffset
    v NPOTTextureRepeat
    v RedOrAlpha8IsRed
    v ElementIndexUint
    v Compute
    v WideLines
    v VertexShaderPointSize
    v BaseVertex
    v BaseInstance
    v TriangleFanTopology
    v ReadBackNonUniformBuffer
    v ReadBackNonBaseMipLevel
  Texture formats: RGBA8 BGRA8 R8 R16 RED_OR_ALPHA8 RGBA16F RGBA32F R16F R32F D16 D32F BC1 BC2 BC3 BC4 BC5 BC6H BC7
```
</details>
</summary>

**Comment by ann0see** [comment]
I think I'm on wayland.

**Comment by dcorson-ticino-com** [comment]
I give up with git.  
It didn't correctly make the changes that are now in rc1 and is telling me now that after making a copy of rc1 and changing 2 files that there are changes in more than 500 files.   
Attached are the two files with changes from rc1 to remove the redundant style changes for recording.
I removed the style changes in clientDlg, the necessary style changes are all done in audiomixerboard.

[clientdlg.zip](https://github.com/jamulussoftware/jamulus/files/6136360/clientdlg.zip)

**Comment by ann0see** [comment]
Thanks! I'll try it soon

> I give up with git.

That's a pitty. You can "git remote add" this repo as upstream, checkout upstream/master create a branch from it and then open a pull request to master on this repo.

**Comment by softins** [comment]
> I tried playing around with different QT_QPA_PLATFORM values, but didn't see a difference.
> Are you using wayland or X11? Would it make sense to share `qtdiag` data?
> 
> qtdiag

I couldn't get `qtdiag` to work:
```
tony@debian10:~/jamulus$ qtdiag
qtdiag: could not find a Qt installation of ''
```
Not sure what env or path I might be missing. I have enough of Qt installed to compile and run Jamulus.

Running Jamulus gives me this. So I suppose I'm on wayland, but I don't understand the significance of these messages:
```
tony@debian10:~/jamulus$ ./Jamulus
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by softins** [comment]
> I removed the style changes in clientDlg, the necessary style changes are all done in audiomixerboard.
> 
> [clientdlg.zip](https://github.com/jamulussoftware/jamulus/files/6136360/clientdlg.zip)

Am I missing something? The zip file reverts the changes to `clientdlg.h` and `clientdlg.cpp`, but doesn't appear to include the changes you mentioned to audiomixerboard. There wasn't a second zip file attached.

**Comment by softins** [comment]
I have updated clientdlg with the above Zip file and recompiled. These are my findings:
1. When not connected to a server, switching between Fancy and Normal/Compact in either direction works fine and does not show the white background.
2. When connected to a server that is not recording, switching between Fancy and Normal/Compact in either direction still works fine.
3. Set skin to Fancy and then connected to a server that is recording. Box title is shown as white with red background as expected. Switching to Normal or Compact does not update the Grp/Mute/Solo buttons, which remain in Fancy style.
4. Set skin to Normal and then connected to a server that is recording. Box title shown as white with red background as expected. Switching to Fancy shows the fancy slider and LEDs, but does not show the fancy background or buttons:
![image](https://user-images.githubusercontent.com/3224952/111077234-b55cc600-84e7-11eb-8b15-a8c20618e93b.png)

**Comment by ann0see** [comment]
For me qt diag gives the following:

<summary>qtdiag
<details>

```
Failed to create Vulkan instance: -9
Failed to create platform Vulkan instance
Qt 5.11.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "xcb" 
OS: Debian GNU/Linux 10 (buster) [linux version 4.19.0-14-amd64]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:
  QT4_IM_MODULE="ibus"
  QT_ACCESSIBILITY="1"
  QT_IM_MODULE="ibus"

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr
  DocumentationPath: /usr/share/qt5/doc
  HeadersPath: /usr/include/x86_64-linux-gnu/qt5
  LibrariesPath: /usr/lib/x86_64-linux-gnu
  LibraryExecutablesPath: /usr/lib/x86_64-linux-gnu/qt5/libexec
  BinariesPath: /usr/lib/qt5/bin
  PluginsPath: /usr/lib/x86_64-linux-gnu/qt5/plugins
  ImportsPath: /usr/lib/x86_64-linux-gnu/qt5/imports
  Qml2ImportsPath: /usr/lib/x86_64-linux-gnu/qt5/qml
  ArchDataPath: /usr/lib/x86_64-linux-gnu/qt5
  DataPath: /usr/share/qt5
  TranslationsPath: /usr/share/qt5/translations
  ExamplesPath: /usr/lib/x86_64-linux-gnu/qt5/examples
  TestsPath: /usr/tests
  SettingsPath: /etc/xdg

Standard paths [*...* denote writable entry]:
  DesktopLocation: "Desktop" */home/[...]/Schreibtisch*
  DocumentsLocation: "Documents" */home/[...]/Dokumente*
  FontsLocation: "Fonts" */home/[...]/.local/share/fonts* /home/[...]/.fonts
  ApplicationsLocation: "Applications" */home/[...]/.local/share/applications* /usr/share/gnome/applications /home/[...]/.local/share/flatpak/exports/share/applications /var/lib/flatpak/exports/share/applications /usr/local/share/applications /usr/share/applications
  MusicLocation: "Music" */home/[]/Musik*
  MoviesLocation: "Movies" */home/[]/Videos*
  PicturesLocation: "Pictures" */home/[]/Bilder*
  TempLocation: "Temporary Directory" */tmp*
  HomeLocation: "Home" */home/[]*
  AppLocalDataLocation: "Application Data" */home/[]/.local/share/QtProject/qtdiag* /usr/share/gnome/QtProject/qtdiag /home/[]/.local/share/flatpak/exports/share/QtProject/qtdiag /var/lib/flatpak/exports/share/QtProject/qtdiag /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  CacheLocation: "Cache" */home/[]/.cache/QtProject/qtdiag*
  GenericDataLocation: "Shared Data" */home/[]/.local/share* /usr/share/gnome /home/[]/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /usr/local/share /usr/share
  RuntimeLocation: "Runtime" */run/user/1000*
  ConfigLocation: "Configuration" */home/[]/.config* /etc/xdg
  DownloadLocation: "Download" */home/[]/Downloads*
  GenericCacheLocation: "Shared Cache" */home/[]/.cache*
  GenericConfigLocation: "Shared Configuration" */home/[]/.config* /etc/xdg
  AppDataLocation: "Application Data" */home/[]/.local/share/QtProject/qtdiag* /usr/share/gnome/QtProject/qtdiag /home/[]/.local/share/flatpak/exports/share/QtProject/qtdiag /var/lib/flatpak/exports/share/QtProject/qtdiag /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  AppConfigLocation: "Application Configuration" */home/[]/.config/QtProject/qtdiag* /etc/xdg/QtProject/qtdiag

File selectors (increasing order of precedence):
  de_DE unix linux debian

Network:
  Using "OpenSSL 1.1.1d  10 Sep 2019", version: 0x1010104f

Platform capabilities: ThreadedPixmaps OpenGL WindowMasks MultipleWindows ForeignWindows NonFullScreenWindows NativeWidgets WindowManagement SyncState RasterGLSurface SwitchableWidgetComposition

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 500
  startDragDistance: 8
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1200
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+2022
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 0
  tabFocusBehavior: Qt::TabFocusBehavior(TabFocusAllControls) 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 0

Theme:
  Platforms requested : gtk3,gnome,generic
            available : gtk3
  Styles requested    : fusion,windows
         available    : Windows,Fusion
  Icon theme          : Adwaita,  from /var/lib/flatpak/exports/share/icons,/usr/local/share/icons,/usr/share/icons
  System font         : "Cantarell" 11
  Native file dialog
  Native color dialog
  Native font dialog

Fonts:
  General font : "Cantarell" 11
  Fixed font   : "monospace" 11
  Title font   : "DejaVu Sans" 12
  Smallest font: "DejaVu Sans" 12

Palette:
  WindowText: #ff000000
  Button: #ffefefef
  Light: #ffffffff
  Midlight: #ffcbcbcb
  Dark: #ff9f9f9f
  Mid: #ffb8b8b8
  Text: #ff000000
  BrightText: #ffffffff
  ButtonText: #ff000000
  Base: #ffffffff
  Window: #ffefefef
  Shadow: #ff767676
  Highlight: #ff308cc6
  HighlightedText: #ffffffff
  Link: #ff0000ff
  LinkVisited: #ffff00ff
  AlternateBase: #fff7f7f7
  NoRole: #ff000000
  ToolTipBase: #ffffffdc
  ToolTipText: #ff000000

Screens: 2, High DPI scaling: inactive
# 0 "DP-1" Depth: 24 Primary: yes
  Manufacturer: Hewlett Packard
  Model: HP LA2405x
  Serial number: []
  Geometry: 1920x1200+0+0 Available: 1920x1200+0+0
  Virtual geometry: 3840x1200+0+0 Available: 3840x1200+0+0
  2 virtual siblings
  Physical size: 518x324 mm  Refresh: 59 Hz Power state: 0
  Physical DPI: 94.1467,94.0741 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "eDP-1" Depth: 24 Primary: no
  Manufacturer: AU Optronics
  Model: 
  Serial number: 
  Geometry: 1920x1080+1920+120 Available: 1920x1080+1920+120
  Virtual geometry: 3840x1200+0+0 Available: 3840x1200+0+0
  2 virtual siblings
  Physical size: 276x155 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 176.696,176.981 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 515 (Skylake GT2) 
Version: 3.0 Mesa 18.3.6
Shading language: 1.30
Format: Version: 3.0 Profile: 0 Swap behavior: 0 Buffer size (RGB): 8,8,8
Profile: None (QOpenGLFunctions_3_0)


Unable to create a Vulkan instance, error code is-9
```
</details>
</summary>

**Comment by softins** [comment]
Removing the calls to `setStyleSheet()` in `audiomixerboard.cpp` cures the above problems, but of course no longer shows the title in red, and is effectively a reversion of b2d7d99f41b49882572eb5e650e855238e0babac and e5ac6cdcb3c4408c7dcd74befc90c69e7bf1e9ce

**Comment by ann0see** [comment]
Ok. So we can conclude that setting the stylesheet doesn't seem to work correctly?
Maybe it is a bug related to Qt?

**Comment by softins** [comment]
Well the next question is: which part of `AM_RECORDING_STYLE` is causing the behaviour?

**Comment by dcorson-ticino-com** [comment]
>Well the next question is: which part of AM_RECORDING_STYLE is causing the behaviour?

I had ann0see remove each line one at a time here https://github.com/jamulussoftware/jamulus/issues/1238#issuecomment-798640354 and according to his response he always had the error.  Of course it could be a combination of the lines.
But why do they work on all other systems?  I think there is a library that is not doing it's work correctly.

**Comment by softins** [comment]
I am about to test a theory. I think the recording title stylesheet is being inherited by child objects. I'm going to test setting an objectname and using that in the stylesheet.

**Comment by softins** [comment]
Hmm, either my theory is wrong, or I haven't yet implemented it correctly.
