### ISSUE TITLE
Installing new 64 bit Jamulus loses ASIO4ALL settings (& installer strongly recommends to remove the old version)

### ISSUE THREAD

**Issue by npostavs** [jamulussoftware/jamulus#1244]
**Describe the bug**

The latest Jamulus builds for Windows are 64 bit, the previous versions were 32 bit. I think ASIO4ALL maintains customized settings per-exe file path and the install location is different for 32 vs 64 bit programs. This means the previously working settings for the old 32 bit version are not carried over to the new 64 bit version. Furthermore, the installer strongly recommends removing the older 32 bit version (this makes sense, because otherwise you end up with 2 sets of shortcuts, and things get kind of confusing).

**To Reproduce**

Have Jamulus working with ASIO4ALL on the old 32 bit version. Install a new 64 bit version, and click yes when installer strongly recommends removing old 32 bit version. Realize that ASIO4ALL is using the default settings now, and you don't remember what the good settings were. Reinstall the old Jamulus version to get the old settings, take a screenshot and get copy over the working settings to the 64 bit version.

I spent about an hour and a half talking someone through this over the phone yesterday.

**Expected behavior**

I don't think it's feasible for Jamulus to avoid this outright, but at the point where the installer recommends removing the old 32 bit Jamulus, it would be good to have a warning about it.

**Operating system**

This applies to Windows only.

**Jamulus version**

3.7.0, 64 bit builds.

**Comment by ann0see** [comment]
I totally forgot that this could happen. Yes, I think this is a problem related to an old bug of the old installer which moved 64Bit binaries to the 32 Bit folder. I don't think we could do much about it, but warn in the installer ("take a screenshot of your ASIO4ALL settings, if you use that before you continue")

**Comment by ann0see** [comment]
This would also affect translations...

**Comment by hoffie** [comment]
Thanks for reporting. I think this is really unfortunate for all those people who helped others getting started with Jamulus/ASIO4ALL.

As I understand it, ASIO4ALL will fall back to default settings because all previous customizations are stored in a tree which is related to the old binary path, right?

Would it be feasable to attempt to copy those registry entries? Would be a breach of abstractions though. :(

**Comment by ann0see** [comment]
> Would it be feasable to attempt to copy those registry entries? Would be a breach of abstractions though. :(

I hope so!

**Comment by ann0see** [comment]
After having looked at the old installer, it seems as if it didn't save a custom path to the registry, so we can't get it in the new version. 

I'm now searching through my registry, but I can't find ASIO4ALL registry keys?

**Comment by ann0see** [comment]
Ok. Can confirm: if I move the binary to the 32 bit folder and name it jamulus.exe (lower case as it used to be before), the old settings get applied.

**Comment by ann0see** [comment]
Ok. Just found it for 3.6.2 in HKEY_CURRENT_USER\SOFTWARE\ASIO4ALL v2 by Wuschel\8A9E7A56

**Comment by hoffie** [comment]
> @npostavs @hoffie can you confirm that both hashes also exist for you?

No Windows here, I was worried about the singers in our choir. :)

> If we can just copy 8A9E7A56 to 7A49ECC9 (maybe after asking the user) we could at least help some users.

If this fixes the default scenario (default installation path?), then this will already help lots of people, I think.

> since it's in HKCU, would we have to do it for every user?

I would think so, yes.

Meta: I think it would be better to avoid editing comments with substantial new content or even pings. Edits do not seem to trigger notifications.
Mentioning @npostavs here again for that reason. :)

**Comment by ann0see** [comment]
Ok. 

I'm currently trying it on my windows machine like that (not yet tested, and copied form the links above)
```
          ; ask to move old ASIO4ALL registry configuration

            ; check if old ASIO4ALL keys exit

            ClearErrors
            EnumRegKey $0 HKCU "SOFTWARE\ASIO4ALL v2 by Wuschel\8A9E7A56" 0

            IfErrors 0 continueinstall

                MessageBox MB_YESNO|MB_ICONEXCLAMATION "Do you want to copy ASIO4ALL settings from the previous version if possible?" /sd IDYES IDNO continueinstall

                    IntOp $0 0 + 0
                    EnumStart:
                        EnumRegKey $R1 HKEY_USERS "" $0 ; foreach user
                        IntOp $0 $0 + 1
                        StrCmp $R1 ".DEFAULT" EnumStart
                        StrCmp $R1 "" EnumEnd

                        ; copy the registry key
                        ${COPY_REGISTRY_KEY} HKU "$R1\SOFTWARE\ASIO4ALL v2 by Wuschel\8A9E7A56" HKU "$R1\SOFTWARE\ASIO4ALL v2 by Wuschel\7A49ECC9"

                        goto EnumStart
                    EnumEnd:

```

**Comment by npostavs** [comment]
Yeah I have both those both hashes, plus a few others since I've been building in random local paths :)

**Comment by hoffie** [comment]
The code should probably ensure that we do not copy and overwrite if the new key exists already. This would cover both people who already run 3.7.0rc1 and have manually fixed things. It would also be necessary for the releases after 3.7.0.

I'm not enough into Windows/NSIS to tell if the code already handles this case.

**Comment by ann0see** [comment]
No, it shouldn't do that until now. We could check if the key already exists and then just skip it.

**Comment by ann0see** [comment]
See my PR. It's not yet ready, but at least we seem to have some code to discuss.

**Comment by softins** [comment]
> Ok. Just found it for 3.6.2 in HKEY_CURRENT_USER\SOFTWARE\ASIO4ALL v2 by Wuschel\8A9E7A56
> 
> And 3.7.0: Computer\HKEY_CURRENT_USER\SOFTWARE\ASIO4ALL v2 by Wuschel\7A49ECC9

I have both those keys on my W7 64-bit system. I think the difference isn't specifically 3.6.2 vs 3.7.0, but rather 32-bit vs 64-bit.

Which raises a related question: does the Windows installer also contain the 32-bit version? i.e. would 3.7.0 install on a 32-bit W7 system? I do have access to one, so can try it.

**Comment by ann0see** [comment]
Yes, it does include a 32Bit Version. I installed it on Win 8.1 32 bit and it works.

**Comment by ann0see** [comment]
@npostavs could you please have a look at my PR?

**Comment by npostavs** [comment]
I'm a little bit late, but I checked the installer autobuilt from rc2 and it copied over the settings correctly.

https://github.com/jamulussoftware/jamulus/actions/runs/655593070
