### ISSUE TITLE
Change reference to Central server to Directory

### ISSUE THREAD

**Issue by dcorson-ticino-com** [jamulussoftware/jamulus#1270]
As we are changing the nomenclature for Central servers to Directories, shouldn't we change the text for the combo-box in the Connect window to "Directory" in the place of "List" ?

**Comment by gilgongo** [comment]
In the English, the word "List" there is intended to be a verb, as is "Filter" (and "Connect"). 

However, your question implies that there may be an advantage in surfacing the concept of a directory server to the user. But the label wasn't "Central server" before, so I'm not sure there is. 

Personally, I'd remove the label all together as the conbo-box is self-labelling (assuming people understand what a genre is, but if they don't the label isn't going to help).

**Comment by ann0see** [comment]
@dcorson-ticino-com can you take care of changing Central Server to Directory Server in the code and documentation?

**Comment by gilgongo** [comment]
@ann0see That's a separate issue, but no matter. I was about to close this one with wontfix if that's OK?

**Comment by ann0see** [comment]
No. I think this is still valid. We should change the term central server to directory server everywhere.

**Comment by gilgongo** [comment]
Not sure I follow. There's a ticket [for that here](https://github.com/jamulussoftware/jamuluswebsite/issues/330), but my comment about this ticket is here https://github.com/jamulussoftware/jamulus/issues/1270#issuecomment-800033722. Do you mean you disagree with that?

**Comment by gilgongo** [comment]
Looks like we'll stick with the verb "List" for consistency: https://github.com/jamulussoftware/jamulus/pull/1629 so closing,
