### ISSUE TITLE
Directory servers Rock, Jazz and Classical have respose times more than 10 minutes at times

### ISSUE THREAD

**Issue by dcorson-ticino-com** [jamulussoftware/jamulus#1275]
Directory servers Rock, Jazz and Classical appear to be down....
Yesterday I got responses after about 1 minute.
Today we had an orchestra rehearsal, directory server Classical/Folk and 10 people on several different providers had no response for over 10 minutes.
In the end I sent all the server IP to log in that way.

At times it works, however.
Whatever it is we need to clear this up.  It does not look good.

**Comment by softins** [comment]
When this happens, it would be useful to know whether [Jamulus Explorer](https://explorer.jamulus.io) can see them.

**Comment by gilgongo** [comment]
_(is this is dupe? I thought I'd seen this somewhere else?)_

I have wondered about the fact that we use CNAMEs on the servers you mention, while others are A records. Could that be implicated? 

```
~$ host rock.jamulus.io
rock.jamulus.io is an alias for jamuluscentral4.drealm.info.
jamuluscentral4.drealm.info is an alias for peter.drealm.info.
peter.drealm.info has address 81.174.155.168

~$ host anygenre1.jamulus.io
anygenre1.jamulus.io has address 62.113.206.102
```

**Comment by hoffie** [comment]
@gilgongo You are probably referring to #1249

**Comment by gilgongo** [comment]
Oh OK. @dcorson-ticino-com in the interests of keeping the issues list to actionable work tickets, I'll close now so we can continue on https://github.com/jamulussoftware/jamulus/discussions/1249 if that's OK.
