### ISSUE TITLE
Jamulus -h does not show the current Jamulus version

### ISSUE THREAD

**Issue by drummer1154** [jamulussoftware/jamulus#1283]
**Describe the bug**
If 'Jamulus -h' is issued, the Jamulus version is not displayed. To get the version of your installed Jamulus SW, you additionally need to issue 'Jamulus -v' afterwards. This is not very user friendly.  The help text shall always be prepended by the version text.

**To Reproduce**
enter 'Jamulus -h' 

**Expected behavior**
Jamulus -h
*** Jamulus, Version 3.6.2
:
Usage: jamulus [option] [optional argument]
:
Example: jamulus -s --inifile myinifile.ini
C:\Program Files (x86)\Jamulus>

**Operating system**
any

**Version of Jamulus**
Version 3.6.2

**Comment by drummer1154** [comment]
I did not manually add the label "bug". The label should be changed to "improvement".

**Comment by hoffie** [comment]
No strong opinion on that from me. Some software does it (e.g. gcc), some doesn't (e.g. bash, cat, ip).

Would you be willing to send a PR?

**Comment by drummer1154** [comment]
@hoffie If you are asking me - yes, of course, the problem is that I am not familiar with the development cycle, honestly I thought that Issue == Problem Report. Maybe you could direct me to some tutorial.

**Comment by ann0see** [comment]
There's no tutorial here, but from my experience it usually works like this:

1. Find and report issue/feature request
2. Discuss and agree on something
3. Start development (preferably the person who opened the issue)
4. Open a pull request; wait for discussion and a merge

Jamulus is led and developed by volunteers. Therefore you can't expect someone to pick it up. 

Development is done with git. I don't have a tutorial in mind, but it's not too difficult:

1. Fork this repository
2. `git clone` your own repository
3. make your changes
4. `git add` and `git commit` your work
5. `git push` your work to GitHub
6. Open a pull request

**Comment by pljones** [comment]
OK, as I challenged @henkdegroot over in his pull request, I'll add this to the issue here:

My "reference" command for the "standard unix behaviour" is `cat`.  It has `--version`:
```
peter@fs-peter:~$ cat --version
cat (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund and Richard M. Stallman.
peter@fs-peter:~$
```
and `--help`
```
peter@fs-peter:~$ cat --help
Usage: cat [OPTION]... [FILE]...
Concatenate FILE(s) to standard output.

With no FILE, or when FILE is -, read standard input.

  -A, --show-all           equivalent to -vET
...
  -v, --show-nonprinting   use ^ and M- notation, except for LFD and TAB
      --help     display this help and exit
      --version  output version information and exit

Examples:
  cat f - g  Output f's contents, then standard input, then g's contents.
  cat        Copy standard input to standard output.

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation at: <https://www.gnu.org/software/coreutils/cat>
or available locally via: info '(coreutils) cat invocation'
peter@fs-peter:~$
```
`--help` doesn't duplicate `--version` output.

Our `--version` could be improved to make it clear which version of the GPL and say where to get it, along with the (C) note and authorship (we should have `--authors` to show the many pages of authors shown in the Help->About text).

**Comment by pljones** [comment]
Oh and another thing: we _really_ should mention Qt in our version (copyright/licence) message.

**Comment by ann0see** [comment]
Any updates here? I think `--version` is ok for now? Please close this issue if no longer needed.

**Comment by ann0see** [comment]
Closing since I didn't get any comment for over a week, so it seems to be stale. Please re-open this issue or open a PR with reference to this issue if we decide to implement it later on.
