### ISSUE TITLE
Jamulus server: Wrong initial recording status wording in log

### ISSUE THREAD

**Issue by drummer1154** [jamulussoftware/jamulus#1284]
**Describe the bug**
Start a Jamulus server with command line option '--norecord'.
The log will reflect this as "- recording will not be enabled" which is completely misleading because by sending SIGUSR2, recording **will** be enabled, reflected in the log by "Recording state enabled".
It is only an issue on line 373 in main.cpp which shall be changed to contain "- Recording state: disabled"

**To Reproduce**
see above

**Expected behavior**
If a Jamulus server - otherwise ready for recording - is invoked with command line option '--norecord', the log shall reflect this by "- Recording state: disabled", else "- Recording state: enabled"

**Screenshots**
see above

**Operating system**
any

**Version of Jamulus**
3.6.2

**Additional context**
- I did not quickly find a location to contain the default text "- Recording state: enabled".
- the upper/lower case of the log texts shall be consolidated.

**Comment by hoffie** [comment]
Thanks for your report!

> I did not quickly find a location to contain the default text "- Recording state: enabled".

From a quick glance, it looks like it comes from here:

https://github.com/jamulussoftware/jamulus/blob/976ad09cf0806842800cce4b6dee175065e9c5d2/src/recorder/jamcontroller.cpp#L56

Do you want to send a PR for this?

**Comment by drummer1154** [comment]
@hoffie Please see https://github.com/jamulussoftware/jamulus/issues/1283#issuecomment-802433582

**Comment by drummer1154** [comment]
I think a "recording control" finite state machine (FSM) can have these states:
o **Disabled** - this is the initial state. If there was no command line argument "-R" or the specified directory is not writable, then this state remains assumed for the current lifetime of the application. Reception of SIGUSR1 or SIGUSR2 has no effect in this state.
o **Enabled** - this is assumed if -R is followed by a writable directory. Reception of SIGUSR2 advances the state to **Active** if at least one client is connected or to **Armed** otherwise.
o **Armed** - in this state the recording function waits for a client to connect; if connected, the state advances to **Active**.
o **Active** - in this state the actual recording takes place, i.e. the first file is opened for writing which is a directory. In case the service user does not have file creation rights and opening the first file for writing fails, then **Disabled** is assumed again. Otherwise recording continues until SIGUSR2 is received, in this event the current recording is terminated (i.e. all currently files open for writing are closed) and the state **Armed** is assumed again. If SIGUSR1 is received, the current recording is terminated and a new recording with related set of files is created without state change.

If the recording FSM is modelled like this, then it is very easy to create consistent log entries initially and subsequently at every state transition - just output "Recording state: %s" where %s is substituted by the new state. The recording thread creation and destroying can also be easily controlled via state transitions: Creation upon entering **Active**, destroying when transiting from **Active** to **Disabled**.

See also #1289.

**Comment by hoffie** [comment]
I have looked at the details of this bug report.

I see three sub-topics:
1. The wrong wording in the log, which should be simple to improve.
2. The inconsistent case usage in log messages.
3. The idea to add a full state machine.

I want to use this issue for 1) and want to keep it open until the relevant PR #1463 is merged, I'll open a seperate issue for 2) and I'm not sure if 3) is necessary. Maybe @pljones could create a seperate issue for that (based on @drummer1154's comment) if this would be useful to do?

**Comment by pljones** [comment]
The log line in question isn't a command line logging entry, it's a status change entry from the recorder.  Hence the different format.

**Comment by drummer1154** [comment]
Please see my input in https://github.com/jamulussoftware/jamulus/issues/1289#issuecomment-818306326

**Comment by npostavs** [comment]
> The log line in question isn't a command line logging entry, it's a status change entry from the recorder. Hence the different format.

I wonder if everyone is really agreeing on the what the line in question is. The OP says

> The log will reflect this as "- recording will not be enabled"

which I think corresponds to this command line option handling code:

https://github.com/jamulussoftware/jamulus/blob/8d305f16d2a3bd6f8e1c5eedc74975a5c7dee58e/src/main.cpp#L399

Even though technically that isn't going to the logfile set by `--log <logfile>` (but it could be logged in some sense by other means).
