### ISSUE TITLE
Jamulus server (Linux) crashes when recorder cannot create recording session subdirectory

### ISSUE THREAD

**Issue by drummer1154** [jamulussoftware/jamulus#1289]
**Describe the bug**
- Run a Jamulus server as a service on Linux with jamulus.service containing
 ProtectHome=false
 User=jamulus_usr
 Group=nogroup
 :
 ExecStart=/usr/local/bin/Jamulus -R /home/vm_owner/Rec --norecord

- To toggle the recording state, issue "sudo /bin/systemctl kill -s SIGUSR2 jamulus"

- This will execute "QDir().mkpath(sessionDir.absolutePath())" in jamrecorder.cpp

- Most likely because there is an access right problem, the server crashes and the log contains
 -- Logs begin at Tue 2021-03-16 09:37:11 UTC. --
 Mar 16 13:27:47 vm-name jamulus[441]: Recording state enabled
 Mar 16 13:27:47 vm-name jamulus[441]: Qt has caught an exception thrown from an event handler. Throwing
 Mar 16 13:27:47 vm-name jamulus[441]: exceptions from an event handler is not supported in Qt.
 Mar 16 13:27:47 vm-name jamulus[441]: You must not let any exception whatsoever propagate through Qt code.
 Mar 16 13:27:47 vm-name jamulus[441]: If that is not possible, in Qt 5 you must at least reimplement
 Mar 16 13:27:47 vm-name jamulus[441]: QCoreApplication::notify() and catch all exceptions there.
 Mar 16 13:27:47 vm-name jamulus[441]: terminate called after throwing an instance of 'std::runtime_error'
 Mar 16 13:27:47 vm-name jamulus[441]:   what():  /home/vm_owner/Rec/Jam-20210316-132747781 does not exist but could not be created
 Mar 16 13:27:47 vm-name systemd[1]: jamulus.service: Main process exited, code=killed, status=6/ABRT
 Mar 16 13:27:47 vm-name systemd[1]: jamulus.service: Failed with result 'signal'.
 Mar 16 13:28:17 vm-name systemd[1]: jamulus.service: Service RestartSec=30s expired, scheduling restart.
 Mar 16 13:28:17 vm-name systemd[1]: jamulus.service: Scheduled restart job, restart counter is at 1.
 Mar 16 13:28:17 vm-name systemd[1]: Stopped Jamulus-Server.
 Mar 16 13:28:17 vm-name systemd[1]: Started Jamulus-Server.
 Mar 16 13:28:17 vm-name jamulus[2777]: - server mode chosen
 Mar 16 13:28:17 vm-name jamulus[2777]: - disconnect all clients on quit
 Mar 16 13:28:17 vm-name jamulus[2777]: - no GUI mode chosen
 Mar 16 13:28:17 vm-name jamulus[2777]: - maximum number of channels: 16
 Mar 16 13:28:17 vm-name jamulus[2777]: - using 64 samples frame size mode
 Mar 16 13:28:17 vm-name jamulus[2777]: - using multithreading
 Mar 16 13:28:17 vm-name jamulus[2777]: - welcome message: This is vm-name in FFM ...
 Mar 16 13:28:17 vm-name jamulus[2777]: - server info: vm-name;FFM;82
 Mar 16 13:28:17 vm-name jamulus[2777]: - recording directory name: /home/vm_owner/Rec
 Mar 16 13:28:17 vm-name jamulus[2777]: - recording will not be enabled
 Mar 16 13:28:18 vm-name jamulus[2777]: Recording state disabled
 Mar 16 13:28:18 vm-name jamulus[2777]:  *** Jamulus, Version 3.6.2
 Mar 16 13:28:18 vm-name jamulus[2777]:  *** Internet Jam Session Software
 Mar 16 13:28:18 vm-name jamulus[2777]:  *** Released under the GNU General Public License (GPL)

- All connected users are disconnected.

**To Reproduce**
See above

**Expected behavior**
If the sub-directory for the recording session cannot be created, the recording state shall revert back to disabled and the server shall continue to run with the currently connected users remaining connected.

**Screenshots**
See above

**Operating system**
GCP n1-standard-1, debian-10-buster-v20210217, Jamulus built from source
git clone https://github.com/corrados/jamulus.git
cd jamulus
git fetch
git checkout latest
=> HEAD is now at 337a4840 r3_6_2
qmake "CONFIG+=nosound" Jamulus.pro && make clean && make

**Version of Jamulus**
3.6.2

**Additional context**
See also #1284

**Comment by hoffie** [comment]
According to my tests, #1463 should fix this.

**Comment by drummer1154** [comment]
I need to say that I was unable to follow up Jamulus development in the past weeks, sorry for that.

I also need to say that I opened this issue (and others) strictly from a user/musician perspective who struggled to set up a Jamulus server as close as possible to the DE-CIX node in Frankfurt because prior tests have shown that this is the only remedy for the latency problems our 3 piece band encountered with all 3 members located in Munich, all, however, contracted to 3 different ISPs (for more info see https://github.com/jamulussoftware/jamuluswebsite/issues/174 which was kindly closed and locked so I cannot comment any further ;-), as well as https://github.com/jamulussoftware/jamulus/issues/756#issuecomment-737903152).

From a user perspective I demand that any application provides as much information as possible so as to help the user to find the root cause for a problem they encountered when using the application, in a short time frame.

Nevertheless I tried to find out the source code location which causes the observed problem(s), even if I do not have any SDK and can only download the sources and inspect them manually.

@pljones: If I now read https://github.com/jamulussoftware/jamulus/pull/1463#issuecomment-816036864 I must say that **I am completely disappointed**.

1) An application crash is absolutely no way for a normal application user to find out where they made a mistake.
2) There is absolutely no hint in the log message issued by Qt as to why the exception happened. @hoffie is absolutely right by saying that "/home/vm_owner/Rec/Jam-20210316-132747781 does not exist but could not be created" is not easily to be seen as the problem's root cause. And there is no hint how to resolve this.
3) The "start up" logging would be helpful if the wording would be clear and unambiguous.

I can accept that the comments to these points might be relevant from a developer's PoV. But a developer also needs to take into account that an application user may stumble into situations which from a developer's PoV might be crystal clear how to resolve but are not at all for the user whose limited free time is as precious as the developer's.

In https://github.com/jamulussoftware/jamulus/issues/1284#issuecomment-802487617 I proposed a design for a recording control FSM which from my PoV would be helpful to provide consistent information to the Jamulus user (both client and server). I absolutely appeciate the approach by @hoffie (https://github.com/jamulussoftware/jamulus/issues/1284#issuecomment-815243614) to separate my proposal from my problem report. But the comment by @pljones (https://github.com/jamulussoftware/jamulus/issues/1284#issuecomment-816037929) shows that apparently there is no willingness at all to improve the user experience.

I also completely agree to @ann0see (https://github.com/jamulussoftware/jamulus/issues/1283#issuecomment-806443743) that
> Jamulus is led and developed by volunteers.

For exactly this reason and because as a musician I appreciate the great overall performance and functionality of the Jamulus software I tried to contribute to the documentation which from my PoV is lacking consistency - see https://github.com/corrados/jamulus/files/5775148/JamulusABDv105.pdf - and also to the source code development by entering issues.

However, my current sad feeling is that I am wasting my time. And sorry for the lengthy text.

**Comment by ann0see** [comment]
@drummer1154 Sorry to hear that. I personally also disagree to some team members points of view (password protection) and some team members disagree with my point of view. I was also quite frustrated at the time I started contributing. 

See:
https://github.com/jamulussoftware/jamulus/discussions/1505

which is your issue now converted to a discussion on the main repo. Probably the initial issue was locked die to inactivity. 

Yes, crashing the server is - in my opinion - not the right way. 

Unfortunately I don't have time in the next weeks since I need to focus on important exams. So please understand that I won't be able to answer every concern/question. Hopefully others take up.

**Comment by pljones** [comment]
@drummer1154 

PLEASE CONTRIBUTE RATHER THAN SIMPLY COMPLAINING ALL THE TIME.

**Comment by hoffie** [comment]
@drummer1154 Several of the issues you've opened have already been worked on by different people, some even had relevant Pull Requests merged. There absolutely is a desire to make Jamulus and its user experience better, so please keep posting issues as you find them. I do find them valuable and helpful.

At the same time, please also keep in mind that everyone is working on Jamulus in their free time. So if a and when an issue is fixed certainly depends on priority, complexity and availability of development resources. Feel free to send PRs for issues yourself. The CONTRIBUTING documentation is currently being worked on by @gilgongo and others. :)

**Comment by drummer1154** [comment]
@pljones
> PLEASE CONTRIBUTE RATHER THAN SIMPLY COMPLAINING ALL THE TIME.

1) From my PoV reproducing and documenting unexpected behavior and trying to detect the root cause is not complaining but **contributing**. So you don't need to shout on me. I already said that at the moment I do not feel to have the competence to offer solutions in source, for two reasons: On the one hand I do not have Qt and only limited C++ knowledge and on the other hand I do not have any SDK environment. I am, however, willing to go into this direction; my idea is to set up an SDK on Windows (Visual Studio ? GNU ?) and later test on Linux - but I really need help to achieve this.

2) I also **contributed** by proposing a design for a recording control FSM which is supposed to provide a consistent recording feature, no matter how it is activated. If it is agreed that this is a path to follow I can develop a state diagram. But - and here I really do **COMPLAIN** - I am not aware of any documentation regarding the interfaces of the SW modules apart from the source files themselves. This makes it quite difficult to propose a sound design - but maybe this is on purpose. I am absolutely aware of the fact that the recording feature - which I highly appreciate, supporting our band's progress - is @pljones's "baby". But as it is released to the public domain, it is also subject to improvement which should not be taken as an insult by the original author.

3) Earlier I felt that there is lack in documentation which could be improved so as to enable new users to better understand how Jamulus works. Therefore I tried to **contribute** by starting a Visio drawing showing a coarse signal flow closer to the current implementation than Volker's. Whether or not Visio is the best choice may be debatable, but after some trials with visual-paradigm Visio as a long term used tool provided the fastest turn-around.

@ann0see
> Your PDF would be very valuable maybe in the community KB? You should open an issue and start preparing a pull request to the _posts/ folder.

Thanks for this assertion; maybe someone can direct me how to continue (which repo?) and all the best for your exams!

@hoffie
> Several of the issues you've opened have already been worked on by different people ... I do find them valuable and helpful.

Thanks also for this input, highly appreciated!

> At the same time, please also keep in mind that everyone is working on Jamulus in their free time.

... This also applies to myself. I am really willing to contribute to further improvement and to help testing, but I definitively think things need to be streamlined further. I am not at all able to check a pile of e-mails every day to find out if there is anything Jamulus related waiting for reaction by me - even if I already moved the Github mails to an account separate from my normal mail conversation. On the jamulus.io HP there should be an immediate link to an organigram showing who is responsible for what - but this is OT here and I do not know where and with whom to discuss this any further ...

**Comment by ann0see** [comment]
> maybe someone can direct me how to continue (which repo?)

That‘s on the documentation ("jamulussoftware/jamuluswebsite") repo. Just have a look at the other .md files and create a pull request with a page including your PDF as picture. Not sure how pictures are handled currently, but you can ask gilgongo.

**Comment by gilgongo** [comment]
For images, you can just use the current "git hub hack" of opening a an issue or discussion thread, uploading the image to get the URL to it (on user-images.githubusercontent.com), and then cancelling the issue/thread. 

Feel free to open a [PR for the knowledge base](https://github.com/jamulussoftware/jamuluswebsite/new/changes/_posts/?value=---%0Alayout%3A%20post%0Atitle%3A%20%22Your%20Title%22%0Alang%3A%20%22en%22%0Aauthor%3A%20%22YourName%22%0Aheading%3A%20%22Heading%22%0A---%0AName%20this%20file%20and%20edit%20the%20parameters%20above%21&message=New%20post).

**Comment by hoffie** [comment]
> If the sub-directory for the recording session cannot be created, the recording state shall revert back to disabled and the server shall continue to run with the currently connected users remaining connected.

@drummer1154 That's how Jamulus 3.8.0 will behave. Thanks for the report again!

**Comment by drummer1154** [comment]
I can confirm that in Release 3.8.0 the access rights behavior is OK now, as far as I was able to test today after installing 3.8.0 on Debian (HEAD is now at e745891 Update version to 3.8.0 for release).
If -R specifies a non-existing directory
- it will be created if access rights permit and recordings are placed there,
- if creation is not allowed, "'/home/record' does not exist but could not be created." is logged, the server keeps running, clients can be connected and if SIGUSR2 is sent, "OnHandledSignal: 12" is logged, no recording takes place and no related message occurs in the client.

If -R specifies an existing directory which cannot be written, "'/home/record' is a directory but cannot be written to" is logged and no other failure occurs.
I was not able to test the original crash when the session subdirectory cannot be created after receiving SIGUSR2.
Thanks a lot to all involved.
Cheers
Helmuth
