### ISSUE TITLE
Pan /

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#1290]
Currently the panorama-slider is labeled “pan”. This confuses people, both because of the slider (pans are knobs), but more importantly, if one is sending mono, like in dual mono with an instrument in one channel and a talkback mic in the other, the slider controls the balance.

I had several instances where somebody became inaudible, only to find out minutes later that they played with the pan slider without knowing it. Especially when you send a single channel out in mono the current configuration yields unintended results

a solution could be to have two sliders, linkable and with each a pan knob. The two sliders would allow better control over the sent volume, and allow dual mono mode. Also visually it would be more like the mixer pane, and aligb visually with the vu-meters in the input section.

**Comment by dcorson-ticino-com** [comment]
This is a known problem.
That the slider has to be set in the middle is non-evident for many, especially as the slider is vertical and not horizontal.
Discussions are on for the next UI improvement step.
Note that input volume must be set using the operating system controls or on the external audio interface if used.

**Comment by gilgongo** [comment]
Hi @reneknuvers You may be interested in the discussion about UI in general here https://github.com/jamulussoftware/jamulus/discussions/1150, of which the pan slider is part.
