### ISSUE TITLE
Jamulus built with CONFIG+="headless nosound" abort()s upon Ctrl+C

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1291]
**Describe the bug**

Running Jamulus built with `CONFIG+="headless nosound"` dumps core when pressing Ctrl+C.

**To Reproduce**

- Build with `CONFIG+="headless nosound"`
- `./Jamulus`
- Ctrl+C
- Observe crash.

**Expected behavior**

Clean exit

**Screenshots**

```
$ ./Jamulus
No GUI support compiled. Running in headless mode.
 *** Jamulus, Version 3.7.0rc2dev-913e4cc8
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
^CQThread: Destroyed while thread is still running
Aborted (core dumped)
```
```
Stack trace of thread 58464:
#0  0x00007f539b803ef5 raise (libc.so.6 + 0x3cef5)
#1  0x00007f539b7ed862 abort (libc.so.6 + 0x26862)
#2  0x00007f539bd629ac _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x909ac)
#3  0x00007f539bd6329a n/a (libQt5Core.so.5 + 0x9129a)
#4  0x000055ea4274d0b7 n/a (/home/christian/Projects/jamulus/Jamulus + 0x210b7)
#5  0x00007f539c21a550 _ZTV7QThread (libQt5Core.so.5 + 0x548550)
```

**Operating system**

`Linux wuechoo 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux
`

**Version of Jamulus**

3.7.0rc2

**Additional context**

- I don't think this is a recent regression.
- I don't think it's too relevant because it happens on intended exit anyway.
- We should still look into it.
- I don't have an idea yet, so feel free to take over and assign yourself.

**Comment by pljones** [comment]
Only the server is meant to be run like this currently.  So this is "expected behaviour".  Using "nosound" and then running without "-s" should fail on start up with an error message.
