### ISSUE TITLE
ubuntu linux server crashes by 15th user.

### ISSUE THREAD

**Issue by michaelberg79** [jamulussoftware/jamulus#1307]
**Describe the bug**
until 14 users on the server all things are running as expected. if a 15th user is joining the server crashes completly. In the error logs I can see the connections. no errors. The connection entries for the 15th user is repeating endless. Getting masses of connect entries in the logfile. This seems to be the reason there is no response from the server anymore (endless loop)

My journalctl -u jamulus
Mar 19 17:07:32 ms033 jamulus[6283]: 2021-03-19 17:07:32, 84.173.187.99, connected (1)
Mar 19 17:10:49 ms033 jamulus[6283]: 2021-03-19 17:10:49, 95.90.209.212, connected (2)
Mar 19 17:15:24 ms033 jamulus[6283]: 2021-03-19 17:15:24, 84.173.187.99, connected (2)
Mar 19 18:05:20 ms033 jamulus[6283]: 2021-03-19 18:05:20, 87.160.37.216, connected (2)
Mar 19 18:10:42 ms033 jamulus[6283]: 2021-03-19 18:10:42, 87.160.37.216, connected (2)
Mar 19 18:11:36 ms033 jamulus[6283]: 2021-03-19 18:11:36, 87.160.37.216, connected (2)
Mar 19 18:11:57 ms033 jamulus[6283]: 2021-03-19 18:11:57, 87.160.37.216, connected (2)
Mar 19 18:13:42 ms033 jamulus[6283]: 2021-03-19 18:13:42, 77.23.253.219, connected (2)
Mar 19 18:19:18 ms033 jamulus[6283]: 2021-03-19 18:19:18, 87.160.37.216, connected (3)
Mar 19 18:19:40 ms033 jamulus[6283]: 2021-03-19 18:19:40, 146.52.110.150, connected (4)
Mar 19 18:21:34 ms033 jamulus[6283]: 2021-03-19 18:21:34, 95.90.173.100, connected (5)
Mar 19 18:29:56 ms033 jamulus[6283]: 2021-03-19 18:29:56, 77.23.253.219, connected (2)
Mar 19 18:45:53 ms033 jamulus[6283]: 2021-03-19 18:45:53, 79.242.219.88, connected (3)
Mar 19 18:48:48 ms033 jamulus[6283]: 2021-03-19 18:48:48, 37.4.249.210, connected (3)
Mar 19 18:52:36 ms033 jamulus[6283]: 2021-03-19 18:52:36, 2.200.95.68, connected (2)
Mar 19 18:55:50 ms033 jamulus[6283]: 2021-03-19 18:55:50, 77.23.251.143, connected (3)
Mar 19 18:56:25 ms033 jamulus[6283]: 2021-03-19 18:56:25, 77.23.251.143, connected (3)
Mar 19 18:57:39 ms033 jamulus[6283]: 2021-03-19 18:57:39, 146.52.110.150, connected (4)
Mar 19 18:57:55 ms033 jamulus[6283]: 2021-03-19 18:57:55, 77.23.253.219, connected (5)
Mar 19 18:58:00 ms033 jamulus[6283]: 2021-03-19 18:58:00, 87.171.255.212, connected (6)
Mar 19 18:58:50 ms033 jamulus[6283]: 2021-03-19 18:58:50, 37.4.249.210, connected (7)
Mar 19 18:59:00 ms033 jamulus[6283]: 2021-03-19 18:59:00, 146.52.105.191, connected (8)
Mar 19 18:59:08 ms033 jamulus[6283]: 2021-03-19 18:59:08, 95.90.173.100, connected (9)
Mar 19 18:59:37 ms033 jamulus[6283]: 2021-03-19 18:59:37, 87.160.37.216, connected (10)
Mar 19 19:01:12 ms033 jamulus[6283]: 2021-03-19 19:01:12, 79.242.219.88, connected (11)
Mar 19 19:02:00 ms033 jamulus[6283]: 2021-03-19 19:02:00, 77.23.252.191, connected (12)
Mar 19 19:02:57 ms033 jamulus[6283]: 2021-03-19 19:02:57, 37.4.233.67, connected (13)
Mar 19 19:07:14 ms033 jamulus[6283]: 2021-03-19 19:07:14, 84.134.31.12, connected (14)
Mar 19 19:07:14 ms033 jamulus[6283]: 2021-03-19 19:07:14, 79.246.127.15, connected (15)
Mar 19 19:07:31 ms033 jamulus[6283]: 2021-03-19 19:07:31, 37.4.232.226, connected (16)
Mar 19 19:07:53 ms033 jamulus[6283]: 2021-03-19 19:07:53, 95.90.172.210, connected (17)
Mar 19 19:09:57 ms033 jamulus[6283]: 2021-03-19 19:09:57, 37.4.232.226, connected (17)
Mar 19 19:11:31 ms033 jamulus[6283]: 2021-03-19 19:11:31, 79.246.127.15, connected (17)
Mar 19 19:12:19 ms033 jamulus[6283]: 2021-03-19 19:12:19, 79.246.127.15, connected (17)
Mar 19 19:13:10 ms033 jamulus[6283]: 2021-03-19 19:13:10, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:14 ms033 jamulus[6283]: 2021-03-19 19:13:14, 95.90.173.100, connected (15)
Mar 19 19:13:50 ms033 jamulus[6283]: 2021-03-19 19:13:50, 79.242.219.88, connected (15)
Mar 19 19:13:59 ms033 jamulus[6283]: 2021-03-19 19:13:59, 95.90.173.100, connected (15)
Mar 19 19:14:09 ms033 jamulus[6283]: 2021-03-19 19:14:09, 95.90.172.210, connected (15)
Mar 19 19:15:05 ms033 jamulus[6283]: 2021-03-19 19:15:05, 84.134.31.12, connected (15)
Mar 19 19:15:30 ms033 jamulus[6283]: 2021-03-19 19:15:30, 95.90.172.210, connected (16)
Mar 19 19:17:04 ms033 jamulus[6283]: 2021-03-19 19:17:04, 79.246.127.15, connected (16)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)
Mar 19 19:23:22 ms033 jamulus[6283]: 2021-03-19 19:23:22, 95.90.172.210, connected (15)

**To Reproduce**
set up a server 3.6.x on ubuntu from sources. join with 15 or more users. All clients are on version 3.6.  
my starting script:
[Unit]
Description=Jamulus-Server
After=network.target

[Service]
Type=simple
User=jamulus
Group=nogroup
NoNewPrivileges=true
ProtectSystem=true
ProtectHome=true
Nice=-20
IOSchedulingClass=realtime
IOSchedulingPriority=0

#### See [Command-Line-Options](Command-Line-Options) ####
ExecStart=/usr/local/bin/Jamulus -s -n -o "ShowChor-LE;Leipzig;82" -u 50 -l /var/log/jamulus

Restart=on-failure
RestartSec=30
StandardOutput=journal
StandardError=inherit
SyslogIdentifier=jamulus

[Install]
WantedBy=multi-user.target

**Expected behavior**
all useres should be able to join until the giving max 15 users. 

**Operating system**
Ubuntu 18.04

**Version of Jamulus**
3.6.1
clients 3.6.x

**Comment by ann0see** [comment]
That's a serious problem. 
It could also be related to missing hardware resources. 

Can you monitor the system resources needed via htop and try without logging enabled? I know a person which ran a server with about 50 users and it didn't crash so it doesn't seem to be a general issue. 

Can other new users join? Do connected users hear any sound?

**Comment by dcorson-ticino-com** [comment]
What processor is your system using ?
I have an ARM processor based server (Odroid-N2) using Ubuntu 20.04 and run it with 25 users without problems and far from the maximum processor capacity.

**Comment by michaelberg79** [comment]
thank for the answers,
Im an geek an not a member of the choir. At next meeting i will join the session and overwatch the server. I hope i am able to get new expierence about the behavior. currently there is a 1,9GHz processor with 4 cores installed. I will try to enable multithreading -T. thx for the hind. The next session is next friday, i will give feedback as soon as possible.

**Comment by passing** [comment]
@michaelberg79 
from my experience, on a VM with a 3.1 GHz CPU, each user raises the CPU consumption by around 5% of one core.
So it is quite plausible that your CPU with 1,9 GHz is maxed out at ~15 clients when multithreading is disabled (Load per client also varies a lot depending on their channel/quality settings).

What's noticable is that the last client in the log connected 37 times within one second.
It would be interesting if the server implementation can (could) handle situations where CPU is maxed out so it doesn't crash.

**Comment by michaelberg79** [comment]
Hi,
yesterday the choir makes a new try with the server. I was a member and could overwatch the server. Last week I added the multithreading of jamulus and stopped some background tasks. All 18 members of the musical choir could join and sing some songs. the quality was good. The cpu usage of all 4 cores raised up to 30-40 percent. One core never could accomplish the tasks. 
Thanks for the hint of enabling multithreading. 
It would be nice if there would be a possibility to get a error in case of run out of ressources.
