### ISSUE TITLE
Icon pushes the PAN control down

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1312]
**Describe the bug**
Please see the third PAN control in the screenshot:
![image](https://user-images.githubusercontent.com/271906/111861660-4fb87180-890d-11eb-9b05-584cbfd0b2c7.png)

This isn't a big deal, just a small visual defect.

**Comment by dcorson-ticino-com** [comment]
This does not happen on Win10, what is your OS?
The icon is a unicode character, the code allows for a max height of 15px, but that rendered character height depends on the OS.
Qt claims to adhere to HTML4 for rendering characters so there is no way I know of to determine an exact pixel height.  There is bigger and smaller from an (unknown) base height.
Maybe the best way to handle this would be to place a pixmap and hide or unhide it.

**Comment by yurivict** [comment]
> This does not happen on Win10, what is your OS?

FreeBSD

> The icon is a unicode character, the code allows for a max height of 15px, but that rendered character height depends on the OS.

You need to use QFontMetrix to determine real size of the character, not just allow a hard-coded value of 15px.

**Comment by dcorson-ticino-com** [comment]
The best would be that one could define the size in usable units and not have to adjust ones design to the vagarities of this or that OS.

**Comment by yurivict** [comment]
This depends not on OS, rather on what fonts are installed. I have a lot of fonts installed (like noto) and Qt chooses a font that violates some of your code assumptions.
