### ISSUE TITLE
Jamulus server should open the UDP port through UPnP

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1314]
Currently users are expected to forward the UDP port ```22124``` on the router for the server to work.

It would be better if this port would be opened automatically through UPnP.

The ```libnpupnp``` library (https://www.lesbonscomptes.com/upmpdcli/npupnp-doc/libnpupnp.html) can do it.

**Comment by gilgongo** [comment]
Hi @yurivict thanks for this. There is a [discussion about UPnP discussion here](https://github.com/jamulussoftware/jamulus/discussions/1041). I'll close your issue for now in favour of that discussion and until an actionable work ticket can be written up for it if that's OK. Please feel free to join in on that.
