### ISSUE TITLE
"Mute Myself" choice should be persistent across sessions

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1315]
When the user chooses to be muted he later assumes that he is muted and it is safe to talk. This choice is currently lost after restart, and there is likelihood that this user would inadvertently cause disruption with his sound while thinking that it is muted.

**Comment by dcorson-ticino-com** [comment]
I disagree, if someone is not muted they will hear themselves and note it immediately.
If however they start a session and are muted they may not notice, or remember if the last session was a while ago.

**Comment by yurivict** [comment]
> If however they start a session and are muted they may not notice, or remember if the last session was a while ago.

Then make it persistent for a while, with a reasonable timeout.

**Comment by yurivict** [comment]
A special Settings checkbox can be added: "Persistent Self-Mute", so users would be able to choose for themselves.

**Comment by gilgongo** [comment]
Hi @yurivict so that this can be discussed before action is agreed since there are clearly pros and cons, I'll move this to Discussion if that's OK.
