### ISSUE TITLE
Install the .desktop file and icon for Jamulus Server (optionally or not)

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1316]
In the FreeBSD port I added such desktop item. The desktop file is the same except ```Name=Jamulus Server```, ```Comment=Jam Session Server```, ```Exec=jamulus -s```, ```Icon=jamulus-server```.

The icon file ```src/res/fronticonserver.png``` is installed as ```jamulus-server.png```.

This is a convenience feature to simplify starting the server.

You can make it optional with a qmake CONFIG option, or permanent.

**Comment by jujudusud** [comment]
Hi Yuri, hi all,
I want to add a Jamulus server icon in Archlinux package too.
I noticed that Windows 10 installs two differents icons while my package for Arch only installs one (the blue).
I think this could be a good improvement if Il can simply have this icon in the .desktop.

**Comment by ann0see** [comment]
Yes. That would be good. I think you could create a Pull Request. But no guarantee that it'll get merged although I'd support it.

**Comment by jujudusud** [comment]
Is there anything new here?
@yurivict do you pull request the new desktop file ?

**Comment by yurivict** [comment]
Sorry, I don't have spare cycles for this.

**Comment by jujudusud** [comment]
I will do that if it's ok for you.
Just the time for to understand how to ... and it will be ok. :-)

**Comment by ann0see** [comment]
@jujudusud I can assign you to this issue if you want

**Comment by jujudusud** [comment]
@ann0see Ok !

**Comment by ann0see** [comment]
Ok great. I'll unsubscribe from this issue now.

**Comment by jujudusud** [comment]
The PR is here #1422

**Comment by jujudusud** [comment]
Need help here to make the new jamulus-server.desktop.in work with the autobuild.
Anyone ?
