### ISSUE TITLE
Jamulus server disappeared from the public server list

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1317]
I started the server hours ago in a Registered state. It first showed up in the list. But now GUI still shows as "Registered", but it isn't in the public list.

I can connect to the server by the IP address.

3.7.0
FreeBSD 12.2

**Comment by dcorson-ticino-com** [comment]
Hi Yuri, 
What is the name of your server and which directory is it on?
I want to see if I can see it.
Don

**Comment by yurivict** [comment]
I've restarted it and now it is shown.

But the fact that the client can be saying that it is online, and the server not having it means that something is broken in their communication protocol.

**Comment by DavidSavinkoff** [comment]
#1170 ?

**Comment by ann0see** [comment]
Closed since I believe it's a bigger issue (the one David linked?)
