### ISSUE TITLE
license clarification: gpl2 or "gpl2 or later"

### ISSUE THREAD

**Issue by seb314** [jamulussoftware/jamulus#1330]
For the nix package of jamulus, a clarification about the license would apparently be [desirable](https://github.com/NixOS/nixpkgs/pull/117337#issuecomment-804793871).
The question is described in more detail [here](https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md) -- apparently it is common for gpl licenses to allow a specific version and also any later versions.

Is this the case for jamulus too?

Thanks!

**Comment by ann0see** [comment]
I'm afraid that I can only link the COPYING file: https://github.com/jamulussoftware/jamulus/blob/master/COPYING

**Comment by hoffie** [comment]
According to [the code](https://github.com/jamulussoftware/jamulus/blob/eaed4c21eedccd3ee16d7a3985f3723963654049/src/main.cpp#L11) it should be *"either version 2 of the License, or (at your option) any later version."*

**Comment by ann0see** [comment]
Closed since the question should be answered.
