### ISSUE TITLE
Minor typo in Dutch translation

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1331]
The Dutch translation contains a minor type in the "what is this" dialog for the audio channels option.
Also the dropdown list text is not consistent compared to the text in this dialog. Seems not translated.
Text highlighted in the screenshot.

![dutch-translation](https://user-images.githubusercontent.com/13550012/112216323-a41b6400-8c21-11eb-9029-6b5a5ab252a3.png)

Version used is 3.7.0.

I would be happy to fix this issue (recently listed added as a contributor). 

Should I fix this myself and add myself to the translators list as well?
Or is it preferred to keep dev/coding and translation separate?

**Comment by ann0see** [comment]
Yes, you can add yourself as second translator.

**Comment by henkdegroot** [comment]
Can you let me know if I should just do the update to the .ts file or should I also generate the .qm file?

On a separate note, I noticed when I use the deploy powershell the translation files seems to be updating (using lrelease), however the actual qm file seems to remain unchanged. Is this something know?
I noticed some discussion around removing the qm files from git as well but that was cancelled as it seemed to introduce more issues. If it is not something known, then I will create a new issue for this to investigate/resolve.

Also noticed the "right-click" command is showing english text, instead of the selected language. Another issue to create :) (which I will do shortly)

**Comment by ann0see** [comment]
I think you don't need to worry too much of these files.
