### ISSUE TITLE
What is This popup when using right click not shown in selected language

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1333]
When using the right-click in Windows, the popup text is shown in English instead of the local/selected language.

![image](https://user-images.githubusercontent.com/13550012/112269579-d73d1200-8c78-11eb-9c6f-88dc2d9d1b9a.png)

Version used 3.7.0
OS: Windows 10

**Comment by jujudusud** [comment]
It's the same here on Archlinux and 3.7.0 or 3.6.2.

**Comment by henkdegroot** [comment]
@jujudusud thank you for the confirmation. 

Can this issue be assigned to me please? So I can resolve this...

**Comment by henkdegroot** [comment]
Update: this issue is actually caused by not having the **qt_nl.qm** file distributed with the release. For almost all other languages, this is part of the release.
The NL is missing, also the SV and PT versions are missing.
As these are not part of the source held in github, I am not sure if I can resolve this. Adding the qt_nl.qm to my local installation makes the text appear in the dutch.

**Comment by jujudusud** [comment]
Is it this one you're talking about @henkdegroot  ?
![Capture d’écran_2021-03-24_20-57-33](https://user-images.githubusercontent.com/12748768/112375978-2f5d2e00-8ce4-11eb-95c8-16039d84532a.png)

**Comment by henkdegroot** [comment]
@jujudusud that is odd, French is working fine on my (windows) system:
![image](https://user-images.githubusercontent.com/13550012/112377087-962f1700-8ce5-11eb-8c69-c2ccdef7f79d.png)

Did you build yourself?

**Comment by jujudusud** [comment]
I'm the co maintainer of the Archlinux Users Repository package for Jamulus.
So yes, I'm on Archlinux and the package is built from the sources using the informations [from this page](https://jamulus.io/wiki/Installation-for-Linux).

**Comment by hoffie** [comment]
Hrm, this translation does not seem to come from Jamulus, but rather from Qt itself. In Arch, this is part of qt5-tools.
I still haven't figured out why it works for some languages (German is fine for me, Dutch is not) and some not. I assume that it might be related to language codes and if they match between Jamulus and Qt.

`/usr/share/qt/phrasebooks/dutch.qph` does contain a translation for `What's This` for me, so this is not an issue of a (technically) untranslated string.

**Comment by hoffie** [comment]
My previous comment is not completely right. The translations are loaded (on my system) from /usr/share/qt/translations/qt*.qm, which is indeed missing `qt_nl.qm` for me. The actual translation would usually live in `qtbase_nl.qm` it seems, but this is missing as well.

Those files are provided by extra/qt5-translations. I have no idea why Dutch is missing there. But this starts sounding like a generic Qt issue?

**Comment by henkdegroot** [comment]
I agree it is a Qt related issue. The required .ts file is available in the Qt repo here: 
[https://codereview.qt-project.org/c/qt/qttranslations/+/227094](url)

On a windows install, the "qt" translation files are located in C:\Program Files\Jamulus\translations
When I manually add the qt_nl.qm to this folder, I get the translated context menu.

I wonder why Qt is not distribution this with the normal install. I can only assume they want to prevent a massive amount of translations included and have cherry picked the ones they assumed would be required by most people.

Perhaps there is a way to include this in the build process?

**Comment by henkdegroot** [comment]
@hoffie I found another possible for this. Just add the "QDialog What's This?" in one of the source files (I have tested by adding it to Clientdlg.cpp).
I.e. add Q_UNUSED(QT_TRANSLATE_NOOP("QDialog", "What's This?"));

This will add the string for translation to the translation files.

It does mean all translation files will incllude the string and can be translated, when not translated Qt will still use the original Qt language text.

Would that be an acceptable solution?

**Comment by trebmuh** [comment]
For what it worth, on LibraZiK-3 (Debian buster based), it needs to have the `qttranslations5-l10n` package installed to get this "what's this" translated. You're probably missing this package (or equivalent) on your distribution.

**Comment by henkdegroot** [comment]
Okay, so that would explain why french works fine on Windows and not in Linux if it is an optional package you need to install.

Guess all other "standard" qt text strings are   not used, else it would be more obvious. 

Op 25 mrt. 2021 13:40, om 13:40, Olivier Humbert ***@***.***> schreef:

**Comment by hoffie** [comment]
> Perhaps there is a way to include this in the build process?

I don't think we should touch the Qt directories. This would only work for platforms which bundle Qt anyway and would not solve it for Linux, for example.

> I found another possible for this. Just add the "QDialog What's This?" in one of the source files (I have tested by adding it to Clientdlg.cpp).
I.e. add Q_UNUSED(QT_TRANSLATE_NOOP("QDialog", "What's This?"));

This has the slight downside of requiring all translators to translate it, I guess? Other than that, I could live with that workaround.

I tried to dig further why qt_nl.ts is missing from the releases. The answer is simple: There simply has been no Qt 5.x release after it was merged: https://github.com/qt/qttranslations/commit/6f8025306c17cbeaf4cd1f130d02bf18798ef715

The latest release is 5.15.2 which was tagged 7 days before the commit was merged: https://github.com/qt/qttranslations/releases/tag/v5.15.2

Confusingly, the file was created in 2018, but only merged on Nov 25th 2020.

So the correct fix is: What for Qt 5.15.3 (or something). Not sure though if/when that'll happen. :(

**Comment by trebmuh** [comment]
> This has the slight downside of requiring all translators to translate it, I guess? Other than that, I could live with that workaround.

Just thinking out loud here: this has also another downside, which is cluttering the consistence of an user desktop environment. Imagine a case with 3 software (for the example sake) with:
1. software 1 using the general translation from the "`qttranslations5-l10n`" (or equivalent)
2. software 2 retranslating one (or more) string(s) in its own way
3. software 3 retranslating one (or more) string(s) in another own way

Soon, the mess is coming.

It sounds to me more of a packager issue. A distro packager should adds "`qttranslations5-l10n`" (or equivalent) as needed at runtime for the application. @ann0see does the automatic .deb building do that? Looking quickly at [this file](https://github.com/jamulussoftware/jamulus/blob/master/.github/workflows/autobuild.yml), it doesn't sound to be there. It'd be probably a good idea to add it [in this file](https://github.com/jamulussoftware/jamulus/blob/master/autobuild/linux/autobuild_deb_1_prepare.sh) IMHO.

**Comment by ann0see** [comment]
No. The run time dependencies are in the control file in distributions/debian (the whole Debian build logic must be re thought. @nefarius2001 merged a PR from me a while ago which cleared it up a bit, but I don't focus on that.

**Comment by hoffie** [comment]
> It sounds to me more of a packager issue. A distro packager should adds "qttranslations5-l10n" (or equivalent) as needed at runtime for the application.

This is not sufficient for Dutch. It could be (I haven't verified) that distribution packages only pull in minimal qt packages without translations. This could lead to other languages missing that translation as well. But the initial issue (Dutch missing the translation) is related to the Dutch translation missing in all Qt 5.x upstream releases.

**Comment by trebmuh** [comment]
> > It sounds to me more of a packager issue. A distro packager should adds "qttranslations5-l10n" (or equivalent) as needed at runtime for the application.
> 
> This is not sufficient for Dutch. It could be (I haven't verified) that distribution packages only pull in minimal qt packages without translations. This could lead to other languages missing that translation as well. But the initial issue (Dutch missing the translation) is related to the Dutch translation missing in all Qt 5.x upstream releases.

I understand that. That said, it sounds to be an issue with the upstream Qt IIUC. So "fixing" this bug (Dutch is missing a translation file from Qt) would then open up the can of worms of all the translators needing to re-translate this string and maybe translating it another way that it's already translated in upstream QT translations, hence cluttering the general user experience.

Not easy to workaround this bug. Unless there is a way of allowing the translation of this string within Jamulus only for the Dutch translation?

**Comment by henkdegroot** [comment]
> So the correct fix is: What for Qt 5.15.3 (or something). Not sure though if/when that'll happen. :(

Qt has release 5.15.3 already but decided from this version and onwards (5.x) they will only provide this to commercial licenced users. Not sure if Qt 6 includes it :)

> Not easy to workaround this bug. Unless there is a way of allowing the translation of this string within Jamulus only for the Dutch translation?

I do not believe there is a way to only include a translateable string in 1 language, as when you manually add it to the ts file, it will be removed as soon as an lupdate is performed to update the translation files.

However it is possilbe to "tag" the translating string with comments which will appear in the ts file and will be visible to translator. We can include a text it only needs translation for Dutch (and perhaps include it relates to a Qt missing text).
In the ts file it will then look something like I show in the attached txt.

[translate_extract.txt](https://github.com/jamulussoftware/jamulus/files/6209648/translate_extract.txt)

**Comment by DavidSavinkoff** [comment]
"What's This ?" can be reduced to "?". Would this be of any use as no translation is needed?

**Comment by henkdegroot** [comment]
> "What's This ?" can be reduced to "?". Would this be of any use as no translation is needed?

Would it then still be clear for user what he/she need to do or has done?
I know if I click the "What's this ?" in the menu, the cursor changes to an arrow with question mark and I can select the item of interest. Are you thinking about showing that arrow with question mark when you use right-click?
Or just show the question mark in the popup?
I wonder how you would convince Qt to do change this default behaviour.

**Comment by henkdegroot** [comment]
> "What's This ?" can be reduced to "?". Would this be of any use as no translation is needed?

Having checked a bit more, I now found there a more actions which cause the native qt translations to be used. Meaning when using Dutch, you will get them in English (as the nl is missing in the Qt files).
While the "What's This ?" is the most obvious, others I found are for instance in the chat window. The right-click in that window provide a context menu with copy,paste,etc. All in English, while when I use German I get proper German text.

I have been working in some other project and they basically distribute all qt language within their application folder (at least in windows) as "windows users" normally expected everything is installed with their application and they do not require to download and install Qt manually (which would not fix the issue in this case anyway).

Maybe we just need to accept it is a short comming of Qt at the moment.

**Comment by hoffie** [comment]
> Qt has release 5.15.3 already but decided from this version and onwards (5.x) they will only provide this to commercial licenced users.

Ah, didn't know that. Sad. :(

> Not sure if Qt 6 includes it :)

It does, but Jamulus doesn't build with Qt6 (yet), I think.

> I now found there a more actions which cause the native qt translations to be used

Too bad. :(

Technically, we could think about bundling the missing files and loading them if the system doesn't provide them. I'm not sure if it's worth the effort and I'm not sure if we are allowed to (it seems like they are licensed as [GPLv3+Qt](https://github.com/qt/qttranslations/blob/dev/LICENSE.GPL3-EXCEPT), while Jamulus is GPLv2-or-later).

> Maybe we just need to accept it is a short comming of Qt at the moment.

Yes, I agree. The situation not optimal, but no disaster either, so let's accept the status quo and avoid putting any more effort into it? If you agree, I suggest to close this issue.

**Comment by henkdegroot** [comment]
> It does, but Jamulus doesn't build with Qt6 (yet), I think.

You are correct, it doesn't build (I did a quick test noticed a few minor changes required but then stopped checking).

Please go ahead and close this issue.

**Comment by jujudusud** [comment]
Solved on Archlinux installing 'qt5-translations' package as @trebmuh advise. Thanks a lot ! :-)
I will update the Package soon.
