### ISSUE TITLE
Issue warning when server-only options are given to a client, or vice versa

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#1336]
> Oh, I was passing the option to the client instead, no wonder I didn't notice any difference. Oops! (maybe passing it to the client should give a warning though, instead of saying `- starting with delay panning`).

There are actually a lot of server-only options that do not generate a warning when given to a client, although they are then ignored. It would be good to tidy that up a bit!

_Originally posted by @softins in https://github.com/jamulussoftware/jamulus/issues/1151#issuecomment-805807035_

**Comment by pljones** [comment]
Should be done now.  #1896

I'll close on that basis.
