### ISSUE TITLE
Create a login to improve security for servers

### ISSUE THREAD

**Issue by khmarbaise** [jamulussoftware/jamulus#1345]
It would be a good idea to add a kind of authorization to the server so the client needs to authorize to prevent attacks on a server because the server has an open port which could be use to attack a server.

For example the server could define a list of users with the access codes(stored in an encrypted way).

**Comment by ann0see** [comment]
I think we already have an issue on that and it's a highly debated topic in the community ;-). 

In the meantime, you can try the code from the eduTools branch which is only a workaround I coded a few months ago.

**Comment by ann0see** [comment]
See: https://github.com/jamulussoftware/jamulus/issues/299

**Comment by gilgongo** [comment]
Hi @khmarbaise so that our issues can be a list of actionable specifications, we'll close this. Feel free to contribute to the discussion at https://github.com/jamulussoftware/jamulus/discussions/1057
