### ISSUE TITLE
ADD A MUTE FUNCTION FOR EACH INPUT CHANNEL

### ISSUE THREAD

**Issue by Blueguit** [jamulussoftware/jamulus#1348]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by ann0see** [comment]
Hi @Blueguit

From your title I understand that you'd like to have a mute function for the left/right input channel? Is that correct?

Could you please give some more information on why exactly you propose this? In my opinion it would be very confusing for inexperienced users if we add a third way to mute something. 

You can usually just disconnect/disable left/right input channels or use the pan slider above reverb to amplify e.g. the left channel and mute the right one and vice versa.

**Comment by dcorson-ticino-com** [comment]
Exactly, you can mute one channel or the other using the pan slider, this functionality exists already.

**Comment by gilgongo** [comment]
More UI complexity (particularly given the dual-channel use case here seems to be an edge case?) isn't to be encouraged I don't think.

**Comment by gilgongo** [comment]
Closing as wontfix. Feel free to [open as a discussion](https://github.com/jamulussoftware/jamulus/discussions) if you want.
