### ISSUE TITLE
Jamulus Server - Direct Input Tracks to [ASIO] Outputs

### ISSUE THREAD

**Issue by ceccareb** [jamulussoftware/jamulus#1359]
The Jamulus server can record client stereo/mono tracks in a Reaper project.   

Given:   Reaper supports ReaRoute which is a virtual ASIO card.   ReaRoute has many inputs and outputs.

Feature:   Add the ability to the Jamulus Server to direct the incoming client tracks to audio inputs of ReaRoute.   

Purpose:   I can now tell Reaper, in real-time, to ingest the audio inputs from Jamulus Server and direct them to separate Reaper tracks.  I can then tell Reaper how to mix each Reaper Track.   I use Reaper as the mixer.   I forward the mix from Reaper to OBS (online broadcasting software).   OBS knows ReaRoute too.   OBS then inputs the output channels from Reaper, combines those channels with video, then records the video or livestreams the video to FaceBook or YouTube.

Example:   I want to tell Jamulus to output my friend Mike's guitar and vocal tracks to ReaRoute's input channels 1 and 2, the bass player Dave's to ReaRoute input channels 3 and 4, etc.   

I use Reaper as the mixer.   I tell Reaper to put ReaRoute 1 and 2 as the source from the guitar and vocal, 3 and 4 for bass and vocal.    I can pan channel 3 to the middle, 4 to right, adjust volume, even add a VST effect.    This is all real-time using the "Audio Monitor = Yes" in Reaper.

Using Reaper, I mix to a stereo out--another ReaRoute channel.

I tell OBS to use the audio input from the ReaRoute channels that were output from Reaper.

**Comment by gilgongo** [comment]
@ceccareb this may need some discussion so I'll move it over there if that's OK.
