### ISSUE TITLE
Move advanced settings to advanced tab

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1374]
**Has this feature been discussed and generally agreed?**

No, but @dcorson-ticino-com already implemented parts of it it in his new UI proposal. 

**Describe the solution you'd like**

Before making big UI changes, I propose to do it in small steps. I think we should start with moving advanced settings in a separate tab in the settings window.

I‘d propose:

1. Move the pan slider there
2. Move the custom central server box there
3. Move feedback detection and input gain there

**Describe alternatives that have been considered**

Leave new settings in the settings dialog which would grow and might get confusing one day.

**Comment by dcorson-ticino-com** [comment]
OK, I'll make a PR with this when we have agreed.
Do we want to put a tab with the user profile in the settings too ?

**Comment by ann0see** [comment]
Yes. That's a good idea. Nevertheless, the current way to open it View>My Profile should still work and open settings

**Comment by henkdegroot** [comment]
> 1. Move the pan slider there

Are you referring to the pan slider that I (as musician) can use to pan between the left and right channel?

As if so, I am regular using this slider to "switch" between mic's. I understand most people may use it to balance between left and right and may only need to do this at initial setup or when their setup changes.

Not sure if there are other people using the PAN slider the way I do, but if there are..perhaps a few select buttons could help?
I.e. 1 to select Left, 1 to select Right, 1 to select "PAN setting/Mix"?

**Comment by ann0see** [comment]
You can always have settings open to switch it there. 

I usually leave it open to monitor my network buffer and ping.

**Comment by DavidSavinkoff** [comment]
The link below points at the quoted text. Three proposals are made which are confusing. My questions are:
1) where?
2) where?
3) where?

https://github.com/jamulussoftware/jamulus/issues/1374?_pjax=%23js-repo-pjax-container#issue-842680546


> **Has this feature been discussed and generally agreed?**
> 
> No, but @dcorson-ticino-com already implemented parts of it it in his new UI proposal.
> 
> **Describe the solution you'd like**
> 
> Before making big UI changes, I propose to do it in small steps. I think we should start with moving advanced settings in a separate tab in the settings window.
> 
> I‘d propose:
> 
>     1. Move the pan slider there
> 
>     2. Move the custom central server box there
> 
>     3. Move feedback detection and input gain there
> 
> 
> **Describe alternatives that have been considered**
> 
> Leave new settings in the settings dialog which would grow and might get confusing one day.

**Comment by ann0see** [comment]
>  in a separate tab in the settings window.

**Comment by henkdegroot** [comment]
> You can always have settings open to switch it there.

Making sense now....after checking the proposal!! I love the new GUI!

**Comment by dcorson-ticino-com** [comment]
Do we have a suggestion of how to reformat the main page if we put the pan in the advanced settings ?
Personally I would put the remaining reverb slider at the very left, push the leds down with reverb above them.
Other suggestions ?

**Comment by dcorson-ticino-com** [comment]
After implementing this I have to say I am not a friend of "Basic" and "Advanced".
Those titles give me no hint as to where I need to look for a certain setting.
I much prefer "Audio" and "Network" that give me an idea where to look (corrected, of course, so that the settings are where they belong).
What do you think ?

**Comment by ann0see** [comment]
Probably yes. However, Network and Sound settings are something related (and should be in the same tab), while the Skin, central server,... are really one time only settings and therefore can be moved somewhere out of sight.

**Comment by henkdegroot** [comment]
> Personally I would put the remaining reverb slider at the very left, push the leds down with reverb above them.

Not sure if removing the PAN should be done in the current GUI. It makes sense in the new GUI you are working on, but not in this as you leave blank space and now seeking a way to fill in the gap or remove it. I guess moving it to the very left will increase the minimum window size. My vote would be to move the input VU meter above the Reverb, as they are all related.

> After implementing this I have to say I am not a friend of "Basic" and "Advanced".

Yes indeed, it would help for users to have some idea of the settings being available in the option shown. So perhaps Network/Sound in the main tab and User Preferences as a second tab?

**Comment by dcorson-ticino-com** [comment]
Here are some images of the state I have now for discussion.
The menus and buttons continue to work as they have, My Profile Profile raising the settings window with the My Profile tab on top, Settings raising the settings window with the Basic tab on top.
One thing that needs to be looked at is how the Basic tab works with other OSs using more fields.

![NewPR01a](https://user-images.githubusercontent.com/64357360/112894986-d6730880-90dc-11eb-813b-46ec07e9c53b.JPG)

![NewPR01b](https://user-images.githubusercontent.com/64357360/112895005-dbd05300-90dc-11eb-90b5-5b430b52a382.JPG)

![NewPR01c](https://user-images.githubusercontent.com/64357360/112895026-e0950700-90dc-11eb-91ec-3bf55786b753.JPG)

![NewPR01d](https://user-images.githubusercontent.com/64357360/112895041-e559bb00-90dc-11eb-87f4-1f4cf54fcf2e.JPG)

**Comment by ann0see** [comment]
Yep. In my opinion that looks great! 

Maybe we could name the basic tab Audio/Network?
