### ISSUE TITLE
'jamulus -s' window doesn't show up when user clicks on the tray icon

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1393]
This code snippet leads to a correct behavior:

```
       connect(&trayIcon, &QSystemTrayIcon::activated, [this](QSystemTrayIcon::ActivationReason reason) {
                switch (reason) {
                case QSystemTrayIcon::DoubleClick:
                case QSystemTrayIcon::Trigger:
                        if (isVisible() && !isMinimized()) {
                                hide();
                        } else {
                                showNormal();
                                activateWindow();
                        }
                        break;
                default:
                        ;
                }
        });
```

**Comment by ann0see** [comment]
Ok. Since you already have a fix, can you open a draft Pull request and link it to this issue by writing 

Fixes: #1393

and a short description in there?

**Comment by dcorson-ticino-com** [comment]
Are you sure?  
Under Win10 this works, but the icon shown is an LED and not the server icon.
It would be self explanatory if it showed the Jamulus server icon.
This should be corrected.

**Comment by yurivict** [comment]
> It would be self explanatory if it showed the Jamulus server icon.

This isn't related to the type of icon. Proper icon should be installed along with the program.

For the record: I use FreeBSD 12.2

**Comment by pljones** [comment]
Does #1731 fix this?

**Comment by gilgongo** [comment]
@yurivict Are we OK to close this now as per #1731 ?

**Comment by yurivict** [comment]
Ok.
