### ISSUE TITLE
Jamulus.pro: Rename WITH_SOUND to WITH_JACK

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1408]
**Describe the bug**
Jamulus.pro uses the `WITH_SOUND` define to enable/disable jack support. This is confusing.

**Expected behavior**
This should rather be `WITH_JACK`

**Version of Jamulus**
d5d4691221b76bc648d605dac867aeaa561d0a52

**Additional context**
Usage of the WITH_SOUND define has to be updated in the code as well, of course.

**Comment by djfun** [comment]
That's pretty simple to do with something like
`find . -type f | xargs sed -i 's/WITH_SOUND/WITH_JACK/g'`

**Comment by hoffie** [comment]
@djfun Yes, should be. Feel free to send a PR (maybe wait for one or two days if some other @jamulussoftware/maindevelopers thinks that fixing this issue this way is not a good idea ;)).
