### ISSUE TITLE
HTML status file contains wrong information after terminating the Jamulus server

### ISSUE THREAD

**Issue by drummer1154** [jamulussoftware/jamulus#1423]
**Describe the bug**
The HTML status file created by the command line option "-m myStatusPathname.dat" contains wrong information after the server was terminated by receiving SIGTERM. It wrongly contains the last status **prior to server termination**, either that no client is connected or the list of previously connected clients.

The file contents suggests that the Jamulus server is still running where in fact it is not.

**To Reproduce**
Please note that multiple status file lines are reproduced below w/o markup in one line.
- Start Jamulus as server with command line options
o -s
o -d
o -m myStatusPathname.dat
- Read myStatusPathname.dat => "No client connected" => OK
- Have client "MyClient" connect to the Jamulus server
- Read myStatusPathname.dat => "MyClient" => OK
- Send SIGTERM to the Jamulus server which then terminates
- Read myStatusPathname.dat => "MyClient" => NOK

**Expected behavior**
Prior to terminating itself, the server shall write "Jamulus server terminated." into myStatusPathname.dat.

**Screenshots**
n/a

**Operating system**
GCP n1-standard-1, debian-10-buster-v20210217, Jamulus built from source
git clone https://github.com/corrados/jamulus.git
cd jamulus
git fetch
git checkout latest
=> HEAD is now at 337a484 r3_6_2
qmake "CONFIG+=nosound" Jamulus.pro && make clean && make

**Version of Jamulus**
3.6.2

**Additional context**
Same behavior in Windows when quitting the server via Ctrl+Q or clicking Window - Exit.

**Comment by hoffie** [comment]
Thanks for the report. I agree that we should attempt to empty the file on exit.

**Comment by drummer1154** [comment]
I can confirm that in Release 3.8.0 the behavior is OK now, tested today after installing 3.8.0 on Debian (HEAD is now at e7458913 Update version to 3.8.0 for release).
Thanks a lot to all involved.
Cheers
Helmuth
