### ISSUE TITLE
Replace non-ASCII characters in recording file names

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#1424]
As discussed in https://github.com/jamulussoftware/jamulus/discussions/1384 

Jamlus supports unicode characters in profile names (as it should), and the OS will also support them in file names too. However, Audacity (and possibly other apps) don't support unicode characters in file names. So if a profile name contains such a character, the server operator cannot import the recording file(s) due to the unicode character being present.

A suggested fix for this is to replace any non-ASCII characters with for example a hyphen when Jamulus writes the recording file using the client's profile name (so the LOF file will use the corrected filenames).

**Comment by reinhardwh** [comment]
Hello Jonathan, gilgongo,

excellent, thanks a lot.

One remark:
Also the LOF file should use the corrected filenames.

**Comment by DavidSavinkoff** [comment]
Why can't the server operator simply rename the file?

**Comment by softins** [comment]
> Why can't the server operator simply rename the file?

Because the filenames are also referenced within the Reaper and Audacity project files.

PR to follow.

**Comment by reinhardwh** [comment]
Excellent
Well done
Filenames and LOF created without special characters
Thanks a lot
