### ISSUE TITLE
I lose other performers when I hit a big cymbal crash

### ISSUE THREAD

**Issue by billthedrummer** [jamulussoftware/jamulus#1445]
**Describe the bug**

I have a Roland VAD-506 e-kit, and after I upgraded to the 3.7 client, when I hit a big cymbal crash, I can't hear any of the performers any more. I'm also on a 3.7 server, so I'm not sure what's causing the problem. I have to stop and restart Jamulus. I haven't changed any of my volume settings.
**To Reproduce**

Hit a loud cymbal crash or double cymbal crash on an e-kit when in a session with other performers.

**Expected behavior**

It shouldn't kick off the other performers.
**Screenshots**

**Operating system**

Windows 10 client from OpenSource, Vultr server
**Version of Jamulus** 3.7

**Additional context**

I'm going to downgrade my client and see if that fixes the problem.

**Comment by gene96817** [comment]
1- when you hit a big cymbal crash, does your channel clip? How long does the clipping condition last?
2- does the condition clear 30 seconds after the clipping condition clears?
3-
> I can't hear any of the performers any more

> It shouldn't kick off the other performers.

That's two different conditions. In the first, you don't hear the other performers but they are still connected. Does their VU meter show activity? The second implies, everyone is disconnected and you are the only person connected?

4- after the crash, if the other performers are connected, turn off Settings/Enable Small Network Buffers and then turn it back on again. That should flush your buffers. Do you now hear the other performers?

**Comment by billthedrummer** [comment]
Hi thanks for the quick response. Sorry, that wasn’t clear. I do see their meters, I just don’t hear them any longer. My channel doesn’t clip, and it doesn’t clear.

I had Enable Small Network Buffers turned off. I understood that didn’t matter. I turned them on, though, and will try that.

**Comment by gene96817** [comment]
I suggest turning on Enable Small Network Buffers, at the largest setting. Then when you get this condition, set the buffers to the smallest setting for 5 seconds and then set it back to the large setting. (The other sequence, small to large back to small, might not work.

**Comment by dcorson-ticino-com** [comment]
> I do see their meters, I just don’t hear them any longer. My channel doesn’t clip, and it doesn’t clear.

That sounds to me like a problem with your audio interface.  If Jamulus doesn't even clip and the meters run normally it doesn't look like a Jamulus problem.  When Jamulus restarts it also resets the audio interface.
What happens if you turn down the input volume some?
When you say restart Jamulus, you mean the client or the server or both ?

**Comment by DominikSchaller** [comment]
You're saying it only happens after upgrading to 3.7, right? Before everything worked.

**Comment by gilgongo** [comment]
Moving to discussion since this isn't clear cut yet.
