### ISSUE TITLE
Musician name wrapping cuts through Unicode Symbols

### ISSUE THREAD

**Issue by passing** [jamulussoftware/jamulus#1451]
**Describe the bug / how to reproduce**
If you use a Unicode Symbol / Emoji as the 8th character in your Profile, e.g. `Mr. Hu 🍽`, then the Symbol is split in half:

**Expected behavior**
The symbol should be displayed correctly

**Screenshots**
- issue happens with symbol as 8th character:
![image](https://user-images.githubusercontent.com/8142186/113585326-601a5d00-962c-11eb-930c-1ed4e48edd0e.png)
- works with the symbol at any other place:
![image](https://user-images.githubusercontent.com/8142186/113585333-63154d80-962c-11eb-838c-2201fb33f249.png)

**Operating system**
issue occurs at least on Windows 10 and Linux (Ubuntu)

**Version of Jamulus**
3.7.0

**Comment by hoffie** [comment]
Thanks for reporting. Not sure if support for such icons has ever been announced, but I agree that it sounds like a bug. Are you planning to work on this?

**Comment by softins** [comment]
Just had a quick look at this. The test wrapping is done manually in `CChannelFader::SetChannelInfos`, which is in `audiomixerboard.cpp`. That function adds in `\n` characters without being Unicode-aware. It should be possible to do it correctly by iterating over the `QString strModText`, but I don't have time to work on an implementation at the moment. Hopefully this should point someone in the right direction, though.

**Comment by djfun** [comment]
I tried to implement something using QTextBoundaryFinder:
https://github.com/djfun/jamulus/commit/3efd59c8354c0ba0cdddf76d46ade046ce0b42d3

btw. I noticed that the Name input field in the Profile dialog also has problems with these characters when the maximum length is reached

**Comment by softins** [comment]
> I tried to implement something using QTextBoundaryFinder:
> [djfun@3efd59c](https://github.com/djfun/jamulus/commit/3efd59c8354c0ba0cdddf76d46ade046ce0b42d3)

Thank you! I looked at `QTextBoundaryFinder` and at your commit. I haven't tried compiling or running it, but it looks promising.

> btw. I noticed that the Name input field in the Profile dialog also has problems with these characters when the maximum length is reached

Maybe the length is being limited by byte count rather than grapheme count? (Just a guess - I haven't looked at the code)

**Comment by djfun** [comment]
> > btw. I noticed that the Name input field in the Profile dialog also has problems with these characters when the maximum length is reached
> 
> Maybe the length is being limited by byte count rather than grapheme count? (Just a guess - I haven't looked at the code)

https://github.com/djfun/jamulus/commit/ce370e95d43b2051ba20160e5ec50f13b2de5748
This should respect the byte count and not split any multibyte characters
