### ISSUE TITLE
Virtualization-Issue Windows Server 2019

### ISSUE THREAD

**Issue by AndreasMAlz** [jamulussoftware/jamulus#1461]
**Describe the bug**
Terrible Audio-Performance von Windows Server 2019 at HyperV (Strato V-Server V40).

**To Reproduce**
Connect to private Jamulus-Server on Strato V-Server Windows V40.

**Expected behavior**
Perfect Audio-Quality at a Server with 6 vCores, 8GB RAM and 1 Gbit/s network rate.

**Screenshots**
It's just to hear.

**Operating system**
Clients: Windows 7, 8 and 10, MacOS (all clients have approx. the same Audio-Issues)
Server: Windows Server 2019

**Version of Jamulus**
3.7.0 on Server and some clients. Other clients still use 3.6.2

**Additional context**
I carried out some rehearsals of a choir with up to 30 singers, equipped with good headsets, at a virtual machine on Microsoft Azure (Standard B2ms, Region Germany-West-Central). The audio-quality was quiet good (Settings: mono-in, stereo-out, "normal" quality). After change over to a V-Server hosted by Strato.de (HyperV) we have growing issues with the sound quality. While ping-times are good, the singers complains "bubble-sound" and drop outs. Latency and Puffer are mostly red or yellow, rarely green. The amount of virtual RAM on the HyperV-Server from Strato ist the same as at MS Azure. The Azure-VM had only 2 vCPUs but 50 GBit/s network-rate, while the Strato-Server just have "up to 1 GBit/s" connection. I guess the reason is the virtualization, that provide just the amount of RAM that actually is needed by Windows. Or are there other possible causes? How should I configure the virtual Windows Server 2019 to provide optimal performance to Jamulus? Thanks beforhand.

**Comment by hoffie** [comment]
Thanks for your report. We're using the Github issues for bugs and fully specified feature requests only while your question sounds like a support request. I'm therefore moving this to a discussion. :)
