### ISSUE TITLE
[server] starting server with -e option when central server is full.

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulus#1476]
**Describe the bug** [EDIT] -+
Starting a server with the -e option, if the central server is full: the server does not -(start)+register to this central as soon as it is full!

**To Reproduce**
- Wait until anygenre1 is full,
- start Jamulus with `-s -e anygenre1.jamulus.io:22124` options,
- if anygenre1 is selected on the list, the server -(never starts)+don't register to another central server.

**Expected behavior**
Don't know what as to be expected here, just jump automatically to another central server, maybe?

**Screenshots**
[Screenshot](https://imgur.com/ekkIrR4.png)

**Operating system**
Archlinux, but I don't know if it's OS dependant.

**Version of Jamulus**
Jamulus, Version 3.7.0
**Additional context**
Don't know if it's the same with no gui or service.

**Comment by dcorson-ticino-com** [comment]
The server will start as soon as the central server has a free slot.

**Comment by gene96817** [comment]
This intended to be a friendly question.
What is the benefit of waiting for a free slot at the central (directory) server?
Would be better for the server to start and let the registration eventually catch up? In this way, regular users of the server could use the IP address to connect. Less convenient but at least the server will be available for use.

**Comment by dcorson-ticino-com** [comment]
To be perfectly honest, I am not 100% sure that the server really doesn't start, and I didn't understand the question of the OP that way.  But it does not show up in the directory list, which for users looking for it means it isn't there, i.e. didn't start.

**Comment by jujudusud** [comment]
Oh yes ! Apologies if I don't use the right words... excuse my poor english, french guy here.
@dcorson-ticino-com you are perfectly right !
- the server starts but can't register to the central server, I will edit my first comment in order to tell the right things.
- the server will automatically register as soon as the central as a free slot. 
So, it works as expected.
yes @gene96817 it is a friendly question. :-)

Now another behavior I don't understand. When starting the server as said  (-s -e), if the central server is full and another server is selected in a prior use with the drop-down menu in jamulus server GUI, the server tries to register on the full server and after that tries the one selected (by the prior use, not intentionally) and register if it is not full. don't know if I am clear.
It seems that `-e` option filled the "custom central server address of the GUI not taking care of the drop down list "genre".

Just to discuss and understand, or tracking a bug if it is one.
