### ISSUE TITLE
Jitter buffer indicator going crazy on all my sound cards on a fresh windows 10 install

### ISSUE THREAD

**Issue by newlaurent62** [jamulussoftware/jamulus#1491]
**Describe the bug**
I made a fresh install of Windows 10.

I started a Jamulus server and connected to it using Jamulus client on the same machine.
The jitter buffer changed from green to red and red to green very often on all my sound cards (Zoom U22 and Berhinger XR18) even if i set local and server jitter buffer to 20 !

I installed the last ASIO drivers for all my sound cards as well as ASIO4ALL.

It was working on my previous windows 10 installation.

**Expected behavior**
The  jitter buffer indicator should stabilize to green. These ASIO sound cards worked on my previous windows 10 installation.

**Operating system**
Windows 10 version : 19042.867, Windows Feature Experience Pack 120.2212.551.0 .

**Version of Jamulus**
3.7.0

**Notes**
The previous windows 10 installation was made by the maker. I did the new one so may be i forgot some steps to get my windows ready for Jamulus ? (drivers ...)

**Comment by hoffie** [comment]
Thanks for your report. This looks like a machine-specific issue at first glance, therefore I'm moving this to a discussion. If it turns out to be a Jamulus bug, we'll open a more specific Issue later.
