### ISSUE TITLE
Servers on custom central server not visible for some clients

### ISSUE THREAD

**Issue by DominikSchaller** [jamulussoftware/jamulus#1502]
**Describe the bug**
In the last two weeks we have some clients which cannot see any server on our custom central server.

**To Reproduce**
Use this central server: jamulus.herrenbesuch.net
Open Connection dialog and select Custom list.

**Expected behavior**
Every client should be able to see the servers.

**Version of Jamulus**
The server version is a patched 3.6.0 server with some local changes.
It seems like all problematic clients are on 3.7.0. But it works for some clients with 3.7.0.
I wasn't able to get more information about the problematic clients yet. It works for me, but I'm still on the 3.6.2 client. Maybe you guys can try to connect to the server and see if there is any problem?

**Comment by hoffie** [comment]
Works for me with both 3.6.2 and current (post-3.7.0) master.

Is there any evidence that it works with 3.6.2 reliably and stops working with 3.7.0?

Traffic captures would always help, but could be hard to get from non-technical people. Maybe you could get at least one from the server side?

**Comment by DominikSchaller** [comment]
Thanks, I will ask them for more details. It happened last week on another server I manage, and today it happened in our rehearsal but I didn't want to spend too much rehearsal time investigating the problem. I just gave them the IP:port and had them type it in directly.

**Comment by DominikSchaller** [comment]
@hoffie What do you mean by traffic captures? Can I get these after the fact (log files)? Or can you tell me what I should prepare for the next test with these guys?

**Comment by hoffie** [comment]
Moving this to *Bug Investigation* for now until we know if/where a fixable issue is. :)
