### ISSUE TITLE
Crash after loud buzz while playing loudly

### ISSUE THREAD

**Issue by dcorson-ticino-com** [jamulussoftware/jamulus#1509]
**Describe the bug**
Jamulus crashed (my very first crash in almost a year of use) after buzzing loudly.  We were playing loudly, but I don't know if it was clipping.  I simply restarted Jamulus and reconnected and continued without a problem.

**To Reproduce**
Doesn't reproduce

**Expected behavior**
Doesn't crash ever

**Screenshots**

**Operating system**
Win10 1909

**Version of Jamulus**
https://github.com/dcorson-ticino-com/jamulus/tree/NewUI-DCO

**Additional context**
The others in the session didn't hear or notice anything other than I was gone suddenly.  They heard no noise, so it was my client. On the Internet the only difference between NewUI-DCO and 3.6.2 is a server list request once a minute.

Are there any possible reasons why playing loudly could cause a crash?
Does a loud buzz for about 0.5 seconds give any clue what could have happened?
Maybe it was a poorly aimed gamma ray that headed into a FET in my CPU (AMD Ryzen7), but are there any possible ideas for a bug?

**Comment by ignotus666** [comment]
I've had this happen a couple of times too - loud playing causing a buzz and an immediate crash. I reconnected and the person I was jamming with said he'd also experienced it occasionally (my crash didn't affect his connection). I've since made sure my input gain is at an appropriate level and it hasn't happened again, but I can definitely say my input was clipping when it occured. A hard kick drum + crash cymbal hit were the culprit. 

I just figured the crash was my own fault for not setting the gain right, but maybe it shouldn't crash?

**Comment by DavidSavinkoff** [comment]
Maybe it is in the opus library code. Which Jamulus version crashes?

**Comment by dcorson-ticino-com** [comment]
> Maybe it is in the opus library code. Which Jamulus version crashes?

It is my own https://github.com/dcorson-ticino-com/jamulus/tree/NewUI-DCO
It is based on 3.6.2, lots of changes in the UI, but none in the protocol or audio data stream.

**Comment by ignotus666** [comment]
I'm using 3.7.0

**Comment by hoffie** [comment]
So, with several people having reported this, it's likely that there is an issue hidden somewhere. However, in order to track this down, we will either have a way to reproduce this (I'm thinking of playing the problematic sound via jack or similar) or we will at least need some debug data.

Is one of the affected people (@ignotus666?) on Linux by chance? A Jamulus debug build (replacing `release` by `debug` in `Jamulus.pro`, running `qmake && make`) should provide a helpful coredump/backtrace. Systemd seems to log this automatically. This might be a practical way to capture relevant data.

**Comment by billthedrummer** [comment]
Something similar happened to me Sunday. I was switching outputs on my e-kit from Direct to Master (long story) and didn't notice I had the Master volume cranked up on the brain. It made a horrendous noise, and knocked me and my bandmates completely off the server. And, it destroyed Jamulus on my Vultr server! Maybe try that as a use case?

**Comment by ignotus666** [comment]
Yes, I'm on Linux and I could look into it, but I'd need detailed instructions as I've never done that kind of thing.

**Comment by ignotus666** [comment]
Ok, just did some testing:

I programmed a thundering blast beat in MIDI, fed it into Jamulus via Jack Mixer and Superior Drummer, and cranked input gain up (speakers/headphones off of course). 

3.7.0 wouldn't crash no matter what abuse I put it through - minutes on end of severe clipping, sudden spikes in gain; nothing. I then tried with the NewUI-DCO version and it crashed immediately. I must have been using that version when it happened (I had it installed for a few days) so apologies for the misleading report that it was 3.7.0. 

I also tested 3.6.2 as that's what NewUI-DCO is based on and no crashing either. So I suppose the question remains what version @billthedrummer is using.

**Comment by billthedrummer** [comment]
I was on 3.7.0 on the server, 3.6.2 on the client.

**Comment by dcorson-ticino-com** [comment]
Thanks for the testing Ignotus.
Interesting that it crashing is tied to volume with my NewUI as there is no change to the sound data flow.
At first thought it must be a protocol problem as although I have not added any new protocol items the timing will be different in the NewUI.
I will keep an eye out as to what it could be.  Have you also felt that once in a while  in the NewUI there are big lags before anything happens, after disconnecting, for example.  That may be related.
In any case it looks like the problem may be NewUI and not Jamulus standard versions.

**Comment by hoffie** [comment]
I was wondering whether it might have to do with the clipping indicator. Maybe NewUI has a bug there or makes an existing bug more likely to occur. I haven't looked at the code yet, but this is the first thing which comes to mind regarding this.

As @billthedrummer is using the official Jamulus versions, this issue does not seem to be NewUI-only, so I'd like to keep this issue open and would request anyone who hits this would add as much details as possible (especially a stack trace).

As long as @ignotus666 is the only person who can reproduce this issue at will (?), it may even make sense to start debugging with NewUI (in the hope that it is still the same bug, but just more likely due some reason).

@ignotus666 Can you try getting a debug dump? Can you try [compiling from source as per the docs](https://jamulus.io/wiki/Installation-for-Linux) but with my changes mentioned [above](https://github.com/jamulussoftware/jamulus/issues/1509#issuecomment-819632663) and try to reproduce the issue?

**Comment by ignotus666** [comment]
I won't be able to look into it until tomorrow night but I'll do the tests you guys suggest.

@dcorson-ticino-com, to try and reproduce it, you just have to blast the input with an audio source at high gain. I know nothing about Windows but it should be doable 
I tested 3.7.0,  NewUI, 3.6.2 and the current git version. Would you like me to carry on with earlier versions?

**Comment by dcorson-ticino-com** [comment]
>Would you like me to carry on with earlier versions?

No, but I will make a new version of the NewUI removing the biggest difference to 3.6.2 in the data transfer.

@hoffie there is a change in the clipping behaviour in NewUI as I discovered that 3.6.2 was setting clipping too late for my ears.  I hear distortion before the clipping indicator showed, so I lowered the level needed for clipping a tiny bit using a floating compare instead of the integer overflow. I don't have any ideas why that might cause a problem 'though.

**Comment by DavidSavinkoff** [comment]
Maybe the opus or floating point library are returning a not-a-number or a divide-by-zero because of an instability. Change the compile options so that the math error can be recovered (maybe also add fake silence for a moment to stabilize).
Loud signals should be tamed before they hit your computer because the result is undefined.

**Comment by ignotus666** [comment]
I finally got round to compiling NewUI again with the changes indicated by @hoffie to get a debug dump and... this happens: I can't get the debug build to crash no matter what I throw at it, while a "normal" build will crash immediately when stressed with high gain. I have restarted and recompiled several times to confirm the behaviour and it's consistent. Dunno if this could provide any clues...

**Comment by hoffie** [comment]
So it sounds like a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug). :)

Just to confirm, you are comparing two builds from the exact same git revision with the exact same instructions except for the debug flag, right?

The debug build causes different compiler options to be used. Most notably, optimizations are turned off (no `-O2`) and debug symbols are enabled (`-g`).

1. Can you try a regular build with added debug symbols? This would involve `make distclean` to get clean up and running `qmake QMAKE_CXXFLAGS=-g && make` to run the actual build. I'm hoping that this may still exhibit the problem but might have useful debugging data. `Jamulus.pro` should be kept unchanged for this test (i.e. start with a fresh source tarball or run `git checkout -f Jamulus.pro` if you are using a git checkout)
2. Are you running a system with systemd? If so, I suspect that even without debugging systems you should get a crash dump in `journalctl -f -n3000`. Can you check that and share it here? I assume it will contain lots of `???` lines without debugging symbols, but maybe we can find a hint anyway.

**Comment by gilgongo** [comment]
Any advance on this? I take it it's reproducable, but we don't know why its happening, is that right? I also don't think we've had any other reports of this issue in the last two months. 3.8.0 has also been release since, does it still happen?

**Comment by ignotus666** [comment]
I could only ever get a regular build of NewUI-DCO to crash - no other builds showed this behaviour in my tests. I suppose it would have been useful to know why that particular build crashed in order to prevent the same behaviour from ever creeping in again, but I never got round to doing hoffie's last suggested tests.
