### ISSUE TITLE
QFSFileEngine::open: No file name specified

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#1513]
**Describe the bug**
When Jamulus client is run from the command line, the warning message `QFSFileEngine::open: No file name specified` gets displayed at times in the program output. It happens every time a new fader gets displayed.

**To Reproduce**
Start Jamulus from the command line: `Jamulus` or `./Jamulus`, etc. Then connect to a server. The message will be displayed for each displayed channel.

**Expected behavior**
No warning message.

**Operating system**
Observed on Linux, running on Raspberry Pi or Intel PC.

**Version of Jamulus**
All versions to 3.7.0

**Additional context**
The cause is this line in `src/audiomixerboard.cpp`:
```
"QSlider::groove { image:          url();"
```
`url()` should not have a missing parameter.

**Comment by dcorson-ticino-com** [comment]
This also happens on Win10 and has been happening at least since 3.5 when I started looking at the code.
It appeared to me to be linked to stylesheets as one can cause more to happen with an invalid stylesheet.
How did you figure out the cause?

**Comment by softins** [comment]
> How did you figure out the cause?

I was running the Jamulus client on my Pi from the command line so I could see the output, and I noticed that a new instance of the error came up every time a new fader was created for a connected client. So I looked closely at the code that created the fader and noticed the empty `url()`.
