### ISSUE TITLE
Can't change my own volume in the mixer. Remains constant

### ISSUE THREAD

**Issue by barrissimo** [jamulussoftware/jamulus#1550]
**Describe the bug**

My own volume remains at some constant level. Pushing the slider up or down all the way doesn't alter it.
**To Reproduce**

Every session, every time. Been noticing this for a while.

**Expected behavior**

... Some control over my volume in the mix. And since I'm playing a wind instrument, I'm already getting some live acoustic sound in my head, so I need less in the mix than might be typical.

**Screenshots**

**Operating system**

   Windows 10, 64 bit, home version, current updates. Jamulus downloaded from github.

**Version of Jamulus**
  3.70

**Additional context**

Interface is a mixer plus a Focusrite Scarlett Solo (I doubt this matters, tho.)

**Comment by npostavs** [comment]
> Interface is a mixer plus a Focusrite Scarlett Solo

Perhaps you enabled its "Direct Monitor" function? (the button on the top right, according to the picture here: https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-solo)

**Comment by barrissimo** [comment]
Yup!  My bad! 😝 duhh.
I was using the headphone output, because it's quite a bit hotter than the
phono plug output, which is rather weak.

**Comment by hoffie** [comment]
So it sounds like this was solved, I'm therefore closing this issue. :)
