### ISSUE TITLE
Mix of formal and informal language used in Dutch text

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1558]
**Describe the bug**
Currently the Dutch language is using a mix of formal and informal. I would like to update all to make them consistent, but to that I need to know what the preferred option is.

In some cases the text can be altered slightly to eliminate this, but unfortunately this cannot be done in all cases.

**Expected behavior**
Textstrings should be consistent.

**Additional context**
This is similar as to using du and Sie in German.

**Comment by softins** [comment]
I guess only other Dutch speakers could discuss this. As soon as we have declared feature freeze for the next release, we can get the `.ts` files updated and then translators can work on the updates. That would be a good time to address this present issue in the appropriate way.

**Comment by henkdegroot** [comment]
I believe the "how to you want to approach" someone is something the main/core team should have a say in.

I am sure the Dutch speakers can come to the appropiate agreement in updating them. Sounds like a good plan to perform this once a feature freeze has been declared so it can all be worked on at once.

@jerogee what do you think?

**Comment by dcorson-ticino-com** [comment]
I think that each language should have the say in how this is done in their case.
Note that in English we always use the formal form, to the point that most English speakers do not even know that their language has an informal form or how to use it.

**Comment by softins** [comment]
> Note that in English we always use the formal form, to the point that most English speakers do not even know that their language has an informal form or how to use it.

You mean like _thee_, _thou_ and _thy_?

**Comment by dcorson-ticino-com** [comment]
>You mean like thee, thou and thy?

Yes, general usage of which died out sometime before 1600.

**Comment by jerogee** [comment]
@henkdegroot, all, I agree that consistency is most important, regardless what is decided.

In the German translation (which I consider the reference as Jamulus was English/German at first), there are some old translation strings in the formal form (_Sie_), but now all is consistently informal (_du_).

Choosing informal over formal:
- We stay close to and consistent with the German translation;
- It is more frequent in apps nowadays;

Choosing formal over informal:
- Nobody will take offence or might feel communication to be too direct;
- Tends to come across as more professional.

I have a slight preference for following the German translation, but are quite agnostic about it. @henkdegroot, what is your take on it?

**Comment by henkdegroot** [comment]
@jerogee  I agree with your statement on formal being more professional and informal becoming more used in app nowadays.
I checked the installationg dialogs now as well, and these strings are all using the formal approach.
In the Dutch application text, 30 lines are using the formal method while 10 are using the informal.

With the above in mind I tend to lean towards the formal approach.

**Comment by jerogee** [comment]
@henkdegroot, alright: let's go for formal / professional. If you will update the relevant translation strings, I am happy to help reviewing.

**Comment by ignotus666** [comment]
FWIW I'm using the informal style in Spanish. I suppose how these different registers are perceived in each country varies, but -personally- when someone speaks to me using the formal "usted" it makes me flinch; I find it sounds cold and distant. I'm aware that in other Spanish-speaking regions and countries the formal style is widespread and used in everyday conversation but... if someone's not happy about it they can always localise it.

Interesting about the use of formal/informal English - I was unaware of that too. Thou hast expanded my knowledge and I thank thee ;-)

**Comment by henkdegroot** [comment]
@jerogee  please review the PR.
