### ISSUE TITLE
ASIO4ALL: Selecting Stereo Mix makes audio unusable

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1559]
**Describe the bug**
If you are connected to a server and select a Stereo Mix device (only verified for Connexant ISST Audio) even after unselecting the device neither audio gets in nor out of Jamulus.
**To Reproduce**
1. Connect to a server
2. Open ASIO4ALL
3. Select a Stereo Mix device on top of a working configuration
4. See that the input level shows some audio coming in but at a constant level (so audio input doesnt't seem to work correctly)
5. Unselect the Stereo Mix device

**Actual behaviour**
I could only reproduce this with Jamulus, not with RTL_Utility:

1. Audio processing (in and out) stops
2. If you disconnect from a server and re-connect, Jamulus gives an error ("Your sound card not working correctly")
3. If you select another driver, this one works as expected, however selecting ASIO4ALL again gives the same error message. 
4. If you restart Jamulus, audio processing works again

**Expected behavior**
At least after disabling the Stereo Mix device, Audio processing should still work. 

**Operating system**
Windows 10

**Version of Jamulus**
Latest from master and from PortAudio PR

**Additional context**
I think https://h30434.www3.hp.com/t5/Notebook-Audio/Stereomix-says-quot-Not-plugged-in-quot-when-headphones-are/td-p/6696507/page/2 is somehow related

In RTL Utility I did the following tests which seem to clarify that it's a problem with Jamulus

1. Set up a working configuration 
2. Play a test tone (works)
3. Select Stereo Mix (input is still set to the headphones): No audio can be heared
4. Unselect Stereo Mix and hear the test tone (although I didn't press the test button)
5. Select the test button and hear the test tone

Can someone test it with a Realtek card?

**Comment by npostavs** [comment]
Seems to work without a problem for with Realtek. Both Jamulus and the RTL_Utility are to produce sound when the Stereo Mix is selected in ASIO4ALL. I also seem to recall coaching someone with a Realtek card over the phone to disable the stereo mix and enable to the mic input; it started working immediately, with no need to restart Jamulus.

![image](https://user-images.githubusercontent.com/287742/116020624-ad2e9500-a614-11eb-98d8-fbb5bc7f3e66.png)

**Comment by ann0see** [comment]
Thanks for your information. Contacted the ASIO4ALL dev but didn’t get a response yet.

**Comment by gilgongo** [comment]
Any advance on this?

**Comment by ann0see** [comment]
No. Probably in a state of "we need to live with it"
