### ISSUE TITLE
settings / sound card  stuck in mixed up situation 

### ISSUE THREAD

**Issue by WoStHH** [jamulussoftware/jamulus#1577]
** BugDescription**

With an ASIO soundcard ( Yamaha Steinberg UR22C) in place and active,
Jamulus (3.7.0) AT FIRST USE sends an alert on non accessible channels /equipment
and that it selects onboard resources 

After the alert happened ,  ASIO4All lets the UR select for input and output, but does not work properly
selection of YamahaSteinbergUSB ASIO is possible, but doesnt work either.

Correct installations additionally show InputChannelSelection and OutputChannelSelection headers 
and allows selections
![YAS_Setup](https://user-images.githubusercontent.com/83417942/116583477-afe00180-a916-11eb-8480-27e0c67ef21b.PNG)

 

**To Reproduce**

Use ASIO interface with other DAW e.g.SonoBus. 
Freshly install and start Jamulus, while sonobus still claims YamahaUSBDriver.
Jamulus throws an error message
Jamulus restarted lets you configure audio, but the chosen setup does not work 

**Expected behavior**

when YAS-USB device can be selected , 
available channels should be read again from HW and offered in the dropdown lists

**Screenshots**
void

**Operating system**
Win10 Pro 19042.928

**Version of Jamulus**
3.7.0

**Additional context**

**Comment by dcorson-ticino-com** [comment]
If you have a Steinberg UR22C why are you using ASIO4ALL ?
Download the Steinberg ASIO driver and install it.
Then all works well.

**Comment by WoStHH** [comment]
Hi guys,Yamaha Steinberg ASIO driver is in place  and Works perfekt with JamKazam and SonoBus.With jamulus, when we use YS or A4aWe never get the the in/out Chanel list displayed,  and Sound is broken.Seems if jamulus cant detect ur Channel info or take over control over ur. No Warning or error thrown.Switched Back to sonobus works immediatelyAny Chance to Add a rescan function , or a log function that makes transparent what could not be chosen for what reason?Br WolfgangVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: DonC ***@***.***> Datum: 29.04.21  21:19  (GMT+01:00) An: jamulussoftware/jamulus ***@***.***> Cc: WoStHH ***@***.***>, Author ***@***.***> Betreff: Re: [jamulussoftware/jamulus] settings / sound card  stuck in mixed
  up situation  (#1577) 
If you have a Steinberg UR22C why are you using ASIO4ALL ?
Download the Steinberg ASIO driver and install it.
Then all works well.

**Comment by ann0see** [comment]
I think you can somehow reload the driver by clicking on the driver which is currently selected?

**Comment by gilgongo** [comment]
Closing as no further update on this.
