### ISSUE TITLE
New tabbed setting always opens in My Profile

### ISSUE THREAD

**Issue by Hk1020** [jamulussoftware/jamulus#1581]
When starting Jamulus the new tabbed settings always open in _My Profile_. This makes it rather hard to look at the network settings which is of much more interest once you have set your name. I think the tabs should be remembered just like all the other states,

**Comment by hoffie** [comment]
Thanks for the report. I agree this would be a downside. I'm therefore tagging this for 3.8.0 to avoid introducing a regression / negative behavior change. If others disagree, we can still de-tag.

@dcorson-ticino-com What do you think?

**Comment by Hk1020** [comment]
Actually, I have mixed feelings about the new tabbed window, especially the split of the network section. While it makes some sense comprehension wise it effectively adds another window and that is complexity. And you can’t look at the two tabs at the same time. But I am sure you discussed this when making the change.

**Comment by dcorson-ticino-com** [comment]
I will have to look at the actual artifact.
It should always open to Audio/Network except when accessing from the menu My Profile.
Something is apparently different than in my version.

**Comment by henkdegroot** [comment]
@Hk1020  I have tested with my own build using the latest master and do not experience this behaviour. On my win 10 system, it works as described by @dcorson-ticino-com .

**Comment by Hk1020** [comment]
@henkdegroot So did I last night. I‘ll try again later. But to be sure I am talking about opening Jamulus. 

- Open Jamulus
- Select settings 
- Select network tab
- Close Jamulus
- Open Jamulus

Now the settings window will open with _My Profile_

**Comment by dcorson-ticino-com** [comment]
OK, you're right.  I discovered it just before your message came through.
I see that I don't store the tab state for user, etc.
I will add that.
I have time this evening.

**Comment by Hk1020** [comment]
I‘d also suggest to move the new Number of Mixer Rows or what it’s called to _My Profile_ as that is the place where you set the appearance of your client. Whether that’s a convenient place is another question. I wouldn’t mind to have it accessible with a single click.

**Comment by hoffie** [comment]
> I‘d also suggest to move the new Number of Mixer Rows or what it’s called to _My Profile_ as that is the place where you set the appearance of your client.

I agree. However, we should wait for input from @pljones as the initial author who, as I understood, was opposed to [placing](https://github.com/jamulussoftware/jamulus/pull/1549#issuecomment-825758069) it there.

**Comment by dcorson-ticino-com** [comment]
>I agree. However, we should wait for input from @pljones as the initial author who, as I understood, was opposed to placing it there.

The master I cloned already has the mixer rows in the advanced tab.

**Comment by dcorson-ticino-com** [comment]
The master I cloned has the mixer rows on the advanced tab.
I agree that it has to do with the appearance of the mixer board.
I have no strong opinion, however.
Will wait to hear from others.
BTW: thanks for finding this @Hk1020 , a good beta test is worth a lot.  As I never would use this use case I would never have found it.

**Comment by pljones** [comment]
I hadn't realised what was "My Profile" has local user interface stuff on it when I objected -- I guess it saves a fourth "Display preferences" tab but it was a bit jarring to see the mix.

So I'm not objecting to moving it.
