### ISSUE TITLE
Drift correction missing from Jamulus?

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#1598]
**Describe the bug**
While using BlackHole (virtual audio driver) on Mac to route sound from MainStage/other apps to Jamulus via BlackHole, I experience irregular "scratchiness" in the sound returned by the Jamulus Server.  BlackHole's developer believes that Jamulus is not providing drift correction.

**To Reproduce**
See [this issue in the BlackHole github issues list](https://github.com/ExistentialAudio/BlackHole/issues/381)

**Expected behavior**
No distortion in the sound

**Screenshots**
N/A

**Operating system**
MacOS 11.14.6 Mojave

**Version of Jamulus**
3.7.0

**Additional context**
See linked issue above for full details

**Comment by gilgongo** [comment]
This comment (and the fact that @softins question to the author has so far got no answer) implies the problem may not be due to Jamulus: https://github.com/ExistentialAudio/BlackHole/issues/381#issuecomment-859358548

**Comment by jujudusud** [comment]
Is using JACK server a solution ?

**Comment by gilgongo** [comment]
Any advance on this? Will close otherwise.

**Comment by softins** [comment]
I would close it, as there is not enough information to action. The linked issue on Blackhole has been closed too.
