### ISSUE TITLE
Update fr_FR app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1609]
Hi @jujudusud,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **fr_FR** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update fr_FR app translation for 3.8.0

Fixes #1609
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by hoffie** [comment]
@jujudusud I have opened this for tracking, although I know that you've already done your part. Thanks for the quick work! :)
I have invited you to the Github org and will assign this issue to you once you've accepted the invitation.

**Comment by jujudusud** [comment]
I have accepted the invitation. Thanks a lot for this, I'm proud to be part of Jamulus organisation and will do my best to help.

**Comment by FredNor78** [comment]
Keyboard shortcut assignments

(hope this is the proper place to post)

In the current French version of Jamulus (3.7.0), once connected to a server, the keyboard shortcut <Alt>+C has two functions, on the first stroke: chat button, on the second sroke:"disconnect". As a result, its use is confusing and need additional moves. Could we decide to choose <Alt>+T for "Tchat" and <Alt>+D for "Déconnecter", or at least two different keys?

Thanks for your attention

Fred
