### ISSUE TITLE
Update nl_NL app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1611]
Hi @henkdegroot, @jerogee,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **nl_NL** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update nl_NL app translation for 3.8.0

Fixes #1611
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by hoffie** [comment]
@henkdegroot I have invited you to the Github org and will assign this Issue to you once you've accepted. :)

**Comment by hoffie** [comment]
Also I'm not sure regarding Dutch if @jerogee is also active, so cc'ing as well. :)

**Comment by jerogee** [comment]
Sure, happy for Henk to take on this round. @hoffie, please make sure that Henk gets added to the translation acknowledgements!

**Comment by henkdegroot** [comment]
@jerogee happy to do this. Just one thing do you have any thoughts about how to translate the "Directory server"? (The "Central server replacement)
What do you think about "adresboek server"? Or could we use "directory server"?

**Comment by jerogee** [comment]
I'd suggest "adresboek server": It is more descriptive to a wider audience (esp. non-tech folks).
