### ISSUE TITLE
Update pl_PL app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1612]
Hi @SeeLook,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **pl_PL** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update pl_PL app translation for 3.8.0

Fixes #1612
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by atsampson** [comment]
One thing to look at: pl_PL currently translates "Recorder" in the instrument list as "Flet prosty", which isn't what's intended - from the icon and the other translations, it's meant to be a recording device, not the wind instrument.
