### ISSUE TITLE
Update pt_BR app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1613]
Hi @melcon,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **pt_BR** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update pt_BR app translation for 3.8.0

Fixes #1613
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by Snayler** [comment]
Sorry, this is not my translation, I'm doing pt_PT translation
