### ISSUE TITLE
Update pt_PT app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1614]
Hi @Snayler,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **pt_PT** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update pt_PT app translation for 3.8.0

Fixes #1614
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by Snayler** [comment]
This is my translation, pt_BR is melcon's translation

**Comment by hoffie** [comment]
> This is my translation, pt_BR is melcon's translation

Sorry, fixed!

**Comment by Snayler** [comment]
> Sorry, fixed!

No problem. I'm quite liking this assignment thing, makes it easier to keep track when the translations are needed.

**Comment by softins** [comment]
@Snayler have you had the time to do this? We are nearly at the stage where we want to do a Release Candidate for 3.8.0

**Comment by Snayler** [comment]
Done #1689
