### ISSUE TITLE
Update sk_SK app translation for 3.8.0

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1615]
Hi @jose1711,
We are getting ready for the 3.8.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **sk_SK** until **2021-05-15**.

Please
- Update your fork to current `master`,
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-05-15

Suggested commit and PR message:
```
Update sk_SK app translation for 3.8.0

Fixes #1615
```

Note: The term "Central server" has been replaced with "Directory server"

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by atsampson** [comment]
One thing to look at: sk_SK currently translates "Recorder" in the instrument list as "Zobcová flauta", which isn't what's intended - from the icon and the other translations, it's meant to be a recording device, not the wind instrument.

**Comment by jose1711** [comment]
> One thing to look at: sk_SK currently translates "Recorder" in the instrument list as "Zobcová flauta", which isn't what's intended - from the icon and the other translations, it's meant to be a recording device, not the wind instrument.

Oh.. thanks for pointing that out. Will fix that. How much time do I have for this? Currently I am quite busy translating some other software.

**Comment by hoffie** [comment]
> How much time do I have for this?

We are planning to tag the (hopefully) last release candidate shortly after 2021-05-15, so it would be good to have it until then. Is that realistic?

**Comment by jose1711** [comment]
> > How much time do I have for this?
> 
> We are planning to tag the (hopefully) last release candidate shortly after 2021-05-15, so it would be good to have it until then. Is that realistic?

Thanks, that sounds fine. Will install git version and see what I can do.
