### ISSUE TITLE
What Is This option not available from My Profile settings

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1622]
**Describe the bug**
The "What Is This" option is no longer available for the My Profile settings.
Previously the "My Profile" dialog included the ? in the menu bar to support this.
Right click on the any item (except the new mixer rows item) does not provide access to the "What Is This" details.

**To Reproduce**
Use r3.8.0 beta and open the "My Profile" tab
Right click any item in the musicians profile section, nothing happens.

**Expected behavior**
What Is This details are available and translated as well. So they should be accessible by the users.
Either by adding the ? option to the menu bar or by allowing the right click to show the "What Is This" popup or both :)

**Screenshots**
Screenshot 3.7.0 dialog:
![musician-profile](https://user-images.githubusercontent.com/13550012/116989616-41ae8c80-acd2-11eb-9e5d-8beb13a1c3b9.png)

Screenshot 3.8.0 beta dialog:
![settings-3-8-0](https://user-images.githubusercontent.com/13550012/116989664-53902f80-acd2-11eb-887a-67b9f25c65d8.png)

**Operating system**
Windows 10 Version 20H2

**Version of Jamulus**
r3.8.0beta

**Comment by hoffie** [comment]
>  Previously the "My Profile" dialog included the ? in the menu bar to support this.

I haven't tested (running a tiling window manager with no decorations...), but this may be relevant place regarding the content help hint in the title bar:

https://github.com/jamulussoftware/jamulus/blob/192391d0e3443a452a9317e74e882d577c550be7/src/clientsettingsdlg.cpp#L32

Maybe `Qt::WindowContextHelpButtonHint` would be the [right flag](https://doc.qt.io/qt-5/qt.html#WindowType-enum) to add?

> Right click on the any item (except the new mixer rows item) does not provide access to the "What Is This" details.

I agree that this could be improved, but I'm not sure if it is a regression. Did this part work differently in 3.7.0 as well?

The reason here seems to be that some labels are defined in `.ui` files and probably lack `setWhatsThis` calls. Might be another candidate for a structured check...

**Comment by dcorson-ticino-com** [comment]
Someone with 3.7 still installed please check if this was working there.

In any case selecting Whats This in the Help window works as does shift+F1

It is interesting that the "?" is in place for the Connect window, but also not for the Chat window.  I thought that all 3 had the same base class and should be working the same.  
I will look into it.

**Comment by henkdegroot** [comment]
> Did this part work differently in 3.7.0 as well?

The My Profile dialog does not respond to the "right click" in 3.7.0. Guess that was no needed as the menu bar already has the ? option. Just wanted to mention the right click, as it is now a bit odd that 1 item in the dialog does respond to right click and the others do not.

**Comment by henkdegroot** [comment]
FYI, in 3.7.0:
In the profile dialog, the musician profile only has 1 text showing for the "what is this" option, not a text per label/box.
The skin and language options in the settings dialog do not have a right click "what is this" text (other items do).
The skin option, when select does respond to the shift+F1.

In 3.8.0 the shift+F1 does work for the skin and musician profile option as well.

A difference I noticed in the code is the (taking the skin as example), the "what is this" text is only assinged to the combo box.
Others items have the "what is this" text also assigned to the label.

**Comment by dcorson-ticino-com** [comment]
Strange, these things are set in clientsettingsdlg, but when attached to the edit box or combo box are not working.
Then I attach the text to the corresponding labels they work.
I still haven't found a way to put the "?" in the title with the min and max icons.
I saw a comment saying that isn't possible under Win10 so maybe that is OS dependent.

**Comment by henkdegroot** [comment]
> Then I attach the text to the corresponding labels they work with left click.

Guessing there is a reason why most "what is this" text string are linked to the edit/combo box and the labels.

> I still haven't found a way to put the "?" in the title with the min and max icons.
To my knowledge on windows this is not used very often, so most people won't miss it or even notice it that it is gone.

Perhaps for now just link the text with the labels would work from my point of view.
