### ISSUE TITLE
ActiveTab heading unvisible at MAC 3.8.0beta

### ISSUE THREAD

**Issue by Sommi486** [jamulussoftware/jamulus#1628]
**Describe the bug**
At the actual 3.8.0beta1 in settings there ist no heading for the active tab.
If you change tab it appers again and new chosen tab has no heading.

**Screenshots**
<img width="389" alt="Bildschirmfoto 2021-05-05 um 09 59 14" src="https://user-images.githubusercontent.com/42489734/117113606-fefcbb00-ad8a-11eb-9525-cb29caf12bd9.png">

<img width="399" alt="Bildschirmfoto 2021-05-05 um 10 18 26" src="https://user-images.githubusercontent.com/42489734/117113776-3f5c3900-ad8b-11eb-83d8-69b45e03be98.png">

**Operating system**
Big Sur 11.3

**Version of Jamulus**
3.8.0beta1

**Comment by softins** [comment]
I suspect it is white text on a white background. Do you use dark theme or light theme? Or another (I only have Mojave, not Big Sur). Can you change themes and try again?

**Comment by Sommi486** [comment]
I use dark theme.

Changing to light theme doesn't solve the bug.

**Comment by softins** [comment]
This is what it looks like on my Mac running Mojave:
![image](https://user-images.githubusercontent.com/3224952/117132804-3e330800-ad9b-11eb-94ba-8110cb25a360.png)
What does a tabbed dialog from another app look like on your system?

**Comment by softins** [comment]
Looks like this bug is not specific to Jamulus
https://forum.qt.io/topic/120907/macos-big-sur-and-qtabwidget-bug

**Comment by Sommi486** [comment]
Here is how it looks on Catalina:
![Bildschirmfoto 2021-05-05 um 13 22 18](https://user-images.githubusercontent.com/42489734/117134391-d0d8a480-ada5-11eb-83e9-616b52f54dec.png)

This is how other Apps look on BigSur:
<img width="243" alt="Bildschirmfoto 2021-05-05 um 13 27 49" src="https://user-images.githubusercontent.com/42489734/117134441-e2ba4780-ada5-11eb-8669-eed1ac8bf2ef.png">

And this is how BigSur Settings look in dark & light mode:
<img width="413" alt="Bildschirmfoto 2021-05-05 um 13 24 05" src="https://user-images.githubusercontent.com/42489734/117134515-f6fe4480-ada5-11eb-9577-8d2316aca916.png">
<img width="412" alt="Bildschirmfoto 2021-05-05 um 13 23 48" src="https://user-images.githubusercontent.com/42489734/117134535-fc5b8f00-ada5-11eb-926f-d0a1481c229c.png">

**Comment by softins** [comment]
Hmm, so Big Sur has broken stuff, leaving framework and app developers to pick up the pieces. Typical!

Not sure of the current status of Qt, but looks like it will affect all apps built with Qt, and only fixed, sometime, with Qt 5.15.x and Qt 6. :(

We currently build with Qt 5.9 for maximum backward compatibility with older macOS versions.

**Comment by softins** [comment]
@Sommi486 please could you try the version at https://github.com/jamulussoftware/jamulus/suites/2658566875/artifacts/58504147 on your Big Sur machine? It is a fresh build using Qt 5.15.2. I expect that it shows the same problem, but would like to be certain.

Despite the strange URL above, it is a dmg contained within a zip file.

**Comment by Sommi486** [comment]
Looks much better. some Glitches with the blue small Line and a asymmetric Effekt Slider. 

<img width="377" alt="Bildschirmfoto 2021-05-06 um 08 24 42" src="https://user-images.githubusercontent.com/42489734/117251583-24e69600-ae45-11eb-93f6-8b0c21eef9f7.png">

<img width="375" alt="Bildschirmfoto 2021-05-06 um 08 24 52" src="https://user-images.githubusercontent.com/42489734/117251594-2adc7700-ae45-11eb-9421-29d6c1e5b14c.png">

<img width="99" alt="Bildschirmfoto 2021-05-06 um 08 25 12" src="https://user-images.githubusercontent.com/42489734/117251602-2fa12b00-ae45-11eb-8d52-b2eff2859daf.png">

**Comment by softins** [comment]
@Sommi486 please could you try the Mac build from https://github.com/jamulussoftware/jamulus/actions/runs/823027995 ?
It uses Qt 5.9.9 as before, but is built with a more compatible SDK. It may or may not give different results from those above, but I don't have a Big Sur machine to try it on.

**Comment by softins** [comment]
I have also created test builds on the compatible SDK (10.15) with
* Qt 5.12.10 at https://github.com/softins/jamulus/actions/runs/823067833, and
* Qt 5.15.2 at https://github.com/softins/jamulus/actions/runs/823304664
If you have the time to out the artifacts from those runs on Big Sur and compare results, that would be great.
