### ISSUE TITLE
Remove unused files and directory in the sources.

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulus#1649]
Identifying some directory and some files that are no longer used for the app.
It's located in : jamulussoftware/jamulus/src/res/homepage/

I'm will create a PR for that as soon as possible.

**Comment by vimpostor** [comment]
Another thing that I found that needs to be cleaned up is that multiple source files somehow have the executable flag set.
Something like `find src/ -type f -exec chmod -x {} \;` should to the trick.
