### ISSUE TITLE
Allow meter style selection to be used in UI

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1658]
**Has this feature been discussed and generally agreed?**
Not fully discussed and agreed yet, happy to receive comments.
Also it is a feature I would like to work on/implement.

**Describe the solution you'd like**
In short, this feature is to allow a user to select the meter style to be used indepently from the Skin selected.
Current there are 3 skins available which use the following settings:

_Normal_
In this skin the meter style defaults to a Bar

_Compact_
In this skin the meter style defaults to a Narrow Bar

_Fancy_
In this skin the meter style defaults to a set of LEDs

This new feature should allow the user to select the meter style to be used in the User Interface Settings options.
The selection will be made using a dropdown list.
It will no longer be connected to the selected skin.
Using the meter style should not increase the space used in the Compact skin when the Narrow Bar is used (the current mode for Compact skin).

Two new Meter Style options should be added:
One option to use Round LEDs (using the same size as the existing LEDs used for buffer/delay display)
Second option to use Small Round LEDs (using the same size as the Narrow Bar, mainly to save space in Compact mode)

**Implementation**
When implemented, this will be using a new setting in the ini file.
Once the feature is available, the default setting for this option will be based on the selected Skin.
When the selected skin is Fancy, the Meter Style is set to LEDs.
When the selected skin is Compact, the Meter Style is set to SLIM_BAR.
When the selected skin is Normal, the Meter Style is set to BAR.

**Comment by gilgongo** [comment]
Happy to discuss here as long as the title and description of this issue remains accurate against that discussion. Please make sure any issues are actionable specs for work :-)

**Comment by gilgongo** [comment]
> The selection will be made using a dropdown list.

The convention when there are only two settings is to use a checkbox (ie [ ] Bar meters). If there are more than two, then radio buttons are preferred so that you can see what the options are, until there are more than maybe 4 chocies, in which case consider using a drop-down. Dropdowns hide options so are not preferred.

**Comment by henkdegroot** [comment]
> The convention when there are only two settings is to use a checkbox (ie [ ] Bar meters).

Actually checking this and found there are 3 settings. There is BAR, SLIM_BAR and LED. I will update the above/original text as well:)

**Comment by henkdegroot** [comment]
> radio buttons are preferred so that you can see what the options are

I proposed the dropdown, as it keeps it consistent in the dialog.
![settings-myprofile-380](https://user-images.githubusercontent.com/13550012/117569021-cda22900-b0c3-11eb-84a7-49801c378a52.PNG)

I agree though on the visibility of available options, but would not see how to make this look nice in the dialog.

**Comment by gilgongo** [comment]
Yes, since we're not using best practice by having radios for Skin and Skill, we may as well be consistent for meter selection I guess :-)

**Comment by henkdegroot** [comment]
@gilgongo , appreciate your comments on this sample/demo:
![MeterStyles](https://user-images.githubusercontent.com/13550012/117714214-e64f3380-b1d6-11eb-9fab-0c2b7eeab717.gif)

It is not finished yet, one issue is the long delay in changing the skin. Not sure if my changes have added additonal delay in this.

**Comment by gilgongo** [comment]
Looks good. LED round is interesting!

**Comment by henkdegroot** [comment]
@gilgongo , seems there is so much logic to think about here. Not really happy yet with how the solution "boundaries" are working at the moment. The height of the Slider set the "spacing" height used for the meter (regardless of the selected meter style). This minimum height is different depending on the selected skin. What I notice is that when I increase the height, you get a vertical added to the dialog and you can move the top section "out of sight". Trying to work on a suitable approach for this.

As a note on the side, when you look at my sample, do you notice the not used space at the top of the BAL dial? This seems to be a result of setting the height for the "muted speaker" label. See #1640. Noticed in several comments about replacing the unicode char with an image. Should I create a new issue to get this look into?
One reason for asking is the round LED height is 14pt while the current LED height is 8pt, placing them nice will increase the space used.

**Comment by gilgongo** [comment]
> Noticed in several comments about replacing the unicode char with an image. Should I create a new issue to get this look into?

Yes, that seems to be a good idea. The use of fonts as part of the structure UI seems a bit unstable to me, since font handling (spacing, proportionality and visual design) is applied based on rules that might have unpredictable results.

**Comment by henkdegroot** [comment]
**The option/selection in the My Profile tab:**
![MyProfile-Meter Style](https://user-images.githubusercontent.com/13550012/118370573-8676d500-b5a8-11eb-805e-c4fc02048923.png)

Next all screenshots with the possible options taken with mimimum height for each.

**Round Leds option with Fancy Skin:**
![fancy-roundleds](https://user-images.githubusercontent.com/13550012/118370347-9b069d80-b5a7-11eb-9622-04b32a980452.png)

**Narrow Bar option with Fancy Skin:**
![fancy-narrowbar](https://user-images.githubusercontent.com/13550012/118370351-a063e800-b5a7-11eb-92ff-3525d5c5b63c.png)

**Bar option with Fancy Skin:**
![fancy-bar](https://user-images.githubusercontent.com/13550012/118370353-a35ed880-b5a7-11eb-9a25-f2246b96fd4c.png)

**Leds option with Fancy Skin:**
![fancy-leds](https://user-images.githubusercontent.com/13550012/118370354-a5289c00-b5a7-11eb-82b9-0754c81d8048.png)

**Round Leds option with Normal Skin:**
![normal-roundleds](https://user-images.githubusercontent.com/13550012/118370360-a9ed5000-b5a7-11eb-837a-09a22bff31ff.png)

**Narrow Bar option with Normal Skin:**
![normal-narrowbar](https://user-images.githubusercontent.com/13550012/118370362-ace84080-b5a7-11eb-898d-e16cae4cefcf.png)

**Bar option with Normal Skin:**
![normal-bar](https://user-images.githubusercontent.com/13550012/118370365-b07bc780-b5a7-11eb-8c40-cd76a3efed44.png)

**Leds option with Normal Skin:**
![normal-leds](https://user-images.githubusercontent.com/13550012/118370369-b5d91200-b5a7-11eb-8426-e3e5cfd750e9.png)

**Round Leds option with Compact Skin:**
![compact-roundleds](https://user-images.githubusercontent.com/13550012/118370374-bb365c80-b5a7-11eb-8edd-e1083130baea.png)

**Narrow Bar option with Compact Skin:**
![compact-narrowbar](https://user-images.githubusercontent.com/13550012/118370380-c093a700-b5a7-11eb-8949-06efa5a76fae.png)

**Bar option with Compact Skin:**
![compact-bar](https://user-images.githubusercontent.com/13550012/118370386-c4bfc480-b5a7-11eb-93b4-54a8481d9a95.png)

**Leds option with Compact Skin:**
![compact-leds](https://user-images.githubusercontent.com/13550012/118370393-cab5a580-b5a7-11eb-9e2f-95505b31a843.png)

**Comment by pljones** [comment]
I'd like the round LEDs to be no wider than the narrow bar.  I love it otherwise :).

**Comment by henkdegroot** [comment]
@pljones , what if I extend the solution with an extra option for Small LEDs?
![small-leds](https://user-images.githubusercontent.com/13550012/118986868-ffe33e80-b97f-11eb-88a2-468c9ac8c1f4.png)

**Comment by pljones** [comment]
The second of the two looks better -- the Input LEDS aren't in the mixer panel, so the "Compact" doesn't apply.

(Whilst you're there...  Can you "glue" the Jamulus "cloud" icon to the top of the left-most panel and the Delay/Buffer indicators to the bottom - basically by making the Reverb slider expand to use all vertical space.  Did I mention that somewhere else, too?)

**Comment by henkdegroot** [comment]
> so the "Compact" doesn't apply.

Makes sense to me, guess the "what is this" text can add some explanation that small leds (and narrow bar) only apply to the mixer board.

I have seen your comment on the Reverb slider somewhere...think it be nicer to have a separate issue for that. I will create one for that.

**Comment by henkdegroot** [comment]
Here is the Small LEDs view for all skins:

![small-leds-demo](https://user-images.githubusercontent.com/13550012/119043649-8cf6b980-b9b9-11eb-9aa0-e5b7c50398d9.png)

**Comment by pljones** [comment]
Another unrelated point... why do the Delay and Buffer LEDs go "flat" but the Input LEDs stay "fancy"..?  It looks a bit wrong. Should be one way or the other.  (I'd go for "fancy" consistently - but it might have been for a good reason like accessibility, which wins.)

**Comment by gilgongo** [comment]
@henkdegroot Can we flag this for the next release do you think?

**Comment by henkdegroot** [comment]
@gilgongo, I don't see any reason why this cannot be added to the next release. It was just too late for 3.8.0...as it required additional translation. It would be very nice to have this included in the next release. At the moment, I even don't think there are any merge conflict with the current master branch. So believe it can even be merged already.

**Comment by gilgongo** [comment]
OK cool. I'll have a look at the PR ...

**Comment by pljones** [comment]
I _want_ this to make it 😁.

**Comment by DavidSavinkoff** [comment]
Is there an option for 'no meter' ?
