### ISSUE TITLE
Fix source files with executable bit

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1670]
Multiple source files somehow have the executable flag set.
Something like `find src/ -type f -exec chmod -x {} \;` should to the trick.

_Originally posted by @vimpostor in https://github.com/jamulussoftware/jamulus/issues/1649#issuecomment-834310723_

**Comment by gilgongo** [comment]
Wonder why? I've noticed +x happening on files transferred from Windows clients to rsync mounts in some circumstances, but that wouldn't seem to apply to git.

**Comment by vimpostor** [comment]
The files did have the execute flag since the very first commit from 15 years ago.
Probably some Ntfs in Linux scenario that caused this.
