### ISSUE TITLE
--clientname does not change the jack client name on Windows 10

### ISSUE THREAD

**Issue by newlaurent62** [jamulussoftware/jamulus#1676]
Hello,

the --clientname option does not change the jack client name in qjackctl.

Example:
`Jamulus --clientname TEST
`
![Jamulus_clientname](https://user-images.githubusercontent.com/10225394/118025592-50471480-b360-11eb-82d3-33656802f888.PNG)

It works on Linux but does not work on Windows 10. 

The jack client name should be "Jamulus TEST".

Kind Regards,
Laurent

Tested on Jamulus 3.7.0 (Windows and Linux)

**Comment by hoffie** [comment]
Hi,

thanks for the report.
Just to confirm, this is on a custom Windows build with `CONFIG+="jackonwindows"`, right?

I currently do not see any platform-specific code in the jack name handling, so I'm a bit lost why this problem occurs.

**Comment by newlaurent62** [comment]
Yes the test has been done with the official 3.7.0 windows build and the Linux version is from Librazik 3 repository. 

I modified the jackrouter ini file. I will try to reinstall jack.

**Comment by newlaurent62** [comment]
I will firstly try to use another program that rename the jack client.

**Comment by newlaurent62** [comment]
So, i tried to reinstall Jamulus 3.7.0 (official build on github) and reinstall Jack v1.9.18 but jack client name does not change.

QJackTrip another software that i use works and i can set jack client name as i wish. 

I also tried Jamulus 3.6.2 but no luck too ...

Any idea ? Someone has the same behavior on Windows 10 (3.7.0 official build) ?

Please try in a terminal if you have intalled Jack : 
```
start "TEST" "c:\Program Files\Jamulus\Jamulus.exe" --server

start "TEST" "c:\Program Files\Jamulus\Jamulus.exe" --clientname TEST -c 127.0.0.1

```

The Jamulus client name option should : 
- set your jamulus windows title to "Jamulus TEST 127.0.0.1 - 1 User" (OK for me)
- set the jack client name to "Jamulus TEST" (Not OK for me).

Kind Regards,
Laurent

**Comment by hoffie** [comment]
> i tried to reinstall Jamulus 3.7.0 (official build on github)

Ah, so you are using the official Jamulus build. As far as I know, this is ASIO-only. If you want to use Jamulus directly with jack on Windows, you will have to do a custom build with `CONFIG+=jackonwindows`, as far as I understand.

You seem to be using `JackRouter` which is something completely different. It leads to a setup which looks like this: Jamulus (ASIO) -> JackRouter (Jack) -> Jackd. In this setup, Jamulus does not have a way to talk to jackd directly.

It may be possible to change the client name for ASIO as well and this may make it work, but this is a different feature request to what's already implemented.

**Comment by newlaurent62** [comment]
You are right : I'm using jack router asio driver.

If it's not possible to change jack client name with the asio driver then my demand is to support jackd directly on windows 10 too.

**Comment by hoffie** [comment]
Note: I am converting this to a Github Discussion for now, as it is not clear yet if and what to do within Jamulus. We try to keep Issues for directly actionable bugs or enhancements. I'm going to reply in the Discussion thread which will be linked from here.
