### ISSUE TITLE
Empty space in mixerboard/Replace muted speaker character by a proper icon

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1684]
**Describe the bug**
In the latest v3.8.0beta2 release, there is big empty space above the PAN dial.
Possible caused by the change to setting the height of the muted speaker icon.
Also note that on Win10 the muted speaker icon appears in standard colors and not in orange

**To Reproduce**
Ensure there is one client you cannot hear, this makes the muted speaker icon to appear

**Expected behavior**
There is no need for the extra space between the dial and the PAN/Speaker text.
Possible solution (as discussed in several other issues/discussions) is to replace the Muted Speaker by an actual graphic/picture instead of using a unicode character for this.

**Screenshots**
![muted-speaker](https://user-images.githubusercontent.com/13550012/118293949-801a2780-b4da-11eb-887c-559d616f79e9.png)

**Operating system**
Win10

**Version of Jamulus**
v3.8.0beta2

**Additional context**
Also note that on Win10 the muted speaker icon appears in standard colors and not in orange, which according to the code should be the color used.
Is a muted speaker icon the best option for this?
Perhaps an ear icon with a cross or a headphone icon with a cross would better represent this function?

**Comment by vimpostor** [comment]
Regression from #1640
I guess an icon would really be better, Qt is handling the height of unicode labels very weirdly. I agree that an crossed-out ear icon would be better.
If we agree on what icon specifically to use, I can fix this myself in the code.

**Comment by henkdegroot** [comment]
> I agree that an crossed-out ear icon would be better.

I share your view, as that is purpose of the icon the client which has this icon shown cannot hear you.

**Comment by henkdegroot** [comment]
Replacing the icon with a different type will require text updates. A solution for short term to be able to include in 3.8.0:

![mono-sample](https://user-images.githubusercontent.com/13550012/118395013-68f94800-b648-11eb-9e83-29914ca38b26.png)

![stereo-sample](https://user-images.githubusercontent.com/13550012/118395023-731b4680-b648-11eb-9f4b-cac00559442d.png)

**Comment by henkdegroot** [comment]
@vimpostor , I did not notice you offered to fix this...apology for that.
