### ISSUE TITLE
Keyboard shortcut for "Mute myself" with the space bar

### ISSUE THREAD

**Issue by fjd** [jamulussoftware/jamulus#1690]
For singers it would be nice to have a quickly accessible key to mute their own mic. Known in German as _Räuspertaste_.

The spacebar is often used for this or it can be configured by yourself.

In addition, support for the headset button would also be possible here.

**Comment by vimpostor** [comment]
When you click on the "Mute" button, it will be focused. After that you can already press the "Space button" to mute/unmute. This will work, as long as the "Mute" button has focus.

Right now the "Mute" button does not have focus by default. The "Connect" button has focus by default, which makes sense to me. However, as soon as one connects to the server, it could make sense to focus the "Mute" button by default. Perhaps something like that could be implemented.
