### ISSUE TITLE
Build option "jackonwindows" not working with JACK2

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1705]
**Describe the bug**
When compiling Jamulus with the "jackonwindows" option, the project file on Win32 is checking the availability of JACK and links the libraries required. However in this check, the old JACK1 folder location is used for windows. This results in a compiled version which only works with JACK1 and not with the more common/current version JACK2.

**To Reproduce**
Add the CONFIG += jackonwindows option to the Jamulus.pro file and compile the release.
This only succeeds when JACK1 is installed and fails when JACK2 is used.

**Expected behavior**
As JACK2 is the current standard, the Jamulus.pro file should be updated for the Win32 builds to use the JACK2 folder locations.

**Operating system**
Windows 10
JACK v1.9.11 64bit
JACK2 v1.9.18 64bit

**Version of Jamulus**
v3.8.0beta2

**Comment by jujudusud** [comment]
JACK version 1.9.11 is also JACK2.

**Comment by henkdegroot** [comment]
> JACK version 1.9.11 is also JACK2.

Interesting, I always assumed it wass jack because the name of the installer is JACK... and the folder it is installed into for windows is named Jack as well. While later versions have the installer named JACK2... and the folder it is installed into for windows is named Jack2 as well.

At least that explains why the compile was succesfull by only updating the references to the new libraries.
Still believe we should update the Jamulus.pro file to point to the correct (current) folders used by jack on windows.
Do you agree?

JACK v1.9.11 64bit: Installs into: C:\Program Files (x86)\JACK
JACK v1.9.18 64bit: Installs into: C:\Program Files\JACK2
JACK v1.9.18 32bit: Installs into: C:\Program Files (x86)\JACK2

**Comment by jujudusud** [comment]
My opinion is as follows:
Jamulus should check if JACK is at the latest version (1.9.18)
If not advise the user to update.
;-)

**Comment by henkdegroot** [comment]
> For this change of install directory, We should Ask upstream if it is a bug or not

Okay, you are sort of agreeing to this....as you state it should check the latest version is installed (not sure if that is possible though in the pro file) and as the latest version installs into a different folder, we should at update the win32 of the pro file.

@hoffie , as I know you have commented on #1678, can you please share your opinion/view on this?

My intend is to update the pro file and add two sections, one for 64 bit and one for 32 bit and make sure the path location check is correct and the INCLUDEPATH and LIBS is set to the correct folders and files.

**Comment by jujudusud** [comment]
Ok, there is a bug here ! from my point of view, the paths are :

-  C:\Program Files\JACK2 for JACK v1.9.18 64bit
- C:\Program Files (x86)\JACK2 for JACK v1.9.18 32bit

So, I'm looking into Jamulus.pro but ... for now ... can't say anything.

**Comment by hoffie** [comment]
As a user, I would expect current Jamulus to work with current jack versions. So, if the existing `Jamulus.pro` logic is outdated regarding that due to changes in jackd installation directories, then we should update as well, I think.

If there is a real need to check multiple locations to find jack, we could do so. If we don't know, I'd rather keep it simple and limit it to the one known current path and provide an easy way to supply a custom path. I don't know how easy this is with `qmake`, but I suspect one could just pass a variable on the command line? This is what I know from other build systems as well -- try to auto-detect dependencies in the common location, but provide a way to override for cases where people have installed to different paths.

It might be useful if some other developer with more knowledge of Jamulus history could chime in additionally (@pljones @softins?).

**Comment by henkdegroot** [comment]
> Could you please share the contain of the three directory listed ?

@jujudusud do you still me to share the contents of these folders?

**Comment by softins** [comment]
> It might be useful if some other developer with more knowledge of Jamulus history could chime in additionally (@pljones @softins?).

I'm afraid this is an area I know nothing about, and have never tried building on Windows myself.

**Comment by jujudusud** [comment]
> > Could you please share the contain of the three directory listed ?
> 
> @jujudusud do you still me to share the contents of these folders?

Yes because I don't have access to a Windows machine for now.

**Comment by henkdegroot** [comment]
Odd....I could not add the zip file here. You can download here: [jack-folders](https://we.tl/t-W9N2lt0Fht)

**Comment by jujudusud** [comment]
ok, the install of JACK 1.9.18 is made in the 2 JACK2 directorys ? right ?
So you have to uninstall the other version (1.9.11) before building Jamulus.
thanks a lot for that. it's good for me. I will update Jamulus.pro on my branch.

**Comment by henkdegroot** [comment]
> ok, the install of JACK 1.9.18 is made in the 2 JACK2 directorys

There are 2 separate installs. 1 for 64-bit and 1 for 32-bit. You need both installed when you want to compile the application for 32 and 64 architecture.

The other version has to be removed indeed, as they are not compatible which each other.

**Comment by jujudusud** [comment]
@henkdegroot 
Could you please test windows 10 64 bits build cloning this branch :
https://github.com/jujudusud/jamulus/tree/pro-win64
after installing JACK 1.9.18 64 bits ?

**Comment by henkdegroot** [comment]
@jujudusud build without issues! Well done.

**Comment by jujudusud** [comment]
Build ok, great ! but ... :

-  is install ok ?
-  and is it running well JACK server + ASIO audio card selected in QJackctl + Jamulus JackonWindows ?

**Comment by henkdegroot** [comment]
I have added "jackonwindows" to the pro file before compiling.

Install ok
Connects to the JACK server (had to manually start jack server, seems like jack is not handling things very well when both 32 and 64 bit is installed)
Jack is selected as the Audio Device.
![jack-working](https://user-images.githubusercontent.com/13550012/118869293-7b43e200-b8e5-11eb-9a6a-5803483ecc28.png)

**Comment by jujudusud** [comment]
I'm preparing a windows 10 64 bits PC in order to test all that stuff.
Installing mingw64 and Qt 5.15 for now. JACK 1.9.18 64 bits is installed also.
See you soon :-)

**Comment by jujudusud** [comment]
All right ! :-)
![jackonwindows](https://user-images.githubusercontent.com/12748768/119178886-92faa200-ba6e-11eb-87e8-0cb5fcf95983.png)

**Comment by jujudusud** [comment]
@henkdegroot could you please have a try to compile on Windows 32 bits + on Windows 64 bits native and cross compile with the latest #1718 Jamulus.pro file ?
If you say that it works and the autobuild also works, we would be able to ask for a merge.
Then the work to update autobuild process to provide Windows Jamulus with Jack package will begin.

**Comment by henkdegroot** [comment]
@jujudusud , going to do that now....had a band rehearsal first today (using Jamulus of course) :)

**Comment by jujudusud** [comment]
I'm just finishing to build for Windows 64 bits and ASIO driver and it's ok. But I don't know how to configure for jack in Qt application, will see if there is a commande line to compile for JACK.

**Comment by henkdegroot** [comment]
> `qmake.exe "CONFIG+=jackonwindows" Jamulus.pro`?

I normally edit the Jamulus.pro and add the "jackonwindows" line to the first CONFIG section. As I also use the windows powershell script to build it. Believe the about would be correct though.

**Comment by jujudusud** [comment]
So, I think it is now ok. waiting for the push release to be merged.
Thanks a lot for help.
