### ISSUE TITLE
Inconsistency in deploy_windows.ps1 script

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#1719]
**Describe the bug**
The deploy_windows.ps1 script contains the following lines:
    [string] $QtInstallPath = "C:\Qt\5.12.3",
    [string] $QtCompile32 = "msvc2019",
    [string] $QtCompile64 = "msvc2019_64",

For Qt 5.12.3, the Qt Compile folders are msvc2017 (not msvc2019).
The locations used here are the ones for Qt 5.15.2.

**Expected behavior**
QtInstallPath should be updated to 5.15.2. This will makes the scripts also equal to the autobuild.

**Operating system**
Win10

**Version of Jamulus**
v3.8.0

**Comment by henkdegroot** [comment]
If you agree on the approach, please assign to me so I can resolve this.

**Comment by ann0see** [comment]
Just assigned you ;-). Thanks for working on this.

**Comment by jujudusud** [comment]
Talking about installing JACK for use in autobuild, this file is the right place to add this dependency installlation.
@henkdegroot , could you add the URLs of 64 and 32 bits JACK ?
