### ISSUE TITLE
Mac: Enable accelerator key functionality

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1726]
Just found this in the [Qt docs](https://doc.qt.io/qt-5/qshortcut.html#details):

> On Mac, shortcuts are disabled by default. Call qt_set_sequence_auto_mnemonic() to enable them. However, because mnemonic shortcuts do not fit in with Aqua's guidelines, Qt will not show the shortcut character underlined.

We should probably consider activating them on Mac, too?
cc @softins @ann0see

_Originally posted by @hoffie in https://github.com/jamulussoftware/jamulus/discussions/1693#discussioncomment-755670_

**Comment by softins** [comment]
For 3.8.0? Or after that, ready for the next release?

**Comment by hoffie** [comment]
> For 3.8.0? Or after that, ready for the next release?

Next release, I'd say. It does look minor, but nobody has tested it yet. This is not a regression or something with huge demand either.

**Comment by HughePaul** [comment]
> This is not a regression or something with huge demand either.

How do I register that this is in huge demand?
