### ISSUE TITLE
Server: Delay panning status is not saved

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1743]
> It seems, that in server mode the 'delay pan' option is not stored in the 'ini'. I observed this on Windows 7 and on an Ubuntu based system.

_Originally posted by @DetlefHennings in https://github.com/jamulussoftware/jamulus/discussions/1707#discussioncomment-771881_

**Comment by henkdegroot** [comment]
Seems to correct :)

Please assign to me....so I can resolve it.

**Comment by hoffie** [comment]
> Please assign to me

Done.

I'm a bit unsure if the fix should be included in 3.8.0. I think we should not merge if rc1 is the last rc (we could just document it as Known Issue and release 3.8.1 shortly afterwards).
If we need an rc2 anyway (for the Mac issue), then we might as well merge a fix for this if it is ready in time.

I'm tagging it for 3.8.0 so it doesn't get lost, but we may move it to 3.8.1.

@jamulussoftware/maindevelopers What do you think?

**Comment by ann0see** [comment]
No. I‘d include it in 3.8.0

**Comment by pljones** [comment]
I'd go with 3.8.0 on the grounds of the Mac leak, otherwise I'd have said it wasn't important enough a fix.
