### ISSUE TITLE
Set up Directory server monitoring

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1745]
We currently don't get any notifications when the official Directory Servers are down. We should implement monitoring for that.

**Comment by dcorson-ticino-com** [comment]
Good idea, Jazz and Classical directories where down (still no response after 30 s) for several hours yesterday evening.
I guess someone was busy working :)
I neglected to signal this.

**Comment by ann0see** [comment]
Would probably be possible with Jamulus PHP or the Python API?

**Comment by hoffie** [comment]
> Would probably be possible with Jamulus PHP or the Python API?

I suppose you are referring to the Jamulus protocol implementations by @softins and @passing. Yes, this would certainly be helpful.

The degree of complexity varies with what we aim for. We could do simple ICMP pings, we could do simple UDP-based send / expect response checks or we could do a full end-to-end test. The latter requires understanding of the protocol.

**Comment by passing** [comment]
> We currently don't get any notifications when the official Directory Servers are down. We should implement monitoring for that.

Apart from the question, how to decide if the service is available or not (there are certainly many different ways), what is the idea for how to run these health checks in general? I would make the following assumptions:
- The solution should not generate any costs (eliminates any comfortable, paid service)
- Notifications need to be just via Email (no SMS, push notifications, etc.)
- Keeping a (centralised) history of events is not required
- Having a "fancy UI" is not required (something like Icinga or some other Monitoring solution)

If that's all the case, the simplest solution could be something like:
- A health check job is running via cron on at least 2 directory servers (to also get notifications when a server running the check is down)
- The job checks all directory servers are reachable(/responding).
- When a server is down, an email is sent (requiring some mail configuration)

**Comment by passing** [comment]
just quickly made a simple UDP-based send / expect response check prototype in bash. You just need a valid ping message and check that the server replies with the same message:

```bash
#!/bin/bash

host=$1
port=${2:-22124}
timeout=3

ping_base64="AADpAwAEAAAAAABvYA==" # PROTMESSID_CLM_PING_MS (time=0)

pong_base64=$(
    echo "$ping_base64" | base64 -d | nc -w $timeout -u $host $port | base64
)

# reply from the server must be the same as what was sent
if [ "$ping_base64" = "$pong_base64" ]
then
    echo $host:$port is responding
    exit 0
else
    echo $host:$port is not responding
    exit 1
fi  
```

I think that would be almost enough (just should also get a loop to do a few retries).
But for sure not suitable if a full end-to-end test is needed.

**Comment by gene96817** [comment]
> When a server is down, an email is sent (requiring some mail configuration)

Depending on your definition of "down", you might not get any email.
It would be more robust to get an email as an all-is-well message. However, this might be the start of a slippery slope to more complexity.

**Comment by ann0see** [comment]
Jamulus PHP gives back a JSON response which could be checked via a bash script. I think we can check for an empty response and interpret this as server not working.

**Comment by passing** [comment]
> > When a server is down, an email is sent (requiring some mail configuration)
> 
> Depending on your definition of "down", you might not get any email.

@gene96817 that's not the case if you do the monitoring in more than 1 locations as suggested:

> "A health check job is running via cron on at least 2 directory servers (to also get notifications when a server running the check is down)"

Of course that is not 100% reliable, but simple to setup and maintain. A 100% solution would require something like heartbeats which requires a more complex setup and some HA alerting solution that you need to run yourself or buy as a Service (as a company you would usually buy this).

> It would be more robust to get an email as an all-is-well message. However, this might be the start of a slippery slope to more complexity.

I'd not recommend going with "all-is-well" messages, as you will likely just ignore them after some time and in the end won't notice when one is missing.

> Jamulus PHP gives back a JSON response which could be checked via a bash script. I think we can check for an empty response and interpret this as server not working.

@ann0see note that it also returns a valid JSON for a not reachable server, so it would require to actually check the contents of the JSON
```
curl -s https://explorer.jamulus.io/servers.php?server=anygenre1.jamulus.io:22124 | jq '.'
curl -s https://explorer.jamulus.io/servers.php?server=www.jamulus.io:22124 | jq '.'
```
but you won't be able to tell if the jamulus servers are online when the server running Jamulus PHP would be down.

**Comment by softins** [comment]
> @ann0see note that it also returns a valid JSON for a not reachable server, so it would require to actually check the contents of the JSON
> 
> ```
> curl -s https://explorer.jamulus.io/servers.php?server=anygenre1.jamulus.io:22124 | jq '.'
> curl -s https://explorer.jamulus.io/servers.php?server=www.jamulus.io:22124 | jq '.'
> ```
> 
> but you won't be able to tell if the jamulus servers are online when the server running Jamulus PHP would be down.

I wonder what would happen if I made the error response return a 404 status (still with the JSON body) instead of a 200?

**Comment by ann0see** [comment]
@hoffie @passing any updates here? 

https://github.com/jamulussoftware/jamulus/issues/1745#issuecomment-847394132 looks quite interesting and if it's really that easy, this issue should be easily resolvable

**Comment by hoffie** [comment]
I've just enabled ping/reachability metrics for the official directory servers on my Prometheus infrastructure based on the below script.

<details>
<summary>script</summary>

```python
#!/usr/bin/env python3
import struct
import socket
import time
import os
import sys
from collections import namedtuple


PROTMESSID_CLM_PING_MS = 1001


# Little Endian:
#   2 byte TAG,
#   2 byte ID,
#   1 byte counter,
#   2 byte length,
#   n bytes data,
#   2 bytes CRC
STRUCT_FORMAT = '<HHBH'
PREFIX_LENGTH = struct.calcsize(STRUCT_FORMAT)
CRC_FORMAT = '<H'
CRC_LENGTH = struct.calcsize(CRC_FORMAT)

LOCAL_PORT = 22224
TIMEOUT = 1.0  # s


DIRECTORIES = [
        ('anygenre1.jamulus.io', 22124),
        ('anygenre2.jamulus.io', 22224),
        ('anygenre3.jamulus.io', 22624),
        ('rock.jamulus.io', 22424),
        ('jazz.jamulus.io', 22324),
        ('classical.jamulus.io', 22524),
        ('choral.jamulus.io', 22724),
        ('127.0.0.1', 22724),
]

METRICS_PATH = sys.argv[1]
METRICS_PATH_TMP = f'{METRICS_PATH}.tmp'

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('0.0.0.0', LOCAL_PORT))
sock.settimeout(TIMEOUT)

Message = namedtuple('Message', ['id', 'counter', 'data'])

class PingTimeoutError(RuntimeError):
    pass


def make_protocol_message(id_, counter, data):
    tag = 0
    msg = struct.pack(STRUCT_FORMAT, tag, id_, counter, len(data)) + data
    c = struct.pack(CRC_FORMAT, crc(msg))
    return msg + c


def parse_protocol_message(msg):
    tag, id_, counter, len_ = struct.unpack(STRUCT_FORMAT, msg[:PREFIX_LENGTH])
    if tag != 0:
        raise RuntimeError("bad tag")

    data = msg[PREFIX_LENGTH:-CRC_LENGTH]
    if len(data) != len_:
        raise RuntimeError("bad length")

    c = struct.unpack(CRC_FORMAT, msg[-CRC_LENGTH:])[0]
    correct_crc = crc(msg[:-CRC_LENGTH])
    if c != correct_crc:
        raise RuntimeError(f"bad crc, expected {correct_crc!r}, got {c!r}")

    return Message(id_, counter, data)



def send_data(host, port, msg):
    sock.sendto(msg, (host, port))


def recv_data():
    return sock.recvfrom(1024)


def crc(bytes_):
    poly = (1 << 5) | (1 << 12)
    mask = 1 << 16
    crc = ~0
    for b in bytes_:
        for i in range(8):
            crc <<= 1
            if crc & mask > 0:
                crc |= 1
            if b & (1 << (8 - i - 1)) > 0:
                crc ^= 1
            if crc & 1 != 0:
                crc ^= poly
    return ~crc & (mask - 1)


def clm_ping(host, port):
    payload = b'\x11\x22\x33\x44'
    msg = make_protocol_message(PROTMESSID_CLM_PING_MS, 0, payload)
    start_time = now = time.time()
    ip = socket.gethostbyname(host)
    send_data(ip, port, msg)
    while now <= start_time + TIMEOUT:
        msg, from_ = recv_data()
        if from_[0] != ip:
            continue
        if from_[1] != port:
            continue
        message = parse_protocol_message(msg)
        if message.data != payload:
            continue
        return time.time() - start_time
    raise PingTimeoutError()



def write_metrics(out):
    for host, port in DIRECTORIES:
        try:
            ping = clm_ping(host, port)
        except Exception:
            ping = -1
        out.write(f'jamulus_server_ping{{host="{host}",port="{port}"}} {ping}\n')

with open(METRICS_PATH_TMP, 'w') as f:
    write_metrics(f)
    os.rename(METRICS_PATH_TMP, METRICS_PATH)

```
</details>

**Comment by ann0see** [comment]
> Currently, alerts are only routed to my mail address. I can easily adjust that to go to team@ instead. Should I do that?

Yes, I'd do that

> It's running on my private infra (similar to the live jamulus.io link checker). That's probably not an issue as the directories are running on private, single-person infra as well.

What's the alternative?
* GitHub actions via scheduled runs?
* Monitoring Provider

**Comment by hoffie** [comment]
@jamulussoftware/maindevelopers I've just adjusted my directory and jamulus.io link checker monitoring to target team@. I'll close this issue for now. If someone thinks that resolving the single-person-runs-Jamulus-infra topic is a priority, please open a separate issue for that.
