### ISSUE TITLE
Rc1 hangs after undefined time on mac os 11.3.1 big sur

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#1754]
Ui becomes unresponsive, but audio keeps playing. VU meters stop working. Happens on matching server version. Other applications running: hijack audio, spotify, chrome, focusrite control. Audio interface: scarlett 18i8. iPad is streaming through USB C

**Comment by ann0see** [comment]
I think that’s a known issue. @softins is working on it. Probably it’s related to the ping/overall delay issue in Jamulus‘s settings.

**Comment by henkdegroot** [comment]
@reneknuvers , it would be good to know if you had the "settings" dialog open when this occurred.

**Comment by dcorson-ticino-com** [comment]
This appears to be a problem that is only happening on Macs.
But to be sure it would be useful if all others would report if they see such behaviour.

**Comment by reneknuvers** [comment]
Yes i had the settings screen open!

Groetjes, René

**Comment by RobyDati** [comment]
I had this problem of Rc1 hangs with audio continues to work on Mac Big Sur 11.3.1. "Setting" dialog is open but was unresponsive, as the mixer and all the UI.    I never experienced this problem with Rc1 on the other 2 platforms I am using: Mac Os Mojave and Linux Ubuntu.   I had this problem only on Mac Big Sur 11.3.1

**Comment by softins** [comment]
I have the same problem on Mojave. Trying to find a solution, but so far without success. See more detail in the related issue #1643

**Comment by gilgongo** [comment]
Closing as duplicate.
