### ISSUE TITLE
Reinstate text changes reverted for 3.8.0

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#1775]
After releasing 3.8.0, need to revert https://github.com/jamulussoftware/jamulus/pull/1762/commits/cf9910720096c1a0000caf114c2f8469f640316f to reinstate the text improvements so they can be translated for 3.8.1

See #1762

**Comment by ann0see** [comment]
Shouldn't we tag the translators here to make them aware of this issue?

This would require a less technical description ;-).

**Comment by softins** [comment]
> Shouldn't we tag the translators here to make them aware of this issue?

After the 3.8.0 release, just to avoid confusion!

**Comment by reneknuvers** [comment]
Now is the time to tag translators!

**Comment by ann0see** [comment]
No. Not yet. We're not ready for the 3.8.1 release. Only the test-translation round for 3.8.0. If you would like to have a new release, please open an issue/discussion.
