### ISSUE TITLE
Documentation and Jamulus release are out of sync

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1779]
**Describe the bug**
There are multiple places on the website which are out of sync or will be out of sync soon. Although we can't do much about it since the translation process started, I will soon focus more on the website.

**Comment by pljones** [comment]
Random note:
- We're not consistent on `sudo apt update` vs `sudo apt-get update`.  The former is more modern.

**Comment by jujudusud** [comment]
Is it already the case with the recent release ?

**Comment by ann0see** [comment]
Only partly.

**Comment by ann0see** [comment]
Could be a dupli
