### ISSUE TITLE
/distributions/jamulus-server.service needs to be removed

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1780]
Todo: Remove this file: https://github.com/jamulussoftware/jamulus/blob/master/distributions/jamulus-server.service

Context:

The documentation will soon tell the user that the .deb file will start a private server. However this is wrong: the systemd .service file (which is different to the one shown on the homepage) configures a public server which registers on Any genre 3. 

I think we should by default not register the server anywhere. The user should make a deliberate choice to register where he wants to register.

Just for my own reference: That's the script shown on the website:
```
[Unit]
Description=Jamulus-Server
After=network.target

[Service]
Type=simple
User=jamulus
Group=nogroup
NoNewPrivileges=true
ProtectSystem=true
ProtectHome=true
Nice=-20
IOSchedulingClass=realtime
IOSchedulingPriority=0

#### Change this to set genre, location and other parameters.
#### See [Command-Line-Options](Command-Line-Options) ####
ExecStart=/usr/local/bin/Jamulus -s -n -e jamulus.fischvolk.de -o "yourServerName;yourCity;[country ID]"

Restart=on-failure
RestartSec=30
StandardOutput=journal
StandardError=inherit
SyslogIdentifier=jamulus

[Install]
WantedBy=multi-user.target
```

**Comment by ann0see** [comment]
Hmm. So there are even more .service files? 

So the one in the Debian folder seems to be the one we’re using while the one in the distributions folder is not used anywhere? We should check if that’s true.

**Comment by gilgongo** [comment]
Maybe a mistake here? https://github.com/jamulussoftware/jamulus/commit/18d06b961ddf45829bfb4d187112eac87290c983?branch=18d06b961ddf45829bfb4d187112eac87290c983&diff=split

**Comment by ann0see** [comment]
Ok. So we might just remove the file in distributions then?
