### ISSUE TITLE
Investigate and improve windows sound handling

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1812]
See https://github.com/jamulussoftware/jamulus/pull/1732#discussion_r637597183 by @pljones 
and https://github.com/jamulussoftware/jamulus/pull/1732#discussion_r640087362

I think this might also result in bad UX: 

Just a speculation: if you e.g. select an invalid device in ASIO4ALL a fatal error message might close Jamulus even if you configure it correctly. 

Might be related to https://github.com/jamulussoftware/jamulus/pull/1378

**Comment by npostavs** [comment]
`// comment by ann0see: why do we clean up the driver even if we changed the driver settings?`

Indeed I removed this cleanup in #1378.

> Just a speculation: if you e.g. select an invalid device in ASIO4ALL a fatal error message might close Jamulus even if you configure it correctly.

Not sure what you mean here exactly, what does it mean to configure an invalid device correctly? But the general of problem of: one mistake in ASIO4ALL configuration dumping you out of Jamulus is what I'm trying to fix in 1378.

**Comment by ann0see** [comment]
Sorry for being unclear here.

Basically I mean:

1. Install ASIO4ALL as only driver
2. Select an incompatible device (e.g. not 48kHz)
3. Close Jamulus
4. Open Jamulus
5. Disable the incompatible device
6. Expect Jamulus to continue; however it throws an error message and quits the App

**Comment by npostavs** [comment]
Yes, except it's arguably even more confusing, because what actually happens is:

4. Try to open Jamulus, get an error message
5. Disable the incompatible device (and tell Jamulus your are done re-configuring ASIO4ALL)
6. Jamulus quits without any explanation

The user has no feedback on whether or not the ASIO4ALL configuration was successful until the next time they open Jamulus.

**Comment by ann0see** [comment]
Since a sound redesign by @pgScorpio is in process, I'll now close this issue. Please continue discussion on https://github.com/jamulussoftware/jamulus/discussions/2400
