### ISSUE TITLE
Document SourceForge release process

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1814]
https://discord.com/channels/807531182094286848/807531182094286851/821873805667991592

From @pljones:
> - you need an authorised SourceForge account.
> - sftp accname@frs.sourceforge.net
> - cd /home/pfs/project/l/ll/llcon
> then you'll see "Jamulus" and "OldFiles" directories.  "Jamulus" is the releases, one directory per release.
> - cd Jamulus
> - mkdir 3.7.0
> - cd 3.7.0
> - Upload all the files.
> And then... On SourceForge, for each of the files uploaded, click the :information_source: icon next to the file (in Files in the admin tools) and set it as "Default for (appropriate) platform)"
> (Note that unsetting the "default" so none is set automatically picks the newest, so don't do that -- explicitly set the default when the release announcement is posted.)

**Comment by gilgongo** [comment]
> explicitly set the default when the release announcement is posted

Now that we have two Mac, Linux and source files, I'm not sure what happens to the non-default.

**Comment by hoffie** [comment]
> > explicitly set the default when the release announcement is posted
> 
> Now that we have two Mac, Linux and source files, I'm not sure what happens to the non-default.

Tbh, I consider the Sourceforge downloads to be legacy. Sourceforge has had a good reputation, but it was lost some time ago. For Jamulus, I still have the feeling that we should continue publishing there as a secondary download source.

Wrt. the actual issue about Mac builds: As far as my macOS release understanding goes, the legacy build is only required for macOS versions which are no longer supported by Apple. It's good to provide such a release as there may be legitimate showstoppers for updating Mac releases apparently (support for other software), but I think our main baseline should be: Support platforms which are still supported by the vendors.

In essence, optimize the first-class options -- Github and current Mac versions (vs. Sourceforge and legacy Mac versions).

**Comment by gilgongo** [comment]
OK. I guess in most cases it'll be fine: if the user chooses to use the SF mirror for Mac, they'll get the Apple supported version. If they have an old machine, they can seek that out in the SF "files" area. Same for Linux headless. We don't explain that anywhere, but I'd rather not clutter up the download pages with "if/then" instructions for a tiny minority who can always post on the forums.

**Comment by gilgongo** [comment]
Now added to Release-Process.md
