### ISSUE TITLE
Feedback killer stops working when changing mono-stereo

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#1821]
When the feedback detection has kicked in, and I change the audio channels setting, the feedback killer stops and feedback starts to occur immediately. The feedback is not detected and remains present.

Found on 3.8.0 on mac os Big Sur 11.4

**Comment by hoffie** [comment]
Thanks for the report. Was this after after a reconnect or within the same connection?
IIRC the feedback detection is currently active some seconds after initial connect. We wanted to wait whether it would be useful to keep it enabled all the time (or after detecting other changes like the Mono/Stereo change you mention).

cc @JohannesBrx

**Comment by reneknuvers** [comment]
As far as I recall, this was within the same connection.

**Comment by softins** [comment]
This may be related to the bug referenced in #2119 and fixed in #2120

**Comment by pljones** [comment]
@reneknuvers, are you able to test using one of the builds here?
https://github.com/jamulussoftware/jamulus/actions/runs/1454059205
(Remember to back up your settings before installing a new version, _expecially_ when it's not a release.)

**Comment by hoffie** [comment]
I wasn't able to reproduce this.

@reneknuvers The current [nightly](https://github.com/jamulussoftware/jamulus/releases/tag/r3.8.1devNightly1) should also have the above mentioned fix and the upcoming 3.8.2 will as well.
I'm closing this issue for now, feel free to re-open if you encounter the problem again on one of those newer versions.
Thanks for your report!
