### ISSUE TITLE
Command Line Options missing from list

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#1837]
**Describe the bug**
There appear to be valid command line options missing from the list at https://jamulus.io/wiki/Command-Line-Options

**To Reproduce**
I'm doing a clean install of 3.8.0, building it myself without a *.deb file.  I'm creating the *.service file manually.  For 3.7.0, my ExecStart was:

ExecStart=/usr/local/bin/Jamulus \
--server \
--nogui \
--serverinfo "School of Rock WS;Seattle, WA;225" \
--welcomemessage "message here" \
--numchannels 20 \
--fastupdate \
--centralserver anygenre2.jamulus.io:22224

**Expected behavior**
Of the command line options I'm using, the Wiki is missing:

--server
--serverinfo
--welcomemessage
--numchannels

--centralserver has been replaced by --directoryserver, so I'm not surprised that it's missing from the Wiki.  But the others are not mentioned in the Change Log so are likely still available, but missing from the Wiki.

**Operating system**
Linux Debian x64

**Version of Jamulus**
N/A

**Additional context**
N/A

**Comment by chrisrimple** [comment]
It looks like --multithreading may also be missing from the Wiki

**Comment by dcorson-ticino-com** [comment]
I think the doc has been separated in two; client doc and server doc.
All those command line options you see missing are server options.

**Comment by jujudusud** [comment]
Since it is a website issue, could you please close it here and open it in jamuluswebsite repository ?

**Comment by chrisrimple** [comment]
> I think the doc has been separated in two; client doc and server doc.
> All those command line options you see missing are server options.

The Wiki shows both client and server command line options on a single page, and the server options I've listed are missing from that page.

**Comment by chrisrimple** [comment]
> Since it is a website issue, could you please close it here and open it in jamuluswebsite repository ?

Done.  Thanks for pointing out the other repository.

**Comment by jujudusud** [comment]
Please see issue 520 in website repository.
