### ISSUE TITLE
Linux deb package not installing server icon

### ISSUE THREAD

**Issue by jujudusud** [jamulussoftware/jamulus#1879]
**Describe the bug**
As discussed here : 
(https://github.com/jamulussoftware/jamuluswebsite/pull/527#discussion_r651921981)
Deb package not installing server icon

**To Reproduce**
Install the deb package and see what append.

**Expected behavior**
Jamulus server icon should be installed.

**Operating system**
Ubuntu debian or others with web installer

**Version of Jamulus**
3.8.0

**Comment by gilgongo** [comment]
This also implies a .desktop file to launch a server too I think?

**Comment by ann0see** [comment]
Yes. The server and also client icon don’t seem to show up on my Debian 11 machine under GNOME. The Debian files need an update.

**Comment by jujudusud** [comment]
We also have to remove `jamulus.png` after having updated Debian files. The new icon is an svg file.

**Comment by ann0see** [comment]
Fixed by https://github.com/jamulussoftware/jamulus/pull/2460
