### ISSUE TITLE
New ASIO SDK available

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#1880]
**Has this feature been discussed and generally agreed?**

No. 

**Describe the solution you'd like**

Download the latest ASIO SDK 2.3.3, and use it to compile the Windows build. 

~~Maybe this fixes the build error in autobuild?~~ no. It’s just a non behavioural change according to the change log. 

**Describe alternatives that have been considered**

Move to portaudio (?)

**Comment by npostavs** [comment]
> **Describe alternatives that have been considered**
> 
> Move to portaudio (?)

It's not really an alternative, portaudio would use the ASIO SDK too.

**Comment by ann0see** [comment]
Ok. So it also downloadeds the ASIO SDK?

**Comment by npostavs** [comment]
No, you gotta download it yourself :)

(it is *possible* to use portaudio without ASIO, but would probably get much worse results for devices that have ASIO drivers)

**Comment by jujudusud** [comment]
What about using Windows 10 new audio APIs (Audiograph or WASAPI) ?

**Comment by npostavs** [comment]
> What about using Windows 10 new audio APIs (Audiograph or WASAPI) ?

That only makes sense to avoid having to use ASIO4ALL (since ASIO4ALL itself uses WDM, as far as I know). If you have a device with a native ASIO driver then using ASIO will most likely give the best results.

**Comment by jujudusud** [comment]
Using ASIO (if available with the hardware) is the only way on Windows to achieve a low latency without New APIs handled on the apps.
Using new Windows 10 APIs is, in my head, the best way to avoid having to use ASIO4ALL with a non ASIO device for Jamulus.

**Comment by henkdegroot** [comment]
> ~Maybe this fixes the build error in autobuild?~

What error have you seen in the autobuild?

**Comment by ann0see** [comment]
It’s gone. It seemed to be a temporary permission error while downloading the .zip file

**Comment by npostavs** [comment]
> Using new Windows 10 APIs is, in my head, the best way to avoid having to use ASIO4ALL with a non ASIO device for Jamulus.

Please check out #870 to try it out then :) (latest installer link is in the first post)
