### ISSUE TITLE
Typo in the page: https://jamulus.io/fr/wiki/Installation-for-Android

### ISSUE THREAD

**Issue by FredNor78** [jamulussoftware/jamulus#1890]
Hi everybody!

Could someone please correct the awful grammar typo in the French version of the page.

The existing sentence "Bien que vous pouvez installer Jamulus sur des appareils Android (et entendre du son), " 

should be rewritten as "Bien que vous puissiez installer Jamulus sur des appareils Android (et entendre du son), "

Many thanks for all you do for the benefit of the community, and keep up the good job

Fred

**Comment by jujudusud** [comment]
Bonjour @FredNor78, je m'en occupe. Merci pour l'information.

Hi @FredNor78, I will do that. Thanks for the advice.

@gilgongo Can you assign me ?

**Comment by gilgongo** [comment]
Ooh I think we're still refining the new po4a process so I'm not sure about that right now (other than you need to edit the .pot file and then you (or somebody else) run the po4a update and then doing a PR to release?). Tagging @ignotus666 ...

**Comment by ignotus666** [comment]
@jujudusud wait until [this PR](https://github.com/jamulussoftware/jamuluswebsite/pull/533) gets merged (or not) and then:

- Make the correction to `translator-files/po/Installation-for-Android.po`
- Next, you can either run `po4a-create-all-targets.sh` locally yourself (you need to install po4a version >= 0.63), or do the correction manually in `/wiki/fr/Installation-for-Android.md` (it's what the script would do for you). The intention is that this last step will be automated in future.
- Submit PR to 'release'.

**Comment by jujudusud** [comment]
Done by # 539 in jamulus website repo

**Comment by jujudusud** [comment]
Fixed since the PR was merged.
