### ISSUE TITLE
Issues with grouping feature

### ISSUE THREAD

**Issue by sthenos** [jamulussoftware/jamulus#1907]
So I got an opportunity to use Jamulus load and save configurations during last nights EHB show.   It worked well for loading and saving a big mix (45 singers in a choir).   The reason I had to use it was because the big choir started the show so I had a good mix for them, then all 45 members individually performed in a number of quartets so I had to alter their levels significantly, then they came together at the end so I wanted to restore my previous big mix.  That worked well, but I also heavily utilised the grouping feature.   This normally works well but there are two flaws:

1.  You can't easily ungroup all 45 people.   I needed to be able to do this.  I was hoping that using the "Clear all stored solo and mute settings" would do it, but it doesn't  I guess the clue is in the name, but I think it really needs to reset pan plus grouping settings too.
2.   When you group it works well on faders, but it does when when you click the pan buttons.  I believe it should just as it would on a group fader on a real desk.

**Comment by wschell** [comment]
I see at least one inconsistency when working with groups: Shift-Fader moves a single fader, but Shift-Pan resets it to neutral. So if grouping works on pan (what I would prefer too), it should behave the same as faders. And grouping should also work for toggling Solo and Mute.
Without any modifier key (Shift, Ctrl, Alt), change settings for whole group.
With modifier 1, change settings only for this member.
With modifier 2, reset fader (to new client level) or pan and toggle mute or solo only for this member.

**Comment by gilgongo** [comment]
Hi @sthenos thanks for this - we'll move it to a discussion until there's an agreement on how to approach the issue.
