### ISSUE TITLE
Headless server frequently crashing when in use

### ISSUE THREAD

**Issue by acerix** [jamulussoftware/jamulus#1916]
**Describe the bug**
Within about the past week, there have been several reports from users of my server getting disconnected randomly when jamming with about 4-8 people connected.  Sometimes they are disconnected and need to reconnect or get loud static noise for about 10 seconds.  In the server logs, I can see it is crashing with a core dump and restarting.

**To Reproduce**
The crash happens randomly when there are several people connect. I suspect the problem started after updating a dependency. 

**Expected behavior**
Not crashing is obvious, but also users should not get noise like that.  

**Screenshots**
Stack trace from systemd journal:
```
Jul 14 13:56:40 psilly.com systemd[1]: Started Process Core Dump (PID 6693/UID 0).
Jul 14 13:56:40 psilly.com kernel: audit: type=1130 audit(1626285400.899:3189): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-6693-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostna
me=? addr=? terminal=? res=success'
Jul 14 13:56:40 psilly.com audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-6693-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=su
ccess'
Jul 14 13:56:41 psilly.com systemd-coredump[6694]: Removed old coredump core.Jamulus-headles.989.92286badf58842e58adb12c4569b8d31.4188.1626196170000000.zst.
Jul 14 13:56:43 psilly.com systemd-coredump[6694]: Process 648 (Jamulus-headles) of user 989 dumped core.
                                                   
                                                   Stack trace of thread 648:
                                                   #0  0x00007f85c0d81d22 raise (libc.so.6 + 0x3cd22)
                                                   #1  0x00007f85c0d6b862 abort (libc.so.6 + 0x26862)
                                                   #2  0x000055c1ac7f159a n/a (Jamulus-headless + 0x1d59a)
                                                   #3  0x000055c1ac7f0ec8 n/a (Jamulus-headless + 0x1cec8)
                                                   #4  0x000055c1ac7f13cc n/a (Jamulus-headless + 0x1d3cc)
                                                   #5  0x000055c1ac7f2565 n/a (Jamulus-headless + 0x1e565)
                                                   #6  0x000055c1ac80f6fb n/a (Jamulus-headless + 0x3b6fb)
                                                   #7  0x00007f85c156e48f _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2e648f)
                                                   #8  0x00007f85c1541308 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b9308)
                                                   #9  0x00007f85c1544439 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2bc439)
                                                   #10 0x00007f85c159a934 n/a (libQt5Core.so.5 + 0x312934)
                                                   #11 0x00007f85c00f710c g_main_context_dispatch (libglib-2.0.so.0 + 0x5410c)
                                                   #12 0x00007f85c014ab99 n/a (libglib-2.0.so.0 + 0xa7b99)
                                                   #13 0x00007f85c00f4871 g_main_context_iteration (libglib-2.0.so.0 + 0x51871)
                                                   #14 0x00007f85c1599f66 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x311f66)
                                                   #15 0x00007f85c153fcac _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b7cac)
                                                   #16 0x00007f85c1548214 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2c0214)
                                                   #17 0x000055c1ac7ec8f3 n/a (Jamulus-headless + 0x188f3)
                                                   #18 0x00007f85c0d6cb25 __libc_start_main (libc.so.6 + 0x27b25)
                                                   #19 0x000055c1ac7efb5e n/a (Jamulus-headless + 0x1bb5e)
                                                   
                                                   Stack trace of thread 650:
                                                   #0  0x00007f85c0e3e18d syscall (libc.so.6 + 0xf918d)
                                                   #1  0x00007f85c13562d6 _ZN11QBasicMutex12lockInternalEv (libQt5Core.so.5 + 0xce2d6)
                                                   #2  0x000055c1ac7f2d16 n/a (Jamulus-headless + 0x1ed16)
                                                   #3  0x000055c1ac80dbc2 n/a (Jamulus-headless + 0x39bc2)
                                                   #4  0x000055c1ac860ed2 n/a (Jamulus-headless + 0x8ced2)
                                                   #5  0x000055c1ac7fa10a n/a (Jamulus-headless + 0x2610a)
                                                   #6  0x00007f85c1355f7f n/a (libQt5Core.so.5 + 0xcdf7f)
                                                   #7  0x00007f85c19d3259 start_thread (libpthread.so.0 + 0x9259)
                                                   #8  0x00007f85c0e435e3 __clone (libc.so.6 + 0xfe5e3)
                                                   
                                                   Stack trace of thread 6692:
                                                   #0  0x00007f85c0e0ba95 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc6a95)
                                                   #1  0x000055c1ac80ae36 n/a (Jamulus-headless + 0x36e36)
                                                   #2  0x00007f85c1355f7f n/a (libQt5Core.so.5 + 0xcdf7f)
                                                   #3  0x00007f85c19d3259 start_thread (libpthread.so.0 + 0x9259)
                                                   #4  0x00007f85c0e435e3 __clone (libc.so.6 + 0xfe5e3)
Jul 14 13:56:43 psilly.com systemd[1]: jamulus.service: Main process exited, code=dumped, status=6/ABRT
Jul 14 13:56:43 psilly.com systemd[1]: jamulus.service: Failed with result 'core-dump'.
Jul 14 13:56:43 psilly.com audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jamulus comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 14 13:56:43 psilly.com systemd[1]: jamulus.service: Consumed 44.845s CPU time.
```
Here is the core dump:
[core.Jamulus-headles.989.f98967b2eaad4017b67008e1416bfcf2.648.1626285400000000.zst.gz](https://github.com/jamulussoftware/jamulus/files/6819222/core.Jamulus-headles.989.f98967b2eaad4017b67008e1416bfcf2.648.1626285400000000.zst.gz)

**Operating system**
Arch Linux (up to date with stable repo, 5.12.12-arch1-1)
Installed using the [jamulus-headless](https://aur.archlinux.org/packages/jamulus-headless/) package in AUR

**Version of Jamulus**
3.8.0

**Additional context**
Let me know if I can provide anything else or fix this on my side, I don't really understand the stack trace. Thanks for the support!

**Comment by npostavs** [comment]
The stacktrace might be more useful if you could build with debug symbols.

**Comment by dcorson-ticino-com** [comment]
Have you looked to see what processor load there is when several clients are attached?
Maybe you have some background process stealing processor power and causing Jamulus to overload.

**Comment by acerix** [comment]
I rebuilt with debug symbols so will wait for another crash to get a new trace. 

I don't have a detailed history but the 30 minute average CPU use went up to 40% and it seems nothing else was using much CPU so it's possible the CPU maxed out.  Right now only 3 clients are connected and it's already using 40%.  I'll try some better monitoring/testing to get more info. I had also tried with and without '-F' and both had crashes.

**Comment by dcorson-ticino-com** [comment]
40% with only 3 clients looks really suspicious.
I would say something else is stealing cpu time from Jamulus.

**Comment by DavidSavinkoff** [comment]
Someone else had a problem similar to this, and found that they were running two instances of the server.
ps -ej

**Comment by acerix** [comment]
The second 40% I mentioned is referring only to the Jamulus process (the first 40% was for all processes).  The server is pretty idle otherwise, <1% CPU, but it's a VPS so the total available CPU is less than a normal server and may get scaled down at times, so in that sense, other VPS's could be stealing CPU time.

I'm probably allowing too many clients for my server to handle, but seems to me it shouldn't crash in that case. Maybe it could refuse new connections, or lowering quality etc.? Or have some way to determine the max clients a server can support?

Thanks for the tip, but I can confirm only one instance is running.

**Comment by ann0see** [comment]
> Or have some way to determine the max clients a server can support?

No. Unfortunately not. It all depends on the hardware resources a server has. Did you check an older version of the jamulus server? Maybe we can trace the bug to the new multi threading improvements?

**Comment by acerix** [comment]
I'm not sure how to reproduce the crash to test an old version, it still hasn't crashed since I turned on debug symbols.

I tried testing the max clients it can handle and was able to connect 15 clients, after that they get stuck "trying to connect", with the server process using 100% CPU.

**Comment by ann0see** [comment]
Ok. Good to hear (although the issue hasn’t been 100% identified 😒)
~~~
Closing this issue then. If you still experience it in future, just re-open it and leave a comment v
