### ISSUE TITLE
Enable mixing with external DAW

### ISSUE THREAD

**Issue by RayChu-TW** [jamulussoftware/jamulus#1925]
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/1840

<div type='discussions-op-text'>

<sup>Originally posted by **emlynmac** June  7, 2021</sup>
I'd like to start working on expanding the multi-track capabilities of Jamulus. 

I have a 16 channel firewire mixer and one of the things I'd like to be able to do is to have individual channels appear as users in the Jamulus mixer.

I'm going to start looking into the code as to how this could be done, but any help would be greatly appreciated or any insights that would make this a no-go also keenly wanted!

To be clear, this is about having multiple up streams to the server from the same host, from different channels of the same interface. On the macOS side, this will be about manipulating the core audio call backs into the stream to the server. 
One question here is whether the audio up stream will be multiplexed or independent. Probably the latter, in order to avoid a change to the protocol but I have yet to look into it. 

Just wanting to get a discussion going around this while I have a look at the how.

Thanks!</div>

**Comment by RayChu-TW** [comment]
I use Reaper reRoute to make my three Mics in Windows10 for three Jamulus processes.
For Reper:
  Track 1: input : my EVO4 Mic1, output : ReRoute 1,2 and Master Send unchecked.
  Track 2: return from Jamulus, input : Reroute 3 and Master Send checked so that I can hear from Jamulus via reaper.
For Jamulus:
  Device select "ReRoute ASIO", input : ReRoute-Client1, Client2, output : ReRoute 3,4
Then repeat the above for other mics, and it worked!!!

**Comment by RayChu-TW** [comment]
Then I would like to make a wish for Jamulus:
Can I  select other  Jamulus track output to reRoute? so that I can receive all Jamulus tracks to mix on Reaper.
Jamulus Server is already a multichannel recorder which is great, but I'd like to mix Jamulus tracks in Real time.

**Comment by ann0see** [comment]
That’s not easy, I‘m afraid. The server does all the mixing and all clients only get a stereo signal. Getting each signal from the server (like the recorder does) leads to synchronisation issues, as far as I remember. See https://github.com/jamulussoftware/jamulus/pull/967#issuecomment-807248062

**Comment by RayChu-TW** [comment]
Thank you so much for the reply and redirection. I got it!!!
Jamulus Server can do multi-track recording is already great work!!!
I appreciate all the work that Jamulus had accomplished. it really helped!!!

**Comment by RayChu-TW** [comment]
Sorry, I would like to try the mastermix but don't know how to run 3.7 beta 
I tried --mastermix in 3.8 but nothing happened...
Thanks for any directions....

**Comment by RayChu-TW** [comment]
Dear Ann0See,
Thank you so much  for the reply, i have closed the topic after reading
your redirection.
One more question, I'd like to run the master mix on server, stated in Release
r3_7_0masterMixBeta (3.7.0dev-6114866)
<https://github.com/cwerling/jamulus-mastermix/releases/tag/r3_7_0masterMixBeta>
but
I don't know how to run it.
I tried --mastermix in Jamulus server 3.8 but nothing happened.
Please point me a direction , thank you in advance.

Warm regards
Ray YL Chu  朱元雷
Art Director of Pop&Jazz Development
TCMC (Taiwan Choral Music Center)
新北市中和區中和路366號8樓之3
8F.-3, No.366, Zhonghe Rd., Zhonghe Dist.,
New Taipei City 235, Taiwan (R.O.C.)
http://www.tcmc.org.tw
+886-2-2920-9028 (O)
+886-2-2920-8961 (F)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ann0see ***@***.***> 於 2021年7月24日 週六 下午4:04寫道：

**Comment by ann0see** [comment]
I‘d ask @cwerling about that? You should be able to specify mastermix via cli, but also need to connect with at least 3 clients to actually profit from it. The director and you yourself are excluded from the master mix mode. Delay panning doesn’t work - as far as I remember.

**Comment by cwerling** [comment]
Dear Ray,

Can you confirm you are using the masterMix fork for both the server as well as all clients?

Most importantly, the mix master needs to have this version. After connecting to a server run with —mastermix, he will see “YOU CONTROL: Master Mix at ServerName” above the mixer board.

Clients can also use regular versions of Jamulus, but their (enabled) faders will not have any effect for them (except their own as well as the mix master’s channel. When using the master mix fork, clients will have this limited controls indicated by disabled faders.

**Comment by RayChu-TW** [comment]
Thank you Ann0See and Christian,
Actually I use "C:\Program Files\Jamulus\Jamulus.exe" -s -p 22126  -w
"Welcome" --mastermix
but nothing happened. this is Jamulus 3.8, I don't know how to run 3.7beta,
does it needs compile or ...?
Thanks!
Ray YL Chu

Christian Werling ***@***.***> 於 2021年7月24日 週六 下午10:30寫道：

**Comment by ann0see** [comment]
Yes, you need to compile the mastermix version. If you’re lucky, there’s a compiled asset under "Checks" in the mastermix PR

**Comment by cwerling** [comment]
You should be able to use the compiled versions under “Assets” in the release here: https://github.com/cwerling/jamulus-mastermix/releases/tag/r3_7_0masterMixBeta
