### ISSUE TITLE
Jamulus buzzing/feedback since latest Windows 10 update 

### ISSUE THREAD

**Issue by gary3113** [jamulussoftware/jamulus#1931]
**Describe the bug**
Jamulus buzzing/feedback since latest Windows 10 update 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by dcorson-ticino-com** [comment]
Hi Gary,
Please give us more information as to your setup and what else may have changed.
We would like to help, but at least for me, my crystal ball in in for repairs this week.

**Comment by gary3113** [comment]
Hi Don,
I have a windows 10 pc I5 Dell Optiplex 3070. The external audio interface is a Yamaha Steinberg UR22MkII with a piano keyboard audio input.
The system has been working fine for weeks when logging onto Jamulus and connecting to any server on the Jamulus list.
This last Friday: as soon as I connected to any Jamulus server the audio sent back from the server was repeatedly oscillating with amplitude increasing (positive feedback)’motor-boating’ sound even before a note was played on the keyboard.
The only thing modified in my system this week was a Windows 10 software update.
Please advise and thanks for getting back to me.
Cheers
Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DavidSavinkoff** [comment]
Maybe the update modified some ASIO or ASIO4ALL settings. Take a look at the Jamulus settings as if you were installing it.
Maybe uninstall Jamulus and dependencies, reboot, install Jamulus and dependencies, configure Jamulus and ASIO and hope for the best.

One question to all: Is it possible that some application wants one setting on ASIO, and Jamulus wants another setting that requires ASIO to be configured each time a different application uses ASIO ?

**Comment by gary3113** [comment]
Hiya David
Sorted it out. Loop-back was enabled on my asio driver which fed-back dreadfully! (And obviously!!)
Thanks very much for your input!
Cheers Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ann0see** [comment]
Closing as resolved
