### ISSUE TITLE
Comma in IP Address results in zilch

### ISSUE THREAD

**Issue by mnopneal** [jamulussoftware/jamulus#1941]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by DavidSavinkoff** [comment]
- Do all languages use periods . for ip addresses?
- Do any languages use commas , for ip addresses?
- I would expect zilch to be the correct response for an improper ip address.
- Maybe Jamulus can be forgiving of a comma because
it is a reasonably safe typo to correct.

**Comment by softins** [comment]
> Do all languages use periods . for ip addresses?

I would expect so.

> Do any languages use commas , for ip addresses?

I'm not aware of any. An IP address is an international standard, surely?

> I would expect zilch to be the correct response for an improper ip address.

An error message would be nice, but the author of this issue did not give any context for what they did.

> Maybe Jamulus can be forgiving of a comma because it is a reasonably safe typo to correct.

No, a malformed IP address is just malformed. It's not hard to get it right!

> Well, it appears commas are used to list multiple ip-addresses:
> 127.0.0.1:22124,1.1.1.1:53

Not sure of the Jamulus context where you would do this. `--listfilter` uses `;` to separate.

> So if you don't type it in correctly, it's garbage in... garbage out.

This is true. I'll close this, and if the author wants to edit the original report with some specific details, they can re-open.
