### ISSUE TITLE
Audio stutter after a while

### ISSUE THREAD

**Issue by hsshhhss** [jamulussoftware/jamulus#1942]
Audio starts to stutter like crazy every 5 to 30 minutes. Ping, Delay, and Jitter are all with green light. 

Not sure how to reproduce it but it happens to me all the time.

macOS Big Sur 11.0.1
Jamulus 3.8.0 installed using dmg file, downloaded from the official website
Audio input is routed from a Loopback virtual channel. The input to the virtual channel is Logic Pro. 

The issue can be resolved immediately by manually switching "buffer delay" and "enable small network..." back and forth. But it will eventually happen again after a while.

**Comment by dcorson-ticino-com** [comment]
>The issue can be resolved immediately by manually switching "buffer delay" and "enable small network..." back and forth. But it will eventually happen again after a while.

That is an indication that it is a network problem.
Clicking a buffer delay or the small network buffers ends the internet connection and then starts it again anew.

**Comment by ann0see** [comment]
Converting this to a discussion since it’s probably not an issue with the Jamulus code.
