### ISSUE TITLE
Create send and receive jack ports for each channel on server

### ISSUE THREAD

**Issue by mikedickey** [jamulussoftware/jamulus#1960]
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/1959

<div type='discussions-op-text'>

<sup>Originally posted by **mikedickey** August 20, 2021</sup>
As the owner of a Jamulus server, I would like to be able to use external software applications for audio processing (recording/mixing/etc), by leveraging the [Jack Audio Toolkit](https://jackaudio.org/) ("Jack").

A Jamulus server currently mixes all audio internally, making it difficult or impossible to use alongside other software applications running on the server. Some examples of these are:

- Digital Audio Workstations (DAWs)
- SuperCollider
- Carla
- PD
- etc.

Jack is a very popular framework used to efficiently share low-latency audio across software applications (especially on Linux, although it is also available for Windows and Mac OS X). Jamulus clients on Linux currently use Jack to integrate with system audio devices. When Jamulus is run as a server, it does not currently open or use any ports in Jack.

I would like support for an additional command line option (let's maybe call it "--jackports"?) on servers (Linux only headless is fine) that causes Jamulus to:

- create "receive" ports for each audio channel being sent from each connected client (i.e. "Jamulus:receive_1" and "Jamulus:receive_2")
- create "send" ports for each audio channel being sent to each connected client (i.e. "Jamulus:send_1" and "Jamulus:send_2")

Audio received over the Internet from clients would only be delivered by Jamulus to the "receive" jack ports, and only the audio being received on the "send" jack ports would be delivered over the Internet to Jamulus clients. When running in this mode, the Jamulus server would not perform any audio mixing itself.</div>

**Comment by ann0see** [comment]
Since the discussion is continuing in #1959 I‘d close and lock this.
