### ISSUE TITLE
unclear error message made precise

### ISSUE THREAD

**Issue by DavidSavinkoff** [jamulussoftware/jamulus#1967]
**Describe the bug**

At line 1047, or nearby, in jamulus/master/src/main.cpp:
QString errmsg = "%1: '%2' needs a numeric argument between '%3' and '%4'.";
Should be rewritten in the Queen's English to be:
QString errmsg = "%1: '%2' needs a numeric argument from '%3' to '%4'.";
In order to be mathematically correct in English.
This fixes the meaning in all places where this message ocurrs.

**To Reproduce**

Jamulus -p
Jamulus: '--port' needs a numeric argument between '0' and '65535'.
Jamulus -u
Jamulus -Q
Notice that for Jamulus -p
Ports '0' and '65535' are correctly part of this range, even though the message states that they are outside of the range.
**Expected behavior**

Jamulus -p
Jamulus: '--port' needs a numeric argument from '0' to '65535'.

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by DavidSavinkoff** [comment]
Could someone fix this please (do the PR etc and also get the credit too), as I'm suffering from chemotherapy.

**Comment by softins** [comment]
I disagree with this. Between 0 and 65535 (or from 0 to 65535) is natural and fully understood in British English. Saying "through 65535" is very much an Americanism (if you go through 65535, do you end up at 65536?).

I'm sure I read somewhere that the standard for Jamulus is British English, although I can't find it at the moment.

So I think it's fine as it is.

**Comment by softins** [comment]
> I'm sure I read somewhere that the standard for Jamulus is British English, although I can't find it at the moment.

I found it at https://github.com/jamulussoftware/jamuluswebsite#readme, referring to the website, but I would say the same regarding the software.

**Comment by DavidSavinkoff** [comment]
I am Canadian and correct in my jurisdiction. American reference material is always immediately available to me, and I will be biased. However, I am usually very aware of our language differences (I received a technical writing award in college). If my new wording for the error message is also 'not incorrect' in formal British English, maybe you could consider it. Note also that the error message could contain [0..65535] in the port example.
I will leave it to you to be certain to be correct.

This bug report came about because of an ambiguity mentioned in #1965

**Comment by ignotus666** [comment]
In fact the application language is en_US as corrados wanted it that way. I'm pretty sure the language selection menu says as much.
The website is in en_UK though because of the people behind the documentation. Just to clarify.

**Comment by softins** [comment]
I'm still not convinced this change is needed, and am having trouble understanding why you consider it such a priority.

As a point of comparison, see the [SQL definition of the `BETWEEN ... AND` condition](https://www.w3schools.com/sql/sql_between.asp), where it explicitly says that the lower and higher bounds are inclusive.

**Comment by DavidSavinkoff** [comment]
Jamulus: '--port' needs a numeric argument between '0' and '65535'.
The statement above unambiguously states that the argument is:
1) between the two following values.
2) states which two values.
There is no escaping the meaning here. The set of numbers can only be 1..65534 by any reasoning mind.
Thus, another wording must be used in order to be correct in any literate English. If this wording is translated to other languages, then this illiteracy is imposed on everyone.

You stated a correct wording: "from 0 to 65535"
This wording is an Americanism.
Use it or be Wrong.
