### ISSUE TITLE
Server 3.8.0 - Line continuation code not working in jamulus.service file

### ISSUE THREAD

**Issue by alanhahn** [jamulussoftware/jamulus#2011]
I previously used "\" as a line continuation code in the jamulus.service file but it is no longer being recognized. 

What was:
*ExecStart=/usr/local/bin/llcon-jamulus/Jamulus \
--server \
--port 22124 \
etc.*
must now become:
*ExecStart=/usr/local/bin/llcon-jamulus/Jamulus --server --port 22124 --etc.*

otherwise the service file throws this error:
**Loaded: error (Reason: Invalid argument)**

See attached for full discussion (on Facebook) of error.

[Jamulus Service File Error Facebook Discussion.pdf](https://github.com/jamulussoftware/jamulus/files/7142931/Jamulus.Service.File.Error.Facebook.Discussion.pdf)

**Comment by softins** [comment]
The problem is that your `-w` text contained unescaped `"` characters, which caused the command to be terminated unexpectedly. This is what you need to do:

```
[Unit]
Description=City-Choir-Jamulus-Main-Server
After=network.target
[Service]
Type=simple
User=jamulus
NoNewPrivileges=true
ProtectSystem=true
ProtectHome=true
Nice=-20
IOSchedulingClass=realtime
IOSchedulingPriority=0
ExecStart=/usr/local/bin/llcon-jamulus/Jamulus \
--server \
--port 22124 \
--centralserver localhost \
--serverinfo "City Choir Main;Toronto;38" \
--nogui \
--multithreading \
--recording /var/jamulusrecording/ \
--log /var/log/jamulus/jamulus.log \
--welcomemessage "<h3>Welcome to City Choir's Jamulus Server</h3>Please check <a href=\"URL\">City Choir's website</a> for our rehearsal schedule. For technical issues please contact <a href=\"mailto:email\">Alan Hahn</a> or <a href=\"mailto:email\">Paul Scott</a>.<p>Note: All Jamulus sessions are recorded for later review after which the recordings are deleted.</p>" \
--numchannels 40
Restart=on-failure
RestartSec=30
StandardOutput=journal
StandardError=inherit
SyslogIdentifier=jamulus
[Install]
WantedBy=multi-user.target
```

Notice the `\"` instead of `"` within the welcome message.

If you want your welcome message to contain complex HTML, it is recommended to put it into a separate file, and give that filename to the `-w` option instead:

```
[Unit]
Description=City-Choir-Jamulus-Main-Server
After=network.target
[Service]
Type=simple
User=jamulus
NoNewPrivileges=true
ProtectSystem=true
ProtectHome=true
Nice=-20
IOSchedulingClass=realtime
IOSchedulingPriority=0
ExecStart=/usr/local/bin/llcon-jamulus/Jamulus \
--server \
--port 22124 \
--centralserver localhost \
--serverinfo "City Choir Main;Toronto;38" \
--nogui \
--multithreading \
--recording /var/jamulusrecording/ \
--log /var/log/jamulus/jamulus.log \
--welcomemessage /usr/local/bin/llcon-jamulus/welcomemessage.html \
--numchannels 40
Restart=on-failure
RestartSec=30
StandardOutput=journal
StandardError=inherit
SyslogIdentifier=jamulus
[Install]
WantedBy=multi-user.target
```

And then put this into `/usr/local/bin/llcon-jamulus/welcomemessage.html`:

```
<h3>Welcome to City Choir's Jamulus Server</h3>
Please check <a href="URL">City Choir's website</a> for our rehearsal schedule.
For technical issues please contact <a href="mailto:email">Alan Hahn</a> or <a href="mailto:email">Paul Scott</a>.
<p>Note: All Jamulus sessions are recorded for later review after which the recordings are deleted.</p>
```

**Comment by alanhahn** [comment]
Thanks ever so much Tony for your detailed and helpful reply. Putting the -w HTML in a separate file worked perfectly. However, using \\" instead of " in the HTML did not work. I resorted to using ' (single quote) instead and that worked perfectly.

Also, using \\ as a line continuation code after the ExecStart= still does not work. I get the same error message as before even though the -w external file now works without error. 

What could be preventing the \\ from working?

**Comment by gilgongo** [comment]
I've also noticed that systemd unit files have some sensitivity to this (maybe to do with extraneous spaces before the trailing `\` or perhaps unix vs other new line, or control characters?):

https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines

You may be better off calling a shell script from the ExecStart instead. This also has the advantage of being able to make changes to that without re-initialising the unit file.
