### ISSUE TITLE
Update fr_FR app translation for 3.8.1

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2020]
Hi @jujudusud,
We are getting ready for the 3.8.1 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **fr_FR** by **2021-09-30**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-09-30

Suggested commit and PR message:
```
Update fr_FR app translation for 3.8.1

Fixes #2020
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by jujudusud** [comment]
Done: 
- Application FR translation,
- Windows FR installer translation.
PR ready to be reviewed.
