### ISSUE TITLE
Update it_IT app translation for 3.8.1

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2021]
Hi @dzpex,
We are getting ready for the 3.8.1 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **it_IT** by **2021-09-30**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-09-30

Suggested commit and PR message:
```
Update it_IT app translation for 3.8.1

Fixes #2021
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by dzpex** [comment]
there are a pull request opened (#1992) if necessary i close it e recreate a new pull request.

**Comment by gilgongo** [comment]
Oh, yes this is a duplicate, isn't it? If you can resolve the conflicts on #1992, then I can merge that and close this one?

**Comment by dzpex** [comment]
yes you can

**Comment by gilgongo** [comment]
Sorry, I confused the issue with the PR.
