### ISSUE TITLE
Update nl_NL app translation for 3.8.1

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2022]
Hi @henkdegroot, @jerogee,
We are getting ready for the 3.8.1 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **nl_NL** by **2021-09-30**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-09-30

Suggested commit and PR message:
```
Update nl_NL app translation for 3.8.1

Fixes #2022
```

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by henkdegroot** [comment]
@jerogee, I have the translation almost done. Will do a PR later. Perhaps you can review?
