### ISSUE TITLE
Update zh_CN app translation for 3.8.1

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2028]
Hi @BLumia,
We are getting ready for the 3.8.1 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **zh_CN** by **2021-09-30**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2021-09-30

Suggested commit and PR message:
```
Update zh_CN app translation for 3.8.1

Fixes #2028
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by BLumia** [comment]
Seems we hit the string freeze date but still would like to ask, could you guys take a look at https://github.com/jamulussoftware/jamulus/pull/2008#issuecomment-916011037 since I think it might be an issue.

**Comment by gilgongo** [comment]
I'm not sure, but I think they're OK - @ann0see ?

**Comment by ann0see** [comment]
We‘re already in the freeze, so I‘m afraid that - except all translators get notified - this needs to be considered for the next release.

**Comment by BLumia** [comment]
> this needs to be considered for the next release.

That's fine :)

**Comment by BLumia** [comment]
A draft PR (#2033) has been created for this issue, the remaining strings will be translated in later patches, I'll mark it as ready to review when I finished the translation.

Before #2033 is ready, I suggest you guys review #2008 first since that one is ready to review :)

**Comment by ignotus666** [comment]
#2008 should be considered part of the translation for 3.8.1 so I can't see why it shouldn't go in (maybe make it part of #2033?). #2007 is a trivial change (the .nsi file for Chinese doesn't get checked without it) that doesn't affect translations, but could also be considered a 'translation' update in a way.

**Comment by gilgongo** [comment]
OK so are we good to merge this PR, 2008 and 2007 now as part of 3.8.1?

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/133933152-991dbe43-5d7e-4509-b574-e6bd18f9f6e2.png)

#2008 should get merged IMO or the JACK-related strings will be completely blank due to 15fe013 didn't add a template untranslated English string. It will be a bug instead of an uncompleted translation that shows the original English copywriting.

btw I personally think it's better to keep #2033 and #2008 two different commits instead of make #2008 a part of #2033. One commit for adding missing translation and one for fixing the blank installer issue.

**Comment by gilgongo** [comment]
OK #2007 and #2008 now merged.
