### ISSUE TITLE
Feature request: MIDI link

### ISSUE THREAD

**Issue by reneknuvers** [jamulussoftware/jamulus#2069]
Objective: to stream midi data from one client to the other. This will allow for control of midi devices and is useful for keeping harmonizers in sync. Other uses are a local controllable click track / metronome, control of remote patch changes, display of chords played on a screen, and control of songbook software

Technical realization: MIDI stream has a max baud rate of 31.25kbaud. A jamulus client software should attach to one midi port as available on Jack or whatever the local OS provides as a midi hook. The stream should be transported along the audio to the connected server and redistributed to each client. Per client the midi stream should be 'muted' or aggregated to a new (virtual) midi port for further use by the local OS.

This breaks: nothing as far as I can tell. Implementation should avoid conflicts with current local midi control functions

**Comment by gilgongo** [comment]
Hi @reneknuvers Thanks for this suggestion! Just so it gets some visibility and so that it can be discussed prior to possibly opening a PR (or a specification for a PR) I'll move this to the Discussions if that's OK.
