### ISSUE TITLE
What's This text for Custom Directories (client)

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#2094]
**Describe the bug**

In the client advanced settings UI, there is a Custom Directories combobox:
![image](https://user-images.githubusercontent.com/1549463/138747635-da9c0513-f1fd-40b4-a668-36fdccfa30f7.png)

The What's This text is out of date:
![image](https://user-images.githubusercontent.com/1549463/138747931-9a996680-62d9-4099-bfae-2757ddde6576.png)

**To Reproduce**
See above

**Expected behavior**
The English text  needs to reflect current usage.  This will mean updating all the translations.

**Screenshots**
See above

**Operating system**
All

**Version of Jamulus**
3.8.1

**Additional context**

Blocked by my changes renaming all the variables.  I'll include the fix in the later PR for https://github.com/pljones/jamulus/tree/bugfix/custom-serverlist-keyboard-control

**Comment by gilgongo** [comment]
The wording is almost OK, but we could expand it like this:

"**Custom directories**: Leave this blank unless you need to enter the address of one of more private directories. Addresses entered here will appear on the Directory list in the connection dialogue."

**Comment by pljones** [comment]
Check my change.

![image](https://user-images.githubusercontent.com/1549463/140645556-5c0d286b-8ab4-475b-b2a2-c938b1a70cda.png)

**Comment by gilgongo** [comment]
Not a fan of help text describing how to use the UI, as that implies the UI isn't usable. But I guess we should. 

BTW the reason I use "private" here is to avoid a circular reference in case the user doesn't immediately know what a Custom directory is ("How should I know if I use custom directories if I don't know what they are?"). Hence also "Leave this blank" for similar reasons.

**Comment by pljones** [comment]
> Not a fan of help text describing how to use the UI, as that implies the UI isn't usable. But I guess we should.

That's because it's not particularly usable in this case.  I argued for making it better and lost, so it needs the description of how to use it.

**Comment by pljones** [comment]
> BTW the reason I use "private" here is to avoid a circular reference in case the user doesn't immediately know what a Custom directory is

I've stated many times now that custom directories are _**NOT**_ the same thing as "private" directories.  There's absolutely no way I'd allow that in the UI "help".

A private directory would use listfilter to limit the registering servers.  A custom directory would allow registration from any server but wouldn't be on the Directories list unless added by hand.  It's not difficult to see the difference...

**Comment by gilgongo** [comment]
> That's because it's not particularly usable in this case. I argued for making it better and lost, 

Yes. Maybe if we get feedback on that we can look at the preferred designs we had for that (I think we looked at an "x" or something next to the entries).

**Comment by gilgongo** [comment]
> I've stated many times now that custom directories are _**NOT**_ the same thing as "private" directories. 

Still interested to see if anyone else [picks up on it here](https://github.com/jamulussoftware/jamulus/discussions/2100) though. But I think it may not affect enough people, perhaps.

**Comment by pljones** [comment]
Updated on my branch:
![image](https://user-images.githubusercontent.com/1549463/140656016-0bf33e8b-8b17-4160-9140-4b165047852e.png)

I note that there's no way using the keyboard to get the what's this cursor active in Settings -- we should add "File/Close" and "Help/What's This" menu items.

I also note that most of the Connect dialog doesn't have What's This text anyway... (a) that should be fixed and, at that time (b) "File/Close" and "Help/What's This" menu items should be added.

**Comment by ann0see** [comment]
@pljones @gilgongo this is tagged for the upcoming release, I think it's a quick fix. Any volunteers for a PR - since it's basically already fixed?

**Comment by gilgongo** [comment]
What's the fix? I'm not clear.

**Comment by ann0see** [comment]
Peters' suggestion one comment above?

**Comment by pljones** [comment]
This looks like it's done.  Please re-open if there's a problem.
