### ISSUE TITLE
Prevent automatic start of Jamulus after installation on windows when no audio driver available

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#2099]
**Has this feature been discussed and generally agreed?**
Enhancement has been mentioned in #2088 

**Describe the solution you'd like**
The last screen of the windows installer contains an option to automatically start Jamulus after the installation completed.
This option is enabled by default and can be disabled by the user (if not desired to start).
The installer allows you to install Jamulus on a system which does not have a audio driver (asio or jack) installed. In this scenario is does not make sense to automatically start Jamulus after the installation completed, as it will fail due to the missing audio driver.

This enhancement applies to the windows installer only and will set the option to automatically start Jamulus after the installation to unchecked when there was no audio driver detected and the user decided to go ahead with the installation.

**Comment by henkdegroot** [comment]
@gilgongo , can you assign this to me please?

**Comment by henkdegroot** [comment]
@gilgongo, actually do you think there will ever be a scenario that you want to auto start if you don't have a correct driver installed during installation?
As if not, we could just remove the auto start option completely for this scenario.
Leaving it there of course when there is a driver detected.

**Comment by gilgongo** [comment]
Yes that would seem potentially less confusing as we know that starting the client won't work when there is a problem with the driver. I suppose it's just possible that the subsequent errors encountered might give you some clues if it wasn't immediately obvious why you had a problem perhaps? But that seems unlikely.

**Comment by ann0see** [comment]
@henkdegroot I'd suggest you to read through https://github.com/jamulussoftware/jamulus/pull/841 to get a few insights in the installer.

**Comment by gilgongo** [comment]
Is this also related @henkdegroot ? Maybe look at it in the same PR? https://github.com/jamulussoftware/jamulus/issues/1756

**Comment by henkdegroot** [comment]
@gilgongo, it is partial related. As the dialog in #1756 is the dialog which will be presented when Jamulus run automatically after the install (without having an ASIO driver present). However #1756 is more about "later". I.e. I may have removed the ASIO driver from my system (or it is not working anymore) and then when I start Jamulus I get this error message.

Perhaps adding a link in that dialog referring to the installation for windows page on jamulus.io would be nice?

**Comment by gilgongo** [comment]
> Perhaps adding a link in that dialog referring to the installation for windows page on jamulus.io would be nice?

Yes, always good to have some "further info" available for when things don't go as expected.
