### ISSUE TITLE
Update server icon for system tray

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2112]
The old (generic) server icon appears the system tray:

![image](https://user-images.githubusercontent.com/4561747/140637420-901aa26b-176d-4f80-bbbc-85ff286781ad.png)

![server-icon-tray](https://user-images.githubusercontent.com/13550012/145638499-903bfbe6-d646-4125-9b61-fdf2c2f11cfa.PNG)

**Comment by henkdegroot** [comment]
Seems to me this icon is used as it is shown the tray icon here? 
On Windows the same icon is used in the system tray.

Should it be different?

**Comment by gilgongo** [comment]
I'm not seeing that on Windows (it's showing correct "server" icon) here:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/4561747/145617101-7cc5094c-7fb6-4b03-8923-80ff68136cad.png">

Or do you mean another place?

**Comment by henkdegroot** [comment]
Here is what I see in my windows system when I run the server:
![server-icon-tray](https://user-images.githubusercontent.com/13550012/145638499-903bfbe6-d646-4125-9b61-fdf2c2f11cfa.PNG)

According to the code, the following two icons are displayed in the system tray, depending on the state of the server:
[https://github.com/jamulussoftware/jamulus/blob/master/src/res/CLEDGreenArrow.png](https://github.com/jamulussoftware/jamulus/blob/master/src/res/CLEDGreenArrow.png)
[https://github.com/jamulussoftware/jamulus/blob/master/src/res/CLEDGreyArrow.png](https://github.com/jamulussoftware/jamulus/blob/master/src/res/CLEDGreyArrow.png)

Extract of the code available in **serverdlg.cpp**: 
    BitmapSystemTrayInactive ( QString::fromUtf8 ( ":/png/LEDs/res/CLEDGreyArrow.png" ) ),
    BitmapSystemTrayActive ( QString::fromUtf8 ( ":/png/LEDs/res/CLEDGreenArrow.png" ) )

So I wonder how you got that view....my test is with 3.8.1.
Also Linux Ubuntu is showing the same icon in the "tray" (probably not called tray in Linux, but I am not a Linux expert)

**Comment by gilgongo** [comment]
Ah OK. The "system tray" is different from the "dock" in each OS then I guess. So the screenshot you post is the Windows system tray:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/4561747/145672479-f899139c-e109-4cd5-86a5-fcf78ecfc70f.png">

Either way, I was under the impression that the Jamulus icons for the client and the server were jamulus-icon-2020.svg and jamulus-server-icon-2020.svg, not the old one shown in CLEDGreenArrow.png and CLEDGreyArrow.png. So if a user sees  jamulus-server-icon-2020.svg in their dock, should they not see the same icon in their system tray?

I wasn't aware of the states though - what do green and grey mean?

**Comment by henkdegroot** [comment]
> should they not see the same icon in their system tray?

Correct, the system tray icon is different.

> what do green and grey mean?

Green means the server is active (i.e. at least 1 client connected)
Grey means the server is inactive (i.e. started but not client connected)

> colour alone as that's an accessibly violation.

I agree, which then raises the question what indicator will be appropriate for this icon/functionality?
For me a X  would be not correct, as X means error and there is no error.
Guessing Play and Pause would be option. 

Like this:
![grey-pause](https://user-images.githubusercontent.com/13550012/145679002-47ebea5a-eca3-4c38-8aa6-d7c2ea85dc60.png)
![green-play](https://user-images.githubusercontent.com/13550012/145679005-335e0782-9f19-4045-82c3-fe0b7325fe03.png)

Maybe we should start a different topic/issue for this?

**Comment by gilgongo** [comment]
I think if the issue here is that we need a new server icon for the system tray which a) reflects the "new" design (jamulus-server-icon-2020.svg) and b) uses something other than colour to convey the state, then I think I'll just change the title of this issue.

**Comment by gilgongo** [comment]
As to the play/pause I think that's better. We may not need the colour in that case? But it does imply the icon might also be a button though, in which case it suffers from both misleading affordance as well as mode error :-( Maybe better if we can overlay a number when users are on the server? So no number is "empty", but the number of people on the server is given otherwise? 

As to using the new icon, I'm not sure if that visually compresses very well at the size need. Might need simplifying...

**Comment by henkdegroot** [comment]
Overlay with the number of users....not sure if that is possible and might impact on performance and the readability might not be good as well.

Guess there is no harm in using the current (new) server icon and add play/pause to this?

Sample (without using colour):
![server-play](https://user-images.githubusercontent.com/13550012/145680281-7b3c4423-312d-4fb2-90f2-7a07b5cda664.png)

![server-pause](https://user-images.githubusercontent.com/13550012/145680286-bd19211a-b979-4225-9ad5-2a11d5f859fa.png)

**Comment by gilgongo** [comment]
OK sure. Hard to say without seeing it in context though. 

BTW I know it's not actually a button, but the play/pause thing makes it look like it is. So might it help if we just showed the "play" icon when people were on the server, and not the pause? Having both (and looking like a button) means that when you see each state you have to think "Is the the icon trying to tell me that I can pause it or that it is paused?" (and vice versa for play - is it playing or can it be played?). Perhaps the absence of the pause mark might help you think of it the right way around?

**Comment by henkdegroot** [comment]
Sure thing, it may look like a button indeed....though silly enough it actually is a button as well, as when you click on it you get to server window in display (or context menu shown).

Think just adding "play" would be sufficient. But should it be play is the question then.
I got the pause/play idea from the ASIO4ALL icon utility which is doing a similar thing.

Not really an expert on accessibility.

**Comment by gilgongo** [comment]
In terms of accessibility, all we need to do is signal the state change in a way that isn't just colour (since not everyone can see colour differences in the same way, and in some lights/screens colour might be hard to see even if you have no visual impairment. So the "play" icon overlay is fine for that. 

In terms of usability, it's harder with the "play" icon because it make it look like a button - and as you rightly point out, it is in fact sort of a button (on Windows at least), but doesn't do what "play" would imply :-) So that's a usability issue perhaps.

There is a bit of a convention of "state indication" in the system tray though, so can we offset the "play" maybe (and make it, say, red?)

![image](https://user-images.githubusercontent.com/4561747/145681413-1125870c-0311-40d8-aad9-f59a9c28364a.png)

**Comment by henkdegroot** [comment]
I like the off-set idea very much....don't think the red play is nice, the second picture seem better and keep the green dot as close as possible to the corner could perhaps be sufficient to distinguish the active/inactive.

**Comment by gilgongo** [comment]
I agree - we could try fitting in a small play button into the do but it might get lost perhaps? Would probably need to actually build it to see:

![image](https://user-images.githubusercontent.com/4561747/145682072-387195a3-4f2c-48a4-b636-4811d7fd0121.png)

**Comment by henkdegroot** [comment]
Looks very good to me

**Comment by gilgongo** [comment]
OK let's see what all the others think...

**Comment by henkdegroot** [comment]
> Or use a gray vs. colored icon?

Thinking that only using gray vs colored will not be an acceptable choice for maintaining accessibility.

But to be honest the current (round) icon is not really much different, it is hard to tell the difference between active and non-active.

**Comment by gilgongo** [comment]
I think that given the "play" symbol has a possibly misleading association with "click me" rather than "the server isn't empty", and that a simple dot is usually used by other apps to signal they are in need of attention or otherwise "active", then a dot would do. We can't use colour alone to signal meaning, as Henk says

**Comment by ann0see** [comment]
Ok. So probably a green dot would do it then
