### ISSUE TITLE
Debian package for latest release

### ISSUE THREAD

**Issue by RobMeerwijk** [jamulussoftware/jamulus#2118]
Current Debian pakage Jamulus release is 3.6.2. As far as I can see  the package is blocked because 2 debian requirements are not met yet. https://tracker.debian.org/pkg/jamulus 

1. Warning: https://appstream.debian.org/sid/main/issues/jamulus.html
2.  Standards version of the package is outdated. The package should be updated to follow the last version of Debian Policy (Standards-Version 4.6.0 instead of 4.5.1). 

I don't know if this is the problem or if there is another reason for the latest release not getting packaged for Debian.

**Comment by pljones** [comment]
Please download the debian package from https://jamulus.io -- we're looking into host a PPA to make it easier to keep up to date.

**Comment by DavidSavinkoff** [comment]
Thorsten Glaser is the Debian packager of Jamulus (as seen in the links you provided). I suppose he will address these two small Debian packging issues.
If the latest Jamulus version is not getting packaged for Debian, then try to contact Thorsten Glaser.

**Comment by RobMeerwijk** [comment]
> Please download the debian package from https://jamulus.io -- we're looking into hosting a PPA to make it easier to keep up to date.

That is a bit too quick. I am using jamulus on a headless raspberry pi. No package available yet for raspbian.

**Comment by pljones** [comment]
According to Facebook, the Jamulus Pi release should be updateable:
https://www.facebook.com/groups/619274602254947/posts/1017500112432392/?comment_id=1017937259055344

I've not seen anything specific from Paul, the maintainer, though.
https://www.facebook.com/groups/619274602254947/user/100000949157510

**Comment by RobMeerwijk** [comment]
> According to Facebook, the Jamulus Pi release should be updateable: https://www.facebook.com/groups/619274602254947/posts/1017500112432392/?comment_id=1017937259055344 Maybe give that a go, instead of Raspian?
> 
> I've not seen anything specific from Paul, the maintainer, though. https://www.facebook.com/groups/619274602254947/user/100000949157510
> 
> Or try it on a Pi Zero 2 https://www.facebook.com/groups/619274602254947/user/100000949157510

Hi, I know about Jamulus Pi, but I did choose my own setup starting from scratch, because I wanted low latency kernel, among other considerations. So that is no option I think. Paul has his own way of working. Although, I can't tell for sure, because I don't have a FB-account. And I don't see how a zero could help me? I have a rpi 4. 

Of course I could compile from source (relatively easy), but I have to do that for all my friends that I provided with a jamulus box. That is do-able, of course. But since there is a 3.6.2 package for raspbian/debian I was hoping that 3.8.1 would become available as well. I contacted Thorsten (see above), no reaction yet.

**Comment by pljones** [comment]
I've opened https://github.com/jamulussoftware/jamulus/discussions/2122 to discuss getting the PPA set up.  Initially it would only be for existing `.deb` builds.

If Github widens the range of supported hardware platforms we can run the build for (and the Qt libraries are available for, of course), adding those to the build process would form a separate issue.

**Comment by RobMeerwijk** [comment]
Thank you. I am running on Debian bullseye. Could that be the issue? On the other hand. On Synology amd64 I am also stuck on the same version. 

Op 14 nov. 2021 15:06, om 15:06, Peter L Jones ***@***.***> schreef:

**Comment by ann0see** [comment]
@mirabilos I assume this issue is for you.

**Comment by mirabilos** [comment]
ann0see dixit:

***@***.*** I assume this issue is for you.

No need to prod, unless there is something very pressing that was
not, like the server list changes, already integrated.

I already told Rob I’ll update my packages periodically, but I’m
short on hacking time both work‑ and health-caused at the moment.

bye,
//mirabilos

**Comment by ann0see** [comment]
Seems to be resolved. So closing

**Comment by mirabilos** [comment]
There used to be `https://jamulus.io/wiki/Central-Servers` list of directory servers run by the Jamulus project. Is this completely gone now (so the “official” directory servers are only baked into the code)?

**Comment by mirabilos** [comment]
Do `--listfilter`, `--serverbindip` and `--serverpublicip` accept IPv6 addresses now (and, if so, in which format), or still only Legacy IP (IPv4)? Does `--qos` work with IPv6 (which also has an iptos octet)?

Asking for the manpage.

**Comment by ann0see** [comment]
Not sure about the IPv6 support for these flags.

I‘d suggest you to open a new discussion to raise more visibility and ping softins.

**Comment by ann0see** [comment]
> There used to be `https://jamulus.io/wiki/Central-Servers` list of directory servers run by the Jamulus project. Is this completely gone now (so the “official” directory servers are only baked into the code)?

No. They’re here: https://jamulus.io/wiki/Server-Linux

**Comment by pljones** [comment]
> Do `--listfilter`, `--serverbindip` and `--serverpublicip` accept IPv6 addresses now (and, if so, in which format), or still only Legacy IP (IPv4)? Does `--qos` work with IPv6 (which also has an iptos octet)?
> 
> Asking for the manpage.

I'm not sure but _anything_ relating to registering a server in a directory is likely to be IPv4 only -- there's no point supporting IPv6 in the options as the protocol doesn't support registration messages containing IPv6 addresses.

**Comment by mirabilos** [comment]
Thanks! I’ll continue…

**Comment by mirabilos** [comment]
+ N 579 Dec 23 Debian FTP Masters             (4111) jamulus_3.8.1+dfsg1-1_source.changes ACCEPTED into unstable

**Comment by ann0see** [comment]
@mirabilos thanks for updating. I hope you’re feeling better now.
