### ISSUE TITLE
German translation of Jamulus server headline is wrong

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2123]
**Describe the bug**
The window description of the Jamulus Server at the top of the window is wrong. Probably this is due to one of the translation a wrong translation (most likely the second).
**To Reproduce**
Open Jamulus Server in German
Look at the window
**Expected behavior**
The window should say Jamulus Server, not Jamulus is the name of the main application
**Screenshots**
![image](https://user-images.githubusercontent.com/20726856/141698010-06afeaf4-305f-44ca-92f5-115ce478095f.png)
**Operating system**
Windows 10

**Version of Jamulus**
Latest
**Additional context**
https://github.com/jamulussoftware/jamulus/blob/d0393c400c860efa6fa613a0b33f91cfcef5c101/src/res/translation/translation_de_DE.ts#L3572

@rolamos could you please update the file?

**Comment by ann0see** [comment]
@rolamos could you please review your translation?

**Comment by rolamos** [comment]
@ann0see , yes I will fix it. Is there a description of the official issue-solving way in github ? Do I have to fetch a local copy first and work on the master branch or can this be done directly in the Github-Web UI ?

**Comment by ann0see** [comment]
You can do it via web ui.
