### ISSUE TITLE
Server list not fully populating

### ISSUE THREAD

**Issue by eajohnson70** [jamulussoftware/jamulus#2167]
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/2166

<div type='discussions-op-text'>

<sup>Originally posted by **eajohnson70** December 10, 2021</sup>
Beginning yesterday afternoon, the Jazz genre server list is not fully populating (including my own server). I've tested this on my daily machine and secondary machine (both Macs on the same network) as well as a new install on a Windows PC on a different network. Is anyone else seeing this behavior?</div>

**Comment by softins** [comment]
Have you compared with what is shown by [Jamulus Explorer](https://explorer.jamulus.io)? Right now I can see 24 servers in the list, although one of them doesn't appear to be responding properly.

**Comment by eajohnson70** [comment]
Yes and the Jamulus Explorer page is missing a ton of servers too.

**Comment by softins** [comment]
> Yes and the Jamulus Explorer page is missing a ton of servers too.

OK, how do you know what ones are missing? Jamulus Explorer is my project, so I would be very interested in any way it is not working correctly. I think it is more likely that the display is correctly showing what servers are successfully registered, and any "missing" servers are actually failing to register with the directory server. Happy to help diagnose why that might be, for any servers you have control of.

**Comment by eajohnson70** [comment]
My server is missing as well as quite a few others that I frequent.

**Comment by softins** [comment]
It looks like there is currently an issue with some of the obsolete jamulus server names in the `fischvolk.de` domain. We'll follow up with the owner of that domain, as there must be quite a few servers still using them.

**Comment by pljones** [comment]
I wouldn't put it like that.  I would expect they've finally been removed after having been deprecated for over a year.

**Comment by eajohnson70** [comment]
Changing the domain name in my server config solved the issue for my server. There must be many more servers out there using the deprecated fisckvolk.de fqdn. I'm guessing that allowing the repo to handle updates is the reason for these addresses sticking in the config?

**Comment by softins** [comment]
Yes, on Linux servers, the config scripts will typically not be updated automatically, as they may well contain customisations.

For GUI apps, servers and clients older than 3.7.0 will be using the deprecated names in `fischvolk.de`. 3.7.0 onwards use `jamulus.io` instead.

**Comment by eajohnson70** [comment]
Is this advertised somewhere and I simply missed it?

**Comment by softins** [comment]
> Is this advertised somewhere and I simply missed it?

The second bullet point in the [release notes for 3.7.0](https://github.com/jamulussoftware/jamulus/releases/tag/r3_7_0) mentioned it, but probably didn't place as much emphasis on the implications at it could have.

**Comment by softins** [comment]
This should now be resolved. It turned out to be an oversight in DNS reorganisation within the last couple of days, which has now been corrected.
