### ISSUE TITLE
Do not show ASIO Device settings and open ASIO settings on JACK version of Jamulus

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2186]
Documenting for future fixing. In theory this is a good first issue ;-). However the description is for the team.

Currently we still show the ASIO device settings button (probably somewhere in settings) and the open ASIO settings button in soundbase.cpp even if we compile the JACK version on windows. We should not use #ifdef _WIN32 in these files.

See:

Is this defined if we're running JACK on Windows?  If so, it's the wrong symbol.

_Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/pull/2168#discussion_r773478884_

**Comment by gilgongo** [comment]
Just a meta point: issues in "triage" are for when we've not decided if we want to deal with them yet. Issues with a milestone can't be in triage, so i've moved this to "backlog" as I assume we've decided we will work on it.

**Comment by pljones** [comment]
Just checking -- this has 3.9.0 but looks like it went into 3.8.2, is that right?

**Comment by ann0see** [comment]
Yes, I think so.

**Comment by hoffie** [comment]
Yep. I've updated the milestone.
