### ISSUE TITLE
--help goes to stderr instead of stdout

### ISSUE THREAD

**Issue by QJKX** [jamulussoftware/jamulus#2190]
Debian, Version 3.8.1

jamulus --help
prints text to stderr instead of stdout.

ditto
jamulus --version

Expected behavior:

text I expect to see should go to stdout.
only errors and debug info should go to stderr.

https://unix.stackexchange.com/questions/8813/should-the-usage-message-go-to-stderr-or-stdout

https://stackoverflow.com/questions/7977852/what-are-the-conventions-for-stdout-stderr-messages

**Comment by ann0see** [comment]
Hi! Thank you for the report and sorry for the delay. Does it go to both?

**Comment by pljones** [comment]
I've got a fix for this.  Although it'll be a while.

```
#include <iostream>
...
<< qUtf8Printable ( UsageArguments ( argv[0], options ) ) << "\n";
...
```

**Comment by QJKX** [comment]
Hi!
>Does it go to both?

So by default I think a console shows both stdout and stderr. If messages were going to both you'd see them twice, and that doesn't happen.

**Comment by ann0see** [comment]
Ok. Just looked at the code: https://github.com/jamulussoftware/jamulus/blob/2f7146b1812da58e6984cb6a2771b98cc273ba53/src/main.cpp#L131

It seems as if due to reasons I don't know this is the only cli option not going to qInfo.

**Comment by pljones** [comment]
> going to qInfo.

`qInfo()` doesn't help.

**Comment by deithohx** [comment]
I'm a qt/c++ novice but the qInfo qCritical functions look like stuff to do with the [logging framework](https://doc.qt.io/qt-5/qmessagelogger.html). I would expect logging to be a toggleable side effect of what the program is doing.


With `--version` and `--help` (and maybe `--serverinfo`) the output text is the purpose of the program. So I think the simple and correct thing to do is to just write to stdout with something like [qTextStream](https://doc.qt.io/qt-5/qtextstream.html).

Cribbing an example
    QTextStream(stdout) << QString("Hello world");

**Comment by QJKX** [comment]
(I'll try this comment again 😬)

I'm a qt/c++ novice but the qInfo qCritical functions look like stuff to do with the [logging framework](https://doc.qt.io/qt-5/qmessagelogger.html). I would expect logging to be a toggleable side effect of what the program is doing.

With `--version` and `--help` (and maybe `--serverinfo`) the output text is the purpose of the program. So I think the simple and correct thing to do is to just write to stdout with something like [qTextStream](https://doc.qt.io/qt-5/qtextstream.html).

Cribbing an example QTextStream(stdout) << QString("Hello world");

**Comment by pljones** [comment]
> > Although it'll be a while.
> 
> So you mean, for this to be fixed all we have to do is wait a while until your changes are implemented?

:)  Well, I only added
```
#include <iostream>
...
std::cout << qUtf8Printable ( UsageArguments ( argv[0], options ) ) << "\n";
...
```
because it was mentioned here - so if someone wants to get the fix done and dusted...?

**Comment by henkdegroot** [comment]
> if someone wants to get the fix done

I will give it is try

**Comment by pljones** [comment]
Just to add, only tested on Linux -- I don't know if Windows is more fussy.  It had some weird stuff added to even get `qInfo()` etc working, IIRC.

**Comment by henkdegroot** [comment]
I have tested windows as well.
