### ISSUE TITLE
Accelerator key collision in several languages

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#2214]
**Describe the bug**
When using English:
The ALT+S key combination has been assigned to two items.
The "Settings" item in the menu bar and the "Settings" option in the main window both use ALT+S.

The applies at least to French, Dutch and German.

**To Reproduce**
When using English:
Press ALT+S repeatedly to see the result. You need to press 3x to get the Settings dialog to appear.
When using Geman:
The repeated ALT+S action does not work at all, this only shows the menu.

**Expected behavior**
When using English:
Press ALT+S should bring up the Settings dialog.

**Operating system**
Windows 10

**Version of Jamulus**
3.8.1

**Comment by pljones** [comment]
@softins Haven't you got a script that spots multiply-assigned shortcuts?

**Comment by softins** [comment]
> @softins Haven't you got a script that spots multiply-assigned shortcuts?

It's not at all thorough, because it has no knowledge of the hierarchy, particularly with menus. It produces output showing multiply-used accel chars within a form, which then need to be checked by hand. The script is in `tools/checkkeys.pl`.

**Comment by henkdegroot** [comment]
I have update the issue, as it is not just for English. Seems at least it is consistent between the languages.

**Comment by softins** [comment]
I've just checked this on my Windows version, and can confirm it happens. I think it's a side-effect of the menu re-organisation that was done between 3.8.0 and 3.8.1. Version 3.8.0 didn't have a "Settings" menu. It was in 3.8.0 that I put significant effort into detecting duplicated accelerator keys. I looked at it in a more cursory way for 3.8.1 and must have overlooked the new clash between Settings button and Settings menu.

The question is, which of the two should have its accelerator key changed, and what to? That could also vary for each language.

**Comment by henkdegroot** [comment]
I would vote to change the Menu item since that was added. Also because CTRL+S also takes you to the Settings (audio/network tab).

**Comment by pljones** [comment]
I don't think _most_ menu items _should_ have accelerator keys - they're accessible pretty quickly with Alt+\<Menu\>\<MenuItem\> shortcuts already.  It's only for the most commonly used things, in my view.  So "Connect" and ... um, that's probabaly it :).

("Platform Standard" items like `Alt-F4 Exit`, `F1 Help` and `Shift-F1 What's This?` accelerators, of course...  I tend to avoid the cut/paste/undo/edit operator keys in any application except where they have a sensible meaning as those operations, too.  "Least surprise"...)

**Comment by henkdegroot** [comment]
> Alt+<Menu><MenuItem> shortcuts already

Isn't that because these are the accelerator keys in the menu's?

**Comment by pljones** [comment]
> `> Alt+<Menu><MenuItem> shortcuts already`
> 
> Isn't that because these are the accelerator keys in the menu's?

Is "Ctrl C for Copy" an accelerator or shortcut?  Is "Alt-E,C for Edit->Copy" an accelerator or shortcut?  In either case, they have to be explicitly added to the software.  You don't get them for free.

**Comment by henkdegroot** [comment]
I would say an accelerator key is one that is part of the text item, while a shortcut can be any key.
Like CTRL+V for Paste. And indeed we already have CTRL+S (at least in English) to directly access the Audio/Network-settings dialog. But you need to remember that, while the Settings option in the dialog is "always" visible. It just does not always show the underline character to indicate there is an accelerator key.

Also as soon as you open a menu item (say ALT+E), the next keystroke is applied/searched for in that menu. So having submenu items only have to be unique within the menu they appear in. Personally I would not mind that these keys would not be used, but believe they are an important factor for accessibility.

**Comment by pljones** [comment]
I don't think anyone is suggesting changing how menu navigation works.

The point is whether or not additional shortcut/accelerator keys are needed for menu items -- i.e. is "Ctrl-C for Connect" _needed_ when we have "Alt-F,C for File->Connect"?

**Comment by henkdegroot** [comment]
Okay, understand you point of view. But this issue is about 1 main menu item being the same as 1 item shown in the dialog.

**Comment by pljones** [comment]
I'd rather none of the checkboxes were there, to be honest.  Using the menus, now they're sane, is easier.  Of course, long time users will find their disappearance disconcerting... ("Where's Settings Gone?")

("Mute Myself" could arguably be moved up with the input values, above the ping/delay/jitter group.  I'd prefer that feature gone completely... but... I lost that discussion... :) .)

**Comment by henkdegroot** [comment]
> I'd rather none of the checkboxes were there, to be honest.

Sounds like it is almost time to move to the "next UI layout"....I still love the proposal in #1343

**Comment by softins** [comment]
OK, I think I agree with changing the Alt-key for the Settings menu. Let's get that into 3.8.2.
