### ISSUE TITLE
64 and 128 sample size is indicated to be preferred (shown in different text)

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#2222]
**Describe the bug**

Different samples size is preferred.

**To Reproduce**

Open the GUI audio/network-settings and check the text shown in the GUI vs the text shown in the WhatsThis details.

**Expected behavior**

Either the same setting should be indicated as being preferred or the WhatsThis text may have the "preferred" reference removed (which will be inline with the Usermanual on the website).

**Screenshots**

![sample-size-preferred](https://user-images.githubusercontent.com/13550012/148596561-e1ca3b09-1a78-4192-8b32-9b6cede309b3.png)

**Operating system**

Win10

**Version of Jamulus**

3.8.1

**Comment by henkdegroot** [comment]
@pljones, thank you for your always thorough review of PR's and spotting this!

**Comment by henkdegroot** [comment]
Any preferences for which solution to implement?

**Comment by pljones** [comment]
Historically, "128, preferred" has always been the case (predating the existance of "small network buffers").

Both the 64 samples for the audio buffers and the "small network buffers" options increase CPU load and potential jitter (particularly on Windows).  It may be perfectly okay to run a RPi4 with 64 samples and small network buffers but a five year old Windows laptop using ASIO4ALL might struggle to keep up with 128/"normal".

I'm inclined to remove "preferred" as it's system-specific.

**Comment by henkdegroot** [comment]
@pljones, in the PR I have removed the "preferred" text from the whats is this text but left the one in the GUI. Not sure if you wanted that to be remove as well.

**Comment by pljones** [comment]
It should be consistent: i.e. the list in the "What's This?" should show the user what they see on screen and explain what it means (and why it says it, which helps them remember what it means).  The radio button labels are explained in the "What's This?" text -- and should match.  So if we're not saying "preferred" in the "What's This?" text, we shouldn't say "preferred" in the label text.
