### ISSUE TITLE
Github: windows-latest build env will switch to windows-2022 soon and will break CodeQL

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2259]
**Describe the bug**

Windows builds currently show this annotation on the Actions tab:
> windows-latest workflows will use windows-2022 soon. For more details, see https://github.com/actions/virtual-environments/issues/4856

Also see https://github.com/github/codeql-action/issues/850
@ann0see tried building with windows-2022 explicitly and it failed in CodeQL:
https://github.com/ann0see/jamulus/runs/4858827768?check_suite_focus=true
> Error: Tracing builds with CodeQL is currently not supported on Windows 11 and Windows Server 2022. Please modify your Actions workflow to use an earlier version of Windows for this job, for example by setting `runs-on: windows-2019`.

We should therefore pin to windows-2019 for now.

- [x] Pin to windows-2019
- [x] Leave this ticket open as a reminder to switch to windows-2022 once CodeQL is fixed and no other stuff breaks (or find another way to remind us)

**Comment by softins** [comment]
Pinned to 2019 in 5a181d1078c647ef29f00cfe45a96dbf822a282e

**Comment by hoffie** [comment]
Tagging for 3.9.0 in order to be reminded to re-check then. If CodeQL doesn't have support for it by then, we'll just move the issue to the next bigger milestone.

**Comment by Kay-kay2019** [comment]
🤣🤣🤣 I haven't used that computer since Jan 31st 2019 or before that. I was about to go into labor. I'll look at it in a few min. Omw home now. Thank you I appreciate  everyone  so much
