### ISSUE TITLE
Automatically add new contributor to source code

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2271]
**Has this feature been discussed and generally agreed?**

Not yet, but related to https://github.com/jamulussoftware/jamulus/pull/2264#issuecomment-1019570820
**Describe the solution you'd like**
 
If a new user opens a PR and this PR gets merged, GitHub actions should open a PR based on the Check contributors script (https://github.com/jamulussoftware/jamulus/blob/master/tools/get_release_contributors.py) and add undocumented contributors automatically to respective files.
**Describe alternatives that have been considered**

Open an issue automatically, automatically comment on the respective (first) PR.

**Comment by hoffie** [comment]
I think we can at least have a check.
I'm not sure yet if automatically creating a PR is possible in a sane way, especially due to the fact that we distinguish translations and code contributions.

**Comment by hoffie** [comment]
Other options:
- No automation: Add a checklist item for contributors to add themselves? Advantage: Decentralized work, people can add themselves in the right places and can choose the appropriate name.
- Semi-automation: Have a CI check remind first-time submitters to add themselves

**Comment by ann0see** [comment]
Other option (probably the easiest): https://github.com/marketplace/actions/welcome-new-users
set up this option and remind first PR contributors to add themselves.

**Comment by pljones** [comment]
Looks perfect!

**Comment by ann0see** [comment]
Since I closed my PR and don't plan to work further on it, I'll hand this issue over to anyone who wants to take it over. Therefore unsubscribing.
