### ISSUE TITLE
Parts of PR #1994 (wrong display of Unicode characters at line wrap) got lost

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2274]
**Describe the bug**

`TruncateString()` in `src/util.cpp` is currently unused and generates a compiler warning on Mac due to this.
This function was initially introduced in ce370e95d43b2051ba20160e5ec50f13b2de5748 via #1994, master merge commit 51589960a80d91b8d5c681349ac21a91d53fefdd. While the function is still there, all the other code from this commit is missing.

I suspect that a (later) bad merge has caused this.

After lots of tracing directly on master, I had a look at the PR's commits again and something seems fishy there:
- ce370e95d43b2051ba20160e5ec50f13b2de5748 adds `TruncateString` + the call in `src/util.cpp` (as expected)
- a8853b6a7deb19e3596fb47bbb72a5baf29c4c7a is a merge commit which still contains the function definition, but lacks any call of the function

So, I believe that the merge commit unwittingly dropped the call. This is no surprise though, as the merge commit likely had severe conflicts to do a parallel huge code reorganization through d94fd69e1404a874beec53d6a721abcd74caf8fb, which moved `CMusProfDlg::OnAliasTextChanged` (where the lost change was) to `CClientSettingsDlg::OnAliasTextChanged`.

- [x] Find the root cause
- [x] Attempt to find further affected PRs/commits: As the problem occured directly within the PR, I don't assume any systematic problems.
- [x] Restore any missing commits #2275

**Version of Jamulus**

master @ 25018800b704cdf23bffa837911a485309ca216e

**Additional context**

**Comment by djfun** [comment]
Before removing the function, please check what happened to the context where it was used.

**Comment by hoffie** [comment]
I have found the likely reason for the missing caller and have updated the issue description accordingly. Will submit a PR shortly.
