### ISSUE TITLE
Update documentation to use correct Linux dependencies

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2289]
I have studied and tested this on both Raspbian 10 and 11, with the aim of making the script compatible with both. This is what I have found:

1. On 10, the package `qt5-default` does two main things: pull in `qtbase5-dev` as a dependency, and set the default version of Qt for `qtchooser`. Without this, there is no default version.
2. On 11, the package `qt5-default` does not exist. `qtbase5-dev` is still available as the main package to install, and the default version of Qt for `qtchooser` is automatically set to 5 by one of the installed dependencies.
3. Using `qtchooser -list-versions` is an OS-independent way of determining whether there is already a default or `qt5-default` is required.
4. Package `qtdeclaractive5-dev` is not required at all, as it only provides modules not used by Jamulus.
5. Package `qttools5-dev-tools` is available on both 10 and 11, and is required on 11 to provide `lrelease` for `qmake`.

So I would recommend the following section of code for installing packages on both 10 and 11 (I have tested on fresh installs of both):
```
# install required packages
pkgs='alsamixergui build-essential qtbase5-dev qttools5-dev-tools libasound2-dev cmake libglib2.0-dev'
if ! dpkg -s $pkgs >/dev/null 2>&1; then
  read -p "Do you want to install missing packages? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo apt-get install $pkgs -y
    # Raspbian 10 needs qt5-default; Raspbian 11 doesn't need or provide it
    if ! qtchooser -list-versions | grep -q default; then
      sudo apt-get install qt5-default -y
    fi
  fi
fi
```
I have a version with this change at https://github.com/softins/jamulus/tree/fix-pi

_Originally posted by @softins in https://github.com/jamulussoftware/jamulus/issues/2267#issuecomment-1022127426_

**Comment by hoffie** [comment]
Do you have any pointers wrt CI? I ran a quick grep and only found COMPILING.md, but nothing autobuild related.

**Comment by ann0see** [comment]
That was just an assumption. It should be here: https://github.com/jamulussoftware/jamulus/blob/master/autobuild/linux/autobuild_deb_1_prepare.sh

**Comment by ann0see** [comment]
It seems to be ok and very basic in the CI.

**Comment by softins** [comment]
> That was just an assumption. It should be here: https://github.com/jamulussoftware/jamulus/blob/master/autobuild/linux/autobuild_deb_1_prepare.sh

That looks to specify exactly the same qt packages as I listed in the raspi script update. Cool, glad I came to the same conclusion. Assuming from that that Ubuntu 18 doesn't need `qt5-default` then, or the builds wouldn't work.

**Comment by softins** [comment]
> Do you have any pointers wrt CI? I ran a quick grep and only found COMPILING.md, but nothing autobuild related.

Just looked at `COMPILING.md`. The Qt dependencies for Linux definitely need revising. I can make a PR for that, but need to check the differences between OS versions (Ubuntu, Debian and Raspbian) in order to be accurate.

**Comment by ann0see** [comment]
I just removed the CI part. It seems as if only the documentation needs to be updated

**Comment by hoffie** [comment]
We should also look into using `--no-install-recommends`. One of the dependencies (I think it's `qttools5-dev-tools`?) pulls in a whole lot of packages, including a full Xorg stack, which is totally overkill, especially on headless systems. Using that option might result in having to specify one or two other dependencies explicitly (`qt5-qmake` comes to mind).
(I haven't done any Raspberry-specific tests, but this is what I've found on Ubuntu. For autobuild, I'll keep track of the `--no-install-recommends` changes).
