### ISSUE TITLE
Update de_DE app translation for 3.8.2

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2301]
Hi @rolamos,
We are getting ready for the 3.8.2 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **de_DE** by **2022-02-06**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-02-06

Suggested commit and PR message:
```
Update de_DE app translation for 3.8.2

Fixes #2301
```

Note: Some of the displayed "untranslated" strings will actually not be new, but will rather be shown due to technical reformatting (e.g. %1). You may be able to easily update them using the "vanished" translations list.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by ann0see** [comment]
@rolamos could you please give us a short update if you work on the German translation?

**Comment by rolamos** [comment]
Reviewed German translation

**Comment by ann0see** [comment]
@rolamos we had some minor changes to the translations. Could you please update the German translation? (It's near the "Pegelmesser" thing, I think)

**Comment by rolamos** [comment]
Hi @ann0see ,
ok I‘ll complete that until Sunday.
Being rather busy at the moment with other tasks.
Regards Roland

**Comment by hoffie** [comment]
@rolamos Any updates on this? We're really planning to get out rc1 today and this seems to be the last task left... :)
Happy if you could do it. If not, I should have some time for this in about two hours (16:00 CET).

**Comment by rolamos** [comment]
Hi Christian, I just came back home late and my plan was to complete it tonight. is there still anything to do ?

**Comment by hoffie** [comment]
Hi Roland,
I think we should have everything for the 3.8.2 German app translations ready, so new stuff is likely to come up in some weeks when 3.9.0 is being prepared. Would be great if you could help there again :)

(I assume you are reading/commenting via email so you likely did not get a notification about the edit to my previous post which pointed to #2387).

If you are looking for other stuff to help with for 3.8.2, then I'd like to point you to https://github.com/jamulussoftware/jamuluswebsite/issues/688 (German web site translations). I think the main translation round is being completed there right now as well, but it should be possible to merge German updates at a later point. If you want to help there, this would be great. Just comment on the ticket if you are working on it or if you have any questions (the process is different). Other translators are also reachable on the discord channel on #translators.

Thanks! :)
