### ISSUE TITLE
Update nl_NL app translation for 3.8.2

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2305]
Hi @henkdegroot, @jerogee,
We are getting ready for the 3.8.2 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **nl_NL** by **2022-02-06**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-02-06

Suggested commit and PR message:
```
Update nl_NL app translation for 3.8.2

Fixes #2305
```

Note: Some of the displayed "untranslated" strings will actually not be new, but will rather be shown due to technical reformatting (e.g. %1). You may be able to easily update them using the "vanished" translations list.

This Issue is assigned to multiple people. Please coordinate who will translate what part.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by henkdegroot** [comment]
@jerogee , translation is almost complete (just doing a final test before submitting the PR). Will request you to review the PR.
