### ISSUE TITLE
Update sv_SE app translation for 3.8.2

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2310]
Hi @genesisproject2020,
We are getting ready for the 3.8.2 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **sv_SE** by **2022-02-06**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-02-06

Suggested commit and PR message:
```
Update sv_SE app translation for 3.8.2

Fixes #2310
```

Note: Some of the displayed "untranslated" strings will actually not be new, but will rather be shown due to technical reformatting (e.g. %1). You may be able to easily update them using the "vanished" translations list.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by ann0see** [comment]
@genesisproject2020 could you please give us a short update if you work on the sv_SE translation?
