### ISSUE TITLE
Update zh_CN app translation for 3.8.2

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2311]
Hi @BLumia,
We are getting ready for the 3.8.2 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **zh_CN** by **2022-02-06**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-02-06

Suggested commit and PR message:
```
Update zh_CN app translation for 3.8.2

Fixes #2311
```

Note: Some of the displayed "untranslated" strings will actually not be new, but will rather be shown due to technical reformatting (e.g. %1). You may be able to easily update them using the "vanished" translations list.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by ann0see** [comment]
Ok: https://github.com/jamulussoftware/jamulus/issues/2247#issuecomment-1033730000;
That’s the comment which pinged all translators. I already thought that something went wrong. Maybe you just missed a mail (The changes are not too big, so I think it’s still ok to raise a PR if you want to). 

Concerning discord access, please mail team@jamulus.io to get access.

**Comment by BLumia** [comment]
Oh sorry, I might click the "Done" icon on the GitHub Notification page by mistake. Anyway PR here: #2391
