### ISSUE TITLE
Translation of GPL preamble in GUI and CLI

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2319]
**Describe the bug**

Status quo:
- The GPL preamble in *About Jamulus* is in English (untranslated). The newly added GPL preamble in `--version` output is translated. That's inconsistent.
- The way of implementing the translation is non-optimal for translators as pointed out by @BLumia in https://github.com/jamulussoftware/jamulus/pull/2313#discussion_r794258387

**To Reproduce**

- Compare *About Jamulus* with `--version`
- or: Perform translations

**Expected behavior**

We should:
- [ ] Decide if this text should be translated at all. For context: `cat --version` translates it.
- [ ] If we do translate, the GUI version should be translated as well (it would be more natural for the command line version not to be translated as other command line outputs aren't translated either).
- [ ] If we wanted to show a translated version on CLI, we would have to load translations, which are [currently loaded for GUI runs only](https://github.com/jamulussoftware/jamulus/blob/master/src/main.cpp#L813).
- [ ] @BLumia suggested using a single `tr ( )` call with included new lines (`\n`). This sounds good to me. There's also the possibility to pass comments to translators such as *"Please align to X characters"* (the status quo value for X is rather wide...?). The way to pass such a comment to translators seems to be to use a special [`//: Comment which is transferred to .ts files by lupdate`](https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments).

**Version of Jamulus**

3.8.2_beta1

**Additional context**

I'm not keen on decoding this, I'm fine either way, but we should be consistent and make life easier for translators.

**Comment by DavidSavinkoff** [comment]
A lawyer is required to translate agreements. Only one agreement should be official... the original in the official language. I have only seen the GPL in English, thus, Jamulus must have disclaimers for unofficial translated versions.

**Comment by henkdegroot** [comment]
The single tr() does not really work well in this scenario, as there is more text involved in the command line output for formatting (which is not part of the translated text). Perhaps I should not have included the option to translate that part in the version output, but in my defense I went for a similar approach as "cat".

**Comment by hoffie** [comment]
> The single tr() does not really work well in this scenario, as there is more text involved in the command line output for formatting (which is not part of the translated text).

Couldn't it be part of it though? I was about to submit a PR with exactly this, but stopped when I saw that the GUI part is not translated.

> Perhaps I should not have included the option to translate that part in the version output, but in my defense I went for a similar approach as "cat".

No worries :)

**Comment by henkdegroot** [comment]
> Couldn't it be part of it though?

Sure the *** which is at the beginning of each line could be part of the text as well.

Found some information related to the translation of the GPL text: https://www.gnu.org/licenses/old-licenses/gpl-2.0-translations.html

Interesting fact, the console won't print my local Dutch text. So it prints in English. Tested this on Windows, not sure if all OS's do the same.

**Comment by hoffie** [comment]
@DavidSavinkoff 
> Only one agreement should be official

@henkdegroot 
> Found some information related to the translation of the GPL text: https://www.gnu.org/licenses/old-licenses/gpl-2.0-translations.html

This issue is "only" about the license declaration though. It's not about the full license text, i.e. the actual agreement. Not saying that the declaration is not important or can't be translated errornously, but it's a big difference in my opinion.

> Interesting fact, the console won't print my local Dutch text. So it prints in English. Tested this on Windows, not sure if all OS's do the same.

Heh, interesting, same here. Looks like translations are not loaded for CLI at all:
https://github.com/jamulussoftware/jamulus/blob/0485745562b387d8e188a7b0a1589cc53e2a95bc/src/main.cpp#L813

**Comment by pljones** [comment]
Headless doesn't load translations -- they're presumed only used in the GUI.

**Comment by BLumia** [comment]
> The GPL preamble in About Jamulus is in English (untranslated). The newly added GPL preamble in --version output is translated. That's inconsistent.

The GPL content cannot be translated since only the English version is valid ([ref](https://www.gnu.org/licenses/translations.html)).

> A lawyer is required to translate agreements.

This issue is about the license declaration than the actual license text, and we're not going to translate the original license text, so I guess it's okay.

> ... agreements

And since we are on this topic, saying it's an "agreement" doesn't very suitable for GPL since the user doesn't need to "agree" to GPL to use the software, see [here](https://www.gnu.org/licenses/gpl-faq.en.html#ClickThrough), but it's a different issue I guess :P

> The single tr() does not really work well in this scenario, as there is more text involved in the command line output for formatting (which is not part of the translated text).

Multiple `tr()` is still okay, but just don't break one single sentence into two `tr()`s. But anyway, one thing I don't understand is, why do we need the `***` in each **line** of the text in 8fb8ce768 in the first place?

**Comment by henkdegroot** [comment]
So should we just remove the translation option from the version text?

**Comment by hoffie** [comment]
Sounds like this would be the easiest path forward, yeah. The efforts are probably spent better elsewhere.
Let's wait for some other opinions as well, though.

**Comment by ann0see** [comment]
Yes. I'd remove it.
