### ISSUE TITLE
mute myself over midi

### ISSUE THREAD

**Issue by paulsijben** [jamulussoftware/jamulus#2323]
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/2322

<div type='discussions-op-text'>

<sup>Originally posted by **paulsijben** January 30, 2022</sup>
The current keyboard shortcut for mute myself works well but only when the Jamulus main window is the active one. Should you need to mute yourself when zoom, sibelius or any other bit of support software one is using, the keyboard shortcut is useless.
It would be great if a MIDI code can be used to achieve this as well.
 
I do not really mind which midi code needs to be used, but as people may be using the X-touch mini already to control incoming channels, CC code 87 or 88 as a default value might be useful.   (see also https://ianmorrish.files.wordpress.com/2019/08/xtouch-mini-mdi-mapping.png?w=1024)
</div>

**Comment by pljones** [comment]
Leaving this as a discussion for now.
