### ISSUE TITLE
Update "URL" to domain in connectdlg.cpp

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2332]
https://github.com/jamulussoftware/jamulus/blob/e375329d6eff0c89a34c121de06d12dbe6b3b5af/src/connectdlg.cpp#L87

shows a wrong text as mentioned by @pljones this should be edited (after this release) a PR can already be raised now.
See below what it should be updated to.

**Comment by ann0see** [comment]
Suggestion: If you know the IP or domain of a server, you can ...

**Comment by pljones** [comment]
"IP" is an ambiguous abbreviation - here meaning "internet protocol".  On it's own, it's not useful.  It's an adjective being used as a noun.  So it needs _address_ (the noun) following, both to disambiguate and to make it correct English.

**Comment by ann0see** [comment]
Ok. Updated it

**Comment by pljones** [comment]
Sorry, was still thinking :)

**Comment by ann0see** [comment]
Ok. is https://github.com/jamulussoftware/jamulus/issues/2332#issuecomment-1028245766 ok

**Comment by ann0see** [comment]
Now the only thing which is missing is a PR ;-). As soon as we get into the "release is upcoming, fix every tagged issue" phase, someone (maybe me) might fix it.
