### ISSUE TITLE
Rephrase mute options in help text

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2335]
The following help text is not precise enough and needs updating:
```
  -M, --mutestream      starts the application in muted state
      --mutemyown       mute me in my personal mix (headless only)
```

I actually have _no_ idea what the "help" text for those two options _means_... so I could be wrong about what that option _does_...

_Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/discussions/2322#discussioncomment-2092079_

**Comment by ann0see** [comment]
Mutestream should refer to "Mute myself" maybe something like "-M Mutes the client input such that no audio gets sent to the server. This is the "Mute Myself" option. 

Not that sure for the other one. 

--mutemyown mutes own channel in personal mix (headless only)

**Comment by pljones** [comment]
OK, so:
* `--mutestream` is the "bypass server" option (which doesn't mute for the client it's set on - just doesn't send the audio to the server for mixing, it mixes it locally, meaning no one else hears you but you do) - i.e. the poorly named "Mute myself" checkbox; and
* `--mutemyown` is "mute me in my server mix" (which means everyone else hears you but you don't) - equivalent to the "Mute" checkbox in the mixer for my own channel.

I guess that
```
     --mutemyown       mute me in my personal mix (headless only)
```
could be
```
     --mutemyown       mute me in my personal server mix (headless only)
```
for added clarity

Perhaps
```
  -M, --mutestream      starts the application in muted state
```
could be
```
  -M, --mutestream      starts the application with the option to bypass the server mix enabled ("Mute myself")
```

**Comment by ann0see** [comment]
@gilgongo can you work on rephrasing these options according to Peter's suggestions: https://github.com/jamulussoftware/jamulus/issues/2335#issuecomment-1028431267 ?

**Comment by gilgongo** [comment]
Probably best not to use the same words in the commands and also in the definitions, particularly if "mute" is usually associated with not hearing the thing you're muting. So would the following be slightly clearer?

```
-M, --mutestream       Do not send my sound to the server ("Mute myself"). Others will not hear me.
```

```
--mutemyown            Cut my sound in my personal server mix (headless only). Others will still hear me.
```

**Comment by ann0see** [comment]
Maybe slightly better – however I doubt we can do much against this confusion

**Comment by ann0see** [comment]
@gilgongo I think the `mutestream` option would be ok. 
`mutemyown` could be

Cut my own sound in my personal mix (headless only). Others will still hear me.

**Comment by pljones** [comment]
We don't use "cut" in describing the mixer anywhere else, though.

**Comment by ann0see** [comment]
I think cut was to avoid the ambiguity between both mute options

**Comment by pljones** [comment]
In that case I think we've a bigger issue.  This should go back to looking at how to describe these options wherever they appear, in my opinion.

**Comment by ann0see** [comment]
Yes. However, the re-phrasing should do exactly that? 
Changes would need to be applied to the website too ofc.

**Comment by pljones** [comment]
I'm thinking of GUI _labels_, the What's This text, the hover text, things like that.

**Comment by ann0see** [comment]
Ok. Yes. But the problem is even larger - as @gilgongo mentioned somewhere: It's mostly related to the Mute Myself vs. mute own channel in own mix confusion.

**Comment by pljones** [comment]
I'm saying I think that should be tackled with priority over changing the help text.

**Comment by gilgongo** [comment]
> I'm thinking of GUI labels, the What's This text, the hover text, things like that.

OK, but what we're looking at here is the description of the command line options for `--mutestream` and `--mutemyown`.  If we can work out the wording here, we can widen it out to the GUI and elsewhere later.

On the wording as it stands, if somebody is used to the standard meaning of the term "mute", they will expect the sound they hear to stop. Yet in the case of `--mutestream` they will hear themselves. We think there may be a confusion in that, but since "mute" is in the name, there's not much we can do.

However, we may be able to better explain by **not** using word "mute" in the definitions (which in any case is best practice to avoid circular definitions). Hence my [suggestions above](https://github.com/jamulussoftware/jamulus/issues/2335#issuecomment-1111389105)

**Comment by pljones** [comment]
"Prevent others hearing what I play" - that might suggest why it's called mute?  The sending to server stuff is a bit more technical that needed.  That would give
```
-M, --mutestream       Prevent others on a server from hearing what I play.
--mutemyown            Prevent me from hearing what I play in the server mix.
```
In both cases, of course, the participant will lose mental latency compensation with others on the server as they're not hearing the mix as others hear it.  I don't think adding any more to the text, though, as it starts to get complicated (i.e. explaining why you'll annoy people by using either setting).

**Comment by ann0see** [comment]
Yes, these descriptions should also work. I'm slightly supporting these suggestions more.

> I just don't think either option should exist at all... :)

There are valid use cases for both (listen only client, Streaming,...)
