### ISSUE TITLE
Hint for buffer delay setting is inaccurate if pipewire is used

### ISSUE THREAD

**Issue by jose1711** [jamulussoftware/jamulus#2347]
**Describe the bug**
Hint for Settings/Buffer Delay shows:
```.. On Linux, use the JACK configuration tool to change the buffer size.```

If a user is using Pipewire this text does not help much - changing the buffer size in - say QjackCtl has no effect. Instead jamulus needs to be started like this (for 128 samples):
```
PIPEWIRE_LATENCY="128/48000" jamulus
```
As Pipewire is being adopted by more and more Linux distribution, hint should be improved.

**Operating system**
Arch Linux, x86_64

**Comment by hoffie** [comment]
Thanks for the report. Would like to submit a PR?

Note: This will likely not make it into 3.8.2 anymore as we are in translation freeze phase (beta) already. But future versions would certainly benefit from that clarification.
Pipewire users might have the benefit that Jamulus will work out of the box for them, so they might not even know that they are using pipewire.

**Comment by jose1711** [comment]
> Thanks for the report. Would like to submit a PR?

I would better pass than on to those with better level of English than me :smile: 

> Note: This will likely not make it into 3.8.2 anymore as we are in translation freeze phase (beta) already. But future versions would certainly benefit from that clarification. Pipewire users might have the benefit that Jamulus will work out of the box for them, so they might not even know that they are using pipewire.

Yes, I can confirm that (no need to start with `pw-jack` or first starting `qjackctl` to start Jack first). Hmm.. thinking about this.. could hints be generated dynamically during the startup (why show Linux-related stuff to Windows users and vice-versa)?

**Comment by pljones** [comment]
> (why show Linux-related stuff to Windows users and vice-versa)?

The audio controls that are specific to one audio subsystem should only be being shown for that audio subsystem.  JACK isn't OS-specific, of course.

**Comment by ann0see** [comment]
Sorry for the maintenance noise here. 

To me it seems a bit difficult to proceed here. @gilgongo @jose1711 @mulyaj do you have any other suggestion on how to move this forward? I think 

> On Linux, use the JACK configuration tool to change the buffer size.

Could be reworded to
> If using JACK, use the JACK configuration tool to change the buffer size. Other APIs like Pipewire might need different (command line) options. Please look in their manual.

**Note: ** I 've unsubscribed from this issue to keep notifications down. If you need me, please ping me.

**Comment by jose1711** [comment]
> If using JACK, use the JACK configuration tool to change the buffer size. Other APIs like Pipewire might need different (command line) options. Please look in their manual.

I think this is good.

**Comment by pljones** [comment]
_Hopefully_, #2645 will close this.
