### ISSUE TITLE
Improve naming meterstyle options

### ISSUE THREAD

**Issue by henkdegroot** [jamulussoftware/jamulus#2353]
**Describe the bug**

New feature in 3.8.2 beta allows the selection of different meterstyle options. Current options are:
LEDs
Bar
Narrow Bar
Round LEDs
Small LEDs

**To Reproduce**

Run jamulus and open the profile settings tab.

**Expected behavior**

Options suggested in #1688 by @pgScorpio (from testing the beta release)

Bar (Narrow)
Bar (Wide)
LED Bar (or LED's (Bar) or Bar (LED's) to be consistent in using a suffix)
LED's (Small)
LED's (Big)

or (Though I personally like the previous one better)

Narrow Bar
Wide Bar
LED Bar
Small LED's
Big LED's

**Decided to implement** 

Bar (narrow)
Bar (wide)
LEDs (stripe)
LEDs (round, small)
LEDs (round, big)

**Version of Jamulus**

3.8.2beta1dev

**Additional context**

Changing this does mean English text changes, and could potentially need local language update as well.

**Comment by henkdegroot** [comment]
My preference would be this option:

Bar (Narrow)
Bar (Wide)
LEDs (Bar)
LEDs (Small)
LEDs (Big)

Like the fact the first part of the option indicates the "type" and the part in brackets the "shape". Not a big fan of the bracket though.

**Comment by pgScorpio** [comment]
> Like the fact the first part of the option indicates the "type" and the part in brackets the "shape". Not a big fan of the bracket though.

Yes the idea was grouping by type and shape...
But feel free to use i.e. a hyphen instead of brackets :
Bar-Narrow
Bar-Wide
LEDs-Bar
LEDs-Small
LEDs-Big

**Comment by pljones** [comment]
I don't like using "Bar" for two different things: "Bar-Narrow" (or "-Wide") means the vertical strip meter.  "LEDs-Bar" then should mean a vertical strip of LEDs..?  Uh?  No.

So it needs to use a different word.  I suggested "stripe" (or "strip").

**Comment by pgScorpio** [comment]
> I don't like using "Bar" for two different things: "Bar-Narrow" (or "-Wide") means the vertical strip meter. "LEDs-Bar" then should mean a vertical strip of LEDs..? Uh? No.

Uh, Yes! 
Just google LED Bar and LED Strip, almost the same results, but still it says nothing about shape, but "LED bar" IS a usual name for this type of VU meter (Just Google LED VU), so maybe use that instead?

> So it needs to use a different word. I suggested "stripe" (or "strip").

These are also disputable, since it's not a stripe either and also "LED's-Big" and "LED's-Small" are led strips, just a different shape (and size).
LED's-Square was also no option because 'the LED's are not really square.
And if we are trying to be exact "Bar" is also not a bar but a stripe, since a bar would be 3-dimensional.

But what's in a name?  
As long as the name is somewhat logical and everybody understands what is meant I'm OK with it.

**Comment by henkdegroot** [comment]
@pljones (and others) any preferences between the below options:

Using brackets:
Bar (Narrow)
Bar (Wide)
LEDs (Stripe)
LEDs (Small)
LEDs (Big)

Using hyphen:
Bar-Narrow
Bar-Wide
LEDs-Stripe
LEDs-Small
LEDs-Big

**Comment by hoffie** [comment]
I prefer the brackets style.

Maybe we can adjust the constant names in the code to match the (partly new) UI labels. It's already confusing to work with the code when trying to remember that "SLIM" means "narrow" for bars, but means "round" for LEDs.
https://github.com/jamulussoftware/jamulus/blob/master/src/clientsettingsdlg.cpp#L443-L447

> Changing this does mean English text changes, and could potentially need local language update as well.

Yep :/ And as much as I would like to have that cleaned up, I think we're going to stick with the status quo for 3.8.2...?

**Comment by henkdegroot** [comment]
> I think we're going to stick with the status quo for 3.8.2...?

Okay....it will make it a bit more challenging to update later as we need to include some logic in upgrade to prevent mapping to the wrong item from the previous saved preferences.


> trying to remember that "SLIM" means "narrow" for bars, but means "round" for LEDs.

Guess this can be modified and made more in-line with the LED types.

**Comment by pgScorpio** [comment]
> @pljones (and others) any preferences between the below options:

As said: As long as the name is somewhat logical and everybody understands what is meant I'm OK with it.
So both are fine with me.

> Okay....it will make it a bit more challenging to update later as we need to include some logic in upgrade to prevent mapping to the wrong item from the previous saved preferences.

Meter style is currently saved as a number isn't it? So that doesn't depend on naming and would need translation between type number and dropdown index anyway right?

**Comment by pljones** [comment]
> Meter style is currently saved as a number isn't it? So that doesn't depend on naming and would need translation between type number and dropdown index anyway right?

Yup, enum as integer goes into the ini file.

**Comment by henkdegroot** [comment]
> enum as integer goes into the ini file.

And the enum integer is the same as the dropdown index value.

**Comment by hoffie** [comment]
> And the enum integer is the same as the dropdown index value.

Right now it is, but does it have to be? Could we keep it as it is now but still update the labels and the sorting later by mapping the labels to the enums explicitly instead of relying on the order?

**Comment by henkdegroot** [comment]
@hoffie, should this issue be classified as a bug or would it be better classified as an improvement? Only selected because that option seemed to fit best (from the available option you can select when creating a new issue).

**Comment by hoffie** [comment]
> Changing this now won't be a big task. Just an update to util.h (for the enums) and an update to the clientsettingdlg.cpp for the combobox items. And since it was noticed during a beta test, I would say it could be done. At least I am not aware of only fixing major issue discovered during a beta....but I could be wrong.

I'm mainly worried about translations. If we have plan for that, I'm happy for this improvement to be included before rc1 (which is roughly targeted for tomorrow).
What about doing it like this:
- Adjust labels (PR)
- After merge, ping translators: "Dear translators, we've had some last-minute changes for the newly introduced level meter texts. If you want, you can submit another PR for 3.8.2. If you don't, that's fine as well. We will use your previously submitted translation and may try to reformat it to match the new English text." (I'd not open per-language issues again as we do not need full tracking for that).¹
- Integrate any translation fixes (not sure if this would be OK post-rc1 and whether this would require a rc2 or whether we could still get right to a stable release)

(Just my idea though, so maybe wait for other maintainers' feedback before going ahead. cc @softins @pljones @ann0see )

¹ I think we've once asked translators how they would like such cases to be handled. I was worried about annoying them with repeated pings, but I think the consensus was that they'd rather get a ping and have a chance to make things even better for their language.

> should this issue be classified as a bug or would it be better classified as an improvement?

I'd say *improvement*. Gonna change it.

**Comment by ann0see** [comment]
My standpoint for fixes like this
- Fix everything now which might introduce the need of conversion in code later on
- Ping translators (give them 1-2 days) if they don’t update it, leave the englisch translation
This is done to avoid potentially unneeded code

**Comment by henkdegroot** [comment]
Just submitted the PR, tested locally using Windows. If any objections by others then this can still be done later.

**Comment by henkdegroot** [comment]
> * After merge, ping translators:

Don't forget to generate new TS files first.

**Comment by pljones** [comment]
> Don't forget to generate new TS files first.

And merge.
