### ISSUE TITLE
Fix line endings (\r)

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2360]
**Describe the bug**

Some code files contain Windows line endings (`\r`), while the rest doesn't. We should be consistent.

**To Reproduce**

```bash
$ find src/ windows/ linux/ android/ mac/ ios/ -regex '.*\.\(h\|mm\|cpp\)' -exec sed -re 's/\r$//' -i {} \;
$ git diff --stat
 src/vstmain.cpp   |  222 +++++++-------
 src/vstmain.h     |  134 ++++----
 src/vstsound.h    |  118 +++----
 windows/sound.cpp | 2436 
 files changed, 1455 insertions(+), 1455 deletions(-)
$ git diff -w
# empty
```

**Additional context**

Should be a simple PR, but we should probably stop pushing for even more PRs for 3.8.2, so tagging for 3.9.0.

**Comment by pljones** [comment]
Even if those `vst*` files likely will never be used...
