### ISSUE TITLE
Levelmeter: Ensure that variables and png names (roughly) match

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2365]
From https://github.com/jamulussoftware/jamulus/pull/2356#discussion_r802018996:

E.g.
`BitmCubeRoundBigLedBlack ( QString::fromUtf8 ( ":/png/LEDs/res/CLEDBlackSmall.png" ) ),`

It's a bit surprising to see "Big" being mapped to "Small" here.

**Comment by ann0see** [comment]
@henkdegroot do you plan to fix this?

**Comment by henkdegroot** [comment]
I notice a few issues related to meterstyle, so perhaps include all in one PR?

**Comment by ann0see** [comment]
Yes you can but please split commits

**Comment by henkdegroot** [comment]
As you can see from the PR, I did a separate one for this.
