### ISSUE TITLE
Include Jamulus for Android in Fdroid (as listening client)

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2372]
In order to move the Android support forward, including Jamulus in an App Store was requested: https://github.com/jamulussoftware/jamulus/discussions/1971
I've opened a inclusion request on Fdroid, an alternative App Store for FLOSS software on Android:
https://gitlab.com/fdroid/rfp/-/issues/2011#note_837311154

**Inclusion in Fdroid?**
According to some comments, Jamulus for Android is usable via 4G/5G even for joining Jams. However, even having an Android app as listening client opens up multiple new opportunities: For example live-streaming would be made easier; also some people - like me - like listening while traveling. I'd prefer Fdroid to the PlayStore for now, since I assume more experienced users use Fdroid and inclusion in the PlayStore needs someone to pay a specific amount of money.

**Inclusion of disclaimer**
I would totally suggest to add a disclaimer to the app as mentioned in the GitLab comment: Something like "Using a cellular or ethernet connection is crucial for using Jamulus. Do not use WiFi and please be aware that audio quality is different from device to device".

If you are totally against inclusion/adding a disclaimer, please state why. The Android version is not yet 100% stable, but I think good enough to be provided as easy to get listen only client.

Next actions:

* I would like to start working on the following: Build a metadata structure for Fdroid: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
* Find someone to test Jamulus from Fdroid via Cellular and a good wired Headphone.

**Comment by pljones** [comment]
Ooooh.... "Latest tab criteria":
>    Name
>    Summary
>    Description
>    License
>    a What’s New entry for at least one release
>    at least one graphic (screenshot or a feature graphic)
>    **at least one of the above translated**

Does that mean we can show screen shots of Jamulus in different languges to pass the lab test?

**Comment by ann0see** [comment]
I think it's the metadata. But I think one language (en-US) is enough

The bot in the post I raised says "en-US is required!"

**Comment by pljones** [comment]
Well, we won't get into their "Latest" tab without the translation(s).  It only needs to be one translation (en-US and en-GB?) of the summary...

**Comment by ann0see** [comment]
I mean, we can probably include one or two translations. But I don't want to put the burden on translators to translate much.

**Comment by pljones** [comment]
I reckon "nice" would be:
- everything required under en-US
- summary translated to all the UI languages (as it's likely never going to change once done and it's good to show the short description in the native language, at least, I reckon)
- a selection of UI screenshots for the client but only in en-US, as these change quite often

**Comment by ann0see** [comment]
Ok. See my PR for minimal metadata. As soon as I have access to an Android phone, I can take screenshots.

**Comment by ann0see** [comment]
> Well, we won't get into their "Latest" tab without the translation(s).

The question is: Do we need that at the moment? It wouldn't be bad of course ;-)

**Comment by pljones** [comment]
Yeah, not essential, but nice to have.

**Comment by ann0see** [comment]
Closing as I'm no longer working on it. Maybe some day an FDroid guy builds QT for the FDroid build system.
