### ISSUE TITLE
Remove unneeded android dependencies

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2379]
https://github.com/jamulussoftware/jamulus/blob/a9d067e957655bcd25a18c6609d76cce70058b0d/autobuild/android/autobuild_apk_1_prepare.sh#L61

To me it seems as if there are too many android dependencies being installed. Should we try to remove them?

**Comment by hoffie** [comment]
We can try, of course. Installing less means less downloads and less stuff to cache, so if it's unneeded we should remove it.

(At the same time, I'm grateful for any change which is *not* done until the first week after 3.8.2 as I'm planning the submit/merge the autobuild refactoring stuff by then. :))

**Comment by ann0see** [comment]
Comment to myself: After trying to run the autobuild scripts in a docker container, I have the impression that there are many unneeded downloads: 
Why do we need to download the Android emulator?

**Comment by ann0see** [comment]
After looking a bit more into android, I think we need to do a lot there:
1. Use aqt for downloading the android build
2. Find unneeded dependencies
3. Streamline the process

So that's a lot to do.

**Comment by ann0see** [comment]
Closing as we should split out the other work
