### ISSUE TITLE
Jamulus does not work with MOTU M2 driver version 4.0.9.0087

### ISSUE THREAD

**Issue by jtravere** [jamulussoftware/jamulus#2390]
**Describe the bug**

Hello there ! I have a problem using Jamulus with my MOTU M2. When starting Jamulus, it seems that the software enters an infinite loop trying to change the buffer size. Impossible to use Jamulus (program not responsing) 

**Operating system**
Windows 10 64 bits Home Edition 21H2 build 19044.1526 

**Version of Jamulus**
3.8.1

**Additional context**

MOTU M2 firmware 1.02 Driver 4.0.9.0087

**Comment by pljones** [comment]
Additional information from various sources:

Earlier versions of the MOTU M2 firmware do not show this issue.

**Comment by ann0see** [comment]
I think that happened with ASIO4ALL for me once too. Maybe worth running a debugger.

**Comment by ann0see** [comment]
@pgScorpio can you quickly drop a link to a compiled binary here? Maybe it fixes this issue?

**Comment by pgScorpio** [comment]
I doubt it will make any difference, since there should be no actual functional difference, just another implementation of the same functionality...

But here is the [Jamulus.exe binary](http://peegee.dsmynas.net/jamulus/windows-asio-redesign-v0.rarjamulus-3.8.1-ASIO-test-v0.zip)

**Comment by jtravere** [comment]
![image](https://user-images.githubusercontent.com/99679336/154317798-df2370b8-9038-402b-acf6-5681ccdc6cdd.png)

**Comment by pljones** [comment]
Thanks for raising it with them - and very nice of them to acknowledge the issue.

**Comment by ann0see** [comment]
I hope this issue is now fixed. Closing since it doesn't seem to be Jamulus related. Please re-open if necessary.
