### ISSUE TITLE
Move vst code to feature branch

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2405]
The vst code _could_ also all get moved to a (dead) feature branch.

_Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/pull/2402#discussion_r810482012_

Years ago corrados did some tests on making Jamulus a vst plugin. Since nobody is working on it, we should archive it on a feature branch.

Related issue: #82

**Comment by ann0see** [comment]
Can we just move the files out or are they included anywhere?

**Comment by pljones** [comment]
*Save current state*
```
git checkout master ; # the files are currently on master
git pull upstream master ; # if not on main repo
git checkout -b feature-jamulus-vst ; # or whatever name to tag current position
git push -u  ; # to create the remote branch tag
```
The above could be done by a jamulussoftware/jamulus owner direct to the main repo.

*Update the tree to remove vst code*
```
git checkout master
git pull upstream master
git checkout -b remove-jamulus-vst
git rm (the vst files)
(update the other files to remove references)
git commit -m 'Remove Jamulus VST code' -A ; # Commit all the changes (I think that works... I avoid letting commit decide for itself which files it's doing...)
git push -u
```
The raise the PR.

**Comment by ann0see** [comment]
Can you do it?

**Comment by ann0see** [comment]
@griels could you please comment why this has been downvoted? Do you have a working version or anything which can move the VST forward?

**Comment by pljones** [comment]
> Can you do it?

Not for a few weeks -- if anyone wants to pick it up beforehand, please do.  The tricky bit is `(update the other files to remove references)` -- but that could be as simple as "keep compiling until it doesn't error".  So "Good first issue"?

**Comment by griels** [comment]
Hi, just seems a shame to throw out good work as DAW integration is an important and not uncommon feature of internet jamming software. We're evaluating various options and Jamulus would be a good one were it not for the lack of VST support. 

I do know a fair whack of C++ so should probably muck in, though...

**Comment by jujudusud** [comment]
> ... the lack of VST support.
> 
> I do know a fair whack of C++ so should probably muck in, though...

If so, the future of FLOSS seems to be VST3 (Linux, Mac and Windows), AU for Mac, LV2 for Linux.

**Comment by ann0see** [comment]
Just note that moving to a feature branch doesn’t mean that the feature will come never. It just means we’re not aware of anyone working on it. A PR (based or not on the feature branch) is always welcome.

**Comment by pljones** [comment]
Just to note that there's no need for Jamulus to act as a VST _host_ - that was not the intent.  This was to enable Jamulus to be used as a VST plug-in, taking audio directly from a VST host.

Given that JACK and ASIO work in completely different ways, it _should_ be possible to have VST (or AU or LV2) as another method of connecting audio in/out.

**Comment by ann0see** [comment]
@griels what do you exactly need? Maybe you can open a discussion (aka forum post) under the "Discussions" tab and tell us a bit more about what you need - maybe some things already work (audio routing), others like multi channel output will probably never be possible with the current design.
