### ISSUE TITLE
Disable travis integration

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2408]
**Describe the bug**

https://github.com/jamulussoftware/jamulus/settings/hooks lists an active Travis CI webhook. As far as I know, we don't use Travis (anymore).
@jamulussoftware/maindevelopers  Can we remove this?

**Comment by ann0see** [comment]
Yes. I probably forgot about it.

**Comment by ann0see** [comment]
Ok. Deleted the webhook:

![996DDB39-EADE-4CA5-BC93-E078E852F9B5](https://user-images.githubusercontent.com/20726856/154835423-34c5b72d-03ef-41fe-a22d-e971c4657770.jpeg)
