### ISSUE TITLE
Releases: Rename .debs (drop _ubuntu_, dash for headless)

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2429]
**Has this feature been discussed and generally agreed?**

Initial discussion here: https://github.com/jamulussoftware/jamulus/pull/2423#issuecomment-1048915034

**Describe the solution you'd like**

- [x] Check that there is no technical reason to name the package like that
- [ ] ~Rename jamulus_3.8.2_ubuntu_amd64.deb to jamulus_3.8.2_amd64.deb~
- [ ] ~Rename headless version accordingly~
- [ ] Replace _ by - for headless to match the package name.
- [ ] grep the source for required updates (autobuild scripts use `ubuntu`)

Reasoning: We provide the .deb to support Debian and Ubuntu. `.deb` already hints that it targets these distributions. Adding `ubuntu` is confusing.

**Describe alternatives that have been considered**

Keep as-is

**Comment by ann0see** [comment]
Related to https://github.com/jamulussoftware/jamulus/issues/795

**Comment by ann0see** [comment]
Actually I don’t remember why we named it "Ubuntu" probably because most users are assumed to use Ubuntu and we build on Ubuntu. I think we could rename it. This might imply changes in unofficial scripts.

**Comment by ann0see** [comment]
@sthenos I think you wrote a script for WorldJam. You might need to change the install links one da

**Comment by ann0see** [comment]
Ah. Ok. So basically it’s semi-officially supported. It might make sense to put it into the installscripts repo.

**Comment by ann0see** [comment]
Current status:

I am not feeling a strong need of removing or not removing "ubuntu" from the file name.
Hoffie is slightly pro, softins is slightly con, so I assume the decision is a draw. 

Suggestions involved
* Renaming all files by appending the OS as a folder
* Renaming ubuntu to linux or debian
* Doing nothing

I think renaming to debian would be good although we can’t for sure guarantee Debian compatibility

**Comment by hoffie** [comment]
Yep. I've crossed out the no langer planned TODO items.
jamulus_headless -> jamulus-headless would still help with consistency with the actual package name, so I've left this TODO item open.

**Comment by ann0see** [comment]
So the only thing left is the rename?

**Comment by pljones** [comment]
a) If the "ubuntu" is staying, can the issue title be changed, please?
b) @softins, if this went ahead, would you be able to update Simon's Script after the release?
c) Who maintains the "ubuntu" build script?

**Comment by softins** [comment]
> b) @softins, if this went ahead, would you be able to update Simon's Script after the release?

Yes, I could do that, but would need a ping or mention to alert me, as I still don't have time to follow what's going on with Jamulus.

**Comment by ann0see** [comment]
Do we want to use the jamulus-headless name now? This needs changes on the website

**Comment by pljones** [comment]
As there's no pressing reason for this being included, I've moved it to 3.9.1.

**Comment by pljones** [comment]
Is anything else going to get progressed on this?

**Comment by ann0see** [comment]
I'll shortly open two PRs (app and docs)
