### ISSUE TITLE
Link Administration page from Website in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2453]
**Has this feature been discussed and generally agreed?**
No

**Describe the solution you'd like**
Put a link either in the docs/README.md file to https://jamulus.io/contribute/Administration or in the Contributing file to make it findable. 

**Describe alternatives that have been considered**
Mentioned above

Any concerns doing that?

**Comment by pljones** [comment]
There's very little in https://jamulus.io/contribute/Administration that's of interest when reading Contributing, I'd think.  README.md could have a para to mention that that page is where project administration is documented.

**Comment by ann0see** [comment]
Let’s put it in this file: https://github.com/jamulussoftware/jamulus/blob/master/docs/README.md

**Comment by ann0see** [comment]
Ok. Edited the file.
