### ISSUE TITLE
Android: Use aqt

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2479]
**What is the current behaviour and why should it be changed?**

All platforms which manually install Qt use `aqt`, only Android doesn't.

**Describe possible approaches**

Convert Android builds to use `aqt`.

**Has this feature been discussed and generally agreed?**

Yes - https://github.com/jamulussoftware/jamulus/pull/978#discussion_r578544946

**Comment by ann0see** [comment]
Duplicate of: https://github.com/jamulussoftware/jamulus/issues/2434

I think?

**Comment by hoffie** [comment]
Yep. Sorry.
