### ISSUE TITLE
Autobuild: Make Changelog generation an extra step

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2480]
**What is the current behaviour and why should it be changed?**

The Changelog is currently generated by `analyze_git_references.py`. This is surprising...

**Describe possible approaches**

Changelog generation should be an individual step.

**Has this feature been discussed and generally agreed?**

https://github.com/jamulussoftware/jamulus/pull/2470/files#r822584276

**Comment by pljones** [comment]
@jamulussoftware/maindevelopers Did this happen, does anyone know?

**Comment by hoffie** [comment]
Meh, this was supposed to be fixed in #2584 already. Somehow it's missing most of the mentioned commits. I will try to re-submit a fixed up #2584 instead.
