### ISSUE TITLE
Autobuild: Invert uses_codeql/run_codeql logic

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2481]
**What is the current behaviour and why should it be changed?**

The `uses_codeql` (soon to be renamed to `run_codeql` as part of #2470 boolean is set to true in almost all cases.

**Describe possible approaches**

It makes more sense to turn the logic around, rename the option to `skip_codeql` and only set this where required (e.g. Mac Legacy).

**Has this feature been discussed and generally agreed?**

No.

**Comment by pljones** [comment]
Ah, Mac Legacy - I think that's why the Mac CodeQL and build were separated.  Mac, Mac Legacy and Mac CodeQL (once).

**Comment by softins** [comment]
> Ah, Mac Legacy - I think that's why the Mac CodeQL and build were separated. Mac, Mac Legacy and Mac CodeQL (once).

No, that wasn't the reason. Before we had Mac Legacy, I tried and failed to combine the build and CodeQL for Mac like it had been for Windows and Linux. I can't remember what stopped it working.

**Comment by hoffie** [comment]
Due to other changes, the difference between run_codeql true vs. false is no longer large. I'm therefore not planning to add this at the moment.

```
$ grep run_codeql: .github/workflows/autobuild.yml  | sort | uniq -c
      3             run_codeql:             false
      4             run_codeql:             true
```
