### ISSUE TITLE
Rename ChangeLog to ChangeLog.md to enable Markdown format (and change release scripts)

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2513]
**What is the current behaviour and why should it be changed?**
Curently the ChangeLog doesn't support styling but includes markdown format since the content gets copied to the release notes. It would be good to rename the file to ChangeLog.md to allow formatting. This implies a change in multiple files and probably different styling.

**Describe possible approaches**
Change the Headlines to `## <Version>` (use grep)
Verify that the changelog getter scripts understand the new format
Test the new workflow
Rename ChangeLog to ChangeLog.md

**Has this feature been discussed and generally agreed?**
No. Maybe not much benefit?

**Comment by hoffie** [comment]
One thing to consider is that ChangeLog or CHANGELOG is a pseudo-standard name and people or tools might look for exactly that name.
The Changelog is also parsed as part of our Debian package build process.

**Comment by ann0see** [comment]
Fixed as I added a Vim comment at the end of the file a while ago. GitHub now handles it correctly.

**Comment by pljones** [comment]
> Fixed as I added a Vim comment at the end of the file a while ago. GitHub now handles it correctly.

Prior to r3_9_1rc1, so dropping from 3.10.0.
