### ISSUE TITLE
Docs: Remove windows/qt-installer-windows.qs / Update COMPILING.md?

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2515]
**What is the current behaviour and why should it be changed?**

[COMPILING.md](https://github.com/jamulussoftware/jamulus/blob/674c657b5fed4ba2ad7e8a3e7201fd3c1fe8ca8b/COMPILING.md#windows) seems outdated and non-optimal.

**Describe possible approaches**

- [ ] qt-installer-windows.qs does not seem to be used anywhere (besides the manual compilation instructions). Should we link to the autobuild script's Qt version definition instead and remove qt-installer-windows.qs? (I don't find the referenced `INSTALL_COMPONENTS` either):
> To determine the Qt version you need, check [qt-installer-windows.qs](https://github.com/jamulussoftware/jamulus/blob/master/windows/qt-installer-windows.qs): under INSTALL_COMPONENTS you will see [...]

- [ ] The example versions should be updated to 5.15.2 (latest binary open source release):
> Select Components during installation: Expand the Qt section, find the matching version, e.g., Qt 5.12.3

- [ ] The referenced MSVC version seems inconsistent (2017 vs. 2019) -> Update to 2019?
> and add the compiler components for your compiler, e.g., MSVC 2017 32-bit/64-bit for Visual Studio 2019

**Has this feature been discussed and generally agreed?**

No.

**Comment by ann0see** [comment]
It was introduced here: https://github.com/jamulussoftware/jamulus/commit/ec999f0265c0bbb0643bb5fb949784bae13a627f

I think @braindef should know more about this file. I think it's no longer needed since we're not using Travis anymore.

**Comment by ann0see** [comment]
Ok. No problem. I think we can safely remove it then.
