### ISSUE TITLE
CI: Run Python syntax check

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2546]
**What is the current behaviour and why should it be changed?**

We've got some Python scripts, but we don't have static code checkers active.

**Describe possible approaches**

We should have checks for
- coding style
- errors which can be detected statically

pyflakes?

**Has this feature been discussed and generally agreed?**

Roughly via Chat.

**Comment by pljones** [comment]
What do the python scripts do?  I mean are the part of workflows or what?  How do they impact the project?

**Comment by hoffie** [comment]
```
$ find -not -path './libs/*' -name '*.py';
./.github/actions_scripts/analyse_git_reference.py
./tools/get_release_contributors.py
./tools/generate_json_rpc_docs.py
```
-> They affect the autobuild/releases, the release process and JSON-RPC doc updates.

**Comment by ann0see** [comment]
De-Tagged from 3.9.0. I think we should focus on getting the most important stuff in.

**Comment by pljones** [comment]
Moving to 3.10.0 as it's notabug.

**Comment by pljones** [comment]
No one assigned.  Dropping milestone and moving to Triage.

**Comment by ann0see** [comment]
Re added as we have a PR
