### ISSUE TITLE
SIGINT handler for Linux headless server does not unregister

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#2555]
**Describe the bug**
Stopping the headless Server should unregister from any Directory with which it is registered.  If this is not done, a "ghost entry" remains in the directory list (visible when a client runs with `--showallservers` or in Jamulus Explorer).

Current behaviour is that the headless Server does _not_ unregister.

**To Reproduce**
```
git checkout master
git pull upstream master
make distclean; qmake && make -j3
./Jamulus -s -n -p <openport> -e <Directory server address>
(check the server is visible and operational)
```
![image](https://user-images.githubusercontent.com/1549463/160280000-ba7e615a-ae1f-4213-b7f6-ce98e1b8e7c2.png)
And this shows the log for Jamulus Explorer successfully retrieving the welcome message:
```
 *** Copyright (C) 2005-2022 The Jamulus Development Team

Server Registration Status update: Registration requested
Server Registration Status update: Registered
2022-03-27 12:44:37, 80.85.86.7, connected (1)
2022-03-27 12:44:37,, server idling -------------------------------------
```
Now shut down the server with Ctrl-C:
```
^COnHandledSignal: 2
```
The signal is _handled_ but the Server doesn't send an unregister request, leaving a ghost entry:
![image](https://user-images.githubusercontent.com/1549463/160280079-7f68158f-69b6-44f9-8aa4-2c982fa7dc87.png)
Note the "Ping", "Version" and "OS" are not now listed.

**Expected behavior**
Stopping the headless server should send an unregister request.  This _does_ happen when using the UI:

Server:
```
./Jamulus -s -p <openport> -e <Directory server address>
...
Server Registration Status update: Registration requested
Server Registration Status update: Registered
...
Server Registration Status update: Not registered
```
Directory:
```
Mar 27 12:51:34 fs-peter Jamulus-Directory2[646838]: Requested to register entry for 192.168.1.19:56850 (81.174.155.168:56850): (private)drealm.info
...
Mar 27 12:52:45 fs-peter Jamulus-Directory2[646838]: Requested to unregister entry for 192.168.1.19:56850
```

**Operating system**
Tested on Linux.

**Version of Jamulus**
jamulussoftware/jamulus@56092960

**Comment by hoffie** [comment]
I don't see this issue on 3.8.2. I do see this issue on `master`. Therefore, sounds like a regression.

**Comment by pljones** [comment]
> I don't see this issue on 3.8.2. I do see this issue on `master`. Therefore, sounds like a regression.

Hm.  I don't see anything obvious.  I added a lock to the OnAboutToQuit but there wasn't anything there for unregistering.

**Comment by softins** [comment]
> > I don't see this issue on 3.8.2. I do see this issue on `master`. Therefore, sounds like a regression.
> 
> Hm. I don't see anything obvious. I added a lock to the OnAboutToQuit but there wasn't anything there for unregistering.

See my comment at https://github.com/jamulussoftware/jamulus/pull/2556#issuecomment-1080801514

**Comment by pljones** [comment]
Closing with #2633
