### ISSUE TITLE
Crash with latest MOTU drivers

### ISSUE THREAD

**Issue by mugnaio** [jamulussoftware/jamulus#2557]
I installed latest MOTU M2 drivers for windows (4.09.0087) and jamulus won't work anymore. When i chose "MOTU M Series" from divers list the software stop responding. IT work fine with ASIO4ALL but obviously this is not an option for me.
All other software work fine with those drivers.

**Comment by mugnaio** [comment]
I rolled back drivers to 4.09.0045 and with those it works, so problem seems related to latest drivers.

**Comment by ann0see** [comment]
I think there already was an issue reported about that and I thought the  company fixed a bug after a support request was made.

**Comment by npostavs** [comment]
Yes #2390 looks the same. I don't see any indication of a fix though? (just that they're working on it)

**Comment by mugnaio** [comment]
Opps sorry for the duplicate.
Anyway I'm not sure what do you mean with "the company fixed a bug", as far as I know 4.09.0087 are the latest MOTU, but I hope the are aware of the problem and they will fix in a future release. Though all other software works fine with that driver version so I'm not sure that was a priority for them.

**Comment by mugnaio** [comment]
I wrote to MOTU support and they sent me beta drivers 90961 that work now.
I think they will release them soon.

**Comment by hoffie** [comment]
Thanks for the report and the update from the vendor.
As there's nothing which we can do from the Jamulus side, I'd like to close this issue. You should still be able to comment on it, e.g. when the new drivers are officially released.
