### ISSUE TITLE
Can't Load or Save Mixer Channels Setup on Mac

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#2560]
**Describe the bug**

Load and Save Mixer Channels Setup does not work on Mac release 3.8.2. Nothing happens when the menu items are selected.

**To Reproduce**

Click on File menu, then on either Load Mixer Channels Setup... or Save Mixer Channels Setup...

**Expected behavior**

A finder dialog should appear for selecting the file to load or save.

**Screenshots**

**Operating system**

Reported on Facebook by a Mac M1 user. Also observed by me on Mojave.

**Version of Jamulus**

3.8.2 release - I suspect the same would be true of 3.8.1 (the first signed release), but not of earlier versions.

**Additional context**

A development version 3.8.2dev-xxxxxxxx I already had installed, which was not signed, displays the finder dialog ok. My suspicion is that a required entitlement is missing to allow this function to work in the sandboxed environment. @emlynmac ?

**Comment by emlynmac** [comment]
Where are the setting stored? Are they hard coded to a path somewhere?
My understanding of the sandboxing of the app will change all paths relative to the sandbox. This should mean that functionality is not affected,  but the one time move to a signed version will not have the settings from a version prior to the signing.

**Comment by softins** [comment]
No, it is supposed to open a finder dialog so the user can navigate to the desired directory and specify the filename. Maybe by default it starts in a directory it is not permitted to?

The action functions for those two menu entries are here:
https://github.com/jamulussoftware/jamulus/blob/178de745d6cdf5218df7f12bbb1e3c9d8c2c39c6/src/clientdlg.cpp#L772-L795

The third argument to `getOpenFileName()` and `getSaveFileName()` is supposed to be a `QString&` to specify the directory. Maybe the literal `""` fails in the sandboxing? The documentation says that an empty string is acceptable.

Maybe instead we should pass a variable string that has been initialised to the working directory (possibly `"."`?), which should allow the user to navigate to a different directory if needed, and the running instance to remember that directory for subsequent invocations of the action in the same run? I haven't tried anything, just looking for ideas.

References:
- https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName
- https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileName

**Comment by softins** [comment]
Just found an [example here](http://www.codebind.com/cpp-tutorial/qt-tutorial/qt-tutorials-beginners-qfiledialog-getopenfilename-example/) which suggests passing `QDir::currentPath()` instead of `""`.

**Comment by emlynmac** [comment]
Ok, so the app expects to be able to load/save to anywhere. 
There is an entitlement that would allow that, but it’s obviously less restrictive from a security perspective. Sandboxing is required for the Mac App Store so we probably need to find a middle ground where storing values can be done without sacrificing security

**Comment by softins** [comment]
Ah, in fact using `QDir::currentPath()` resets the navigation to the app's current directory on each invocation of the dialog box. So if the user navigated to a different directory when saving, the app doesn't remember where they were when they go to load again.

So in that resepect it is actually more user-friendly to actually pass `""` as the dir parameter. The question is, why does the sandboxed environment not like that? It doesn't even display the dialog for any directory.

**Comment by softins** [comment]
This is related to the unresolved #2131 too.

**Comment by emlynmac** [comment]
So then from reading here: https://developer.apple.com/documentation/security/app_sandbox
We probably need to add:

[com.apple.security.files.user-selected.read-write]

(https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_files_user-selected_read-write)

A Boolean value that indicates whether the app may have read-write access to files the user has selected using an Open or Save dialog.

to the entitlements.

I have no means to build QT binaries at the moment, but I pushed a branch with this change here:
https://github.com/emlynmac/jamulus/tree/autobuild/bugfix-2560

Building here: https://github.com/emlynmac/jamulus/actions/runs/2053888808

**Comment by softins** [comment]
Thanks, I'll give it a try tomorrow.

**Comment by emlynmac** [comment]
I have a branch with this change and a build here - benefits of being PDT :)
https://github.com/emlynmac/jamulus/actions/runs/2055138522
