### ISSUE TITLE
Coding style: Drop un-indented code in favor of // TODO: comments

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2591]
**What is the current behaviour and why should it be changed?**

The current code selectively disables `clang-format` and deliberately un-indents code which is only kept for compatibility reasons.
The idea is obviously that this should make the code stand out.

This has downsides:
- readability
- specific instances confuse clang-format despite the disabling (see #2587)

**Describe possible approaches**
It would be good to find an alternative approach here which keeps the regular indentation.
One possible idea from https://github.com/jamulussoftware/jamulus/pull/2587/files#r845895199 is using #defines.

global.h:
```cpp
#define COMPAT_JAMULUS_BEFORE_3_6_1
```
somecode.cpp:
```cpp
#ifdef COMPAT_JAMULUS_BEFORE_3_6_1
if (someConditionToCheckOnlyForOldJamulusVersions)
{
#endif

  someRegularCodeForAllVersions();

#ifdef COMPAT_JAMULUS_BEFORE_3_6_1
}
#endif
```

Another approach is a style using regular `TODO` comments (see below discussion for examples).

**Has this feature been discussed and generally agreed?**

No, needs agreement.

**Comment by ann0see** [comment]
Why wouldn't a regular "// TODO: " comment be enough? Some errors (at least eclipse for Java) highlight it.

**Comment by ann0see** [comment]
See https://medium.com/imdoneio/the-imdone-pitch-feedback-welcome-386430accf01

**Comment by ann0see** [comment]
@jamulussoftware/maindevelopers any objections to use // TODO: style or special comments like // ### TODO BEGIN 

// ### TODO end

**Comment by hoffie** [comment]
> Any objections to use // TODO: style

I'd be fine with that as well.

**Comment by ann0see** [comment]
Ok. Since nobody responded, I think the next action here would be to convert all unintended places into the style I suggested:
```
// TODO: BEGIN
/* some comments
*/
// TODO: END
```

**Comment by pgScorpio** [comment]
> Ok. Since nobody responded, I think the next action here would be to convert all unintended places into the style I suggested:
> 
> ```
> // TODO: BEGIN
> /* some comments
> */
> ... code...
> // TODO: END
> ```
> 
> @pgScorpio ?

Yes I can do this if you want.
@hoffie can you change the title of this issue accordingly?

**Comment by ann0see** [comment]
Done.

**Comment by pgScorpio** [comment]
question: 

Only change clang-format off/on where it is used for TODO ?? There are quite some cases where it is used for TEST too.

**Comment by ann0see** [comment]
Hmm. Tests could have a // Test BEGIN
/* test description */
... Code ...
// Test END

Syntax

**Comment by pgScorpio** [comment]
> Hmm. Tests could have a
> 
> // Test BEGIN /* test description */ ... Code ... // Test END
> 
> Syntax

Shouldn't we keep the format more consistent with TODO ?
```
// TEST: BEGIN
/* test description
 */
... code...
// TEST: END
```

**Comment by pgScorpio** [comment]
Another one is (i.e. multiple times in windows/sound.cpp):
```
                                   // clang-format off
// NOT YET TESTED
                                   // clang-format on
```
But I think it's OK to leave this as is?

**Comment by ann0see** [comment]
> Shouldn't we keep the format more consistent with TODO ?

Yes. Probably better to remain consistent 😀.

**Comment by ann0see** [comment]
> Another one is (i.e. multiple times in windows/sound.cpp)

Not sure. Maybe append a Todo: Not yet tested

**Comment by pgScorpio** [comment]
> > Another one is (i.e. multiple times in windows/sound.cpp)
> 
> Not sure. Maybe append a Todo: Not yet tested

Did you have a look at that code?
It is used 31 times, clang-format off/on does no harm here, and I don't think using TODO comments would do any good on the readability of the code here, on the contrary...

Of course I could just change "NOT YET TESTED" to "TODO: NOT YET TESTED", but does that have any added value? and would that be in the scope of this issue/PR?

**Comment by ann0see** [comment]
I remember this code. The //Todo: prefix might – in some IDEs – Highlight the code. So it's good to follow the syntax everywhere where something might need to be done (now or in future). 
Maybe that could be part of another PR, yes
