### ISSUE TITLE
Jamulus 3.8.2 MacOS --inifile option is not working

### ISSUE THREAD

**Issue by ginjo** [jamulussoftware/jamulus#2592]
**Describe the bug**

On MacOS, when launching Jamulus with the CLI, specifying the ```--inifile``` option, the .ini file is neither read, created, nor saved at the path specified with the ```--inifile``` command line option.

```/Applications/Jamulus.app/Contents/MacOS/Jamulus -i /Users/Bill/Jamulus/Guitar.ini```

**To Reproduce**

* Install Jamulus 3.8.2 on MacOS.
* In Terminal run ```/Applications/Jamulus.app/Contents/MacOS/Jamulus -i /path/to/any.ini```
* Make some changes to settings.
* Quit Jamulus.
* Relaunch Jamulus from Terminal with the exact same command used before.

**Expected behavior**

Jamulus should read existing .ini file, or create missing .ini file, and save changed settings to .ini file, per the path given with the ```--inifile``` option.

In Jamulus 3.8.0 this works as expected: The Guitar.ini file is created at the path provided, and any changes made are saved when the Jamulus instance is quit. Further launches, given the same ```--inifile``` path, read the Guitar.ini file into the Jamulus instance.

**Screen Shots**

The command prints the expected results of the launch, even though the .inifile is not read.

    MacBook:Jamulus Bill$  /Applications/Jamulus.app/Contents/MacOS/Jamulus -i /Users/Bill/Jamulus/Guitar.ini
    - client name: Guitar
    - initialization file name: /Users/Bill/Jamulus/Guitar.ini
    - allocated port number: 22134

**Operating system**

MacOS Mojave 10.14.6

**Version of Jamulus**

Jamulus 3.8.2, downloaded from the jamulus.io web site.

**Comment by gilgongo** [comment]
Is this due or related to https://github.com/jamulussoftware/jamulus/issues/2131 ?

**Comment by ann0see** [comment]
Yes, I think that's a duplicate. Can you check the nightly we published: https://github.com/jamulussoftware/jamulus/releases/tag/r3_8_2nightly1

**Comment by ginjo** [comment]
Good news, The r3_8_2nightly1 creates, reads, and writes the ini files in the location of my choosing, just as it worked in 3.8.0.

Thanks!

**Comment by ann0see** [comment]
Just realised that the nightly isn’t signed – shame on me. Can you check https://github.com/emlynmac/jamulus/suites/6058234035/artifacts/209062626 from Emlyn‘s repo (and report if a "this developer cannot be verified" warning popps up and if your issue is fixed if it doesn’t pop up?

**Comment by ginjo** [comment]
Yes, that newer version works perfectly in regards to the ini files, and there's no developer verification warning. Thanks!

**Comment by ann0see** [comment]
Thanks. Good to hear.

**Comment by ann0see** [comment]
Since your issue was resolved, I'll close this then. As soon as the new version is out, you can upgrade to a stable version ;-).
