### ISSUE TITLE
linux/sound.h should not depend on src/server.h

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2628]
One thing I noticed when I was doing my various changes... linux/sound.h depends on src/server.h.  It shouldn't - not sure if you want to go fixing this here, though.  (It means moving the high resolution timer from src/server.* to src/util.* - was a simple cut-n-paste.)

__Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/pull/2575#issuecomment-1100919070__

**Comment by pgScorpio** [comment]
I think we better create a new file i.e. timers.h.
util.h is already becomming a receptacle (or trash can) with a lot of code that is not really "utility".
Better to keep specific code in specific files.

Is there already someone working on this one?

**Comment by ann0see** [comment]
Probably @pljones 

https://github.com/pljones/jamulus/compare/patch/move-high-precision-timer...pljones:patch/rethink-int-ext-serverlist-entry?expand=1

**Comment by pljones** [comment]
> I think we better create a new file i.e. timers.h. 

I'm not sure it's "big" enough to warrant that -- too many files with tiny amounts of code in is a nightmare to manage.

> util.h is already becomming a receptacle (or trash can) with a lot of code that is not really "utility". Better to keep specific code in specific files.

Agreed on that point.  Something needs doing.

> Is there already someone working on this one?

Yep.
