### ISSUE TITLE
create-dmg: investigate new compression options 

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2663]
Create-DMG has received an update. We should update the scripts and investigate later on if we should also switch to a new compression format. 
https://github.com/create-dmg/create-dmg/issues/128

I don’t think we can switch the format without breaking backwards compatibility for the legacy build.

**Comment by hoffie** [comment]
#2664 has been merged. Are there any plans to change further options, such as compression formats? If so, what benefits would we expect?

**Comment by ann0see** [comment]
Benefits would be smaller .dmg files for modern versions of macOS. I don't plan to do anything for the upcoming release
