### ISSUE TITLE
Installer CI script check did not start on #2667

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2677]
**Describe the bug**

Changes or additions to the installer files did not execute the CI job for testing the installer.

**To Reproduce**

Open a PR adding a new language to the installer. 

**Expected behavior**

CI script runs and checks for issues 

**Screenshots**
/

**Operating system**
/

**Version of Jamulus**
/

**Additional context**
Maybe due to my file moving around the .yaml file got a typo

**Comment by ann0see** [comment]
Maybe this fixes it https://github.com/ann0see/jamulus/commit/6eb8b24fc994e32dfb45b6a6b73aa48d002f75b8

**Comment by hoffie** [comment]
Yep, sounds good.

**Comment by pljones** [comment]
Is this still an issue?

**Comment by ann0see** [comment]
Yes, I think so.

**Comment by ann0see** [comment]
I've opened a PR
