### ISSUE TITLE
Sign Steinberg agreement

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2687]
Now that we've [done what Steinberg require](https://github.com/jamulussoftware/jamulus/issues/2417) for ASIO, we can sign and send the agreement to them once 3.9.0 is out.

**Comment by hoffie** [comment]
Tagging for 3.9.1 as an additional reminder, but we should really do that once 3.9.0 is out as stated above.

**Comment by gilgongo** [comment]
Sent now that release is out.
