### ISSUE TITLE
iOS: Investigate Qt6 crash & update afterwards

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2711]
> Finally found out (again) how to view iOS crash logs. 
> You need macOS and The console App.
> I think that's the error:
> ![image](https://user-images.githubusercontent.com/20726856/176964308-c6d76d73-edd2-43de-a89b-a4585e404322.png)

> We probably need to change the application class. 
> Or maybe https://forum.qt.io/topic/82102/can-t-create-qapplication-for-ios-using-cmake-build

_Originally posted by @ann0see in https://github.com/jamulussoftware/jamulus/issues/2300#issuecomment-1172693513_

(Also see further investigation by @pljones in that ticket)

Original commit (including a relevant workaround) for reference: de632f4a9f84200f72ace34a101770c5b7a48fcf

**Comment by hoffie** [comment]
See https://github.com/jamulussoftware/jamulus/pull/2625#issuecomment-1275690542:
>  `QMAKE_LFLAGS += -Wl,-e,_qt_main_wrapper`

Thanks to @danryu.

**Comment by pljones** [comment]
@hoffie any progress on this?

**Comment by ann0see** [comment]
I think the GUI gets messed up with QT 6.

**Comment by ann0see** [comment]
I've compiled and successfully installed 3.10.0dev-6f57737c on iOS 17.4.1 with QT 6.7.0. I think we should open a new issue where we collect the UI issues if it doesn't exist yet.

**Comment by ann0see** [comment]
Closing. Will open another issue on updating iOS builds to Qt6
