### ISSUE TITLE
Finalise Korean translation

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2714]
- [x] Add translator to Organisation 
- [x] Update translation issues script 
What else?

**Comment by ann0see** [comment]
@bagjunggyu I've now added you to the translators group on GitHub to allow us ping all translators at once if there's a new release.

**Comment by bagjunggyu** [comment]
@ann0see Thanks :) I did it now.

**Comment by ann0see** [comment]
Fixed by @gilgongo
