### ISSUE TITLE
Checkbox controls should be "self-labelling"

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#2723]
I think it's more accessible (and better UX) to use "self-labelling form elements". 

So for example, it should be:

`[ ] Audio Alerts`

not split between a label and the control:

Audio Alerts          ` [ ] Enable`

The reason is mainly so that the control doesn't get separated from its label by a screen reader, but also in some contexts words like "enable", "on", "set" etc. might have unintended semantic or translation problems leading to "mode error". Better to let the user interpret the active state from the control than use a word for that state.

This issue currently applies to the Audio Alert and Feedback Protection controls in Settings. Other controls are compliant.

**Comment by ann0see** [comment]
Feedback Protection should also be changes

**Comment by henkdegroot** [comment]
What about the "Enable Small Network Buffers" option?

**Comment by pljones** [comment]
> What about the "Enable Small Network Buffers" option?

The solution to the issue should document the means used to identify _all_ the affected checkboxes.  Without that, it shouldn't be considered complete, as we need to have confidence we're finding and fixing all of them now.

We could also do with a coding style check for the issue to prevent it arising again.

**Comment by gilgongo** [comment]
Not sure how best to spec it, but checkboxes should have no other label other than the one that comes after the box. That label should also not contain words thqat clash with the function of the control like "enable..." "turn on..." etc. So they would need to change to:

![image](https://user-images.githubusercontent.com/4561747/187304961-38e89637-2565-47d6-ba53-6d2ffcbc93d3.png)

Not sure why Input Boost was not a dropdown in the first place.

**Comment by gilgongo** [comment]
> @gilgongo can you do that and raise a PR?

Not sure I'm qualified to do that.

**Comment by hoffie** [comment]
> Not sure why Input Boost was not a dropdown in the first place.

Huh, what version of Jamulus is this? Input boost is supposed to be a combo box (dropdown).

**Comment by gilgongo** [comment]
> > Not sure why Input Boost was not a dropdown in the first place.
> 
> Huh, what version of Jamulus is this? Input boost is supposed to be a combo box (dropdown).

Yes, got that wrong. The machine I'm on can't run Jamulus so I didn't check.

**Comment by ann0see** [comment]
Any news here?

**Comment by pljones** [comment]
If my grep worked, the full list of checkboxes and whether they need changing looks like this:

src/clientdlgbase.ui
"chbLocalMute" OK
"chbSettings" OK
"chbChat" OK

src/clientsettingsdlgbase.ui
"chbAudioAlerts" Needs fix
"chbAutoJitBuf" OK
"chbEnableOPUS64" Needs fix
"chbDetectFeedback" Needs fix

src/connectdlgbase.ui
"chbExpandAll" OK

src/serverdlgbase.ui
"chbEnableRecorder" Needs fix
"chbEnableDelayPanning" Needs fix

**Comment by pljones** [comment]
These changes are here, stacked up waiting on #2839:
https://github.com/pljones/jamulus/tree/bugfix/%232723-self-label-checkboxes

### src/clientsettingsdlgbase.ui
* "chbAudioAlerts" Needs fix - fixed
Also adjusted layout to use "Form Layout" for the two group boxes.  This layout makes it clearer which label is associated with which field in the editor.  The "User Interface" section also lost the massive (and, in my view, ugly) gap:
![image](https://user-images.githubusercontent.com/1549463/188868572-48d025d2-829d-4978-a48e-7023c80c071e.png)


* "chbEnableOPUS64" Needs fix - fixed
Linux/Jack and Windows/ASIO:
![image](https://user-images.githubusercontent.com/1549463/188870223-1fdb8f27-3470-42d0-a946-2a614855d0bf.png) 
![image](https://user-images.githubusercontent.com/1549463/188870409-b59189d2-d39a-41f7-bdbb-112547c46f24.png)
Again, I've used "Form Layout" for the "Input" and "Output" channel mapping sections and for the audio "Channel" and "Quality" controls.

* "chbDetectFeedback" Needs fix - fixed
![image](https://user-images.githubusercontent.com/1549463/188870901-71ed689c-cb79-4316-af27-729abdb1936d.png)

### src/serverdlgbase.ui
* "chbEnableRecorder" Needs fix - fixed
Along with making "My Server Info" group box into "Form Layout":
![image](https://user-images.githubusercontent.com/1549463/188871777-7a1611f0-8fec-4bcc-885e-831da3aee9e4.png)

* "chbEnableDelayPanning" Needs fix - fixed
Along with a "Grid Layout" container, which (I think), makes things much tidier:
![image](https://user-images.githubusercontent.com/1549463/188871376-c56d4ff9-2299-49fd-9431-86ae617d3e43.png)

**Comment by pljones** [comment]
Also, I note that my builds, [the misaligned faders issue](https://github.com/jamulussoftware/jamulus/issues/2772#issuecomment-1222610777) isn't present:
Linux: ![image](https://user-images.githubusercontent.com/1549463/188877599-f8d43566-6659-43bd-82e2-129af1e2c6bf.png)
Windows: ![image](https://user-images.githubusercontent.com/1549463/188878194-8caefe18-3c2f-4720-a764-da5355cb0d95.png)

So maybe it's something else in the toolchain?
