### ISSUE TITLE
Regression: Gain changes not applied in all cases (e.g. new client level = 0)

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2730]
> I started up a fresh instance of 3.9.0beta1 (compiled from src on Ubuntu 18.04) with no existing ini file, set a username, stereo out, new client level at 0%, connected to a server with players on it (Jamsuckers 212.83.56.10 on Any Genre 1, running version 3.8.2dev-1646e905 on Linux).
> 
> I expected no audio as new client was at 0% and indeed all the sliders were at 0 yet there was audio. I double checked to make sure I hadn't accidently looped a jack port mapping but there wasn't one. I further tested this behaviour against other servers with players on them, deleting the ini file and starting from scratch with the same settings each time. Server versions tested against were 3.8.1 and 3.8.2dev-c5111db6-dirty. All had the same client behaviour, there was audio even though all players sliders were at 0%.
I repeated above procedures using 1% and got the reduced volumes expected, which were quite lower in volume than what I heard when new client level was at 0%.
> 
> I tested same procedure with 3.8.2 (compiled from src on Ubuntu 18.04) against the same servers and got the expected behaviour of no audio when new client level was set to 0%.
> 
> Bug?

_Originally posted by @rdica in https://github.com/jamulussoftware/jamulus/discussions/2725_

I can confirm this behavior.

To be checked:
- [x] Is the actual value relevant (i.e. is 0 or 1 problematic or is this just the most extreme effect?)
- [x] Is new client level completely broken or does it only affect initial connect?
- [x] The sliders look correct, but the mix is wrong. It seems like the levels aren't properly sent to the server. Should confirm this via Wireshark.
- [x] Was the level change rate limiting merged post-3.8.2 and could it be related?

**Comment by pljones** [comment]
Having looked at the code... it's a nightmare.

The big, big problem is this is implemented in the mixer panel, which is a GUI component.  It should be in the client, either directly in CClient or in a non-GUI class handling the mixer.

The latter seems the better approach -- currently CClient doesn't know very much about what appears in the main client GUI.  Effectively splitting mixer into behaviour/state and a UI controller tied to it with signals/slots would clean things up and make them more consistent.

Unfortunately, it's not a quick fix, of course.  For 3.9.0, given I've no idea what change broke it, I'm not going to propose this is done.

**Comment by hoffie** [comment]
Reproducing instructions:
- Start a server
- Connect a client with permanent audio
- Start a 3.9.0beta client with a fresh config, set new client level to 0, connect to the server.
- Watch new client level work properly.
- Disconnect
- Connect again
- Observe fader at 0%, but audio being at 100%
- This is repeatable.

Reverting #2535 (more specifically: 2db5156a191bf25a3dbd47e8f02b887516f0127a and 68d56127275687a892157fd2594147087a3c0698) fixes it for me.

**Comment by hoffie** [comment]
I'm suspecting two problems here:
https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/client.cpp#L404

1. It seems like this array isn't reset on reconnect. Not sure if this is the relevant part here.
2. It looks like it defaults to 0. This is a mismatch compared to the server, which sets all channels to 1. Therefore, the don't-repeat-same-client-level-protocol-messages logic might omit a required set-gain-0 message. https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/server.cpp#L1365

With the following debug patch, the problematic situation is confirmed:
```diff
diff --git a/src/client.cpp b/src/client.cpp
index 99f74caf..2a3ca9a7 100644
--- a/src/client.cpp
+++ b/src/client.cpp
@@ -390,6 +390,8 @@ void CClient::SetRemoteChanGain ( const int iId, const float fGain, const bool b
     // send the actual gain and reset the range of channel IDs to empty
     oldGain[iId] = newGain[iId] = fGain;
     Channel.SetRemoteChanGain ( iId, fGain );
+    qInfo() << "SetRemoteChanGain: directly sending gain changed message for iId =" << iId << ", oldGain =" << oldGain[iId]
+            << ", newGain =" << newGain[iId];
 
     StartDelayTimer();
 }
@@ -407,6 +409,13 @@ void CClient::OnTimerRemoteChanGain()
             float fGain = oldGain[iId] = newGain[iId];
             Channel.SetRemoteChanGain ( iId, fGain );
             bSent = true;
+            qInfo() << "OnTimerRemoteChainGain: sending gain changed message for iId =" << iId << ", oldGain =" << oldGain[iId]
+                    << ", newGain =" << newGain[iId];
+        }
+        else
+        {
+            qInfo() << "OnTimerRemoteChainGain: skipping unchanged gain changed message for iId =" << iId << ", oldGain =" << oldGain[iId]
+                    << ", newGain =" << newGain[iId];
         }
     }
```

```
SetRemoteChanGain: directly sending gain changed message for iId = 0 , oldGain = 1 , newGain = 1 (iId=0 is the 3.9.0 client)
OnTimerRemoteChainGain: skipping unchanged gain changed message for iId = 1 , oldGain = 0 , newGain = 0 (iId=1 is the playing client; oldGain=0 is a wrong assumption by the client, because oldGain is actually 1 (the default) at the server)
```

**Comment by pljones** [comment]
If I remember correctly, that method also checks for a _new_ (i.e. previously unseen) channel.  There might be some point where `oldGain[iId]` can be set to `1` to start with...

Thanks for digging into this.

**Comment by hoffie** [comment]
a791cffea709a98c40da41478445654e3f3fa30c fixes it for me, but I have to do some more thinking, if this is correct or sufficient. I suspect we might still miss the case where a client disconnects and another client takes the existing channel id.

**Comment by hoffie** [comment]
> If I remember correctly, SetRemoteChanGain also checks for a new (i.e. previously unseen) channel.

Do you mean this?
https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/client.cpp#L380

I think it only optimizes the list of channels to check, doesn't it?

**Comment by ann0see** [comment]
Pinging @softins here for more insight.

**Comment by softins** [comment]
I can cast my rusty eye over the code later, but I'm away on holiday till 30 July with no access to hardware.

**Comment by hoffie** [comment]
> I suspect we might still miss the case where a client disconnects and another client takes the existing channel id.

It's hard to trigger on the case. The protocol doesn't have a concept for "new channel", as far as I can see. The UI handles it by triggering on the client list updated here:

https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/audiomixerboard.cpp#L1225
via
https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/clientdlg.cpp#L871

I'm currently looking into hooking into this protocol message as well (not via UI of course) and resetting `oldGain` for unused channels there.

**Comment by pljones** [comment]
Yeah, this is all the horrid "do it in the UI layer" stuff that the client should be handling...  It stinks trying to keep track of state using UI widgets...

**Comment by pljones** [comment]
> client list updated here:
> 
> https://github.com/jamulussoftware/jamulus/blob/fa204ad4f3025b7b2a1a8c1130ad998784faeb4a/src/audiomixerboard.cpp#L1225

Yeah, I was wondering if just sticking the " = 1" in there was possible but I couldn't seem to work out how to get it right.
