### ISSUE TITLE
3.9.0 Beta2  Chat window size on clean start

### ISSUE THREAD

**Issue by dcorson-ticino-com** [jamulussoftware/jamulus#2736]
**Describe the bug**
After a clean installation the chat window opens at Connect very small at the top left corner of the screen.
After closing Jamulus and restarting, the chat window opens the same at the top left corner of the screen.
After changing the window size and closing Jamulus the behaviour is as normal.

If I remember correctly the default size of the popup windows is always usable.  Could it be that there is a change in the startup behaviour that is skipping setting defaults somewhere?  Maybe also the reason for the user volume bug.

Found on Win10

**Comment by ann0see** [comment]
Hopefully not the Qt6 support...

**Comment by hoffie** [comment]
Thanks.
@dcorson-ticino-com Can you confirm that this issue does not occur with previous versions (if so, which)?

> Hopefully not the Qt6 support...

What part are you suspecting?

**Comment by ann0see** [comment]
Nothing specific. It's just interesting that it showed up in this beta. However: maybe it's also related to some ini file reading logic which changed? But that's just guessing

**Comment by dcorson-ticino-com** [comment]
A clean install of 3.8.0 puts the chat window with a usable size in the middle of the Jamulus window.
This is how I remember it.

**Comment by rdica** [comment]
`3.9.0beta1` fresh start (no existing ini) had the chat window open middle of the screen on my Ubuntu 18.04 desktop. I noticed in testing `3.9.0beta2` with a fresh start (no existing ini) that window popped up top left corner of screen. The size of the window in both versions remained unchanged for me.

**Comment by pljones** [comment]
Didn't happen for me - I installed on Win10 today and it was fine.  I have non-default window positions but the chat window size is default and it positioned correctly and used the right size.

**Comment by dcorson-ticino-com** [comment]
OK something's weird 'though.
I just did another clean install, uninstalled Jamulus and removed AppData>Jamulus.
This time I have the right size, but the position is still not right, upper left corner.

**Comment by hoffie** [comment]
> `3.9.0beta1` fresh start (no existing ini) had the chat window open middle of the screen on my Ubuntu 18.04 desktop. I noticed in testing `3.9.0beta2` with a fresh start (no existing ini) that window popped up top left corner of screen. The size of the window in both versions remained unchanged for me.

I don't think this can be explained by the version change. I don't see any code changes which could be related. So something else must be going on?
```
$ git diff r3_9_0beta1..r3_9_0beta2 --stat | grep -v translation/
 .github/autobuild/mac.sh             |    4 +-
 .github/workflows/autobuild.yml      |    8 +
 COMPILING.md                         |   19 +-
 ChangeLog                            |    2 +-
 Jamulus.pro                          |    4 +-
 distributions/debian/control         |    4 +-
 mac/deploy_mac.sh                    |    6 +-
 src/serverdlg.cpp                    |    2 +-
 src/serverlist.cpp                   |    2 +-
 src/util.cpp                         |    4 +
 src/util.h                           |    2 +-
 tools/create-translation-issues.sh   |    7 +-
```

**Comment by hoffie** [comment]
@dcorson-ticino-com Any luck tracking this down any further?

**Comment by dcorson-ticino-com** [comment]
No, and the last install with 3.9.0 was OK.
It must have picked up some strange ini file here on this compi.
I think I need to clean out all the old test versions here.
Don

**Comment by hoffie** [comment]
Thanks for the feedback. I guess it's fine to close this issue then. Feel free to re-open if this issue re-appears somehow.
