### ISSUE TITLE
Evaluate opusenc --no-phase-inv for Jamulus for improved mono quality

### ISSUE THREAD

**Issue by 38github** [jamulussoftware/jamulus#2743]
**What is the current behaviour and why should it be changed?**
I believe it is not used since downmixing does not sound good when using low latencies.

This options makes a big difference in audio when stereo material is downmixed to mono. Stereo material only lose very small position quality where I have noticed that some things like cymbals are a little more to the center of the stereo image. I believe most people will not notice any difference at all. It was introduced in opus-tools 0.2 (Sep 18, 2018)

```
--no-phase-inv
    Disable use of phase inversion for intensity stereo. This trades some stereo quality for a higher quality mono downmix, and is useful when encoding stereo audio that is likely to be downmixed to mono after decoding.
```

**Has this feature been discussed and generally agreed?**
I have personally not seen it being discussed.

**Comment by pljones** [comment]
This needs further discussion.

Is this a client feature?

Is this a server feature?

Can it be configured dynamically at run time rather than on program launch?

What _is_ the current behaviour?  There _is_ current behaviour and it's not described.

**Comment by hoffie** [comment]
Context:
https://twitter.com/marcan42/status/1264844343237435393
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/409
https://gitlab.xiph.org/xiph/opus-tools/-/blob/master/src/opusenc.c#L1000
https://opus-codec.org/docs/opus_api-1.2/group__opus__genericctls.html#ga10fa1f6eab136baf83c232afa989b6a8
https://github.com/mumble-voip/mumble/issues/4210
https://github.com/xiph/opus/blob/c9d5bea13e3cb7381bfa897a45d8bab4e7b767a7/celt/celt_decoder.c#L214

As far as I understand, this is both an encoder and decoder flag. Setting it is supposed to improve audio quality when downmixing opus stereo streams to mono.
- For Jamulus servers, mono streams are generated for mono listeners and stereo streams for stereo listeners. I don't think there is use for that. https://github.com/jamulussoftware/jamulus/blob/48168a67827bacf05d4d574f76aa6587191ceba0/src/server.cpp#L90-L97
- For Jamulus clients, this might indeed be interesting. Clients can send stereo streams (although they might often be unrelated [e.g. one for microphone, one for piano]). Those streams might be mixed down to mono for other clients. Adding the necessary encoder ctl could probably be done here for stereo streams: https://github.com/jamulussoftware/jamulus/blob/48168a67827bacf05d4d574f76aa6587191ceba0/src/client.cpp#L82-L87

@38github Did you try this? Is there some audible/provable improvement?

**Comment by 38github** [comment]
@hoffie 
Thank you for responding and having an interest in this feature. Yes, I have encoded quite some music with 2.5ms frame sizes to see what effect it had on transients and when I listened to my music in mono it had severe washy artifacts during high frequency content such as cymbals. Kind of like really low bitrate MP3. When I tried the --no-phase-inv a week ago I was astound what a difference it made. The only downside I noticed, and it was very minor, was that higher frequencies when played as stereo was a little bit more to the center.

I might make some samples to demonstrate.

**Comment by 38github** [comment]
[opus_2_5ms_no-phase-inv_vs_standard.zip](https://github.com/jamulussoftware/jamulus/files/9145485/opus_2_5ms_no-phase-inv_vs_standard.zip)

This zip-file has four files. Read the filenames to know which is which. I have encoded the mono downmixes to FLAC so that no further loss would occur.

Bitrate: 224 VBR
Complexity: 10

**Comment by DavidSavinkoff** [comment]
I think --no-phase-inv can be made into an option for advanced users and experimenters (as a quick hack to fix the odd problem). Down-mixing stereo to mono is non-trivial when it comes to the phase of a sound source being captured with two spatially separated microphones (or mono chorused to stereo and back to mono). It may be best to pick one channel or the other instead of blindly mixing the two signals equally. Thus, the user's unsound methods and expectations may not work in reality ... but can be made to sound better with --no-phase-inv at the expense of good stereo.

**Comment by 38github** [comment]
An option would be a good start. The stereo image is barely touched and I think almost no one will hear any difference at all. Would it be a GUI option or something to place in a conf file?

**Comment by DavidSavinkoff** [comment]
Is it /not possible to use the pan knob to mix stereo down to mono?
Using the pan knob will give some control over phase cancellation.

--no-phase-inv is not explained very well with opus.
I believe opus should remove the --no-phase-inv algorithm and
educate themselves on mixing stereo down to mono.

Furthermore, if all you want is a quick-n-dirty mono mix, then
suffer the dirty part instead of ruining the whole point of stereo
in Jamulus.

**Comment by 38github** [comment]
It is not about how you mix stereo material but how opus does tricks what do not sound good when downmixed to mono 

The chances that you will notice the extremely small loss in stereo image is slim to none.

**Comment by pljones** [comment]
So, where does this happen?  My current understanding of the flow is:

For a client that is configured with mono input, the OPUS codec encodes a single mono stream and the server decodes a single mono stream.  It duplicates that to two (equal phase) stereo channels when mixing to stereo for another stereo client (or for a client configured as mono in/stereo out).

For a client that is configured with stereo inputs, the OPUS codec encodes a single stereo stream and the server decodes a single stereo stream.

The server then mixes the stereo inputs (applying levels and pan positions) to stereo outputs for each client.

When the server encodes for a client configured for mono, it down mixes (it might be part of the mix cycle, like the up mix to stereo is, I can't remember) _prior_ to sending to the OPUS codec as a single mono stream.  The client decodes this and duplicates it to both channels.

When the server encodes for a client configured for stereo, it sends a single stereo stream to the OPUS codec.

So I'm still not getting _what_ changing the OPUS codec is doing for a mono feed.

**Comment by 38github** [comment]
All the other client's stereo audio streams get down mixed and sent to you as mono which causes artifacts from phase trickery opus did to their audio.

**Comment by pljones** [comment]
You're saying the encode stereo at the client -> decode stereo at the server process is made better - but _only_ when the server is then mixing the stereo to mono?  Wouldn't it be better, then, to look at that mix down process, rather than the codec cycle, if that's what's causing the issue?

**Comment by 38github** [comment]
The opus codec during stereo encoding on the user's computer is responsible for the poor down mix result on the server. I think best would be to enable --no-phase-inverse on both ends so that people never have to worry about the artifacts at any time.

**Comment by pljones** [comment]
If people are using [client stereo] -> [server] -> [client stereo], they will only experience _up_ mix from mono to stereo at the server, from mono clients.  As far as you've said, there's no benefit in this case.

If people are using [client mono] -> [server] -> [client mono], you're saying that _other_ stereo clients' signal will suffer in their mix when down mixed to mono?

What if they choose [client mono] -> [server] -> [client stereo], so there _is_ no down mix to mono?  Presumably in this case, they also experience no benefit?

I would expect most people to be using either the first or last cases - i.e. gaining no benefit.

**Comment by DavidSavinkoff** [comment]
> It is not about how you mix stereo material but how opus does tricks that do not sound good when downmixed to mono.
> 
> The chances that you will notice the extremely small loss in stereo image is slim to none.

By cross examining the two sentences above, one can see potential falsehoods in logic.
So:
- can you prove that these statements are not hearsay.
- what exactly is happening?
- why does opus do phase tricks to stereo when it appears that mono needs the tricks to sound good?
- why do the individual stereo channels sound good on their own?
- why do you want to do a mono mixdown when you can use one of the stereo channels?
- why does the stereo mix suffer when you use  --no-phase-inv , if it is actually better?

**Something is wrong here.**
Is the problem with the Opus engineers, or is it with the armchair engineers in the chat forums?
If Opus is messing with the stereo phase, why does delay pan work?
There is a bag-o-worms here.

WILL DELAY PAN SOUND CRAPPY WITH --no-phase-inv ?
WILL STEREO REVERB SUFFER?

SAY NO TO --no-phase-inv !!!
SAY NO TO --no-phase-inv !!!
...

**Comment by 38github** [comment]
> By cross examining the two sentences above, one can see potential falsehoods in logic.

> Is the problem with the Opus engineers, or is it with the armchair engineers in the chat forums?

> WILL DELAY PAN SOUND CRAPPY WITH --no-phase-inv ?
> WILL STEREO REVERB SUFFER?
> 
> SAY NO TO --no-phase-inv !!!
> SAY NO TO --no-phase-inv !!!

This really took a profoundly turn and for no reason. It is saddening that you behave this way while also appearing to be not read up on the matter.

**Comment by DavidSavinkoff** [comment]
> This really took a profound turn and for no reason. It is saddening that you behave this way while also appearing to be not read up on the matter.
>
I guess I wasn't clear.
My position is that itis good to have a --no-phase-inv option for those that need it. However this should not be the default. 

It looks like --no-phase-inv imposes intensity-stereo or joint-stereo or MS-stereo or whatever-you-want-to-call-it on more than just the lowest quality stereo encoding. I can't tell what type of encoding happens with Jamulus because it is convoluted (not as in convolution, but as an English word), but there may be all kinds of stereo side effects.

**Comment by hoffie** [comment]
Given that there seem to be different judgements regarding if and by how much this change could improve sound, I'd suggest someone (@38github?) to try out these changes within Jamulus. I've already [pointed](https://github.com/jamulussoftware/jamulus/issues/2743#issuecomment-1189573851) to the seemingly relevant code parts, so I guess this could be tried with a <10 line change.

**Comment by 38github** [comment]
> It looks like --no-phase-inv imposes intensity-stereo or joint-stereo or MS-stereo or whatever-you-want-to-call-it on more than just the lowest quality stereo encoding

It was a long time ago we had to worry about i.e. Fraunhofer's issues with Joint Stereo (I did hang out at r3mix). What this option does is disabling one feature of all the features in Intensity Stereo. It seems it actually does less which is to not invert phase.

Have you listened to the audio files in the attached zip file in earlier post?

**Comment by pljones** [comment]
@38github

The problem with the files in the ZIP is you give no indication of how this relates to Jamulus and audio cycle, so they are of no use in making a judgement.

**Comment by 38github** [comment]
Audio cycle?

**Comment by 38github** [comment]
- Ten users use stereo in client. They get back a stereo mix and they hear no real difference. **Good**

- Ten users use stereo in client. Eleventh user use mono and recieves a downmixes to mono summed from all the ten users and it has a lot of artifacts. **Bad**

**Comment by DavidSavinkoff** [comment]
Instead of debating, someone should make a fork of Jamulus with --no-phase-inv and exhaustively test for unexpected stereo problems (delay pan, reverb etc). Does 'Jamulus' actually have a problem in real practice? Note that #2743 is the first time that anyone complained about stereo to mono mixing

**Comment by pljones** [comment]
"hear no real difference" - so do they hear a difference or not?  Is the stereo image degraded or improved?

"Eleventh user uses mono" - how many times does this happen?  Why would anyone choose to receive mono from the server?

**Comment by 38github** [comment]
I think any further discussion from my part will be in vain. I have provided sound samples, scenarios where it it will overall improve sound experience, etc. Now it is up to you to decide if you are interested or not. Regards.

**Comment by pljones** [comment]
But you haven't provided scenarios in terms of how Jamulus works.  If you're not prepared to do that, I don't think there's necessarily any evidence supporting a need for change.

**Comment by hoffie** [comment]
While I find this idea interesting to evaluate (thanks!), I'm going to close this issue for now as noone has volunteered to perform the necessary steps to evaluate it in the context of Jamulus.
If someone is going to try it and finds benefits, I'm sure we would welcome such results / such a PR. Feel free to comment/re-open. :)
