### ISSUE TITLE
Create chatlog on the client

### ISSUE THREAD

**Issue by Snayler** [jamulussoftware/jamulus#276]
I was thinking it could be useful to create a chatlog file on the server (and maybe on the client) so that people can keep a log of what was said in chat.

Sometimes we share links with each other and it would be nice to be able to go back and consult these links at a later time, without fear of closing Jamulus and loosing the chat log. One example use-case, a covers band where people share youtube links to songs for everyone to study for the next rehearsal. Sure one could just copy the chatlog during the session and paste it in some file, but having the server/client do this automatically would be a plus.

**Comment by corrados** [comment]
I would not store any chat on the server. If a log shall be implemented, it should be done on the client side. Because if I am in a session with another musician and I want to write something to him, I do not want others to see my text if any other connects to that same server after we both have left.

**Comment by Snayler** [comment]
Ok, that makes sense from a privacy point of view. Yes, only client side during a session could work.

**Comment by corrados** [comment]
I just changed the title to reflect our discussion.

**Comment by Snayler** [comment]
> I do not want others to see my text if any other connects to that same server after we both have left.

I re-read this and realized something. My initial idea was not to have a "persistent" chat, where messages from an older session could be read when someone connected after. The idea was for the server to keep a text log file.

As for privacy concerns, I also realized that's gone out the window as soon as recording was implemented. We never know if a server is recording, in which case our voice conversations can be recorded. Jamulus as it is right now and on public servers, should not be regarded as a privacy oriented means of communication, from a client point of view.

**Comment by corrados** [comment]
Ok, but for whoom is that text log file for? For the server operator to find out if someone has texted something illegal?

**Comment by corrados** [comment]
> We never know if a server is recording

I already thougt about this issue. We may implement an indicator that recording is enabled. Then every client can clearly see whats going on and can disconnect from that server if he does not want his audio to be recorded.

**Comment by Snayler** [comment]
> Ok, but for whoom is that text log file for? For the server operator to find out if someone has texted something illegal?

Yes, I want to police my own server</joke>. I was thinking more in private server terms. Someone forgets to turn on the chat log during rehearsal, can ask server operator to send him the log. But now that I gave more than 1 second thought on this, the log can be sent from another member connected at the time. And people might want to text stuff not meant for the server operator to know, so privacy outweighs convenience.

> I already thougt about this issue. We may implement an indicator that recording is enabled. Then every client can clearly see whats going on and can disconnect from that server if he does not want his audio to be recorded.

I was about to open an issue to request that feature. That would effectively solve these privacy concerns with server recordings, and give users the choice.

**Comment by corrados** [comment]
> I was about to open an issue to request that feature.

Yes, go ahead. It's a useful feature.

**Comment by gilgongo** [comment]
@Snayler Are you OK with this? Shall we close the issue?

**Comment by corrados** [comment]
Why is this closed? The feature is not yet implemented.

**Comment by Snayler** [comment]
Sorry, I thought it was

**Comment by gilgongo** [comment]
Oh OK. I assumed it had morphed into a server recording indicator. 

I would think that a server-side chat log will meet some stiff opposition from privacy advocates, but we shall see :-)

**Comment by corrados** [comment]
@Snayler I have implemented the feature and we are discussing it in the pull request https://github.com/corrados/jamulus/pull/844. Since you originated the feature request, maybe you want to contribute to that discussion.

**Comment by ann0see** [comment]
I'll close this for now since the PR was closed too.
