### ISSUE TITLE
CI: Get rid of Ubuntu 18.04 build environments

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2786]
**What is the current behaviour and why should it be changed?**

Our Debian/Ubuntu builds currently use Ubuntu 18.04 in order to get the best compatibility with older Debian/Ubuntu releases.
18.04 will no longer be supported by the Github runners as of 2022-08-22 (first brown-out period which deliberately fails builds). It will be fully unsupported by 2022-12-01.
See: https://github.com/actions/runner-images/issues/6002

**Describe possible approaches**
1. Use Ubuntu 18.04 containers on 22.04 Ubuntu (haven't looked how easy this would be, but it might be the least amount of changes regarding the output)
1. Try building on Ubuntu 20.04 while still keeping compatibility somehow
1. Move to 20.04 and drop older targets (not that nice as 18.04 is still supported until 2023, I think)

**Has this feature been discussed and generally agreed?**

External trigger, we have to live with it.

**Comment by hoffie** [comment]
#2792 implements option 1.

**Comment by pljones** [comment]
18.04 LTS five-year maintenance period ends 23.04, so we need to have a plan in place _soon_ for moving off.

I don't see anything holding us back from that, either, really.  Any client or server user who chooses to run an unsupported OS also has the choice of building Jamulus from source.  We don't necessarily aim to _remove_ compatibility.

**Comment by hoffie** [comment]
> 18.04 LTS five-year maintenance period ends 23.04, so we need to have a plan in place _soon_ for moving off.

Yep. It's just sad timing that Github ends 18.04 runner support now and not in 2023, but so be it.

> I don't see anything holding us back from that, either, really. Any client or server user who chooses to run an unsupported OS also has the choice of building Jamulus from source. We don't necessarily aim to _remove_ compatibility.

Right. We have to reason to use 18.04 for building except for 18.04 compatibility by itself. Therefore, once 18.04 is EOL, we can safely up that to 20.04 (maybe after cross-checking with Debian oldstable).
