### ISSUE TITLE
Mac: Sign non-release builds with self-signed key

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2791]
**What is the current behaviour and why should it be changed?**

Currently, only release builds are signed via @emlynmac. Now that we provide M1 builds (#2357), it would be interesting to sign non-release builds as well, as M1 Macs refuse to run unsigned binaries by default.

**Describe possible approaches**

It should be sufficient to use a self-signed key for that.

- [x] ~Key generation~ (turned out to be unneeded)
- [x] Build logic changes

**Has this feature been discussed and generally agreed?**

See #2357

**Comment by ann0see** [comment]
I can create a cert. However, should we share it internally?

**Comment by pljones** [comment]
Should it go into jamulussoftware/assets or jamulussoftware/settings/secrets/actions?

**Comment by ann0see** [comment]
Since it's a cryptographic key, it needs to go to the secrets tab, not a repo.

**Comment by hoffie** [comment]
> However, should we share it internally?

I think it should be ok to store it as a secret only. It will not be easily recoverable there though (but we shouldn't need it).
In addition to the key, we also need to adjust the build logic to avoid trying the online (apple.com) parts of the signing process. I guess it makes sense to do this via another boolean secret to make that decision (or derive it from the cert if possible?).

**Comment by emlynmac** [comment]
Maybe have a look at the existing signing system and add the relevant gitHub secrets to enable signing.
It may require some further changes to make sure the notarization path is not followed, but should be simpler to do that way.

**Comment by ann0see** [comment]
I think I followed https://www.simplified.guide/macos/keychain-cert-code-signing-create once.

**Comment by ann0see** [comment]
I think I've now added everything unrelated to notarization from my side on this repo. So we'd need to skip MACOS_CERTIFICATE_ID and NOTARIZATION_PASSWORD

**Comment by ann0see** [comment]
Ok. I've now added a fake password and for the MACOS_CERTIFICATE_ID the name of the certificate, but on a workflow_dispatch run nothing changes.

**Comment by hoffie** [comment]
I think we need several more changes (which could probably be done on a fork first):
- https://github.com/jamulussoftware/jamulus/blob/e14f3dd9af84271c22575cf4ce7b10dbac0c2bdd/.github/autobuild/mac.sh#L44 needs dropping, I think
- These `if`s need additional checks for the `NOTARIZATION_PASSWORD` secret: https://github.com/jamulussoftware/jamulus/blob/e14f3dd9af84271c22575cf4ce7b10dbac0c2bdd/.github/workflows/autobuild.yml#L387 https://github.com/jamulussoftware/jamulus/blob/e14f3dd9af84271c22575cf4ce7b10dbac0c2bdd/.github/workflows/autobuild.yml#L399

Not sure if this is everything, but I guess both of it is mandatory for it to work.

**Comment by ann0see** [comment]
Yes, that could be done. 

However, I think we still need something else: https://github.com/jamulussoftware/jamulus/runs/7982936025?check_suite_focus=true#step:10:7 should have imported the cert, but it didn't.

**Comment by hoffie** [comment]
I think PRs don't have access to the target repo secrets, not sure if this changes if the PR comes from the same repo as that one did.

**Comment by ann0see** [comment]
The secret tab says there's only no access for PRs from forks

**Comment by emlynmac** [comment]
Each fork has its own secrets. For testing and developing, you'll need the values in your fork

**Comment by ann0see** [comment]
@emlynmac I just did that, but they didn't show up as "env" in GitHub actions' log. I also don't see any place where one could enable them from being read. Did you have to enable anything?

**Comment by ann0see** [comment]
Ok. I think I now know what went wrong.

**Comment by ann0see** [comment]
Actually, I think our way is not the way to go: https://wiki.lazarus.freepascal.org/macOS_Big_Sur_changes_for_developers#Code_signing_-_Intel_vs_M1

Probably we need ad hoc signing

**Comment by hoffie** [comment]
So, might `codesign --force --deep -s - MyApp.app` be sufficient? :o

**Comment by ann0see** [comment]
Maybe?

**Comment by hoffie** [comment]
I'm currently running test builds with the `macdeployqt -codesign="-"` logic, which should be rather equivalent to the above call.
Logs: https://github.com/hoffie/jamulus/runs/7993202492?check_suite_focus=true#step:10:7814

**Comment by hoffie** [comment]
I've linked the resulting test build and asked for testers here, as my branch was mainly about the universal builds and the codesigning would just be a positive side effect: https://github.com/jamulussoftware/jamulus/issues/2790#issuecomment-1225603029

**Comment by hoffie** [comment]
Feedback was positive: https://github.com/jamulussoftware/jamulus/issues/2790#issuecomment-1225683743
