### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [jamulussoftware/jamulus#2830]
Don't know if this is only for documentation, but
https://github.com/jamulussoftware/jamulus/search?q=any+later has lots of GPLv2+ notices
Consequently, https://github.com/jamulussoftware/jamulus/blob/master/COPYING is correct
whereas https://hosted.weblate.org/projects/jamulus/directories/#information is not, because it says LGPLv2-only

Can be changed to GPLv2-or-later in
https://hosted.weblate.org/settings/jamulus/respectivecomponent

I can do it if you add "kingu" in https://hosted.weblate.org/access/jamulus/#users :)

Would be best to at least mention https://github.com/jamulussoftware/jamulus/blob/master/APPLEAPPSTORE.LICENCE.WAIVER in the info field on Hosted Weblate.

**Comment by hoffie** [comment]
Thanks for raising this!
Pinging @ignotus666 @ann0see @gilgongo here.

**Comment by ignotus666** [comment]
Hmm, I used that license for the documentation based on [this](https://github.com/jamulussoftware/jamuluswebsite/blob/a0a643c223e6c80609cc90380e26bdf995895106/LICENSE), though I'm not sure if the "only" part is correct. Let's see what the others say.

**Comment by ann0see** [comment]
Jamulus is GPLv2+ and the site is LGPL code wise CC-BY-SA content wise

**Comment by ignotus666** [comment]
Duh! Found it. I'll change it on weblate when I get a chance.

**Comment by ann0see** [comment]
@comradekingu I've added you. 
Probably it's worth getting in touch with @henkdegroot if you plan to contribute with NL translation (discuss that in another issue).

**Comment by henkdegroot** [comment]
@ann0see, what inside information do you have? Not saying Allan won't be able to help with NL, however he is from Norway :)

**Comment by ignotus666** [comment]
Licence updated. The appstore stuff doesn't apply yet because only the website content is on Weblate for now.

**Comment by ann0see** [comment]
> however he is from Norway :)

Urgh. Then I misremembered. 😇. If he wants to add a new language, feel free to open an issue.

**Comment by ann0see** [comment]
Closing as the license has been changed by @ignotus666

**Comment by comradekingu** [comment]
@ann0see Somehow
https://hosted.weblate.org/projects/jamulus/jamulus-app/
is still -only
when there is 
https://github.com/search?q=repo%3Ajamulussoftware%2Fjamulus%20any%20later&type=code
and
https://github.com/jamulussoftware/jamulus/blob/582de166f4486b55ebb3b74c50623f21dd3111b4/linux/debian/copyright#L10

https://hosted.weblate.org/user/kingu/ is not an admin, so I can't fix that.

**Comment by ann0see** [comment]
I thought this was fixed. I've updated it now.
