### ISSUE TITLE
Maintenance: Move main branch to "main"

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#2840]
*Change*

Update github and any automation, plus documentation and Weblate to show the project main branch is named "main".

*Reason*

To remove sensitive references.

**Comment by ann0see** [comment]
@pljones any updates on this?
As there isn't much happening at the moment, I think it's good to 
1. Create a main branch
2. Search for occurrences of "master" in the docs
3. Replace all these occurrences with "main"
4. Change the target branch of all open PRs to "main"
5. Set the default branch to "main" on GitHub
6. Add a warning message to the README.md file on the old master branch - better replace it fully and remove the content of master
7. Wait some time to let the build of dependent distros/scripts fail
8. Remove the master branch fully

**Comment by pljones** [comment]
I've a lot happening, currently, so if anyone wants to pick the issue up, feel free.

**Comment by ann0see** [comment]
Master branch is now deprecated.

**Comment by ann0see** [comment]
The website has been updated too.

**Comment by hoffie** [comment]
Maybe also post a Discussion announcement (targeted at developers)?

**Comment by ann0see** [comment]
Yes. Maybe with a link to what needs to be changed locally (git commands).

**Comment by pljones** [comment]
Thanks - maybe summarise here what changes were done.

**Comment by ann0see** [comment]
* Created a new branch called main based on master branch
* Changed Jamulus.pro on master such that qmake returns an error saying that the user compiles from the wrong branch
* Added a note to README.md on master saying that this is the wrong branch
* Used Atom search and replace to replace all ocurrances of master by main in the source files and committed this to main (this failed at first, but I fixed it with a force push)
* Changed the main repo default branch on GitHub to main
* Changed ocurrances of master to main on jamuluswebsite release branch and resolved conflicts
* Opened a discussion on the Forum to explain the change

**Comment by ann0see** [comment]
Todo: Decide on when to remove the master branch fully.

**Comment by ann0see** [comment]
I've now removed even more files on the old master branch to make the error more obvious. I think a few weeks after the next release, we should get rid of the master branch fully.

**Comment by pljones** [comment]
@ann0see do you want to leave this until after 3.10.0 is cut or can it complete now?

**Comment by ann0see** [comment]
I'd like to remove it shortly after the release is out. Some people might pull at that time and then it's better to get a human readable error rather than some strange got error.

**Comment by ann0see** [comment]
I've now added an actionable link to the pinned discussion: https://github.com/jamulussoftware/jamulus/blob/master/README.md

**Comment by pljones** [comment]
Moved to "Waiting Externally" as "time" is ... um ... external, right?

**Comment by ann0see** [comment]
You could argue that. Yes.

**Comment by ann0see** [comment]
Added a ChangeLog entry for this one. See #3093

**Comment by pljones** [comment]
https://github.com/jamulussoftware/jamulus/commit/dd01e0089da68b376df6f4b6a8a094255c0a398f is related.

**Comment by pljones** [comment]
https://github.com/orgs/jamulussoftware/discussions/2984
> To raise awareness without a cryptic git error message and allow a smoother transition, the master branch still exists for a few weeks but compilation from master instead of main will fail.

Is that still valid?  I thought the _branch_ had now gone?

**Comment by ann0see** [comment]
No. The branch should be deleted shortly after the release as there might be people cloning from master.

**Comment by ann0see** [comment]
I think that we should delete the old branch after the coming weekend.

**Comment by ann0see** [comment]
Ok. Master branch is now gone.
