### ISSUE TITLE
Update nb_NO app translation for 3.9.1

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#2877]
Hi @comradekingu,
We are getting ready for the 3.9.1 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **nb_NO** by **2022-10-08**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-10-08

Suggested commit and PR message:
```
Update nb_NO app translation for 3.9.1

Fixes #2877
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/docs/TRANSLATING.md).

Thanks for contributing to Jamulus!

**Comment by ann0see** [comment]
Todo:
Add him to utils.h, the org and Discord/Element

**Comment by ann0see** [comment]
@comradekingu I've just invited you to the organisation as new translator such that you get some more access. A link to discord should follow by E-Mail from someone of the team.

**Comment by pljones** [comment]
Closing for 3.9.1rc1 - any updates will be picked up in a future release.

**Comment by hoffie** [comment]
> Todo: Add him to utils.h

@ann0see I think that part is still missing, right?
