### ISSUE TITLE
Small ping, small JACK latency, very large delay using Pipewire on Fedora 36

### ISSUE THREAD

**Issue by fwiep** [jamulussoftware/jamulus#2883]
**Describe the bug**

When using Jamulus with Pipewire on Fedora 36, JACK's latency is small (<10ms), the ping is very small (<10ms), but Jamulus' delay is between 80 and 100 ms (indicator turns red).

**To Reproduce**

1. install a clean Fedora 36, Pipewire comes preinstalled
2. edit or create `~/.config/pipewire/jack.conf` and set `node.latency = 512/48000` in `jack.properties`
3. restart Pipewire: `systemctl --user restart pipewire.service`
4. download Jamulus' sources and build using instructions; don't forget `--prefix=/usr` when configuring
5. start Jamulus
6. connect to a nearby server (ping <10ms)
7. see the enormous delay (>80ms)

**Expected behavior**

Having set JACK's latency to a low value, and having a small ping to a nearby server, I would expect to get only a small delay in Jamulus.

**Screenshots**

![2022-09-26_jamulus-large-delay-on-pipewire](https://user-images.githubusercontent.com/25373881/192377195-8dbdff8d-8653-4d55-aa49-612321aba5fe.png)

**Operating system**

Output of `inxi --system --audio`:
```plain
System:
  Host: WaanzinsPC2 Kernel: 5.19.9-200.fc36.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 42.5 Distro: Fedora release 36 (Thirty Six)
Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio
    driver: snd_hda_intel
  Device-2: Intel 8 Series/C220 Series High Definition Audio
    driver: snd_hda_intel
  Device-3: M-Audio RunTime DFU / Fast Track Ultra 8R type: USB
    driver: snd-usb-audio
  Sound Server-1: ALSA v: k5.19.9-200.fc36.x86_64 running: yes
  Sound Server-2: PipeWire v: 0.3.58 running: yes
```
Jamulus was built from `master`, at commit `cebb1562d5d488d70ce30cb7611dccf462bef93e`.

**Version of Jamulus**

Jamulus, Version 3.9.0dev-cebb1562

**Additional context**

Is there an additional setting I can change in Pipewire or how can I help to resolve this issue?
Thanks!

FWieP

**Comment by jujudusud** [comment]
Hi,
You said you are using PipeWire with a fast track ultra maudio.
You are using a config file with 'node.latency = 512/48000'.
In order to use Jamulus, you have to use '128/48000' instead.

**Comment by fwiep** [comment]
> In order to use Jamulus, you have to use '128/48000' instead.

Just now, I did. The delay becomes about 50ms with a ping of 7ms. The indicator turns yellow.

This is probably enough to be jammable, but would there be any way to get the indicator to go green using PipeWire?
Is the `node.latency` setting the only thing determining the delay?

Thanks!
FWieP

**Comment by pljones** [comment]
Looks like there's around 20ms extra latency coming from somewhere.  With a ping like that my Windows box, running ASIO4ALL, gets under 30ms reported.
![image](https://user-images.githubusercontent.com/1549463/192447466-ea5a9b25-c07c-464a-91f3-34ef83a6fd98.png)
(Although I don't know how accurate that is with ASIO4ALL...)  That's running buffer size 64 samples, enabled small network buffers and for the above low quality audio, giving an overall audio stream rate of 612kbps.  Auto jitter had settled to 8 / 4.

**Comment by fwiep** [comment]
Thank you @jujudusud and @pljones for answering so quickly. With your help, I have set up my Jamulus with ~40ms delay with a ~5ms ping. This has some audible artifacts, but at least there is no noticeable delay. And the indicator turns **green**! :D

![2022-09-27_small-delay-on-pipewire1](https://user-images.githubusercontent.com/25373881/192456322-787c41c0-4b5b-4472-8eca-fc0b353a1a84.png)
![2022-09-27_small-delay-on-pipewire2](https://user-images.githubusercontent.com/25373881/192456362-1a08642d-831a-41cd-b397-9e8d61346a1c.png)

Thanks again, case solved.
Frans-WIllem
