### ISSUE TITLE
Request: aarch64 deb build

### ISSUE THREAD

**Issue by 38github** [jamulussoftware/jamulus#2887]
Is there a possibility that you can add an aarch64 target in the linux_deb autobuild, please?

**Comment by hoffie** [comment]
Thanks for the reminder. I had once prepared that, but forgot to follow up after the main-build-only logic was implemented and merged. I've rebased the branch and I'll submit a PR once the build is successful:

https://github.com/hoffie/jamulus/tree/autobuild-aarch64
https://github.com/hoffie/jamulus/actions/runs/3141790394

**Comment by hoffie** [comment]
@38github Can you try the artifacts from here? https://github.com/hoffie/jamulus/actions/runs/3142313102

**Comment by 38github** [comment]
It worked great as a server using -F -T. Thank you very much!

When using another build (-O3 -flto) on a SoC with four Cortex-A53 @ 1.2GHz cores and 512MB RAM I had six clients whom all connected using 64 samples and low network buffers. The ping was stable (only 1ms of fluctuation every now and then). The audio had no sudden drop outs or artifacts and the average CPU usage was 60-66% and evenly spread across the cores. The RAM usage was around half. This with also a Mumble server running at the same time. Impressive! I will increase -n to 8 and see if it still is rock solid.
