### ISSUE TITLE
Weblate takes too much credit

### ISSUE THREAD

**Issue by DavidSavinkoff** [jamulussoftware/jamulus#2904]
**Describe the bug**

Weblate takes too much credit in the code commits and Changelog. Weblate is a service, not an author and cannot make claims as a person such as copyright etc. Is Weblate GPL and Copyright compatible?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by pljones** [comment]
No credit has so far been given to Weblate - the ChangeLog for rc1 hasn't been released yet, partly because I want to get the proper list of translators rather than just mentioning Weblate.

**Comment by hoffie** [comment]
So, there are multiple parts, as I understand it:
1. Code: It seems like the Weblate options are rather limited right now. I agree that it would be best to have commits with real authorship information, but currently this doesn't seem possible (@ignotus666, correct me, if I'm wrong...). That part would be **can't fix** then.
2. Changelog: This can be worked on on the Jamulus side. That part should still be worked on.
3. Other mentions: #2908 adds the weblate user to the ignore list for release announcements. That part should soon be **fixed**.

**Comment by hoffie** [comment]
@ignotus666, @ann0see: Are we squashing by author yet (I assume we currently squash by language)? It seems like Weblate can do it and might better preserve authorship information then? https://docs.weblate.org/en/weblate-4.3.2/admin/addons.html#squash-git-commits

**Comment by ann0see** [comment]
We have squash by language, I think.

**Comment by ann0see** [comment]
I‘ve just updated the ChangeLog with the contributors from Weblate

**Comment by DavidSavinkoff** [comment]
Be free to close this issue once enough has been done.

**Comment by ann0see** [comment]
Done.
