### ISSUE TITLE
Build: Update iOS build environment (macos-10.15)

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2939]
I realized just now that iOS is also still built on 10.15. This is going to fail and we must get rid of this dependency for 3.10.0.
I guess once #2711 is fixed, we should try to align the iOS environment with the Mac non-legacy one?

Related: #2773

**Comment by hoffie** [comment]
I made a quick attempt at updating just the build environment (without Qt) for now, but it seems like a dead end.
Even the lowest Xcode version (13.1) has incompatible changes which would require workarounds:
https://github.com/hoffie/jamulus/actions/runs/3365069827/jobs/5580150018#step:10:46
https://gitlab.kitware.com/cmake/cmake/-/issues/22459

So it seems like the best course of action will be via #2711.

**Comment by ann0see** [comment]
I tested your commit, and the GUI seems to be broken (more than it used to with Qt5). Buttons are outside of my screen etc.

**Comment by hoffie** [comment]
Thanks for testing. I guess we'll need someone with iOS access to try further fixes. Therefore, I'm removing my assignment.

**Comment by pljones** [comment]
@hoffie how's progress on this?

**Comment by ann0see** [comment]
It's certainly a blocker. I'm not sure, but I can look into it - unfortunately I don't have access to a mac at the moment as my VM constantly crashes and is unusable.
