### ISSUE TITLE
Logging: Don't complain about serverinfo if no --serverinfo is given

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2947]
**Describe the bug**

`Jamulus -s -n` logs `Ignoring invalid serverinfo, please verify the parameter syntax.`.

**To Reproduce**

**Expected behavior**
No error should be logged if no `--serverinfo` is given.

**Screenshots**

**Operating system**
Linux

**Version of Jamulus**
master

**Additional context**
Issue got introduced in 5b2c2de6d0d2ee2363957b87a5ee984b2cce3e9f.

**Comment by pljones** [comment]
@hoffie how is progress on this?
