### ISSUE TITLE
JACK Autobuild fails during installation of JACK

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#2992]
**Describe the bug**

https://github.com/jamulussoftware/jamulus/pull/2991 shows that the JACK build fails - most likely - due a permission error https://github.com/jamulussoftware/jamulus/actions/runs/3861264997/jobs/6701549076#step:8:167

I guess this has to do something with a GH runner update.

**To Reproduce**

Run the JACK Autobuild via GitHub Actions

**Expected behavior**

JACk should install without error on GH actions.

**Screenshots**

/
**Operating system**

Windows

**Version of Jamulus**

/
**Additional context**

I think we might fix it by allowing choco to write to C:\ProgramData\chocolatey\lib-bad\jack maybe there's also a better way?

Tagging @henkdegroot as he knows a bit more about the JACK build.

**Comment by henkdegroot** [comment]
Going to check this. While the log does indicate a permission error, I don't think that will be the issue as I believe the account used in the github action is an full admin account (to prevent issues like this). It might be some file lock due to another process not releasing the file or something like that.

**Comment by henkdegroot** [comment]
The JACK installation is failing due to an issue with Autohotkey v2 being used now, while previous v1 was used. Because of this the autohotkey script fails. Going to see if I can provide a fix for that and get that updated in the choco package library.

**Comment by ann0see** [comment]
Same procedure as last time…

Who builds the installer? I suppose there’s a git repo for JACK on windows somewhere. It might be worth raising an issue requesting a real silent installer.

**Comment by henkdegroot** [comment]
Posted a PR to get the issue resolved. https://github.com/chtof/chocolatey-packages/pull/82

Might be a good improvement to JACK to get a silent installer: https://github.com/jackaudio/jack2

**Comment by henkdegroot** [comment]
I have also checked if we can manually install Autohotkey v1 before JACK but due to how the choco packages refers to the AHK dependency, it will still download to latest version 2.

**Comment by ann0see** [comment]
Actually, I googled a bit and the installer does support a silent installer with the `/SILENT` or `/VERYSILENT` parameters!

**Comment by henkdegroot** [comment]
So that would mean we need to implement our own download and install of JACK? Instead of using choco for the installation.

**Comment by ann0see** [comment]
I think choco could/should use the SILENT parameters, but OFC, we could also download it manually - but I'd rather prefer not to as choco seems less work. 

Another option would to change to winget. If JACK is on winget already.

**Comment by ann0see** [comment]
I've just opened issues on WinGet and the JACK repo. Personally, I'd prefer WinGet as I think it will become a standard in future.

**Comment by henkdegroot** [comment]
Seems WinGet isn't really supported to run on a Windows Server environment....not as straight forward install as Windows 10/11.
It might become the standard one day....

**Comment by ann0see** [comment]
Just read about it. Server 22 might work. It seems that they're aware of the issue and a lot of people would like to have it on servers too.

**Comment by ann0see** [comment]
We might need to really install JACK by hand if nothing happens on the choco side.

**Comment by henkdegroot** [comment]
Maybe not a bad solution, it is sourced from a git url and not often updated. Only downside seems that you can "see" if and when the jack install completed. Guess a check can be done to check a folder has been created or not before continue to the next step.

Using /VERYSILENT /SUPPRESSMSGBOXES /NORESTART for 32bit and 64bit jack installer seems to work fine.

**Comment by ann0see** [comment]
I think we could use gh to download the JACK binary directly: https://cli.github.com/manual/gh_release_download
