### ISSUE TITLE
POST MERGE review for JACK pr

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3012]
https://github.com/jamulussoftware/jamulus/pull/3003#issue-1563243061 needs a post review and some more work on the comments by @pljones

**Comment by pljones** [comment]
Comments now unresolved: https://github.com/jamulussoftware/jamulus/pull/3003/files

**Comment by ann0see** [comment]
My repo is fully ok: https://github.com/ann0see/jamulus/actions/runs/4176891051/jobs/7233773890

Maybe it's really the new version which doesn't work.
