### ISSUE TITLE
The `check-json-rpcs-docs.yml` script fails

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3018]
**Describe the bug**

The `check-json-rpcs-docs.yml` script fails.

**To Reproduce**

Run the `check-json-rpcs-docs.yml` script on pljones:bugfix/remove-remaining-directory-server-mentions:
https://github.com/jamulussoftware/jamulus/actions/runs/4270698668
https://github.com/jamulussoftware/jamulus/actions/runs/4270698668/attempts/1

**Expected behavior**

A clean run

**Screenshots**

![image](https://user-images.githubusercontent.com/1549463/221366639-3b20ccb1-287c-4829-8eaa-0c96daaf2acb.png)

**Operating system**

Github build Linux.

**Version of Jamulus**

n/a

**Additional context**

Blocking https://github.com/jamulussoftware/jamulus/pull/3017

**Comment by pljones** [comment]
I've still no ideas on this.  The build step in error is this one:
![image](https://user-images.githubusercontent.com/1549463/227788673-dedf167e-9c50-44e3-8a17-c1478c862dfb.png)

**Comment by ann0see** [comment]
No. I don't think so. Can you run the script locally and see if it shows any changes?

**Comment by ann0see** [comment]
https://github.com/jamulussoftware/jamulus/settings/actions is set to read and write permissions, but the check still fails.

**Comment by ann0see** [comment]
I've just pushed an update of the qm files: https://github.com/jamulussoftware/jamulus/commit/07722bfa648b15fd5e5f195b63bbe874b924594a locally that shows up as diff for me on a clean build. But we don't modify them in this script.

**Comment by pljones** [comment]
This no longer fails on https://github.com/jamulussoftware/jamulus/pull/3017.

I don't know how to get `check-json-rpcs-docs.yml` to run, though, against https://github.com/pljones/jamulus/tree/bugfix/rpc-remaining-directory-server-mentions, for example, to see if it fails there.

**Comment by ann0see** [comment]
@pljones Please close this if you think it's no longer valid - I think that's the case

**Comment by pljones** [comment]
Closing as mentioned branch no longer exists.
