### ISSUE TITLE
The Jamulus build system runs with an unsupported clang format version

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3019]
**Describe the bug**

The Jamulus build system runs with an unsupported clang format version:
```
Run DoozyX/clang-format-lint-action@c3b2c943e924028b93a707a5b1b017976ab8d50c
  with:
    clangFormatVersion: 10
```
Ubuntu only provides `apt` with 11 to 15:
```
$ sudo apt install clang-format<TAB><TAB>
clang-format     clang-format-11  clang-format-12  clang-format-13  clang-format-14  clang-format-15
```
(https://apt.llvm.org/ only provides 15 and newer.)
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**To Reproduce**

Install and use the earliest supported clang-format version:
```
$ clang-format --version
Ubuntu clang-format version 11.1.0-6
$ make clang_format
...
$ git diff
(nothing changed)
$ git status
Your branch is up-to-date with 'origin/bugfix/#2723-self-label-checkboxes-forms1'.
```

Run "Verify coding style" on https://github.com/pljones/jamulus/tree/bugfix/remove-remaining-directory-server-mentions
https://github.com/jamulussoftware/jamulus/actions/runs/4270698669/jobs/7435420804
https://github.com/jamulussoftware/jamulus/actions/runs/4270698669/attempts/1

**Expected behavior**

Consistent clang format behaviour with _at least_ clang-format-11 (but, given https://apt.llvm.org/, I'd suggest getting onto 15 as soon as we can).

**Screenshots**

n/a

**Operating system**

Github build system on Linux.

**Version of Jamulus**

n/a

**Additional context**

Blocking https://github.com/jamulussoftware/jamulus/pull/3017

**Comment by ann0see** [comment]
I'm not sure if there's still a reason for the old clang format version. 
Even Debian Stable uses clang format 11.

**Comment by ann0see** [comment]
Related to: https://github.com/jamulussoftware/jamulus/issues/2552
