### ISSUE TITLE
Jamulus automatically connects to JACK even with --nojackconnect

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3021]
**Describe the bug**

Jamulus automatically connects to JACK even with `--nojackconnect`.

**To Reproduce**

Run Jamulus client with `--nojackconnect`:
```
$ ./Jamulus --nojackconnect
- disable auto Jack connections
- allocated port number: 22134
Connecting to JACK "default" instance (use the JACK_DEFAULT_SERVER environment variable to change this).
Cannot connect to server socket err = Connection refused
Cannot connect to server request channel
jackdmp 1.9.20
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2021 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
JackTemporaryException : now quits...
Jack main caught signal 2
```

**Expected behavior**

Jamulus should not connect to JACK automatically:
```
- disable auto Jack connections
```

**Operating system**

ChromeOS Version 110.0.5481.181 (Official Build) (64-bit)
XServer XSDL 12 Mar 2021 (Final)

```
Linux fs-peter 5.15.0-67-lowlatency #74-Ubuntu SMP PREEMPT Wed Feb 22 15:27:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ apt list xfce4
Listing... Done
xfce4/jammy,jammy,now 4.16 all [installed]
```

**Version of Jamulus**

bugfix/3019-unsupported-clang-version:
```
Jamulus, Version 3.9.1dev-c7b9dc18
```
(so I presume it's there on master)

**Additional context**

Yes, yes, I'm running Jamulus on a Chromebook by remotely running X to my Linux box...  Ignore that bit.  Can someone with a more convention set up check it's also broken on Linux for them?

**Comment by ignotus666** [comment]
Isn't it to prevent JACK from connecting Jamulus' audio outputs to the default inputs? Works for me (current master).

**Comment by pljones** [comment]
Ah right, so it should auto-start JACK, JACK should auto-connect to the (hardware) audio I/O it can find, but to leave Jamulus alone.  OK.

I'll close this.
