### ISSUE TITLE
Investigate styling of else blocks with/without `{`

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3022]
Throughout the Code we sometimes omit `{` in if/else blocks which might be confusing for developers and clang format. In general  think this is a somewhat questionable style which led to confusion. We should overthink when omitting `{` is really ok. 

Related to a comment by pljones:

So this is the one I think is questionable...  I think.  It should be same level as after the `if` on line 920.

_Originally posted by @pljones in https://github.com/jamulussoftware/jamulus/pull/3020#discussion_r1122229837_

**Comment by pljones** [comment]
Note that the reference comment was not about _omitted_ `{`.  It's about the insertion of comments between a keyword and its `{`.  `clang_format` does the right thing with the `{` block, as far as I could tell: https://github.com/jamulussoftware/jamulus/pull/3020#discussion_r1126903303

**Comment by ann0see** [comment]
Then comments should also be inside the blocks...

**Comment by pljones** [comment]
Actually... now I look _again_, I think it's styling _is_ wrong...
```
        else
            //### TODO: END ###//
            // if "directorytype" itself is set, use it (note "AT_NONE", "AT_DEFAULT" and "AT_CUSTOM" are min/max directory type here)
            //### TODO: BEGIN ###//
            // compatibility to old version < 3.8.2
            if ( GetNumericIniSet ( IniXMLDocument,
```
The `{` and `}` before the `else` are correctly nest at the same level as the `else`.  The comment causing a break _in the middle of the `else if` statement_ is what throws things.  The `{` and `}` for the last line above are nested below the `if` rather than the `else`, as they (questionably) should be.  We use the `TODO: BEGIN`/`TODO: END` in several places...  The problem here is the statement breaks - it's going to cause weird styling and I think we have to live with it.

```java
if (a == b)
{
  // do stuff
}
else
  if (c == d)
// ... code block here
```
It would put the brackets under the `if` rather than the `else` even without the comment, I'd imagine.

**Comment by ann0see** [comment]
Hmm. Now I seem to get it. Yeah. 

```
else // something 
  if (...) 
  {
    ...
  }
```

Should probably never be allowed. 

Always write else and if on the same line 

```
} else if (something) 
{

```. Or use (not recommending that though)

```
else
{
  if ( something ) 
  {
  }
}
```

**Comment by pljones** [comment]
However, we've adopted guidance that deprecated code should be bracketed by comments that enclose only the deprecated code (such that the BEGIN to END lines can simply be deleted and leave the code compilable).

That means if an `if (..) { .. } else` block prefixes an alternative flow (introduced by its own `if`), the code to be deleted is the first `if` to the `else` but not the second `if` - which forms `else if` in normal layout.  We end up with
```java
// TODO: BEGIN
if (..)
{
  ..
} else
// TODO: END
```
which can be removed, followed by
```java
if (..)
{
  ..
}
```
... but clang-format doesn't think the second `if` (or the preceding comments or following `{ .. }` block) should be at the same level as the first, but indented.

**Comment by pljones** [comment]
I have a feeling that - as most of this is about problems caused by "TODO - remove this sometime" blocks - we'll ignore this issue in the same way we ignore the "TODO - remove this sometime" instruction.

**Comment by ann0see** [comment]
Closing. Don't think it's worth having this open anymore.
