### ISSUE TITLE
Conductor's baton as an instrument choice

### ISSUE THREAD

**Issue by TyMVega** [jamulussoftware/jamulus#3024]
Not a super big deal, but probably easy for all y'all.  Can we get a conductors baton for instrument of choice?  

Thanks for what you do...  Words don't do it.

**Comment by ann0see** [comment]
I think it's doable if we have a license wise compatible icon. But please keep in mind that we already have lots of icons. I've linked this issue in our designer chat. Maybe we'll find something

**Comment by TyMVega** [comment]
Did you just add that?  Amazing if so, in any case I went to look for the
other options and I see a conductor so thank you either way <3

**Comment by ann0see** [comment]
I didn’t add anything yet as the picture is missing- sorry. But I hope someone finds one.

**Comment by ann0see** [comment]
Ah sorry. I think I misunderstood. Do you want to be able to show that for every instrument? That would mean that we need double the pictures or a whole new - backwards incompatible logic.

**Comment by TyMVega** [comment]
No I just want to be able to choose conductor as my instrument.  I discovered after I posted here and saw your response that there is such an option on android, it's a humanoid in a suit with a conductors baton which suits my needs just fine.  I have also since discovered that that option doesn't show up on the linux client I'm typing from now and I looked for it on Windows yesterday and pretty sure it wasn't there.

This is not a big deal...  Lowest possible priority really...  But it is something that makes sense to have and I'm sure others would want that too.

Appreciate your attention

**Comment by ann0see** [comment]
Ok. Understood. For me it shows up on any OS. Do you have the latest version on your Linux/Windows machine?

**Comment by TyMVega** [comment]
Presumably as I just downloaded today...  3.8.1+dfsg1-1(Bubuntu/amd64) is what it says under help.  I pulled it from software center, this is a brand new rig so it's possible that I installed Jamulus before updating the machine.  I will poke around and see if an update or a system update and reinstall fixes it.

**Comment by TyMVega** [comment]
Actually I should just uninstall and install from the website after checking numbers...

**Comment by TyMVega** [comment]
So not current, I'll reinstall.

**Comment by ann0see** [comment]
Yeah, the Debian/Ubuntu repo is probably outdated. Shameless plug: We're working on our own repo solution

**Comment by TyMVega** [comment]
Word.  Thanks for your help I think you've gone above and beyond on this
lol.

Very impressed with this software and community.

Tv
