### ISSUE TITLE
Add clear GPL license header to missing scripts like autobuild

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3026]
**Describe the bug**

Currently there's no license header in the autobuild scripts. At the beginning when I created the first script, I assumed that it's clear that they are under the same license as the source code files (GPL v2+). After some research and reading Debian discussions, this doesn't seem to be the case. This we should add missing license headers to the autobuild scripts. There are multiple authors, so I think at least the main contributors (@hoffie, @henkdegroot,???) should give an ok. 

**To Reproduce**

See autobuild and tools scripts

**Expected behavior**

Licensing should be clear in all files

**Screenshots**

/

**Operating system**

/

**Version of Jamulus**

/

**Additional context**

/

**Comment by pljones** [comment]
> At the beginning when I created the first script, I assumed that it's clear that they are under the same license as the source code files (GPL v2+).

Generally, it would be argued I think, that therefore the correct licence is "the same license as the source code files (GPL v2+)".

**Comment by henkdegroot** [comment]
Sounds like something that should be done, only contributed a little to these.
