### ISSUE TITLE
New JACK autobuild fails on GitHub Actions Pull Requests

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3035]
**Describe the bug**

The JACK build fails on GitHub Actions PRs if Workflow Permissions are set to "Read repository contents and packages permissions". No fail can be seen on PRs by me/if "Read and write permissions" are set.
**To Reproduce**
https://github.com/jamulussoftware/jamulus/pull/3031 with "Read repository contents and packages permission" set doesn't fail but https://github.com/jamulussoftware/jamulus/pull/3011 does. 
This is a successful run while write permissions were enabled: https://github.com/jamulussoftware/jamulus/actions/runs/4515448402/jobs/7952904802

**Expected behavior**

No matter what permissions are set the JACK build succeeds for GitHub actions and other contributors. 

**Screenshots**

/
**Operating system**

Windows on GH
**Version of Jamulus**

/
**Additional context**

I strongly believe this is a permission error we miss a setting or Autobuild permission somewhere. Something related to GH_TOKEN maybe?

**Comment by ann0see** [comment]
Currently we have set the permissions to read and write.

**Comment by pljones** [comment]
Should we make 3.10 dependent upon this or leave until 3.11?

**Comment by ann0see** [comment]
I think it's not that important to get correct before the next release.

**Comment by pljones** [comment]
How easy is this to test?  Can a list of steps be included to demonstrate failure and success cases?

If we _know_ it's down to a permission issue (e.g. `unzip needs write permissions` - which is perfectly sane), do we have reason to restrict the permissions?  Can we restrict permissions so that only the `unzip` step has write permission on a specific target directory (e.g. by granting write on that target from a "higher power" / elevated privilege state)?

**Comment by ann0see** [comment]
As I said above, just change the permissions in the GitHub repository and run two same builds. Once with and once without write permissions. They can be changed here: https://github.com/jamulussoftware/jamulus/settings/actions

Once the build fails, once it goes through. I'm unsure if this is still the case, but I'm currently working on Weblate.

**Comment by ann0see** [comment]
Is unzip the problem? Especially I thought write means that we write to the Repo or something on GitHub- not in the runner.

**Comment by pljones** [comment]
I thought it was the unzip that was failing?  Maybe I've missed something.

**Comment by ann0see** [comment]
I would need to check it again and look at the logs.

**Comment by hoffie** [comment]
Hi there.

after some hours of debugging, I believe this is related to timing.

https://github.com/jamulussoftware/jamulus/blob/135e9442f6f36fcc75baeb980480e4247aa072c1/.github/autobuild/windows.ps1#L182
We are invoking the JACK installers, but as they are GUI applications (even if we pass parameters to have them run unattended), they will detach from the console and just launch in the background. The build continues nevertheless, which means that by the time that `qmake Jamulus.pro` runs it is more or less luck if JACK installation has already completed or not.
Waiting for the installers to complete seems to fix this. Will submit a PR.
