### ISSUE TITLE
Blocker: "Perform CodeQL Analysis" takes 6h for Linux

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3049]
**Describe the bug**

See https://github.com/jamulussoftware/jamulus/actions/runs/4713980244/jobs/8379530170

**To Reproduce**

Rerun the job

**Expected behavior**

The job should not fail.   This is  **blocking the build**.

**Comment by ann0see** [comment]
Feels like a GitHub related issue to me. We might need to update the OS some time soon.

**Comment by ann0see** [comment]
@pljones I don't think this is still an issue?

**Comment by pljones** [comment]
9m 36s - so yes, looks fixed.  Closing.
