### ISSUE TITLE
Add automated update to pylint

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3056]
As soon as #3052 is merged, pylint should be updated automatically too. 
_Originally posted by @ann0see in https://github.com/jamulussoftware/jamulus/pull/3052#discussion_r1174123173_

**Comment by pljones** [comment]
OK, #3052 is merged, so this needs picking up before Release 3.10.

**Comment by ann0see** [comment]
Yes. I think we'd need to find a regex and edit the update script

**Comment by ann0see** [comment]
If I find time, I can look into this.

**Comment by pljones** [comment]
@ann0see is this still a 3.10.0 blocker?

**Comment by ann0see** [comment]
If I find time I can look at it

**Comment by ann0see** [comment]
In the best case depandabot would handle this. Dropping it from the release for now.

**Comment by pljones** [comment]
Will #2346 cover this?

**Comment by ann0see** [comment]
Feel free to list it there too.

**Comment by pljones** [comment]
OK, added there.  Closing.
