### ISSUE TITLE
Convert GitHub Tracking Board to modern board

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3079]
**What is the current behaviour and why should it be changed?**
Currently the Tracking board uses an old format. It seems as if GitHub is no longer focussing on it. Especially the mobile App doesn't support it and it's quite hidden in the Webui. 
We should check if it can be converted easily
**Describe possible approaches**

Click on the conversion button and set the automisations?

**Has this feature been discussed and generally agreed?**
Not yet.

**Comment by pljones** [comment]
OK, so we should start a "new-style" project and add a few issues and PRs, at least, before committing to this.  Once we've played without and determined that it's useful, we can see about moving issues left on the old board to the new one.

**Comment by ann0see** [comment]
Ok. See the new board (I've added some automations)

**Comment by pljones** [comment]
OK, I can see why Github are pushing it.  Much nicer than the legacy board! :)

**Comment by pljones** [comment]
I'd rather we started soon, yes.

I'd recommend anything we've not tagged as milestone 3.11.0 as Triage with no milestone - unless there's a PR raised, in which case I'd put it in backlog as we should look to clear those rather than start more new work.

**Comment by ann0see** [comment]
Ok. Doing some stuff now. I think we'll need to update some of the tooling scripts.

**Comment by ann0see** [comment]
I believe that everything should be ok now. @pljones I'm closing the old Tracking board now.

**Comment by pljones** [comment]
OK, one problem - the "Milestone" doesn't appear on the "Board" view, so you can't just click it to filter quickly.

**Comment by ann0see** [comment]
Maybe there's a setting/column for that?

**Comment by pljones** [comment]
Ah, got it.  Click the _tab_ dropdown to customise the tab settings:
![image](https://github.com/jamulussoftware/jamulus/assets/1549463/1ef91435-109c-47fa-8528-63a28f02fb30)

**Comment by ann0see** [comment]
I think we need to update the link to the project in the release checklist

**Comment by pljones** [comment]
I've moved all the old 3.10.0 tickets to the new board now - just finishing off by removing them from the old one.

**Comment by pljones** [comment]
I've also made sure all the non-3.10.0 open tickets are on the new board and off the old board
https://github.com/jamulussoftware/jamulus/issues?q=is%3Aopen+project%3Ajamulussoftware%2F2

I bulk moved all the 3.10.0 closed ones to the new board and then bulk moved them from Triage to Done... hopefully nothing spuriously got picked up from Triage in the process...

**Comment by ann0see** [comment]
Thanks!

I think this is now done. Closed.
