### ISSUE TITLE
Place build generated files in separate folder

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3092]
**Describe the bug**

Currently, the build generated files e.g. `.moc` are scattered in the whole root directory. This is the case especially on manual builds. 
https://github.com/jamulussoftware/jamulus/pull/2588 tried to clean them up by moving them into a separate folder however it was not successful.

This is annoying as there are a lot of files.

Please note that if the files are moved, the `.gitignore` file needs to be updated too.

**To Reproduce**

Run a build on e.g. Linux and see the files in the root.

**Expected behavior**

Have a clean root directory.

**Questions/Comments**

* Why is this a problem? I think overview is the main issue
* Cross compilation is more difficult
* Make clean removes them

**Comment by pljones** [comment]
QtCreator does out-of-tree builds by default.

`make distclean; qmake && make && make clean` keeps the project root clean and leaves the user with the option of _not_ running `make clean`.

`make` needs to remain re-runnable from a point of failure with any proposed solution.

**Comment by softins** [comment]
I have a simple solution for this, which is in my queue for raising a PR soon.
