### ISSUE TITLE
My Profile tab sometimes disappears

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3114]
**Describe the bug**

Sometimes with at Qt 6.5.1 based builds, the My Profile tab disappears. See https://github.com/jamulussoftware/jamulus/pull/3099#issuecomment-1650321258

**To Reproduce**
We don't know.

* Freshly install Jamulus
* Open Settings
* Sometimes observe that My Profile doesn't show up

**Expected behavior**

My Profile always shows up

**Screenshots**

Not reproducible 

**Operating system**

Happens on Windows and Linux, Probably macOS too.

**Version of Jamulus**
Unsure, but not yet released version from main.

**Additional context**

Probably a Qt 6.5 bug. @pljones initially experienced it.

**Comment by ann0see** [comment]
I'd downgrade Qt 6 for the release if we can't fix this.

**Comment by pljones** [comment]
I was wondering (and haven't had a chance to investigate) whether this is a change between a client running Qt5 and then being upgraded with the same profile to Qt6.  When did, for example, the country codes in the profile change?  Or the flags?

**Comment by pljones** [comment]
OK... Some initial investigations.

Clean profile, Qt5.12.2 run from QtCreator:
![image](https://github.com/jamulussoftware/jamulus/assets/1549463/1844bae4-450b-4442-8a0a-f927860e208f)

Clean profile, Qt6.5.1 run from QtCreator:
![image](https://github.com/jamulussoftware/jamulus/assets/1549463/fd001759-a306-4f55-812f-565fc83f652a)

Once Qt's incredibly slow server has allowed me to get Qt6.5.2 installed, I'll try that.

**Comment by pljones** [comment]
https://github.com/jamulussoftware/jamulus/pull/3110 may fix this, then?

**Comment by ann0see** [comment]
> Are we using Qt6 < 6.5.2 for any build?

No. I don't think so

**Comment by pljones** [comment]
Also checked and replicated the behaviour on Linux Qt6.5.1 vs Qt6.5.2 - looks like they've fixed it.

**Comment by pljones** [comment]
Linked to https://github.com/jamulussoftware/jamulus/pull/3110, which appears to be the fix.
