### ISSUE TITLE
Update nb_NO app translation for 3.10.0

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3132]
Hi @pljones,
We are getting ready for the 3.10.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **nb_NO** by **2023-08-20**.

Please either [update the translations on Hosted Weblate](https://hosted.weblate.org/projects/jamulus/) or use Git:
- Update your fork from `jamulussoftware/jamulus` `main` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2023-08-20

Suggested commit and PR message:
```
Update nb_NO app translation for 3.10.0

Fixes #3132
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/main/docs/TRANSLATING.md).

Thanks for contributing to Jamulus!

<a href="https://hosted.weblate.org/engage/jamulus/"><img src="https://hosted.weblate.org/widgets/jamulus/-/jamulus-app/multi-auto.svg" alt="Translation status" /></a>

Progress: https://hosted.weblate.org/changes/browse/jamulus/jamulus-app/nb_NO/?start_date=2023-07-30

**Comment by ann0see** [comment]
@pljones is this really your language?

**Comment by pljones** [comment]
I changed the script to assign any "unsupported" languages to the person running the script to either find a translator and re-assign or close as unsupported.

**Comment by ann0see** [comment]
> I'm not sure we should offer partial translations - I don't think it looks good.

We did in the past. Having parts translated is better than having nothing translated.

**Comment by ann0see** [comment]
Closing. Translation updates after today may not be part of the final release.
