### ISSUE TITLE
CodeQL is reporting "Security" issues in Jamulus source

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3161]
**Describe the bug**

[CodeQL has been reporting the following "Security" issues](https://github.com/jamulussoftware/jamulus/security/code-scanning?query=branch%3Amain+path%3Asrc) in `src/client.cpp`:
> Multiplication result converted to larger type High
> \# 18 opened January 10, 2021 05:44 • Detected by CodeQL in src/client.cpp:1314 main
> Multiplication result converted to larger type High
> \# 17 opened January 10, 2021 05:44 • Detected by CodeQL in src/client.cpp:1268 main
> Multiplication result converted to larger type High
> \# 16 opened January 10, 2021 05:44 • Detected by CodeQL in src/client.cpp:1260 main

which were closed as "Won't fix".  Re-opening this as an issue.

**To Reproduce**

View the "Security" tab, "Code scanning alerts"->"View alerts" with the "open" filter removed.

**Expected behavior**

We shouldn't have any type "High" security defects.

_Every build_ should report the CodeQL security defects in Jamulus src _clearly_.

**Comment by ann0see** [comment]
Agree. Security issues must be taken seriously! It's a numeric overflow - maybe we need to use a greater immediate type?

**Comment by pljones** [comment]
> Every build should report the CodeQL security defects in Jamulus src clearly.

Currently, the CodeQL process _appears_ to kick off only when a "build all targets" autobuild runs.

I've not yet understood when the Security tab picks the results up - it appears there's a configuration somewhere that's related to the above, but I'm not sure how.

**Comment by softins** [comment]
I've pushed a branch to my repo that I think should fix this easily. See https://github.com/softins/jamulus/commit/e12c00044e5b050c6e429ff5d0c48ae4cb186c5e

It compiles without warnings and doesn't appear to flag the branch under Security.

I can raise it as an alternative PR to #3162 if @pljones is happy.

**Comment by softins** [comment]
In fact, an even better solution is to completely remove the multiplication from the index, and just step an index by the multiplication factor. See https://github.com/softins/jamulus/commit/a3885acb1be4c501976f428175b2d142d8a0461e

I can raise this as a PR instead if @pljones is happy.
