### ISSUE TITLE
Repository installer doesn't complete (setup_repo.sh)

### ISSUE THREAD

**Issue by houbsta** [jamulussoftware/jamulus#3196]
The script to set up the repo does not allow for updates to happen on Ubuntu 20.04 / AWS 

Download the file from https://raw.githubusercontent.com/jamulussoftware/jamulus/main/linux/setup_repo.sh 
Make it executable
`$ sudo ./setup_repo.sh`

It's expected that the repo should be installed however the following output is seen:

```
Setting up Jamulus repo at /etc/apt/sources.list.d/jamulus.list...
Installing Jamulus GPG key at /etc/apt/trusted.gpg.d/jamulus.asc...
Running apt update...
E: Failed to fetch https://github.com/jamulussoftware/jamulus/releases/latest/download/./InRelease  401  Unauthorized [IP: 185.199.109.133 443]
E: The repository 'https://github.com/jamulussoftware/jamulus/releases/latest/download ./ InRelease' is not signed.
[snip echo'd text]
```

I would expect the repo to not report being "unsigned"

Output of `uname -a`

`Linux ip-172-26-XX-XX 5.15.0-1048-aws #53~20.04.1-Ubuntu SMP Wed Oct 4 16:44:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

I can probably force the repo to work, but I'd expect the installer script to work on a nominal Ubuntu 20.04 installation.

Most other entries in `/etc/apt/sources.d/` do not resemble the jamulus.list

-> either including a `[signed-by=/etc/.../key.gpg]` before the URL and / or
-> include ` bionic main` or similar, post URL, rather than `./` as seen in the jamulus.list file

**Comment by ann0see** [comment]
Hi @houbsta 
We are aware of this or a related issue. It's due to a bug in apt. You'll most likely need to update your OS (or apt). 

Please see https://github.com/orgs/jamulussoftware/discussions/3180
