### ISSUE TITLE
Detect Ubuntu version in setup_repo.sh

### ISSUE THREAD

**Issue by houbsta** [jamulussoftware/jamulus#3198]
**What is the current behaviour and why should it be changed?**

Currently the script to add the jamulus repository for Ubuntu fails under Ubuntu 20.04 - which is still officially supported by Ubuntu and therefore many users may not see the need to upgrade. 18.04 and previous are no longer supported so users should certainly upgrade from those release versions.

**Describe possible approaches**

By detecting the current Ubuntu version (with something like `lsb_release -sr` no doubt) if that version number is < 22.04 then the script should stop execution and return a warning like "WARNING: Ubuntu versions less that 22.04 have a bug in their apt version for signed repositories. Not adding jamulus repo. Either install the deb file manually [see https://jamulus.io/wiki/Installation-for-Linux] or update your system to at least Ubuntu 22.04"

This is followed up from https://github.com/orgs/jamulussoftware/discussions/3180#discussioncomment-7552208

**Comment by houbsta** [comment]
I have added the code to check for a recent apt (2.4.x branch) to the pull request #3199

**Comment by houbsta** [comment]
Not sure what I need to do here - it's assigned to me, but what action do I need to take for this and #3199  ?

**Comment by ann0see** [comment]
I believe it's done, so it's just for protocol.
