### ISSUE TITLE
"Delete server" button doesn't show properly on macOS

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#3241]
**Describe the bug**

The "Delete server" button that was added in #3159 doesn't show properly on macOS. At least on my Mac running Catalina 10.15. The button is there, but it is too narrow to show the whole icon.

The button acts correctly when clicked on.

**To Reproduce**

Download and install a recent build artefact, e.g. from https://github.com/jamulussoftware/jamulus/actions/runs/8031934048. In this case, I installed the Mac Legacy, which had been built with Qt 5.15.2

**Expected behavior**

The button should be wide enough to show the backspace icon.

**Screenshots**

![image](https://github.com/jamulussoftware/jamulus/assets/3224952/0edcd0ef-3a48-4987-880f-8771f6811572)

**Operating system**

MacOS 10.15 Catalina

**Version of Jamulus**

3.10.0dev-dbd6e61

**Additional context**

The button shows correctly on Windows, and when compiled on my Raspberry Pi. I haven't been able to try a more recent MacOS or the non-legacy build.

**Comment by ann0see** [comment]
That's bad. Does the same happen in the server where a comparable button is?

**Comment by softins** [comment]
> That's bad. Does the same happen in the server where a comparable button is?

I will look more closely. Checking the various dev versions I have installed, it seems the delete button in the connect dialog shows up ok with Qt 5.9.9, but is truncated as shown above with Qt 5.12 or Qt 5.15. However, in all three cases the delete buttons in the Server Options page show up fine. I'll have to see what the subtle differences are.

**Comment by softins** [comment]
It appears ok in the artifact I downloaded from #3260. I'll check again once that has been merged and built with Qt 5.15.2.

**Comment by pljones** [comment]
![image](https://github.com/jamulussoftware/jamulus/assets/1549463/38b30788-c2de-491a-808d-2617b3e04ca9)
![image](https://github.com/jamulussoftware/jamulus/assets/1549463/14f210f6-005b-4f57-9192-3a113f63af2d)
Hmm... they're not identical.  The button in the server is larger and the glyph in the client is bold...

**Comment by softins** [comment]
> Hmm... they're not identical. The button in the server is larger and the glyph in the client is bold... (And, of course, different fonts between Linux and Windows. Probably some of the styling is set by the OS theming...)

Yes, the button in `connectdlgbase.ui` has a `<bold>true</bold>` in the `font` setting. We can make sure all is consistent in the PR to fix this issue.

**Comment by ann0see** [comment]
@pljones since this is a bug, can we move it to 3.11.0 back?

**Comment by pljones** [comment]
I think we'll have to do _something_, so yeah.  I'd like the PR asap, of course :)

**Comment by pljones** [comment]
If we've no MacOS developers, we may have to drop MacOS support...

**Comment by ann0see** [comment]
Before we drop macOS support I'll get into macOS development.

**Comment by chrisrimple** [comment]
There are very likely some MacOS developers among the WorldJam participants.  I'll put out a call...

**Comment by softins** [comment]
> If we've no MacOS developers, we may have to drop MacOS support...

I can look at it after my holiday.
