### ISSUE TITLE
Server de-registers on GUI state change

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3287]
I tested running the server on macOS and it needed multiple tries to show up as directory. The directory did not show up for a local client if a path for recordings is set. It may not be related and needs more investigation (test with a path that is not writable).

It seems as if on 3.10.0 the directory shows up instantly.

_Ursprünglich gepostet von @ann0see in https://github.com/jamulussoftware/jamulus/pull/3259#discussion_r1614890230_

**Comment by softins** [comment]
I'll try it here and see if I find the same, and do some diagnosis if I do. But it will probably be after the weekend.

**Comment by softins** [comment]
I just tried the latest build of mac legacy, and it seems to register ok. I had one occurrence at the start when it registered, but then dropped back pretty quickly to not registered. But I've been unable to replicate that with several attempts: it has been registering fine and staying registered.

Is there a repeatable way you have found to demonstrate the problem?

**Comment by ann0see** [comment]
>  I had one occurrence at the start when it registered, but then dropped back pretty quickly to not registered. 

I think that's what I saw. I don't have macOS access at the moment but 
I think it has to do with restarting the server having a recording directory set to which the application doesn't have access to -> reason sandbox. 
If the directory is set again, the sandbox has a whitelist to the chosen directory. But this may be reset after an app restart.

**Comment by ann0see** [comment]
Let me try to come up with steps to reproduce:
1. Install a build with hardened runtime/sandbox enabled
2. Set a recording directory
3. Set custom directory address to localhost to register as directory. 
4. Choose the custom directory -> everything should work as expected
5. Close the server
6. Re open the server and connect a client with custom directory as localhost. 
7. Check the registration status.

**Comment by ann0see** [comment]
@softins could you please try again and wait a bit on the Server GUI?

**Comment by softins** [comment]
> 1. Install a build with hardened runtime/sandbox enabled

What does this mean? Is it a special kind of build, or some special setting to apply to an installed application?

**Comment by ann0see** [comment]
This means that it's a sandboxed build. Both legacy and normal from the CI should be sandboxed.

**Comment by ann0see** [comment]
Seems like a blocker!

**Comment by ann0see** [comment]
@softins can you reproduce this bug on your Mac?

**Comment by ann0see** [comment]
Now this also seems to apply to other directories like any genre 1, not just registering with localhost.

**Comment by pljones** [comment]
Have you tried downgrading your version of macOS?  That would help diagnose the problem, at least.

This occurs on a 6.7.x build, too?

**Comment by ann0see** [comment]
It occurs on legacy and non legacy but doesn't seem to happen on 3.10.0. So I suppose it's a bug on our side.

**Comment by pljones** [comment]
What version is the non-Legacy build now?

**Comment by softins** [comment]
I have just been testing on my Macbook. It looks like the latest version of GUI server will register with a directory (I tested using `private.jamulus.io`), but as soon at its window loses focus, such as when switching to a client to try connecting, the server loses its registration and the GUI reports "Not connected". It then does not appear in the list of servers shown in the client's Connect dialog.

I can see in Jamulus Explorer that the registration did initially succeed, and was maintained as long as the GUI retained focus. When it lost focus, the registration was actively cancelled with the directory, as Explorer showed the server was gone.

I went back to 3.10.0 server, and this behaviour doesn't happen; the registration is maintained when the server window loses focus.

Thankfully, I have about 16 different post-3.10.0 versions of Jamulus and JamulusServer app installed, so I want through them from earliest to latest until I got to one exhibiting the loss of registration.

By checking the commit IDs of the latest working build and the first failing build, I've deduced that the change in PR #3144 is what breaks it. This is the PR that adds the saving of settings on GUI state change. It was intended to fix an issue on the Android version of Jamulus client. But in server mode it does seem to kill the registration. I haven't diagnosed why yet. It's probably not specific to the Mac.

**Comment by pljones** [comment]
It's really intended for mobile rather than desktop.  If it does affect the Windows desktop (I think I tested it there, though), we could make it mobile-only.

**Comment by softins** [comment]
I think on the client it's fine, but needs specific testing of the GUI server on the various platforms, and its effect on registration. I'm away for another week, so can't do much except on my Macbook.

**Comment by pljones** [comment]
It sounds almost like MacOS is putting the app to sleep following that commit and, as it didn't previously acknowledge "states", it wasn't doing so.  Is there some setting that can be used not to put the app to sleep when it's not got focus?  Or like the run in background power states on Windows?

**Comment by pljones** [comment]
Oh!  It switches to "Not registered" _immediately_ the window loses focus.  Strange.

**Comment by ann0see** [comment]
> MacOS is putting the app to sleep

This can happen and is called App Nap I think. But it doesn't seem like that.

**Comment by pljones** [comment]
src/settings.cpp 982:
```
    // we MUST do this after saving the value and Save() is only called OnAboutToQuit()
    pServer->SetDirectoryType ( AT_NONE );
```

**Comment by pljones** [comment]
I think the easier fix is to add a parameter to `CServer::Save` that indicates it's being called to handle `QCoreApplication::aboutToQuit` rather than some other reason.

**Comment by pljones** [comment]
PR raised - if someone could check on MacOS, please?
