### ISSUE TITLE
Upgrade main macOS runner to macOS 14 (also upgrades to Apple Silicon arm)

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#3296]
**What is the current behaviour and why should it be changed?**

Currently we build on x86. The upgrade will change to arm64. All modern Mac devices are arm64, so it makes sense to also switch the build. It should also support x86.
The upgrade happens if we switch to macos-14 and needs some small changes to the mac.sh script. PR is following

**Comment by pljones** [comment]
I've tagged this for 3.12.0 -- it's a good idea to get onto the current architecture as soon as we can.  It _shouldn't_ be a major change, just switching which is the main artifact?

By the way, there are three linked branches opened that appear to relate to this -- are they all doing the same thing?

**Comment by ann0see** [comment]
They are all related as I tried working with code spaces online as my local setup is somewhat complicated (new OS install). But only the branch from which the PR is opened is relevant.
