### ISSUE TITLE
Update TRANSLATING.md for embed_translations

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#3310]
I've just noticed that `docs/TRANSLATING.md` needs to be updated now that we've added `embed_translations` to `Jamulus.pro`:

In the section **Adding a new language**, there is no longer any need to add `.qm` files to `Jamulus.pro` or a resource file, nor to run `lrelease`. I think `lupdate` is still needed.

I will do the changes soon and check for anything else required. This Issue is to ensure it doesn't get forgotten.

**Comment by ann0see** [comment]
@softins I believe this is done and the needs documentation flag is no longer necessary? Please untag.
