### ISSUE TITLE
Support delay panning in the server

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#332]
Instead of a volume panning, a delay panning can be applied in the server.
There should be a server command line argument which switches between volume and delay panning.
Initial code was already supplied by Detlef Hennings and can be found on a branch:
https://github.com/corrados/jamulus/commit/d5459802f022604b837f2679116bd7fd69418b1d

**Comment by corrados** [comment]
There is an updated code available on the following branch: https://github.com/corrados/jamulus/tree/feature_hennings_delay_pan2

**Comment by ann0see** [comment]
Closed via: https://github.com/jamulussoftware/jamulus/pull/1151
