### ISSUE TITLE
Genre 1 invisible - plus de genre1

### ISSUE THREAD

**Issue by Melaniedrum22** [jamulussoftware/jamulus#3424]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating system**

**Version of Jamulus**

**Additional context**

**Comment by Melaniedrum22** [comment]
Bonjour , je suis française ,  je ne connais pas l anglais pardon , depuis que j ai installé la nouvelle version de jamulus , j'ai bien accès a tous les genres , mais le genre1  la page est blanche . j ai désinstallé jamulus et réinstaller des version précédente mais cela ne fonctionne . la page genre 1 est blanche . j espère que vous pourrez m aider .
merci pour votre aide

**Comment by ann0see** [comment]
Cette erreur est causée par la "fragmentation UDP". 

Malheureusement, vous ne pouvez pas y faire grand-chose, à part changer d'accès à Internet. 

Je suggère d'utiliser deepl (https://www.deepl.com/) pour traduire la conversation.

**Comment by ann0see** [comment]
CC: @jujudusud

**Comment by jujudusud** [comment]
Bonjour @Melaniedrum22, normalement on parle en anglais mais il arrive qu'on puisse faire des exceptions.
En fait, lorsque genre1 ne se remplit pas automatiquement et qu'il reste vide c'est souvent à cause d'un "filtrage réseau" soit de la part de ton opérateur internet, soit des règles d'un pare feu dans l'endroit où tu utilises Jamulus. Du coup, tu ne peux pas faire grand chose contre ça.
Ce qui est possible par contre, si tu connais le serveur sur lequel tu dois te connecter avec d'autres personnes, tu peux t'y connecter en le nommant directement.

**Comment by ann0see** [comment]
I will close this as it's a known bug. 

See: https://github.com/jamulussoftware/jamulus/issues/3242
