### ISSUE TITLE
iOS build using macos-12 runner now fails

### ISSUE THREAD

**Issue by softins** [jamulussoftware/jamulus#3433]
Github have now discontinued support for the macos-12 runner, so we need to move those builds to at least macos-13.

Just raising this issue to give it visibility.

**Comment by softins** [comment]
Now that the macOS Legacy build has been successfully moved to the macos-13 runner, have updated the issue title to just refer to iOS.

Don't yet know what the right solution is for iOS. Needed also to change the SDK version from 13 to 14, and the build no longer succeeded.

**Comment by ann0see** [comment]
Updating to Qt6, I suppose.
Otherwise building Qt 5.15 from source.

There are still some open PRs and issues with the Qt6 build.

**Comment by softins** [comment]
See also #3293 and the comments there about the need to move from the "legacy build system" to the "modern build system" when using SDK 14.

**Comment by ann0see** [comment]
I've tried to compile Jamulus locally on macOS with the 18.2 SDK and it fails with a linker error related to ffmpeg. (Will try to debug it further and then open an issue) I do not remember that we use ffmpeg anywhere. 

The qtmultimedia plugin might pull it in.

**Comment by ann0see** [comment]
I'd go further as follows:
* Upgrade main to Qt6
* Afterwards debug further UI issues
* The problem is that the CI breaks otherwise.
