### ISSUE TITLE
Move download links away from SourceForge?

### ISSUE THREAD

**Issue by dyfer** [jamulussoftware/jamulus#473]
Hello,
First, thank you for Jamulus. I've been researching various low-latency audio solutions and I've been using Jamulus for some of my projects currently.

I was wondering if it would be desirable/possible to move the download links (the actual binaries, as well as the link from the Jamulus website) to GitHub, or some other place, but away from SourceForge. SourceForge tends to have quite a bit of ads that sometimes trick users to download other software; I've seen this happen at least once.

**Comment by corrados** [comment]
Jamulus just recently got rewarded to be the Project of the Month. I am using Sourceforge for my open source projects for more than a decade now. I see that there are ads when downloading but I am not so much offended by that. I want to stick to Sourceforge.

**Comment by dyfer** [comment]
I understand, thank you for your response. And again, thank you for your work on Jamulus!

**Comment by corrados** [comment]
The Jamulus project will soon be moved to the Github jamulussoftware organization. We also will have automated installer builds on Github. So, maybe now is the time to move away from Sourceforge so I re-opened this Issue.

**Comment by ann0see** [comment]
Yes. I think once the new release process is ready, you will be able to download the binaries from GitHub. Have a look at the release page now. There already is a beta release!

**Comment by gilgongo** [comment]
@ann0see Does this ticket need further discussion or can we now agree what to do? If so, please edit the original above so we can be clear if there's anything else to do on it. Or move it to a discussion otherwise.

**Comment by ann0see** [comment]
Outcome of this issue: 

The new release process allows us to host binaries on GitHub and SourceForge. Have a look at the [Jamulus GitHub releases page](https://github.com/jamulussoftware/jamulus/releases)

**Comment by gilgongo** [comment]
OK and if we combine this with https://github.com/jamulussoftware/jamuluswebsite/issues/322 then we should be cool?

BTW what's the reason why binaries are on both GitHub and SourceForge? We'd only use one URL, no?

**Comment by ann0see** [comment]
Reason for SourceForge:

It has always been there and moving download URLs might be tricky for long term users. Also having two mirrors gives us a better up-time guarantee. My ISP also has a bad peering to AWS where GH hosts its files. So I‘d focus on GitHub but still keep SF up to date.

**Comment by gilgongo** [comment]
I see, but our "canonical" URL would be GH I take it. Could have both on the download page I guess no harm in that (SF spam issues aside), but are we able to prevent redirecting the user from our site to SF (that is, do we have a "raw" download link for them)?

**Comment by ann0see** [comment]
> I see, but our "canonical" URL would be GH I take it. Could have both on the download page I guess no harm in that 

Yes. That’s a good idea. 

> Direct link to SourceForge

I don’t think so. I struggled with a raw download link from SF during the work with the installer.

**Comment by gilgongo** [comment]
Seeing as @ann0see has got the "back end" of this sorted out, and now that we have a ticket for the front end (https://github.com/jamulussoftware/jamuluswebsite/issues/322), I'll close this now if that's OK @dyfer
