### ISSUE TITLE
Allow Jamulus to disconnect from Jack to be able to change audio settings

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#533]
On Windows (using ASIO) it’s possible to change e.g. the buffersize while Jamulus runs. On Linux this is not possible (you have to set it up in jack, therefore have to close jamulus, change settings in jack and then reconnect). That's not ideal. 

Ardour solves the problem by letting the user disconnect from Jack. Would this be possible with Jamulus too?

**Comment by ann0see** [comment]
Just triaging issues. I think this issue is something which @pgScorpio should be aware of in his sound redesign ;-). Maybe it's worth thinking about JACK disconnectivity too. But that should then be linked in the respective discussion: https://github.com/jamulussoftware/jamulus/discussions/2400

**Comment by pgScorpio** [comment]
In the sound redesign it is not neccesary to close jamulus. Just disconnect from the server change Jack settings, reselect Jack device and connect to the server again.

**Comment by ann0see** [comment]
Ok. Closed then
