### ISSUE TITLE
UPnP support

### ISSUE THREAD

**Issue by diegodlh** [jamulussoftware/jamulus#579]
I haven't delved into the Jamulus code base yet to propose a solution myself, so I'm posting this here as an open question/suggestion in case someone can pick it up.

UPnP support (that is, automatic configuration of port forwarding for the server) was suggested in the Sourceforge discussion forum [long time ago](https://sourceforge.net/p/llcon/feature-requests/14/), but finally rejected with implementation of central servers.

However, the central server solution does not always work, and in some cases (such as [when clients are behind carrier-grade NAT](https://sourceforge.net/p/llcon/discussion/server/thread/f72b293af0/)) port forwarding has to be configured for public servers as well.

**Comment by gilgongo** [comment]
This is great idea but probably needs some discussion on how best to spec it up for an actionable work ticket. To that end, I'll move it to a discussion so as not to clutter up the Issues.
