### ISSUE TITLE
Use a different approach to get external IP address

### ISSUE THREAD

**Issue by atsampson** [jamulussoftware/jamulus#633]
From discussion in #572...

`NetworkUtil::GetLocalAddress` is used by `CServerListManager`'s constructor to provide an idea of the server's own address for the first entry in the server list. Currently it works by opening a TCP connection to Google's public DNS server and using Qt's wrapper for `getsockname` to get the local end's address, which isn't ideal for privacy reasons.

We could rework this to use a `connect()`-ed UDP socket, which would achieve the same effect without actually sending any packets (on Linux/FreeBSD at least; I don't know if this works on Windows/MacOS). Or we might be able to get the address from one of the Jamulus server's existing sockets when replying to a server list request.

**Comment by pljones** [comment]
Given the version lookup is done to the Default Central Server list server, that might as well be the address used.

**Comment by pljones** [comment]
Well, jamulus.fischvolk.de doesn't have port 80 open.

The requirements here are:
- we need a host that has a fixed IP address (to avoid slow DNS look ups)
- we need a host that is always available (to avoid slow connection set up and failure)
- we need a host that exposes a TCP service
- we need a host that is happy to have random connections to an exposed port (we're not high volume is a redeeming feature here)

**Comment by gilgongo** [comment]
Given the fact that this ticket originally came from the POV of privacy, [I see](https://www.techradar.com/uk/news/best-dns-server) CloudFlare "_doesn't just promise that it won't use your browsing data to serve ads; it commits that it will never write the querying IP address (yours) to disk. Any logs that do exist will be deleted within 24 hours_." 

So maybe 1.1.1.1 is a good enough alternative?

**Comment by ann0see** [comment]
As a quick fix 1.1.1.1 might work.

**Comment by corrados** [comment]
@pljones Do you want to apply the change (since you have written that code)?

**Comment by pljones** [comment]
Done: #662

**Comment by gilgongo** [comment]
Note to self: update privacy statement when this gets released.

**Comment by ann0see** [comment]
I think it has been merged

**Comment by corrados** [comment]
Ok, should we close this one then?

**Comment by ann0see** [comment]
Not sure. We still rely on a third party.

**Comment by pljones** [comment]
The _default_ here needs to be to use the Well Known service.  Perhaps, in some circumstances, someone is running a server list with registered servers that do not expose their public IP addresses - but that case is going to be incredibly rare if it ever happens.  Should it happen, perhaps an IP/port rewriting rule could be inserted in a firewall, or similar, to have the lookup handled some other way, without being routed outwards.

**Comment by gilgongo** [comment]
> We still rely on a third party.

From what I understand, that's not going to be possible if the central server(s) don't have well known TCP ports open. Which they don't.

**Comment by atsampson** [comment]
I haven't had a chance to try implementing this yet, but I've had a look through the Qt documentation today and found a few more potential ways of doing it if my first suggestion above doesn't work on all platforms. So we could:

- Open a `QUdpSocket`, `connect()` it to an arbitrary Internet address (which for UDP doesn't send/receive any packets, it's just setting up the local address), read the local address.
- Defer filling in the server list entry until we get our first packet from another host, and look at the destination address of that packet (using `recvmsg` with the `IP_PKTINFO` socket option set, or changing the socket code to use `QUdpSocket` and using `QNetworkDatagram::destinationAddress()` which is Qt's wrapper for the same thing).
- Use `QNetworkInterface` to get a list of the local network interfaces' addresses and filter out those that are obviously not public addresses - this is a bit more work so it's less preferable than the above two options.

So it looks like there are plenty of options that don't need a remote server or any network communication at all.

**Comment by gilgongo** [comment]
Well. Rocking good news!

**Comment by pljones** [comment]
I tried the first option and it didn't appear to work - hence using TCP.

A central server _could_ be started with a "known" set of hosts, so there wasn't an option to wait without significantly rewriting the start up code, which wasn't a priority.

And the third option is not only messy, it's unreliable in many situations (e.g. within cloud data centres, it can give completely the wrong answer).

**Comment by pljones** [comment]
Has anyone managed to get option 1 working on Windows, Mac and Linux yet?

**Comment by corrados** [comment]
There is another closed Issue https://github.com/corrados/jamulus/issues/690 in which it was recommended to make the IP lookup time out higher (from 500 ms to 5 s). But when there is another method of getting the local IP is going to be supported, that Issue would no longer be relevant.

**Comment by hoffie** [comment]
When reading the code, I stumbled upon the 1.1.1.1 address and found this issue. I fully agree with @atsampson. For finding a machine's external IP¹, no actual network traffic should be necessary. I quickly tried what @atsampson proposed and it seems to work as expected (#1011).

¹ We are still talking about the existing approach which just finds the external IP. This will be equal to the public IP for Internet-facing machines. For machines behind NAT, it will be the private IP within the NAT environment. If one really wanted to find the external IP, one would need to contact an external service (STUN, an API). But I do not think that this is in the scope of this issue.

**Comment by pljones** [comment]
Just to note @softins (https://github.com/jamulussoftware/jamulus/pull/1011#discussion_r578548118) points out that no exposure happens whilst retaining functionality simply changing the protocol to UDP.  (In case people aren't following the code, too.)

**Comment by hoffie** [comment]
Will merge in a second. Thanks for anyone involved, especially @atsampson! :)

> Note to self: update [privacy statement](https://github.com/corrados/jamulus/wiki/Privacy-Statement) when this gets released.

https://github.com/jamulussoftware/jamuluswebsite/pull/333
