### ISSUE TITLE
Show version number during mouse hover on Name

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#717]
For the WorldJam, it would be helpful if, in the Mixer view, hovering a mouse over a connection's Name would show the client version that they're running, along with their Profile information.  This would make it easy to determine if the connected performer has updated to the latest client.

Also valuable to see on mouse hover would be the operating system of the user, so perhaps add that as well.

**Comment by corrados** [comment]
> For the WorldJam, it would be helpful if, in the Mixer view, hovering a mouse over a connection's Name would show the client version that they're running, along with their Profile information.

If you say it is helpful, my question is in what regard is this helpful? Do you need this information during a live gig or during the sound check? If you are referring to the sound check, I think it would be easier to talk to the person and tell him to install the latest Jamulus version if he does not already has it.

**Comment by chrisrimple** [comment]
During WJ soundcheck, we do remind all performers to update to the latest version.  But with 10 musicians waiting in a soundcheck server for their turn to soundcheck, being able to see those with an old version (who may not be technical and realize that they need to update) so we can inform them would be nice.

**Comment by corrados** [comment]
I have a better solution for you. Since you are under control of the soundcheck servers, you should write that in the Server Welcome message, like: "Please make sure to upgrade your Jamulus software to the latest version". So everybody who enters the soundcheck server will read this.

**Comment by chrisrimple** [comment]
I'm not sure that's a "better" solution, since it requires all joiners to read and pay attention to the server welcome message, which seems unlikely to happen.  :)  I'm not saying this is a high-priority feature request, maybe just something to consider whenever next making changes to the popup contents or layout.

**Comment by corrados** [comment]
> I'm not sure that's a "better" solution, since it requires all joiners to read and pay attention to the server welcome message, which seems unlikely to happen. :)

That may be the case. But it does not hurt to implement that since you can do it right now without having to modify the Jamulus source. Maybe there is someone who is actually reading this ;-).

**Comment by gilgongo** [comment]
This seems marginal as per the KISS principle, so closing if it's OK with you @chrisrimple
