### ISSUE TITLE
[Question] Is Jamulus working on Big Sur and/or Mac M1?

### ISSUE THREAD

**Issue by gegeweb** [jamulussoftware/jamulus#749]
Im working on the french translation of the website documentation and to be up to date I need to know if Jamulus have been succefully compiled and tested on macOS Big Sure running on a M1 processor.
If not we'll have to add a warning on the related pages. (see https://github.com/jamulussoftware/jamuluswebsite/issues/88) 

About Mac OS Big Sure, actual binary works fine (Intel processor) and I've succefully compiled Jamulus with QT5 on this OS.
_(instructions on the doc are incomplete (we will fix that), and there is no icon for the `Jamulus.app` application builded, and only client is builded, not the server application)_

I have only some minor cosmetic issues in the UI of the server with the official binary downloaded on sourceforge. (I'll open a new issue later for that).

**Comment by gegeweb** [comment]
Unfortunatly I don't have a Mac M1 (and not sure if I want one… I will probably switch to PC and GNU/Linux in futur) for testing this point.

**Comment by pljones** [comment]
> there is no icon for the Jamulus.app application builded
> and only client is builded, not the server application

Both these points sound like you didn't run the installer build, only the code build.  There is only one executable created.

**Comment by gegeweb** [comment]
> Both these points sound like you didn't run the installer build, only the code build. There is only one executable created.

As I say, probably because documentation is incomplete at this time I've followed the verry succint instructionabout macOS here:
https://jamulus.io/wiki/Compiling

* missing how-to installing homebrew (Requirements)
* missing how-to fix the failure with `brew link qt5 --force` if `/usr/local/Frameworks`doesn't exist yet.
* missing the installer build step ;)

And parhaps other things, that was the first time I compiled a software with XCode on macOS (I was curious)…

**Comment by gegeweb** [comment]
> because documentation is incomplete

But maybe it's a deliberate choice?

**Comment by gegeweb** [comment]
> Both these points sound like you didn't run the installer build, only the code build. There is only one executable created.

I've looked on the Apple's doc about XCode but don't find the command for the missing step.
Could you tell me how to do?

Then we will also be able to update the doc.

Thanks.

**Comment by pljones** [comment]
You'll need someone who knows about MacOS, I think.

**Comment by gegeweb** [comment]
> You'll need someone who knows about MacOS, I think.

There is `mac/deploy_mac.sh`wich do the job.

**Comment by ann0see** [comment]
I assume we could compile a native binary for M1 Macs with Xcode 12 somehow.

**Comment by gegeweb** [comment]
@ann0see 

> I assume we could compile a native binary for M1 Macs with Xcode 12 somehow. It might even do it automatically (but I don't think so)

I unfortunately haven't a Mac M1 to try that.

I'm on Big Sure, I'll check if there is M1 as a target (I am not familiar with XCode).
I've some issues with `deploy_mac.sh` to understand/fix before…

There is a warning on Big Sure that say 11.0 is not a supported configuration for QT, but it compile and works.

**Comment by ann0see** [comment]
You can open the .xcodeproject file probably to change the build options

**Comment by gegeweb** [comment]
> You can open the .xcodeproject file probably to change the build options

https://github.com/al45tair/dmgbuild/issues/29

**Comment by gegeweb** [comment]
> 've some issues with `deploy_mac.sh` to understand/fix before…

https://github.com/al45tair/dmgbuild/issues/29

**Comment by gilgongo** [comment]
Possible issue with Big Sur? https://sourceforge.net/p/llcon/discussion/software/thread/487c151a57/#835c/0af3/37ea/a572

**Comment by gegeweb** [comment]
Jamulus works fine here on Big Sure (Intel processor).

<img width="784" alt="Capture d’écran 2020-12-09 à 09 10 58" src="https://user-images.githubusercontent.com/9108457/101602478-7c034e80-39fe-11eb-9f87-96b925977e6d.png">

<img width="766" alt="Capture d’écran 2020-12-09 à 09 12 26" src="https://user-images.githubusercontent.com/9108457/101602666-c08eea00-39fe-11eb-8993-ab3c5348679f.png">

**Comment by gilgongo** [comment]
OK. So can we close this issue then?

**Comment by gegeweb** [comment]
Yes, we need to know if it works on a M1 processor.
We need user feedback for that.
No Mac M1 for testing on my side.

**Comment by gegeweb** [comment]
Two issues here:
* the binary compiled on a Intel processor work on a M1 processor? (with compatibility mode?)
* If no, can we compile on M1/Big Sure (probably yes) and made the package/dmg? (see above for the issue with dmgbuild on Big Sure / XCode 12)

**Comment by 2xbass** [comment]
I am running 3.6.2 on Big Sur on a M1 MacBook Air and also on one of the old MacBook 12" running Big Sur.  Everything seems fine.

**Comment by ann0see** [comment]
I assume it runs with Rosetta 2, not natively?

**Comment by gilgongo** [comment]
Not sure if this is a Big Sur issue or not: https://sourceforge.net/p/llcon/discussion/533517/thread/1b2a9e6078/#8161

**Comment by njc235** [comment]
@ann0see I have it running on my M1 MacMini on BigSur but as you rightly say, it's running I Intel mode via Rosetta 2. Latency does seem a little higher than I would have expected and it may be for that reason. I would have no idea how to compile it on the m1 but I'd be willing to try if anyone wants to show me the way.

**Comment by ann0see** [comment]
You could try https://jamulus.io/wiki/Compiling

or even better run mac/deploy_mac.sh and open the Xcode project file with xcode

**Comment by ann0see** [comment]
I think Qt is working on native arm64 support: https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-85279

**Comment by gegeweb** [comment]
> You could try https://jamulus.io/wiki/Compiling
> 
> or even better run mac/deploy_mac.sh and open the Xcode project file with xcode

I've succefully compiled Jamulus with XCode on Bug Sur (Intel processor) following these, but there is an issue with the deploy script.
See my previous comment : https://github.com/corrados/jamulus/issues/749#issuecomment-739247428
There is a warning about unsuported platform with QT, but it works (compile) on Intel processor.

**Comment by corrados** [comment]
Has anybody been able to compile Jamulus to run native ARM code on the new Mac?

**Comment by njc235** [comment]
> Has anybody been able to compile Jamulus to run native ARM code on the new Mac?

I have an M1 MacMini but I don't have the first idea how to compile code. If anyone has the time to spend with me, I am happy for my machine to try to do this.

**Comment by gilgongo** [comment]
Hi all - until we have some definable action to take to add to a to-do list or codebase change, I'll move this to a discussion if that's OK.
