### ISSUE TITLE
Improve recording recovery script and add to Jamulus install

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#750]
In https://github.com/corrados/jamulus/issues/130, @pljones provides a script to rebuild an RPP file when the server fails to create one for a recorded session.  I have a few requests...

- Create a duplicate script to make the LOF file for Audacity
- Add both scripts (or a combined script) to the Jamulus Server install (at least headless, maybe GUI as well)
- Provide basic instructions on editing/operating the script

I think there are many people operating Jamulus cloud servers that would benefit from these additions.

**Comment by pljones** [comment]
It should be easy enough for the same script to generate the LOF whilst it's doing the RPP - the calculations need to be done, it's just the output format that differs, really.

I've just fixed the help text to point out the one potential issue -- it _must_ be given the correct server fast update value (and currently it only understands `-F` not `--fastupdate`).  That could be a command line option.

It also generates the RPP UUIDs using the server name -- currently set as a variable in the script, again would be better as a command line option.

**Comment by pljones** [comment]
I've started work on this... (This is just to say "I've started" -- I've not tested that the code does what it currently does, which is what it should and I've not started on the LOF side at all, except to allow a filename to be given.)
https://github.com/pljones/jamulus-jamexporter/blob/feature/recover-lof/src/bash/recover-recording.sh

**Comment by pljones** [comment]
@chrisrimple, PR #775 (merged) provides the final version, including LOF support.  I tweaked a couple of bits from the one above, too.

**Comment by pljones** [comment]
From the original request, this bit is outstanding:
> Add both scripts (or a combined script) to the Jamulus Server install (at least headless, maybe GUI as well)

I'm not sure how this would work.  The recovery script has dependencies (bash, various shell tools, sox).  It's also in one of the module sub-projects.  So the (Linux-only?) build would need to ensure that sub-project was current, then the (per-distribution) build would need the new dependencies added.

@corrados -- Is this something you'd be happy having added to the main distribution?

**Comment by chrisrimple** [comment]
@pljones My thinking about including it with the install is to provide the unedited .sh file somewhere under the install path, just as is done for the unedited jamulus.service file, then include instructions (in the file?) for what needs to be edited, any permissions that need to be set, where the file should be moved (if necessary for execution), etc.

**Comment by pljones** [comment]
Whilst the `--help` option explains how to run it, it probably could do with a page explaining it.

It's a bit vicious.  Any empty or non-recoverable file gets `rm` applied to it with a heavy hand.  That's probably the bit to be aware of that isn't made particularly clear anywhere...

It complains if it's clearly run from the wrong place (dirname doesn't start `Jam-`) -- but if you fool around you can confuse it... it's not _that_ careful (and it uses the dirname to set the Reaper file header _date_, so it's expected to be correct... for Reaper).

Plus it wants `uuidgen`, `ffprobe`, `sox` and `soxi` in PATH.  Oh, and `cat`, `awk` and `date`, and I'm taking as read it's run under a decent version of `bash`.

**Comment by corrados** [comment]
What is the status of this issue?

**Comment by pljones** [comment]
> What is the status of this issue?

https://github.com/corrados/jamulus/issues/750#issuecomment-743986996

Inclusion in the main distribution is all I see outstanding from what @chrisrimple was asking for.

**Comment by corrados** [comment]
> Inclusion in the main distribution

@chrisrimple What exactly do I have to do to support this?

**Comment by pljones** [comment]
Also, it might make sense to think more in terms of having this controlled from 
https://github.com/vdellamea/jamulus-server-remote
rather than being part of the Jamulus server code, I think there's a strong argument against it being included.

**Comment by MITEL-UNIUD** [comment]
This is an extremely useful script in the rare cases you need it. In those cases, you might be willing to do some extra work. I think what Chris is suggesting here : https://github.com/corrados/jamulus/issues/750#issuecomment-744025812 is more than sufficient. Said that, the server remote can be easily adapted to run it too.

**Comment by corrados** [comment]
> Also, it might make sense to think more in terms of having this controlled from https://github.com/vdellamea/jamulus-server-remote

That's an interesting project. I just added it as a submodule in the tools directory of Jamulus.

**Comment by vdellamea** [comment]
Thanks. By the way, I just released some minor update (and  the previous comment it's me with the work account - sometimes I make some confusion :) .

**Comment by pljones** [comment]
@chrisrimple 
> @pljones My thinking about including it with the install is to provide the unedited .sh file somewhere under the install path

That could be done.

> then include instructions (in the file?) for what needs to be edited, any permissions that need to be set, where the file should be moved (if necessary for execution), etc.

Someone would need to write that up from the existing documentation provided.

As such, I think it should be covered under a separate request.  (Also, this is getting little attention.)

**Comment by gene96817** [comment]
I have not yet used this feature. However, could you confirm that a person that uses this feature needs to have administrator rights to the server? I am reluctant to introduce this feature to my chorus because I don't want to be supporting every jam session.

This feature appears to be the best reason a person (wanting to have a recording) needs to have their own server.

**Comment by pljones** [comment]
What we're talking about here is a data recovery script.  Yes, it is intended to be used by someone who knows what they're doing.  You can choose to make it available to whoever you like, of course - it does nothing to prevent you as you're meant to know what you're doing.

**Comment by gilgongo** [comment]
The first part of this ticket seems to have been done with https://github.com/jamulussoftware/jamulus/issues/750#issuecomment-743726112 but I'm not sure what the situation is with "add to Jamulus install".

**Comment by pljones** [comment]
> I'm not sure what the situation is with "add to Jamulus install".

It could be done.

I'm not that keen on it being done, though.  I'd rather it were just mentioned (and linked) from wherever the jam recorder documentation lives.

**Comment by gilgongo** [comment]
OK good - so what's the suggested mention and link that's needed exactly ("If you need to do X, you can use [link to Y]..")?

**Comment by pljones** [comment]
Something like that.  A short description of what it does (scans the current directory for what look like jam recording WAV files, creates the project files), plus link to the github repo where it can be downloaded.

The main point is it's just something I wrote for use myself that could be useful for others (now I tidied it up a bit) - it will change to suit my needs, along with the other scripts that live with it.  (Others are at liberty to fork it, of course.)  So I don't think people should see it in the same light as Jamulus, which is a co-operative development.

**Comment by gilgongo** [comment]
Well, one for the next release then...!

**Comment by gilgongo** [comment]
> A short description of what it does (scans the current directory for what look like jam recording WAV files, creates the project files), plus link to the github repo where it can be downloaded.

I've added a link to this and @vdellamea repo in Tips & Tricks for now. May look at splitting out server and client tips into subsections of the relevant manuals one day perhaps though. Bit reluctant to scatter "by the way..." style things in the manuals.

**Comment by gilgongo** [comment]
So now we are linking+explaining the utilities in question, what's the status on @chrisrimple original requests? Does this indicate that we can now close? https://github.com/jamulussoftware/jamulus/issues/750#issuecomment-755199297

**Comment by gilgongo** [comment]
Assuming silence to mean it's OK now.
