### ISSUE TITLE
Jamulus server crashed when toggling recording if disk error occurs

### ISSUE THREAD

**Issue by cdmahoney** [jamulussoftware/jamulus#766]
My server (jamulus 3.6.0git running on ubuntu in the cloud) crashed when an out of disk space error occurred on starting recording. 

The command used to start recording is:
> systemctl kill -s SIGUSR2 jamulus22125

Where jamulus22125 is the name of the service file that creates the service. Under normal circumstances this works perfectly.

The output of journalctl contains:
> Dec 05 13:50:18 server_name jamulus[35647]: OnHandledSignal:  12
Dec 05 13:50:18 server_name jamulus[35647]: Recording state enabled
Dec 05 13:50:18 server_name jamulus[35647]: **Qt has caught an exception thrown from an event handler. Throwing**
Dec 05 13:50:18 server_name jamulus[35647]: **exceptions from an event handler is not supported in Qt.**
Dec 05 13:50:18 server_name jamulus[35647]: **You must not let any exception whatsoever propagate through Qt code.**
Dec 05 13:50:18 server_name jamulus[35647]: If that is not possible, in Qt 5 you must at least reimplement
Dec 05 13:50:18 server_name jamulus[35647]: QCoreApplication::notify() and catch all exceptions there.
Dec 05 13:50:18 server_name jamulus[35647]: terminate called after throwing an instance of 'std::runtime_error'
Dec 05 13:50:18 server_name jamulus[35647]:   what():  /home/jamulus/recordings/fastgrup/Jam-20201205-125018674 does not exist but could not be created
Dec 05 13:50:19 server_name systemd[1]: jamulus22125.service: Main process exited, code=killed, status=6/ABRT
Dec 05 13:50:19 server_name systemd[1]: jamulus22125.service: Failed with result 'signal'.
Dec 05 13:50:49 server_name systemd[1]: jamulus22125.service: Scheduled restart job, restart counter is at 1.
Dec 05 13:50:49 server_name systemd[1]: Stopped Jamulus-Central-Server.
Dec 05 13:50:49 server_name systemd[1]: Started Jamulus-Central-Server.

The problem seems to be that the disk error provokes an exception, which jamulus doesn't handle. Could jamulus be modified to catch the exception? (of course, something bad is still likely to happen sooner or later, but maybe not quite as dramatic as the server going down just as you're about to being a recording.)

**Comment by pljones** [comment]
I think at the moment I'm deliberately throwing an exception to cause the server to go down.  It's a "this should never happen" scenario and the server operator is the only one who can investigate why it happened.

**Comment by cdmahoney** [comment]
OK, so next time I'll be prepared... Or I'll increase the disk space on the server to prevent the problem.

Thanks!

**Comment by pljones** [comment]
Of course, this could originally only happen when the recorder first started, not any time you toggle or start a new recording.

Perhaps it's more acceptable to disable recording if starting to record fails, logging the error.

The only problem is that people already find setting up recording difficult.  If the server ran okay but just wouldn't enable recording, it would make it harder to diagnose issues, perhaps.

**Comment by corrados** [comment]
@pljones What is the status of this issue? Do you intend to change anything in the code? If not, should we close this issue then?

**Comment by pljones** [comment]
I'm not intending to change anything - as I say, it's deliberate as, if the user has asked for recording, it's one of the few ways the server has of saying "That doesn't work" that is explicitly noticeable (when headless).

**Comment by ann0see** [comment]
@pljones would it be possible to give a more detailed error message here like: "Could not start recorder because of missing disk space. Either disable recording or save recordings to a location with more disk space"?

**Comment by pljones** [comment]
>  /home/jamulus/recordings/fastgrup/Jam-20201205-125018674 does not exist but could not be created

That's really all the server knows based on the Qt error it gets, as far as I remember.

**Comment by ann0see** [comment]
Ok. If nothing can be made, I‘ll close this now.
