### ISSUE TITLE
Windows SmartScreen: Jamulus Code Signing

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#785]
Currently, if you install Jamulus on Windows, SmartScreen warns you on Windows 10 (Error: This software might harm your PC). MS Edge even blocks the download.

This evokes a bad impression especially for new users. 

Due to the frequent release cycle there’s no way Jamulus might get on SmartScreen‘s list of known ~~hardware~~ software. 

There are two options to solve this issue:

1. Buy an overly expensive code signing certificate although there‘s something like https://www.certum.eu/en/code-signing-certificates/
2. Make one installer which downloads the latest version of Jamulus and after some time will be downloaded enough times to get on the whitelist. The installer of Jamulus should be able to do online installs, I think. This would also allow us to do a few pre-checks (e.g. is an ASIO Driver installed?)

Related
#550 macOS

**Comment by pljones** [comment]
If this kicks off (point 2, I suppose), then it and #738 should be done together, I suppose.  No point getting it right in one then binning it and getting it wrong in the other...

My Windows scripting is too ancient to pick this up, unfortunately.  (Even for #738 it should be redone in a more modern manner whilst retaining the flexibility.)

**Comment by gilgongo** [comment]
Is there a suggestion that Microsoft may have whitelisted the installer now?

**Comment by ann0see** [comment]
Probably. But only the current version. Once we have a new release it starts again

**Comment by corrados** [comment]
Isn't this very much related to #550? I don't want to have two issue with the same topic. Can we close one of these?

**Comment by ann0see** [comment]
This issue focuses on Windows, while the other focuses on macOS. We might have to handle it differently

**Comment by gilgongo** [comment]
Please continue with any further thoughts here https://github.com/jamulussoftware/jamulus/discussions/1042
