### ISSUE TITLE
Input channel mapping is correctly translated as "Invoerkanaal" mapping

### ISSUE THREAD

**Issue by gilgongo** [jamulussoftware/jamulus#786]
_(posting on behalf of a forum user)_

There's a quite significant mistake in the Dutch translation of Jamulus.
It's mostly apparent on Windows, because of the way ASIO4All works. If a
Windows user goes to Settings, there'll be a Device selection, and an Input
and Output Channel selection.

Output channel mapping is translated as _Uitvoerkanaal in kaart brengen_
which is wrong.

It should have been translated as: **Uitvoerkanaal mapping**

**Comment by corrados** [comment]
Does anyone taking care of this?

**Comment by gilgongo** [comment]
Does anyone speak Dutch? We could just paste in the suggested wording, but that might be risky...

**Comment by ann0see** [comment]
Who's the dutch translator? According to https://de.bab.la/woerterbuch/niederlaendisch-deutsch/in-kaart-brengen in kaart brengen can be translated to "aufnehmen" in German which means "to record". Did the forum user say what the problem is?

**Comment by corrados** [comment]
You can find it in the About dialog of Jamulus: @jerogee

**Comment by jerogee** [comment]
@corrados, thanks for pinging. I am subscribed to #77, but do not regularly check new issues coming in so missed this one. @gilgongo, @ann0see, thanks for thinking along.

The user is right: "Uitvoerkanaal in kaart brengen" is indeed not semantically correct here. 

In English it is "Input Channel Mapping and Output Channel Mapping" and see that in German it is set to "Kanalzuweisung" (covering both). In Dutch that becomes "Kanaaltoewijzing". I will update the NL translation file to replace any mention, and include it in a pull request once @corrados gives us the signal to finalize translations 1 week before release.
