### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [jamulussoftware/jamulus#803]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Jamulus on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by corrados** [comment]
Can you do it?

**Comment by 38github** [comment]
Finally this is soon a reality and we don't have to wait for distros to update their repositories. Even old dstros with out-dated dependies will probably be able to run latest versions.

**Comment by corrados** [comment]
Great. Any volunteers?

**Comment by 38github** [comment]
If I had the knowledge I would be on it right away!

**Comment by ranfdev** [comment]
I have a christmas present for you
```json
{
  "app-id": "io.jamulus.Jamulus",
  "runtime": "org.kde.Platform",
  "runtime-version": "5.15",
  "sdk": "org.kde.Sdk",
  "command": "Jamulus",
  "rename-desktop-file": "jamulus.desktop",
  "rename-icon": "jamulus",
  "finish-args": [
    "--share=ipc",
    "--socket=x11",
    "--socket=wayland",
    "--filesystem=host",
    "--device=dri"
  ],
  "modules": [
    {
      "name": "jack2",
      "buildsystem": "simple",
      "build-commands": [
      	"./waf configure --prefix=/app --htmldir=/app/share/doc/jack/ --classic",
      	"./waf build -j $FLATPAK_BUILDER_N_JOBS",
      	"./waf install"
      ],
      "config-opts": [
      ],
      "sources": [
        {
          "type": "archive",
          "url": "https://github.com/jackaudio/jack2/archive/v1.9.16.tar.gz",
          "sha256": "e176d04de94dcaa3f9d32ca1825091e1b938783a78c84e7466abd06af7637d37"
        }
      ]
    },
    {
      "name": "jamulus",
      "buildsystem": "qmake",
      "config-opts": [
      ],
      "sources": [
        {
          "type": "archive",
          "url": "https://github.com/corrados/jamulus/archive/r3_6_2.tar.gz",
          "sha256": "6bea992f0e4b6a9d08104f8ad9d42b630d523da258e201f70418cecda1c11dac"
        }
      ]
    }
  ]
}
```

It's the flatpak manifest needed to build Jamulus. You can save it as `io.jamulus.Jamulus.json`
Then:
```sh
# To build and install
flatpak-builder build io.jamulus.Jamulus.json --force-clean --install --user
# To run, just click on the icon, or run this command
flatpak run io.jamulus.Jamulus
```

The program compiles (and opens) without issues, but I can't test if it actually works, because I don't have `jack` installed and my sound card isn't working at the moment.

If you need to change some things in the file, take a look at the flatpak of Musescore, because some dependencies are similar (qt, jack...) : https://github.com/flathub/org.musescore.MuseScore/blob/master/org.musescore.MuseScore.yaml

**Comment by 38github** [comment]
ranfdev: If this working and will be the foundation for providing easy distro agnostic installations of Jamulus then I could kiss you!

**Comment by corrados** [comment]
Thanks, ranfdev. @ann0see Is it possible to include this in the Github auto-generation which you recently implemented for the Debian packages?

**Comment by corrados** [comment]
The Pull Request is merge. Can you close this Issue then?

**Comment by ann0see** [comment]
The GitHub action seems to fail.

Also should we should follow the official Flathub process: https://github.com/flathub/flathub/wiki/App-Submission

**Comment by 38github** [comment]
I built the flatpak but when I started it and had already started jack I recieved the following:

```
flatpak run io.jamulus.Jamulus
Gtk-Message: 12:51:34.332: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:51:34.373: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:51:34.374: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

I also got the Jamulus window that says that it can't open because JACK is not started. I have read that Flatpaks don't work well with JACK which is a shame. Maybe an AppImage is a better solution until Flatpak and JACK works flawlessly?

**Comment by corrados** [comment]
If the Flatpak does not work as expected, I should remove it from the repo for now. Do you agree?

**Comment by 38github** [comment]
https://github.com/flatpak/flatpak/issues/1509#issuecomment-751475728

This comment has some information about how to make JACK work with pipewire. Is this something you can help us with, @ranfdev ?

**Comment by ranfdev** [comment]
> Is this something you can help us with, @ranfdev ?
I'll take a look and send another pull request with the changes, if anything improves.

**Comment by ranfdev** [comment]
> The GitHub action seems to fail.

I don't know, in my fork the action works fine.

**Comment by ann0see** [comment]
@corrados I think you might need to select the actions you want to allow on this repo.

**Comment by corrados** [comment]
I have enabled all Actions now. So it should work now (hopefully).

**Comment by corrados** [comment]
BTW, if we now have some Actions experts here, how about supporting this for Jamulus: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository (see also this https://github.blog/2020-09-30-code-scanning-is-now-available/ and this https://github.com/corrados/jamulus/issues/593).

**Comment by 38github** [comment]
Interesting... In Tumbleweed, if I install the package `pipewire-modules-jack-override` Jamulus shows up in the graph of Qjackctl. If I start VLC with JACK output I can connect it to Jamulus and in Jamulus I can see that it recieves sound. The problem though is that Qjackctl does not give me a soundcard sinc to connect the sound so that I can hear it coming out of my soundcard.

**Comment by Yajo** [comment]
I see some PRs have been merged already. This is awesome, in these pandemic times to make jamulus easily available to more people! 🎸

Is this published anywhere, to test the build? Are there instructions on how to make it work? (deal with host-installed JACK, pipewire and all that stuff...). Also, (and this is maybe a stupid question) would it be possible to add a secondary launch option to the desktop icon that boots jamulus with `--server`?

**Comment by 38github** [comment]
An update: In Fedora 33 by replacing Pulseaudio with Pipewire I can now use a normally compiled Jamulus (rpm) with `PIPEWIRE_LATENCY=64/48000 jamulus` and it shows up in Qjackctl. I will Flatpak compile Jamulus and try that too!

**Comment by 38github** [comment]
It works! In Fedora 33 by replacing Pulseaudio (a lot of hassle) with Pipewire I now got Jamulus working with Qjackctl and everything! I did not use the nightly Pipewire repo but the main repo packages. Fired up Jamulus with "pw-jack flatpak run io.jamulus.Jamulus" and opened Qjackctl and connected to Jack and everythign I expected and wanted is was there.

I am glad I asked for help on bulding this on flatpak.org. Thank you @LeandroStanger, @ranfdev, @corrados and @ann0see !

**Comment by corrados** [comment]
Since we have the Github Action for Flatpak creation merge to the Jamulus Git repo, shouldn't we close this Issue now?

**Comment by ann0see** [comment]
Is the flatpack on flathub? I couldn't find it. I think it should be added there. Afterwards this issue is solved.

**Comment by 38github** [comment]
> Is the flatpack on flathub? I couldn't find it. I think it should be added there. Afterwards this issue is solved.

No, unfortunately.

**Comment by ann0see** [comment]
Somebody should try to add it there. I don't know how to do it unfortunately and don't want to maintain it. What we could do is to integrate it in the auto build #854

**Comment by ann0see** [comment]
I see somebody opened a forum post here: https://discourse.flathub.org/t/jamulus-online-jamming-for-musicians/1024

The github action can build the file but unfortunately I couldn't install it on my debian 10 VM: https://github.com/ann0see/jamulus/releases/download/patch-2/io.jamulus.Jamulus.flatpack

If the release is gone see this zip file:
[io.jamulus.Jamulus.zip](https://github.com/corrados/jamulus/files/5838869/io.jamulus.Jamulus.zip)

**Comment by Yajo** [comment]
Are there strong reasons to not maintaining the build in flathub? 🤔  Don't get me wrong, I'm curious.

I see that [app submission](https://github.com/flathub/flathub/wiki/App-Submission) is quite easy. I've done it in the past actually, for other app, withouth prior flatpak knowledge, and all is easy and pretty well documented.

Quoting from that page:

> **Flathub is primarily intended as a service that is used by app developers to distribute their apps**. Our goal is to give developers control of their apps and to allow them a closer relationship with their users without middlemen getting in the way. However, as part of setting up Flathub, some applications are being distributed on Flathub without the involvement of their developers. **We would prefer that these applications are controlled by their authors**.

So, it seems they want flathub to not be a burden to an app devs, but a helper.

Flathub provides a lot of commodities for flatpak maintenance, including in-PR easy-to-test builds, a bot that watches for new releases upstream, a beta channel, and of course a multi-distro repo with a huge user base that would get updates automatically. One random recent example can be seen in https://github.com/flathub/com.mojang.Minecraft/pull/73, and [this post](https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/) has some better explanation.

So, AFAICS, the burden vs. benefit of having the flatpak build here or in flathub, IMHO, favors flathub as the right tool for the job.

**Comment by ann0see** [comment]
I don't use flathub/flatpak but I don't see any problems if somebody else maintains it.

**Comment by ann0see** [comment]
@Yajo can you maintain it?

**Comment by Yajo** [comment]
Thanks for the offer. I'd love to, but TBH right now I'm the main maintainer of [Copier](https://copier.readthedocs.io/) and it takes about 100% of my "FLOSS maintenance time". I'm sorry to say that I wouldn't be realistically able to maintain it. 😞

**Comment by ann0see** [comment]
Any updates on this? I think the only thing which is missing at the moment is the maintainer.

**Comment by gnafuthegreat** [comment]
I'd just like to chime in and say a) the flatpak @ann0see published appears to work well for me on Fedora 33 with pipewire-jack-audio-connection-kit installed (which replaces JACK and will be the default in Fedora 34) and b) I'd love to see this get into Flathub so more folks can use it!  Especially on Fedora where it's not currently available in the official or RPM Fusion repos, I think having it on Flathub and having it "just work" with PipeWire would be great.

It does look like Flathub prefers an application's author(s) be involved in getting it onto Flathub, but it's not explicitly required.  I don't know if I feel comfortable throwing my hat in the ring to help maintain the Flathub build, but I'm happy to test it!

**Comment by joao-p-marques** [comment]
Hi :wave: @ann0see I'd like to try and take the current work and port it to Flathub.

**Comment by ann0see** [comment]
Great!

**Comment by joao-p-marques** [comment]
I'll try to do some testing in the next few days and report back here 🙂

**Comment by joao-p-marques** [comment]
I have submitted the PR for adding the app to Flathub in the link mentioned above. 

I tested locally and I am able to access the audio devices from the flatpak and connect to servers. 

If it is accepted, I will add some documentation on how to set up `pipewire` and use the app.

**Comment by ann0see** [comment]
It seems as if this can be closed: https://github.com/flathub/flathub/pull/2101
