### ISSUE TITLE
Debain build script version output doesn't reflect package version.

### ISSUE THREAD

**Issue by 38github** [jamulussoftware/jamulus#804]
I downloaded the latest tarball of 3.6.2 and compiled it in Debian 10/Buster using the shell scripts but the resulting deb filez were named 3.5.10git even though I changed version in the control file.

Is this something that can be easily changed so that the compilation detects the version that I being compiled for any downloaded version?

**Comment by ann0see** [comment]
I think the problem is in the changelog file.

**Comment by ann0see** [comment]
can you try the debian autobuild script?

**Comment by 38github** [comment]
ann0see: I will try it out but I can't really say when, unfortunately.

**Comment by ann0see** [comment]
Any updates here?

**Comment by 38github** [comment]
I am sorry but I haven't tested it. Maybe it is best to close this issue since I haven't participated in testing.

**Comment by ann0see** [comment]
Ok. I think these packaging scripts must also be updated to some extent. But that's another todo.
