### ISSUE TITLE
WinGet pkg

### ISSUE THREAD

**Issue by brandonaut** [jamulussoftware/jamulus#805]
I'd like to add Jamulus to [WinGet](https://docs.microsoft.com/en-us/windows/package-manager/winget/), to make Windows installs/updates easier. I've started a WinGet manifest file [here](https://github.com/brandonaut/winget-pkgs/blob/jamulus/manifests/Jamulus/Jamulus/3.6.2.yaml), but I'm not sure what to fill in for some of the fields. In particular:

1. Who should be listed as the publisher? (`Jamulus`? `corrados`? `Volker Fischer`? `llcon`? Something else?)
2. What is the license type of Jamulus? I don't see one listed in the repo.

Any other feedback on the manifest is welcome.

**Comment by ann0see** [comment]
Great news. I hope the smartscreen warning doesn't block it https://getimageview.net/2020/06/02/microsoft-defender-smartscreen-is-hurting-independent-developers/

**Comment by DavidSavinkoff** [comment]
Jamulus should make the following link readily available to anyone curious:
https://sourceforge.net/projects/llcon/files/Jamulus/
People will, then, use and trust Jamulus sooner or later or live without. md5sums should be made available also.

**Comment by gilgongo** [comment]
> What is the license type of Jamulus? I don't see one listed in the repo.

It's shown on the [Github "about" panel](https://github.com/corrados/jamulus) and mentioned at top of the readme.md.

**Comment by corrados** [comment]
> Who should be listed as the publisher? (Jamulus? corrados? Volker Fischer? llcon? Something else?)

Good question. What are the other open source projects using? Full names or account names or something else?

**Comment by DavidSavinkoff** [comment]
IANAL, but It is important to be unambiguous as to ownership.
Thus, Jamulus is copyrighted by Volker Fischer and others as seen in the 'Jamulus :: Help :: About' menu.
The GPL v2 and copyright estabilsh ownership. I don't know if the 'publisher' is a necessary placeholder, but it should probably refer to the Owners (persons in this case) or be a blank placeholder (N/A if necessary).

Jamulus
Copyright (c) 2005-2021 Volker Fischer and others.

**Comment by corrados** [comment]
What is the status of this Issue? Any updates?

**Comment by brandonaut** [comment]
Sorry for the silence. I need to get permission from my employer so I can sign the CLA.

**Comment by ann0see** [comment]
Any updates here?

**Comment by brandonaut** [comment]
Sorry, no updates yet. Still waiting to get permission from my employer. Someone else may want to take this up instead...

**Comment by ann0see** [comment]
Thanks for your update. That's a pitty.

**Comment by ann0see** [comment]
Small Update: Jamulus is on WinGet now.
