### ISSUE TITLE
Automated github builds

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulus#854]
Hi,

the CI automation is reworked as part of #853 and #835  (<< notice the numbers? nice coincidence)

My supposed way of handling releases is this:
- Release-Tags: all tags starting with an "r" are built and released with their version number (from .pro file)
- Release-Latest: the tag "latest" is built, too (when moved to a new release)
- Pre-Releases: all branches are built on push, and released with their name marked as "prerelease". If that is too much build time, it could be restricted to the master branch.

Whenever a tag/branch is moved, the old release for that name is replaced. Since the release-tags "rx_x_x" stay, they

Driving thoughts:
- simple flow in automation (one flow, one task. Not mixing release & latest)
- automated builds of intermediate development acessible to non-building users

@corrados is that acceptable?
@corrados do you need the "latest" files to have the "latest" filenames?
@corrados  shall pull-requests also build (Pre-Release)?

**Comment by nefarius2001** [comment]
by the way, why is there a "git" at the end of the VERSION in .pro file?

**Comment by nefarius2001** [comment]
look at my repo for an idea of how the result looks like:

all Releases (& Tags): https://github.com/nefarius2001/jamulus/releases
"latest" release always available with this URL: https://github.com/nefarius2001/jamulus/releases/tag/releasetag%2Flatest

**Comment by corrados** [comment]
In the past there were no nightly builds for Jamulus. The binaries were only on Sourceforge if I made an official release.

The "git" at the end of the version number shows that this is not an official version but a developer version.

I would prefer to have control over the versions which are generated. At least I would do some basic tests before a version is publicly available. So, an official release version and an official beta version is sufficient in my opinion.

If the script searches for an "r" at the beginning of a tag, I could do both, a release and a beta version. For a release, I would use a tag like "r3_6_2". For a beta version I would use a tag like "r3_6_2_beta3". That would be me preferred way of doing it.

**Comment by pljones** [comment]
Ideally testing should be automated, too.

**Comment by nefarius2001** [comment]
I totally agree to make only releases manually available via website & sourceforge. 

In my opinion automated building is a step to better quality, since you immediately notice breaking builds.

On the other hand, developers who come to GitHub and have access to the repo can build any version themselves. You want those people to test as much as possible. 
 What is the benefit of making it difficult for those? What downsides are you expecting? That inexperienced users accidentally download experimental versions and are unsatisfied with Jamulus as a product?

**Comment by corrados** [comment]
> For a beta version I would use a tag like "r3_6_2_beta3".

BTW: This does not work since it starts with an "r" and would initiate a release process with moving latest tag, etc. So we would need a special tag beginning for beta releases.

> In my opinion automated building is a step to better quality, since you immediately notice breaking builds.

We have this already on the Github Jamulus homepage:
![grafik](https://user-images.githubusercontent.com/46655886/104936308-a3115080-59ac-11eb-8a1c-32e6e344dc85.png)
BTW, I just noticed that it failed. @ann0see, can you please check why it fails? It looks like the Windows build does not work.

> You want those people to test as much as possible. What is the benefit of making it difficult for those? What downsides are you expecting?

If you automatically create new deploy binaries for each Git commit, I think this is a waste of resources. My personal opinion is that it is better if I decide when it is a good point in time to create a beta version. This can also be on request, of course.

**Comment by ann0see** [comment]
>  It looks like the Windows build does not work.

Yes. The PR was already merged by you. It should work now. I think you have to use a Qt account to login in Travis Ci?

**Comment by corrados** [comment]
Maybe we don't need Travis anymore. As far as I understood, the CodeQL also compiles for all OSs. The only thing which Travis does additionally is that it compiles normal and headless in Linux. Does the CodeQL does something similar?

**Comment by ann0see** [comment]
>  Does the CodeQL does something similar?

No. I don't think so.

**Comment by pljones** [comment]
> Does the CodeQL does something similar?

Not currently.  With less code, there's less to go wrong, so I took the view not to do that.  It is, of course, possible to extend what gets built.

I'll say it here, too - we need to standardise across the workflows: (a) generate the executable for each os and architecture; (b) each subsequent workflow step: (b1) code quality, (b2) test, (b3) executable vulnerability test; (c) anything else like packaging. So (a) is common, (b) happens on each pull request (ideally b1 and perhaps b2 on each commit), with (c) depending on what's being done.

**Comment by nefarius2001** [comment]
I would also strongly prefer to have the build steps not code-duplicated in two separate files.
Is there a reason the flatpack is treated separately?

> If you automatically create new deploy binaries for each Git commit, I think this is a waste of resources. 

When building and vulnerability-checking are standard anyway, the only additional step/resource I request is storing the results publicly available. Not for every commit, but only for branch-heads and release-tags.

**Comment by ann0see** [comment]
> Is there a reason the flatpack is treated separately?

No. Flatpack was written by someone else. Probably we can add it to your changes.

**Comment by ann0see** [comment]
I want to add this: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions

I think we should also have a look at securing our actions.

**Comment by ann0see** [comment]
I think we should clarify how these automated GH builds work:
See:
https://github.com/nefarius2001/jamulus/pull/4#issuecomment-764967633

**Comment by ann0see** [comment]
Not adding the latest tag automatically has a few advantages: 
Corrados could set the release tag and let GH Actions build all the binaries. If everything works, he also sets the latest tag which would then start the final build (these binaries would then be uploaded to sourceforge. Since the binaries of the latest tag would always be accessible via the same link, this would allow convenient download via GitHub too. Two mirrors are always better than one.)

**Comment by nefarius2001** [comment]
> If you automatically create new deploy binaries for each Git commit, I think this is a waste of resources. 

@corrados are you worried about disk space, computation time or something different?

**Comment by corrados** [comment]
If this process is finished, we'll have Jamulus binaries on Sourceforge and also on Github. But if we have so many binaries, users might get confused what to download. And yes, I am a bit worried about disk space and computation time. But it seems nobody cares about such things nowadays...

**Comment by ann0see** [comment]
> But if we have so many binaries, users might get confused what to download.

Not necessarily. If we don't actively show the GitHub releases page but e.g. only link the binary URL to GitHub on jamulus.io they would never see this page. I'd link the "latest" link on jamulus.io so that users don't have the feeling that they switched the Page. Furthermore we could add a (non prominent) link to sorceforge named "Mirror 2 (SourceForge)". Two mirrors are better as we know from the excessive downtime from Qt.

**Comment by corrados** [comment]
I think we have new reached a point where this: https://github.com/corrados/jamulus/issues/475 is getting relevant. Could you implement this for your automated builds? We should discuss the final version numbering in the referenced issue.

**Comment by nefarius2001** [comment]
Environment is a good argument.
Maybe a weekly build of master only? Or on pull requests?

**Comment by pljones** [comment]
> What are the benefits of sourceforge as a download mirror? They provide some rankings and visibility, I guess?

Facebook's spam detector blocked me posting a link there...

**Comment by ann0see** [comment]
> What are the benefits of sourceforge as a download mirror?

Pro:
Statistics and multiple mirrors
Con:

Bad reputation for some people (there's an issue somewhere).

**Comment by pljones** [comment]
Are there other content delivery networks for open source projects with a decent reputation - i.e. that aren't going to get blocked because they allow spammy / malware content?

**Comment by nefarius2001** [comment]
`    # download artifact
    - uses:                       actions/download-artifact@v2
      with:
        name:                     io.jamulus.Jamulus
        path:                     ~/io.jamulus.Jamulus
        retention-days:           14`
        
I found a compromise:
The artifacts of a job can saved for a defined retention time (=> finite, small amount of disk space necessary)
Building is part of CodeQL anyway, if it is possible I would like to combine those two workflows. (=> no extra computation)

**Comment by pljones** [comment]
> The artifacts of a job can saved for a defined retention time (=> finite, small amount of disk space necessary)
> Building is part of CodeQL anyway, if it is possible I would like to combine those two workflows. (=> no extra computation)

So we'd run through to the end of CodeQL to get the artifact to be packaged up, then pass that through to the packaging workflow, if it gets triggered - or else it would expire.

I wonder if there is any way to make sure the packaging workflow only triggers after the CodeQL workflow, so it can use the provided artifact.  That is, can one workflow trigger another when certain conditions are met?

**Comment by ann0see** [comment]
Yes, See: https://github.com/corrados/jamulus/blob/11e775bacc407fa19ee55ab715dbe4004569fd1a/.github/workflows/autobuild.yml#L63

**Comment by pljones** [comment]
Can that be done between files - could `create_release` be in a separate file from `autobuild.yml`?

I don't like files that just get bigger and bigger and more complex to maintain.  Keeping discrete operations separate makes it less likely one change will cause unexpected "damage" to something it wasn't intended to touch.

**Comment by ann0see** [comment]
> I don't like files that just get bigger and bigger and more complex to maintain

Me neither. I couldn't get this to work (I tried it).

**Comment by pljones** [comment]
Probably need to do something like this:
https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

... though I'm still unsure exactly how.

**Comment by pljones** [comment]
https://docs.github.com/en/actions/creating-actions/about-actions

> A composite run steps action allows you to combine multiple workflow run steps within one action. For example, you can use this feature to bundle together multiple run commands into an action, and then have a workflow that executes the bundled commands a single step using that action. To see an example, check out "Creating a composite run steps action".

**Comment by nefarius2001** [comment]
I like dividing, too. Though those are dependant anyway, so I see them separated enough by sections in one file.
i think different names are possible, but I'm still at "make it work" :)

**Comment by ann0see** [comment]
Just thinking of a release script:

./release.sh r3_6_3

```bash
#!/bin/bash

editor ChangeLog
editor Jamulus.pro
git add ChangeLog Jamulus.pro
git commit -m "${1}"
git push
git tag "${1}"
git push origin "${1}"
# Create latest release
echo "Moving latest tag to current commit..."
git tag -d latest
git push --delete origin latest
git tag latest
git push origin latest
```
This should make releasing on Linux quite easy. I hope, I've included all needed commands.

**Comment by ann0see** [comment]
@nefarius2001 If you need help, please ping me. I will unsubscribe a few issues including this one.

**Comment by hoffie** [comment]
@nefarius2001 Now that #978 is merged, would this already cover the scope of this issue so it could be closed?
I think there were some further ideas regarding additions/optimizations (release script?), but it might make sense to spec them as individual tickets?

BTW: This is *really* cool. Being able to build new releases for all platforms quickly is such a great thing for testing out new stuff! :)

**Comment by gilgongo** [comment]
Closing off now. Any related stuff can be raised as separate issues.
