### ISSUE TITLE
Automated Android-APK for multiple platforms

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulus#857]
@ann0see reported for the APK not to work on his Intel Processor
https://github.com/corrados/jamulus/issues/835#issuecomment-761681511
https://github.com/corrados/jamulus/issues/835#issuecomment-761748926

Target:
- find out on which platforms / processor types the APK is working
- add missing ones
- make a realease-build, not debug-build

**Comment by ann0see** [comment]
Maybe the problem also was due to an old version of Android (4.4.4). Can anyone else confirm my issue?

**Comment by ann0see** [comment]
I just ran the apk which was generated from my release in an Android for intel VM and it crashed "Jamulus keeps stopping" error message.

**Comment by nefarius2001** [comment]
> Why is this a debug .apk? Would it also be possible to use a release apk or is this just for building during normal PR runs?

found during review of #978
