### ISSUE TITLE
About hosting nsProcess.dll binary

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#859]
https://github.com/corrados/jamulus/pull/841#issuecomment-761888194

Was merged now and should work correctly. However we currently get nsProcess.dll from a forum post which is clearly not the right way to do it. If we can host this file ourselves, this would be great.

**Comment by corrados** [comment]
Is it possible to auto detect the Qt version installed in C:\Qt (i.e., auto set the `[string] $QtInstallPath = "C:\Qt\5.15.1"`)?

**Comment by ann0see** [comment]
Via Qt5_Dir this should be possible but at least the GitHub action I used broke Jamulus on 64Bit Windows 10.

**Comment by ann0see** [comment]
I've now created a new repo in the jamulussoftware organisation called assets. We could upload the file there. But is this really needed? I assume this plugin could be licensed under a free license but we can't be 100% sure.

**Comment by corrados** [comment]
I would not do that. What's wrong about a link to the forum post? The initial post if from 2005. So, the old link lasted about 15 years on the same place. Qt has changed their URL more than once in that period of time ;-).

**Comment by ann0see** [comment]
Yeah. But there are a few issues with that:

1. The forum is not secured (no https --> this is not acceptable at least for me)
2. We shouldn't just use the forum as "hosting" service

**Comment by hoffie** [comment]
> The forum is not secured (no https --> this is not acceptable at least for me)

The missing authentication due to this could be somehow mitigated by including a checksum (sha256 or something) in the installer and verifying it after the download. This would imply additional complexity, of course.

> We shouldn't just use the forum as "hosting" service

I agree. With Jamulus becoming more and more popular (which is great!), installation numbers will rise and place load on such third party services, which may be a problem especially when they are not optimized for this (e.g. a download through a forum/php application).

**Comment by ann0see** [comment]
Yes. We could use a checksum.

Luckily we don't need to download this file on every install (only during compile time we need it). Nevertheless it's not optimal to do it as we do currently. How can we clarify the license of this file? Talk to the creator(s)? I doubt we get an answer in this thread.

**Comment by ann0see** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7.1

I think this might be something we could use.

**Comment by ann0see** [comment]
I got an answer now: http://forums.winamp.com/showpost.php?p=3200634&postcount=68

I think we can then avoid to download it from the forum and descide how to process.

**Comment by mirabilos** [comment]
ann0see dixit:

>Tagging @hoffie and @mirabilos here: What do you think?

Huh? What do I have to do with this? If I see a .dll file,
I will remove it, like any other precompiled binaries, for
Debian packaging.

**Comment by ann0see** [comment]
That’s good to hear. I think there was a discussion that adding this file might have prevented integration in a distribution. 

Thanks for this answer!

**Comment by mirabilos** [comment]
ann0see dixit:

>That’s good to hear. I think there was a discussion that adding this
>file might have prevented integration in a distribution.

Ah okay. Well, it’ll normally do, and you probably should include
the full source code, ideally also build it yourself, but in Debian
I can tell it files and subdirectories to exclude (and already do
so for e.g. the binary *.qm files) so no worry.

**Comment by hoffie** [comment]
> Tagging @hoffie and @mirabilos here: What do you think?

It seems small (20kb), the source seems included so one could think about vendoring it directly in the Git repo similar to libopus. If one wants to avoid binary files within git, one could try building it from source (I have zero experience with this on Windows) or could place it somewhere else which is designed for downloads (e.g. some internal jaumulus.io address). Besides that, I do'nt know what to reply either? :)

**Comment by ann0see** [comment]
Yes. The question is what we should do with this file:

1. Host it e.g. on assets.jamulus.io (would be easy but maybe not necessary)
2. Host it in this repo (this was already the case but as far as I followed the discussion, compiled binaries are not wanted and compiling it on every run/release is not needed)
3. Download it from the forum post (I don't like this idea)

**Comment by mirabilos** [comment]
ann0see dixit:

> compiling it on every run/release is not needed)

Why not?

You’re compiling Windows binaries anyway. You’ll be needing it
only there. So you’d just be compiling one more thing, which,
compared with the rest, is done super-quick. You’d be gaining
full (source-level) control over shipped binaries even.

**Comment by ann0see** [comment]
Hmm. That’s a good argument. So we‘d use a git submodule with the code of this dll compile it before the installer gets made —> problem solved?

**Comment by mirabilos** [comment]
ann0see dixit:

>Hmm. That’s a good argument. So we‘d use a git submodule with the code
>of this dll compile it before the installer gets made —> problem
>solved?

I’d personally do it like this but with subtree-merging, because
I hate git submodules ;) but yeah that is what I’d do were I in
that position. Of course, it’s not my call, you can do it differently…

**Comment by ann0see** [comment]
I didn't work with submodules yet ;-). So I'm open to everything.

**Comment by mirabilos** [comment]
ann0see dixit:

>I didn't work with submodules yet ;-). So I'm open to everything. 

Be very, very careful.

If you decide to go with subtrees, I’ve updated a writeup about these:
http://www.mirbsd.org/permalinks/wlog-10_e20161220-tg.htm

Subtree merging is basically, you’re importing the source code of
that DLL into the repository directly, but with all history intact.

Good luck either way,
//mirabilos
-- 
<ch> you introduced a merge commit        │<mika> % g rebase -i HEAD^^
<mika> sorry, no idea and rebasing just fscked │<mika> Segmentation
<ch> should have cloned into a clean repo      │  fault (core dumped)
<ch> if I rebase that now, it's really ugh     │<mika:#grml> wuahhhhhh

**Comment by ann0see** [comment]
As far as I understand, there is no git repo yet. Also the visual studio project is outdated.

**Comment by mirabilos** [comment]
ann0see dixit:

>As far as I understand, there is no git repo yet. Also the visual studio project is outdated.

Then you can’t do a submodule ;-)

Just import it by putting it into a new subdirectory and 'git add' that.

**Comment by ann0see** [comment]
Yes. That's maybe the easiest solution. Just trying to update the project file and I will then move the Source, Include and Readme.txt folders/files to windows/nsProcess
