### ISSUE TITLE
Channel Levels Improvement

### ISSUE THREAD

**Issue by nicolopozzato** [jamulussoftware/jamulus#86]
It's very interesting to be able to see almost in real time the level that each user sends to the server.

I think of three improvements:

1) At the moment my input LEDs are 1/2 notches higher than the LEDs that I see lit on the "mixer" and this problem occurs especially with the voice. I often speak and even if I send with the very high volume the LEDs on the mixer do not update so often. (this I think is a problem of data communication from the server, maybe it averages the values? it should send the audio peak value...)

2) could the led series be transformed into a bar? I mean a vertical bar that shows the current level, the rms, and the peak value (usually of the last moments) (this would be very interesting, perhaps with a more "updated" graphics but I think it's a bit more work having to create the bar from scratch)

3) Add either a second bar or a quick toggle button to display the server values ​​in the level bar on the mixer (as it does now) or display the values ​​relating to what I hear on the headphones (therefore mirroring the volumes set on the mixer) (this would immediately help to see the highest or the lowest users not compared to the server but to the current mix that I hear on headphones (if a person is mute I don't have to see any signal, if I select "solo" I have to see only their signal based on how I have the faders in the mixer)) (maybe and option to have the two bar one near the other or to have the toggle button)

I hope I explained myself.

**Comment by corrados** [comment]
1. This is a design decision. The level at the server is only checked in intervals to keep the CPU usage as low as possible. Therefore you miss the high peaks which the local input level meter will pick up. Therefore the level at the faders is usually a bit lower. But the intention for the fader meters was to see who is active and if a musician is heavily overloaded. The initial idea was just to add one LED for that but we decided to put an LED bar in. But it is not meant to be a super exact indicator.

2. There is already an Issue for that: https://github.com/corrados/jamulus/issues/73

3. This would be a very low priority feature. The current LED bars are intended for showing the actual input level. This is the important information. Having displayed the post fader level is nice to have in my opinion.

**Comment by corrados** [comment]
The only remaining feature request in this Issue is a post fader level meter. I actually do not see a real use case of this. If anybody wants to keep this Issue open, please write a message. Otherwise, I'll close this Issue sometime in the future.
