### ISSUE TITLE
Windows installer doesn't build correctly in a path with spaces

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#864]
#841 Sorry for opening another installer issue.

This is low priority at the moment.

If you build the Windows Installer in a path containing spaces, the resulting installer creates folders in $INSTDIR which relate to the folder where the installer was built. So e.g. if your build is in "C:\Users\My User\jamulus", the installer creates a folder in $INSTDIR which look like this: "$INSTDIR\C\Users\My" 

I think the problem is related to quoting in CMD. At the time of writing this, the error can be traced back to this + a few lines after: https://github.com/corrados/jamulus/blob/1ce54ba0566c9064939f88ea13f35999cb97ae61/windows/installer.nsi#L138
see commit 6aa10d6 if the line changed.

Maybe we could execute this line in PowerShell which allows better quoting?

**Comment by henkdegroot** [comment]
@ann0see I have been looking into this issue today and believe I have a fix for this. The issue actually is not quoting related, however it is due to the "for" function used to generate the folder names. The function "cuts off" due to the space in the path.
The following change resolved the installer issue on my system:

File to be update: **installer.nsi**

Current statement in the file at line 122:
    !system 'cmd.exe /v /c "for /f "usebackq" %d in (`dir /b /s /ad "${prefix}"`) do \

Should be update to:
    !system 'cmd.exe /v /c "for /f "usebackq delims=" %d in (`dir /b /s /ad "${prefix}"`) do \

The delims= option for the for instruction will replace the default delimiters (space and tab) with nothing.

Perhaps you can test/verify this and update the office code?

**Comment by ann0see** [comment]
Great! I didn't have time to check it yet, but could you please open a pull request which contains your suggested fix?

**Comment by henkdegroot** [comment]
@ann0see just did the pull request....first time here, so hope it meets the standards. 
Will this issue be linked to the PR automatic or should I do that somewhere?

**Comment by ann0see** [comment]
I can link it for you. It can be done automatically if you type fixes: #864

**Comment by henkdegroot** [comment]
Should I have added that "fixes" in the PR? If so, can I still update that?

**Comment by ann0see** [comment]
No. I already linked this issue for you. Thanks for doing this!

**Comment by henkdegroot** [comment]
@ann0see thank you ! Now while doing more checks, I found the installer works fine now...but the uninstall is not. This will require a similar fix. Should a new issue be opened for that or can I just do another PR to add to this issue?

Sorry for all the question...just want to make I am doing it correct.

**Comment by ann0see** [comment]
No problem. I'd prefer you include it in the Pull Request you just opened.

**Comment by henkdegroot** [comment]
Okay, performing checks now if the same fix works before adding to the PR

**Comment by henkdegroot** [comment]
Seems to work fine, so PR has been updated. Though when I commited local I did not add --amend. Still looks good to me in the PR. Hope my first contribution will not be my last.

**Comment by ann0see** [comment]
You can still amend it and do a force push

**Comment by ann0see** [comment]
Yes. It is. Just remove the warning from the page (release branch; every language) if possible
