### ISSUE TITLE
Jamulus process doesn't get killed if you select a device with wrong sample rate (ASIO4ALL)

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#872]
I think some if not all read cross errors in ASIO4ALL are related to an application competing with Jamulus. This lead me to the thought that Jamulus itself might be the problem sometimes. Inexperienced users will probably try Jamulus with ASIO4ALL by trial and error. 

Now my bug report:

Steps to reproduce:
0. Make sure only ASIO4ALL is installed on your PC
1. Select a device which doesn't support 48kHz in ASIO4ALL (I chose an output device) and the devices which work
2. Wait for the "No usable ASIO driver found... do you want to open the driver settings" warning
2. Click on yes and unselect the wrong device
3. Click on the warning which asks you if you configured your device correctly and click on yes
4. See the warning "Jamulus could not be started because of audio interface issues" (this shouldn't come up if you chose the correct devices!)
5. Click on quit
6. Open the Task manager (this will show you that a Jamulus process (at least as background process) is still running)
7. Open Jamulus. Sometimes (not always) ASIO4ALL now shows a red cross which disallows you to select the correct input/output device. (I think you have to unselect the working device to experience this issue).

To solve this problem, you have to find the non working Jamulus process in the Windows Taskmanager and kill it.

**Comment by npostavs** [comment]
Oh, I forgot to actually comment here. I think #1325 might fix this, but please test it because I'm not able to use ASIO4ALL to reproduce the problem.
