### ISSUE TITLE
Overall Turnaround MS

### ISSUE THREAD

**Issue by AndyMcProducer** [jamulussoftware/jamulus#877]
Hiya, what shoudl or what can the overall ms be when connected to local host?
Even at 32buffers I'm getting 16 to 20ms.

Anyone have some info or tweaks to share on this?

**Comment by pljones** [comment]
The best place to start: https://jamulus.io/wiki/Getting-Started

**Comment by AndyMcProducer** [comment]
Ping to local host is 0 to 1ms but turnaround is 16ms. So this pushes towards 40ms and over sometimes.

**Comment by ann0see** [comment]
Which OS are you using? Do you use an audio interface? If yes which one?

**Comment by gene96817** [comment]
I am seeing pings 0-3 ms and an overall delay of 10-13ms (with the shortest buffer).

**Comment by gene96817** [comment]
for my case, MacOSss 11.1, built-in audio, USB mic (Blue Snowball).

**Comment by pljones** [comment]
From my upstairs machine, through one switch to the main switch downstairs, then back to the switch where my server(s) live, I get 0ms ping, 10-12ms overall delay.  About the same downstairs (that only has the one switch to go through).  64 samples per buffer on both.  Echo AudioFire4 upstairs, Zoom UAC-2 downstairs.

**Comment by dcorson-ticino-com** [comment]
When the ping time is 0, the overall delay is the time your interface introduces (more or less).  Jitter buffering adds time too, but with ping 0 there will be little or no jitter so that can be ruled out.
There are many audio interfaces that have latencies of 10-12ms, but I have also seen interfaces with much more such as internal audio interfaces.

**Comment by AndyMcProducer** [comment]
I'll try running the server on another machine on the lan here. I got 2 sound devices and both seem to hit around the same, if i turn off auto on the jitter then o can get it down but not tested the sound with it down yet.
