### ISSUE TITLE
Create a consistent set of instrument icons

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#899]
The current instrument icons were either created by different people or downloaded from the internet. They are not consistent and have issues like mentioned in https://github.com/corrados/jamulus/issues/876.

Our designer team should create a consistent set of instrument icons.

**Comment by gilgongo** [comment]
For the curious, we're talking about 50 icons here :-) As icon set challenges go, this is meaty one.

**Comment by Erioldoesdesign** [comment]
This is such a fun issue for any graphic designer, illustrator or visual designer. Mind if I promo it on https://opensourcedesign.net/ ?

**Comment by gilgongo** [comment]
No that should be fine. If anyone else wants to do it too, then we can have a competition :-) BTW could we do the same for a Jamulus skin? I've been trying to get various people I know to have a look at the idea but so far no luck.

**Comment by Erioldoesdesign** [comment]
@gilgongo might also be best to carve up between multiple designers tbh 50 icons is a chonky project!

**Comment by gilgongo** [comment]
Yes, hence my comment about 50 - that's one heck of a lot of icons.

**Comment by ann0see** [comment]
Can you show your work in the linked GitHub discussion? 

I'll close this issue in favor of the discussion.
