### ISSUE TITLE
Move official Jamulus repo to Github Organisation

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#908]
The Jamulus project has become too large to be hosted in a private Github account (i.e. the corrdos-account). It has to be moved to a Github Orgainsation account. We could use the existing https://github.com/jamulussoftware/jamuluswebsite project or create a new one.

Has anybody experience with that? What is with the Issues and Pull requests? Are they moved as well or are they lost by the movement?

Here is the Github help page on that topic: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

Reading in that page, this concerns me:
![grafik](https://user-images.githubusercontent.com/46655886/106160952-ae236800-6186-11eb-89c9-6f58c677f8e8.png)

**Comment by corrados** [comment]
I just created a test project in my private corrados accound and did the transfer to jamulussoftware: https://github.com/jamulussoftware/testprojectformove

That seemed to work. All the issues and pull requests were still there. So that looks good.

@ann0see, @pljones, @gilgongo Should I transfer it now?

**Comment by ann0see** [comment]
For me, this would be ok.

**Comment by corrados** [comment]
One thing I would like to test. @ann0see: I have moved back the test project to my corrados account. Can you please create a fork and two branches and do small changes on both of these branches. Then please create a pull request for one of your branches. After that I'll move the repo again. I would be interested what happens to your branches? I think you have to change to URL of the git repo in your local repo. The question is also what happens to the fork you have created of that test project in your ann0see Github account.

**Comment by corrados** [comment]
I'll also ping all the people who have active pull requests and branches on the repo:
@npostavs, @nefarius2001, @storeilly, @hoffie, @dcorson-ticino-com, @genesisproject2020, @dingodoppelt
Because it might be that they have to change the URL of the repo, too.

**Comment by ann0see** [comment]
I hope I did this right?

**Comment by corrados** [comment]
Great, thanks. I have now moved the project again. Can you please go to your local repo and try to make a pull without adjusting any path/setting in your repo. I would be interested what error message you see then.

**Comment by ann0see** [comment]
> I think you have to change to URL of the git repo in your local repo

Sorry to say that, but I did the changes via the GitHub UI and didn't clone it locally. But my URL doesn't seem to change so also the local url probably won't change?

**Comment by ann0see** [comment]
If Jamulus is moved, you will also be able to use the teams (including the ability to ping the translators in the translators team). This would make the translation process a lot easier.

**Comment by corrados** [comment]
BTW. if everything fails with the actual jamulus repo, I think it is possible to revert everything, i.e., move it back to corrados.

**Comment by ann0see** [comment]
> of the git repo on your PC

Which one? My fork or your fork?

**Comment by corrados** [comment]
Can you also please create an Issue in that test project, set it to "watch" and other things?

**Comment by corrados** [comment]
> Which one? My fork or your repo?

That is a good question. Maybe do it with both if possible. But I think doing it with the original repo will be more critical.

**Comment by ann0see** [comment]
user@device:/tmp$ git clone https://github.com/corrados/testprojectformove
Klone nach 'testprojectformove' ...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 8), reused 3 (delta 2), pack-reused 0
Entpacke Objekte: 100% (17/17), Fertig.
user@device:/tmp$ mkdir jj
user@device:/tmp$ cd jj
user@device:/tmp/jj$ git clone https://github.com/ann0see/testprojectformove
Klone nach 'testprojectformove' ...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 8), reused 3 (delta 2), pack-reused 0
Entpacke Objekte: 100% (17/17), Fertig.

That's what I did

**Comment by ann0see** [comment]
Ok. Added the stars/watch/...

**Comment by corrados** [comment]
Thanks. The stars and everything looks like to be transferred correctly. Now the interesting part is what you get if you do a pull in both of your clones.

**Comment by ann0see** [comment]
esamt 3 (Delta 0), Wiederverwendet 0 (Delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/jamulussoftware/testprojectformove.git
To https://github.com/corrados/testprojectformove
   8645108..f259ab7  main -> main
That's the output of your repo. But I think pushing works (since I'm an owner of the jamulussoftware organisation)

**Comment by corrados** [comment]
Thanks for testing. Ok, so it seems everything should work fine in theory. So we could do it with the official Jamulus repo now.

I'll wait now for some days to give the other Jamulus developer/contributer the chance to discuss their possible concerns here before I actually do it.

**Comment by ann0see** [comment]
Great. I think the only "problem" would be that me and @gilgongo would become administrators and we need to add @pljones to the organisation

**Comment by ann0see** [comment]
I also had a discussion with mulyaj about project management. The organisation could allow this to be easier (GitHub boards, ...).

What do you think about this?

**Comment by corrados** [comment]
Yes, definitely. But let's do this step-by-step. First step is to move the repo. Other steps will follow. BTW: I have already updated the main developers list: https://github.com/orgs/jamulussoftware/teams/maindevelopers
Additionally, I added @softins to the main developers list since he is a very good programmer and has done a significant contribution to Jamulus. And, he is the developer of the Jamulus Explorer, too.

**Comment by ann0see** [comment]
Yes. Just saw this.

**Comment by corrados** [comment]
After the movement, some links like this one: https://github.com/corrados/jamulus/blob/121a223cd622514778cf73d4c47ecf916c2c04be/src/util.cpp#L483 must be adjusted in the Jamulus source code.

**Comment by DavidSavinkoff** [comment]
I think you should be wary of GitHub. Be Certain that you can have all history of everything that has been done (code and conversation and history). Then be certain that you can host it yourself.

youtube-dl was unjustly attacked this way and suffered permanent consequences.

GitHub WILL trash your account at the whim or whiff of DMCA (or whatever).
GitHub is, thus, an unreliable convenience. Not a repository.

**Comment by corrados** [comment]
Ok, that may be the case. But it does not make any difference if the Jamulus repo is located in my private Github account or in the jamulussoftware organisation Github account. This applies to both.

**Comment by corrados** [comment]
Let's get things done. I'll now initiate the transfer of the jamulus repo to the jamulussoftware. Keep the fingers crossed that everything works as expected :-).

**Comment by corrados** [comment]
> After the movement, some links like this one: [...] must be adjusted in the Jamulus source code.

done

**Comment by dingodoppelt** [comment]
thanks for the ping @corrados :)
i just issued a "git remote remove upstream", then "git remote add upstream https://github.com/jamulussoftware/jamulus" and everything seems to be working as expected.
cheers, nils

**Comment by corrados** [comment]
Thanks for the positive feedback. I was a bit worried about this change but it seems that everything has worked as expected.

**Comment by corrados** [comment]
Since the movement is done, I'll close this Issue now.

**Comment by softins** [comment]
I know this is closed, but this is the first opportunity I've had to comment. Thanks for adding me.

Now the URL for the repo has changed, we need to publicise it to people who might be using it in scripts. I can tell the WorldJam folks. I can also raise a PR for grundic's docker project.

**Comment by corrados** [comment]
> I can tell the WorldJam folks. I can also raise a PR for grundic's docker project.

Thank you!

**Comment by pljones** [comment]
I edited my .git/config files... that worked, too.

OK, so I pulled the latest source and submodules and see one problems in the main repo and more in submodules - mostly in install instructions:
```
android/automated_build/__example__jamulusbuild.sh
tools/jamulus-server-remote/QUICK-INSTALL.md
tools/jamulus-server-remote/README.md
tools/jamulus-docker/Dockerfile
tools/jamulus-docker/README.md
distributions/installscripts/install4fedora.sh
distributions/autobuilddeb/control
distributions/debian/watch
distributions/debian/control
distributions/debian/copyright
```
That ignores all references to `corrados` as a user name.

**Comment by storeilly** [comment]
Thanks for the ping also!

Stephen

**Comment by ann0see** [comment]
This issue is now no longer resolved since @corrados has an own repo. Outdated scripts will now no longer be redirected to jamulussoftware/jamulus.

**Comment by corrados** [comment]
Ups, sorry. I've deleted the corrados/jamulus again.

**Comment by ann0see** [comment]
@corrados 

No problem. We’re currently discussing that the redirect isn’t the best way to solve the issue. 
If we found a better solution we‘ll message you.

In the meantime you could probably fork the repo directly to a different name/account/… 

Tagging
@pljones since he had some opinions on this
