### ISSUE TITLE
Enabled Discussions feature for the Jamulus repo

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#910]
I just enabled the Discussions feature for the Jamulus repo. I saw that there are a lot of support questions here in the Issues tap which should better be posted in the Discussions area.

**Comment by corrados** [comment]
These are basically the Issues which have the label "documentation" applied (as with this Issue, too).

**Comment by ann0see** [comment]
Yes. You're right. We're also using this in the documentation repo. Should I move some?

**Comment by corrados** [comment]
Yes, if you like, then please do so.

**Comment by corrados** [comment]
I guess this Issue is also a candidate to be moved to the new Discussion feature ;-). Let's close this now.
