### ISSUE TITLE
Get rid of fischvolk.de

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#919]
Many years ago, I registered the URL fischvolk.de (which stands for fisch(er)volk(er)) for private stuff. As a quick hack, I have used that URL for the Jamuls software as well. Since Jamulus has become more and more popular, this URL does not look very professional anymore. We now have our own Jamulus URL with jamulus.io. @gilgongo, would it be possible to use that for the Jamulus Central server addresses?

See, e.g., here: https://github.com/corrados/jamulus/blob/bf17b52659e8c5717c9bf4a66942087bc665907d/src/global.h#L99

**Comment by gilgongo** [comment]
I can certainly put them in the jamulus.io zone file. Shall I put them in as CNAMEs or A records? I think A records will resolve slightly faster, but with CNAMEs you'd be able to re-point them from fischvolk.de if you needed to.

**Comment by pljones** [comment]
There's some magic being done somewhere currently for the server lists I host.

**Comment by corrados** [comment]
This is what I have configured right now:
![grafik](https://user-images.githubusercontent.com/46655886/106238610-70175a00-6201-11eb-84d1-ada0504d1b54.png)

**Comment by gilgongo** [comment]
There is perhaps also the question of who should control jamulus.io. 

Right now, I have it registered with hover.com and host the zone file on my own name servers. These are maintained by myself and some others along with a bunch of other domains as part of a server "co-operative". This is for free, basically.

I'm happy to renew the registration for some years, but should @corrados have control of the domain itself (either the DNS or the registration as well)?

I don't know how other open source projects handle this. Is there a concept of shared or escrow domain ownership, for example?

**Comment by pljones** [comment]
Probably the better names from now on for the `drealm.info` ones are `jamuluscentralX.drealm.info` where `X` is the same as the `22X24` `X` port number.  They all resolve to the same IP, of course.

**Comment by corrados** [comment]
> There is perhaps also the question of who should control jamulus.io.

It would be great if you could continue to keep ownership of that URL and also that you manage the port forwardings and DNS entries.

**Comment by corrados** [comment]
Please post here when you have done the DNS entries for the Central Servers so that I can change it in the Jamulus source code.

**Comment by gilgongo** [comment]
> Probably the better names from now on for the drealm.info ones are 

Sorry, I'm not sure what ports you mean. Can you explain?

Looking at what you have [here](https://github.com/jamulussoftware/jamulus/issues/919#issuecomment-769601557) it seems that (for example):

```
jamulusrock.fischvolk.de is an alias for jamuluscentral1.drealm.info.
jamuluscentral1.drealm.info is an alias for peter.drealm.info.
peter.drealm.info has address 81.174.155.168
```

That's maybe a lot of DNS lookups, so I was going to put the following in jamulus.io, based on jamulus/src/global.h (although jamulusanygenre1 isn't listed there):

```
jamulus     IN A 66.113.206.102 # DEFAULT_SERVER_ADDRESS
jamulusanygenre1     IN A  66.113.206.102  # CENTSERV_ANY_GENRE1
jamulusanygenre2     IN A  66.113.204.131  # CENTSERV_ANY_GENRE2 
jamulusanygenre3     IN A  66.113.204.131  # CENTSERV_ANY_GENRE3
jamulusrock      IN A  66.113.206.102  # CENTSERV_GENRE_ROCK
jamulusjazz      IN A  66.113.206.102  # CENTSERV_GENRE_JAZZ
jamulusclassical   IN A  81.174.155.168  # CENTSERV_GENRE_CLASSICAL_FOLK
jamuluschoral   IN A  81.174.155.168  # CENTSERV_GENRE_CHORAL
```

**Comment by corrados** [comment]
I am not sure if you can use an IP number for pljones server. I did use an URL instead.
Please note that the IP addresses of my servers are incorrect. You have to use a 62 at the beginning, not a 66.
The jamulusrock and jamulusjazz are not hosted on my server but on pljones server.

**Comment by corrados** [comment]
So I would say it should be:

```
jamulus               IN A      62.113.206.102                # DEFAULT_SERVER_ADDRESS
jamulusanygenre1      IN A      62.113.206.102                # CENTSERV_ANY_GENRE1
jamulusanygenre2      IN A      62.113.204.131                # CENTSERV_ANY_GENRE2 
jamulusanygenre3      IN A      62.113.204.131                # CENTSERV_ANY_GENRE3
jamulusrock           IN CNAME  jamuluscentral4.drealm.info   # CENTSERV_GENRE_ROCK
jamulusjazz           IN CNAME  jamuluscentral3.drealm.info   # CENTSERV_GENRE_JAZZ
jamulusclassical      IN CNAME  jamuluscentral5.drealm.info   # CENTSERV_GENRE_CLASSICAL_FOLK
jamuluschoral         IN CNAME  jamuluscentral7.drealm.info   # CENTSERV_GENRE_CHORAL
```

**Comment by corrados** [comment]
Maybe even better, we should omit the jamulus at the beginning (since we have it already in jamulus.io):

```
anygenre1      IN A      62.113.206.102                # CENTSERV_ANY_GENRE1
anygenre2      IN A      62.113.204.131                # CENTSERV_ANY_GENRE2 
anygenre3      IN A      62.113.204.131                # CENTSERV_ANY_GENRE3
rock           IN CNAME  jamuluscentral4.drealm.info   # CENTSERV_GENRE_ROCK
jazz           IN CNAME  jamuluscentral3.drealm.info   # CENTSERV_GENRE_JAZZ
classical      IN CNAME  jamuluscentral5.drealm.info   # CENTSERV_GENRE_CLASSICAL_FOLK
choral         IN CNAME  jamuluscentral7.drealm.info   # CENTSERV_GENRE_CHORAL
```
Additionally, as seen in my new list, the entry "pure jamulus" is not needed, actually.

**Comment by pljones** [comment]
> Maybe even better, we should omit the jamulus at the beginning (since we have it already in jamulus.io):

Yes, that's the what I was thinking, too.

I take it your DNS would CNAME _all_ the entries to jamulus.io for resolution, rather than leaving them as they are, once the new entries are in place?

**Comment by gilgongo** [comment]
OK I've added those to the domain now. .

**Comment by corrados** [comment]
Thank you :-). I'll change the code now and try out if it all works as expected.

**Comment by corrados** [comment]
I just tested it. The entries with the fixed IP address work but pljones Central server do not. I assume the syntax of the lines with the CNAME is somehow incorrect. Maybe the syntx for CNAME entries is differently defined for your provider? Can you please check?

**Comment by corrados** [comment]
Oh, it seem that it is not your fault. This is what I get when I try out the addresses in the command line:

traceroute jamuluscentral4.drealm.info
traceroute: unknown host

@pljones, can you please activate these URLs on your side?

**Comment by gilgongo** [comment]
Oh BTW can you confim that the following will be correct for the next server documentation release?

| Genre |   Server address           |
|-----------|------------------|
|**Any Genre 1** |`anygenre1.jamulus.io:22124`|
|**Any Genre 2** |`anygenre2.jamulus.io:22224`|
|**Any Genre 3** |`anygenre3.jamulus.io:22624`|
|**Genre Rock** |`rock.jamulus.io:22424`|
|**Genre Jazz** |`jazz.jamulus.io:22324`|
|**Genre Classical/Folk** |`classical.jamulus.io:22524`|
|**Genre Choral/Barbershop** |`choral.jamulus.io:22724`|

**Comment by corrados** [comment]
Yes, this is correct.

**Comment by softins** [comment]
CNAME records need a dot at the end of the target name, so that it is an absolute name, not relative to the current domain.

So:
```
rock           IN CNAME  jamuluscentral4.drealm.info
```
would return `jamuluscentral4.drealm.info.jamulus.io`, and it needs to be:
```
rock           IN CNAME  jamuluscentral4.drealm.info.
```

**Comment by ann0see** [comment]
Closed via https://github.com/jamulussoftware/jamulus/commit/72ff3ae2c199d891c59863070b510107be9e487a
