### ISSUE TITLE
Remove .travis.yml

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#921]
After the move of the repo, the Travis check does not work anymore. Since we have the CodeQL, it is not necessary anymore anyway. So, this file should be removed. @ann0see You already asked the question about this file in one of your pull requests. And yes, I agree with you, we should remove that file. Do you agree?

**Comment by ann0see** [comment]
Yes. We can remove it (I don't see any benefits from leaving this enabled) b

**Comment by corrados** [comment]
Ok, thanks for the feedback. So, I'll remove that file now.
