### ISSUE TITLE
Change request: Mark recording active status really outstanding

### ISSUE THREAD

**Issue by Hk1020** [jamulussoftware/jamulus#925]
I'd like to suggest a GUI change. Currently, if there is an active recording it is shown to the user by only a small label in the status line. I think this gets overlooked by almost everyone. I'd like it to look like something similar to when `mute myself` is active. Recording is something that everyone should be aware of. You are not allowed to secretly make audio recordings. So I think this should really stand out.

**Comment by ann0see** [comment]
I agree, that recording should be made more visible (It could be a privacy issue). The mute myself bar is very visible but adding two bars in the UI might look odd. @jamulussoftware/designers what do you think about this?

**Comment by dcorson-ticino-com** [comment]
I would use the red bar for a recording message and show mute myself differently.
Ann0see did you get my jamulusUI working? There I left the red bar, but think it is superfluous as the mic is the indication of sound on.  Probably the input levels should not be shown in that case too.

**Comment by pljones** [comment]
It wouldn't be a good idea to have the two indicators looking the same.

It also wouldn't be a good idea to have more screen estate taken up by by the recording indicator.

The user has control over the "Mute myself" indicator -- so it makes sense for it to take up screen estate as they can turn it off.

The idea with the recording indicator was for it to be present, to change the layout, but not to disturb things too much.

I don't think there's an option to add formatting into the title of the group box around the mixer.  But I could be wrong there.  If there is, it might be possible to make it stand out more without clashing or taking up more space.

**Comment by DavidSavinkoff** [comment]
There is plenty of room for a Recording (or Record or Rec.) LED at the far left side of the Jamulus client below the jamulus cloud insignia. Traditionally the red led would be either On (red) or Off (black).

**Comment by dcorson-ticino-com** [comment]
After thinking about this for I while I think that it is important that the recording indication is connected to the server used and not the client application.  Thus I think the best place for the indication is where it is now, in the frame of the audiomixerboard.
I would suggest a slowly blinking red led next to the recording text.
If that is not possible an indication in the user portion of the display would need an explaining text such as "recording activated on the server".
I would have some time Wednesday-Thursday to take a closer look and implement this if it is desired.

**Comment by pljones** [comment]
> 
> 
> There is plenty of room for a Recording (or Record or Rec.) LED at the far left side of the Jamulus client below the jamulus cloud insignia. Traditionally the red led would be either On (red) or Off (black).

The left side is about what the client is doing.  The client is not recording, therefore it wouldn't indicate correctly what was happening.  The reason for the current location in the same place as the server name is it's that server that's recording.

**Comment by DavidSavinkoff** [comment]
The far left already has two LEDs, one for the server buffer and the other
for the client buffer.
I mentioned the far left side because there is cordoned off space there,
that is suitable for odds and ends.
Note that the recording LED must be viewable from the client because
the server is only viewable by the remote computer running it
(and is probably running headless). Note that the recording is only
accessible at the server. Some musicians may not wish to jam on
a recording server for legal reasons.

**Comment by Hk1020** [comment]
> The far left already has two LEDs, one for the server buffer and the other for the client buffer. I mentioned the far left side because there is cordoned off space there, that is suitable for odds and ends. Note that the recording LED must be viewable from the client because the server is only viewable by the remote computer running it (and is probably running headless). Note that the recording is only accessible at the server. Some musicians may not wish to jam on a recording server for legal reasons.
> […](#)
I don’t know what you have in mind but a tiny LED is not sufficient. It should be something really obvious, which is why I suggested the mute myself bar. Doesn’t have to be like this exactly but it has to be really obvious to anyone using the client.

**Comment by pljones** [comment]
> The far left already has two LEDs, one for the server buffer and the other for the client buffer.

No, it has a "Delay" LED and a "Buffer" LED.  These relate to the client side experience and can, to a certain extent, be controlled by changes made by the client user, through the settings panel.

> I mentioned the far left side because there is cordoned off space there, that is suitable for odds and ends.

Putting "odds and ends" somewhere ends up with a confusing user interface that's hard to understand.  Not a clear design.

> Note that the recording LED must be viewable from the client

The recording indicator is viewable from the client now, of course.

> Some musicians may not wish to jam on a recording server for legal reasons.

That's why there's a recording indicator next to the server details.

**Comment by ann0see** [comment]
> Ann0see did you get my jamulusUI working?

@dcorson-ticino-com : yes. It did work. We should open an issue on this and discuss it there ;-). 

Concerning the topic of this issue, I will have a thought too later.

**Comment by dcorson-ticino-com** [comment]
`It also wouldn't be a good idea to have more screen estate taken up by by the recording indicator.`
pljones gave me the idea.  I am implementing changing the title and border of the mixing table to red during recording.
Existing visual elements are used.  I think it will be very visible, but not disturbing as a small blinking indicator might be.

**Comment by softins** [comment]
Is it possible to have the indicator where it is now, but make it white text on a red background, or something else that makes it stand out? I'm not yet sure what flexibility there is in Qt.

**Comment by dcorson-ticino-com** [comment]
My first attempt at doing something useful for Jamulus is now in my fork at 
https://github.com/dcorson-ticino-com/jamulusUI-01

I have implemented the bigger recording indicator in my new UI, but the MixerBoard is identical to that in the master.  If this recording indicator finds approbation I will make a master clone and implement it there, now knowing how to do it.

I spent an inordinate amount of time trying to get the dynamic styles of Qt to work, without success.  So I have taken the sledge hammer out and use stylesheets.
The style sheet for the Mixerboard is set with the routine SetMixerBoardDeco in clientdlg depending on the recording state and the skin used.  The routine is called on recording state change, deconnect and skin change.  It works, but I don't like the fact that it appears to be very slow.  Is Qt interpreted? I don't see any other reason why it should take so long to update the window, at least 1/10th of a second I'd say.  As an event that happens very seldom I would think that can be accepted 'though.

As to the rest of the UI I will open a separate issue.  The idea was to be cleaner, better separate client from server and retain the "Jamulus feeling".

**Comment by Hk1020** [comment]
> 
> My first attempt at doing something useful for Jamulus is now in my fork at
> https://github.com/dcorson-ticino-com/jamulusUI-01
> 

I've just tried it. It's a good start.

> I have implemented the bigger recording indicator in my new UI, but the MixerBoard is identical to that in the master. If this recording indicator finds approbation I will make a master clone and implement it there, now knowing how to do it.

I think the wording stating the fact of recording needs to be stand out more. I accidentally just connected to a server that was recording and at first sight the red frame was just some kind of decoration. I didn't make the connection something special was going on even though I knew why I was trying this.

An idea: Invert the text background to red and use letters in white and bold face. Ideally with double line height. People need to read "recording" immediately without thinking.

**Comment by dcorson-ticino-com** [comment]
So I just pushed a new version.  This time with red background for the text, but no red border.  For me, I think it is good.

**Comment by Hk1020** [comment]
> 
> 
> So I just pushed a new version. This time with red background for the text, but no red border. For me, I think it is good.

Yes this is better. But I shouldn't be the only one to comment.

**Comment by softins** [comment]
> > So I just pushed a new version. This time with red background for the text, but no red border. For me, I think it is good.
> 
> Yes this is better. But I shouldn't be the only one to comment.

I can pull and build it tomorrow. You could also post a screen shot here for comment.

**Comment by dcorson-ticino-com** [comment]
Screenshots of recording and not recording.

![Recording](https://user-images.githubusercontent.com/64357360/106958115-37174200-6739-11eb-951a-4f0234f520a4.JPG)
![NotRecording](https://user-images.githubusercontent.com/64357360/106958139-3e3e5000-6739-11eb-9a68-f7ab6f0ba04d.JPG)

**Comment by softins** [comment]
Does Qt allow just having the “[RECORDING ACTIVE]” part in red?

**Comment by dcorson-ticino-com** [comment]
> Does Qt allow just having the “[RECORDING ACTIVE]” part in red?
Unfortunately no, also no bold. The title formatting is very limited.
I would have referred that too.

**Comment by Hk1020** [comment]
> 
> 
> > Does Qt allow just having the “[RECORDING ACTIVE]” part in red?
> 
> Unfortunately no, also no bold. The title formatting is very limited.
> I would have referred that too.

I don't know anything about qt really but I think you need to use a different control as the QGroupBox which is currently being used. I just saw that when I tried myself to make this bold. You can set the whole title in bold but I didn't like the result when I tried. Google suggested QLabel would allow more detailed html formatting.

**Comment by dcorson-ticino-com** [comment]
The mixer table is in a QGroupBox and using it's title means we are using the screen real estate to best advantage.
I don't think it is worth redeveloping the entire interface or expending more screen space when we now have a good solution.
Having the Server name on the red background too just makes the indication more obvious, which was the goal.
