### ISSUE TITLE
Favicon for a Plucked Psaltery

### ISSUE THREAD

**Issue by ArianeKl** [jamulussoftware/jamulus#940]
I would like to have added a favicon for a plucked psaltery - please find attached the favicon which I have created from my own photo of my plucked psaltery - thank you very much in advance.
Best wishes
Ariane
![Favicon Jamulus_Plucked Psaltery_transparant background_27x27](https://user-images.githubusercontent.com/72198945/106615759-113d4200-656d-11eb-98c2-53fa958a039d.png)

**Comment by ann0see** [comment]
Hi @ArianeKi! 

This sounds interesting. I‘m not sure about the resolution but for me it‘s a bit pixelated. Furthermore, there’s an issue on redesigning these icons. 

Maybe someone of the designers team can comment here?

You must keep in mind that there are already a lot of instruments in Jamulus and I think we must find a way to maybe categorise them. So there might be some open issues here.

**Comment by geheimerEichkater** [comment]
It sure has a very low resolution, the icon is probably going to raise more questions than giving answers. However, the short term solution would be to take this favicon if possible. Maybe in future we could approach the underlying issue with a plan to create proper structure (just to write something down: percussive, monophonic (-> woodwind, brass, solo instrument, …), polyphonic (-> keys, strings, …), voice and allow for individual text input for the individual instrument?

**Comment by ArianeKl** [comment]
If the favicon is not working due to the low resolution (I am sorry but I do not know how to improve it any further since I have been working on it quite long) - I could also use the already existing favicon for a harp - the plucked psaltery is also called lap harp - so it is quite "okay" in an extended sense : )

**Comment by atsampson** [comment]
If possible, I'd suggest using a name that would cover the whole psaltery/zither/autoharp family for this one - the icon would be distinctive for any of those. I'm not sure which term is easiest to translate into the other languages Jamulus supports.

If you did want to make the icon bigger, you could rotate it 45°, and/or shorten the soundbox portion a bit to emphasise the shape. (I did both of those with the mandolin icon...)

There are existing instrument classification hierachies out there - e.g. MusicBrainz has [a very comprehensive one](https://musicbrainz.org/instruments) - but the current approach based on what people are actually playing on Jamulus seems to work fairly well.

**Comment by ann0see** [comment]
I'll close this issue now since the solution is probably to use the harp icon. In long term, this is something for a re-design of Jamulus.
