### ISSUE TITLE
Move installer translation scripts to /src/res/translation/wininstaller

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#944]
Currently the translators need to jump between /windows/ and /src/res/translation this could be unified.

**Comment by jerogee** [comment]
Agreed to have those in one place. I noticed by accident that there was a windows installer that supported translations.

**Comment by softins** [comment]
Is there a tool for managing and editing the `.nsi` files, in a similar way to `lupdate` and `linguist` for Qt? Wondering what info I need to give to a new translator about how to manage these files.

**Comment by ann0see** [comment]
There's no tool I know about to edit these files. They're just plain text files. Have a look at the installerlng.nsi file. This one can be edited to add a new language
