### ISSUE TITLE
Qt 5.15 breaks macOS < 10.13 support

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#959]
**Describe the bug**
According to https://doc-snapshots.qt.io/qt5-5.15/macos.html and a user which beta tests the GitHub actions created macOS binaries they do not work on his macOS 10.12 machine
**To Reproduce**
Download a macOS binary from my repo (releases page) and run it on an old version of macOS

**Expected behavior**
The new release process should not break support for old macOS versions.
**Screenshots**
None

**Operating system**

macOS (binary from GitHub actions)

**Version of Jamulus**

Unrelated

**Additional context**
Should be possibly solved by e.g. using aqt on macOS and installing aversion of qt <5.15

The new binaries for windows should also be tested (e.g. Windows 7)

**Comment by ann0see** [comment]
Maybe this fixes it (not yet tested the binary since I don't have a mac with this old os)

```bash
#!/bin/sh -e

# Sets up the environment for autobuild on macOS

# Please run this script with the first parameter being the root of the repo
if [ -z "${1}" ]; then
    echo "Please give the path to the repository root as second parameter to this script!"
    exit 1
fi

cd "${1}"

echo "Install dependencies..."
#brew install qt5
#brew link qt5 --force
python3 -m pip install aqtinstall

python3 -m aqt install --outputdir /usr/local/opt/qt 5.12.9 mac desktop
# add the qt binaries to the path

export PATH=/usr/local/opt/qt/5.12.9/clang_64/bin:"${PATH}"

sh "${1}"/mac/deploy_mac.sh

# Move the created installer to deploy
cp "${1}"/deploy/Jamulus-*installer-mac.dmg "${1}"/deploy/Jamulus-installer-mac.dmg
```

**Comment by ann0see** [comment]
Note for other readers:

Still waiting for an answer of the beta tester. But I'm quite sure it works. For the binary see: https://github.com/ann0see/jamulus/releases/tag/latest

The above code will become a PR once I receive an answer.

**Comment by 38github** [comment]
Does this mean that a friend of my who use macOS 10.10 will be able to finally install Jamulus?

**Comment by ann0see** [comment]
I hope so! But we can't be sure
