### ISSUE TITLE
Add version string to flatpak build

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#965]
Currently the automatic flatpak build doesn't have a version number. @nefarius2001 do you want to fix it (probably just a small change)?

**Comment by nefarius2001** [comment]
can do.
should it be in the filename only, or also in the package description?
I have no experience with flatpack so far, anyone who can give a hint what is important?

**Comment by ann0see** [comment]
I think file name only is ok. No idea how to do it in the flatpak file.

**Comment by nefarius2001** [comment]
Suggestion:

The "app-id": "io.jamulus.Jamulus"  in the manifest will stay unchanged
I will rename the input parameter "bundle" for the github-action https://github.com/bilelmoussaoui/flatpak-github-actions as follows:
"io.jamulus.Jamulus.flatpak" => "jamulus_${{jamulus_buildversionstring}}.flatpak"

**Comment by ann0see** [comment]
Just found out: There's a PR pending for flathub. Maybe this isn't needed anymore then. 

https://github.com/jamulussoftware/jamulus/issues/803#issuecomment-774684410

**Comment by nefarius2001** [comment]
does that mean flatpak can be disabled as a total?

**Comment by ann0see** [comment]
Probably yes. So I will close this issue and re-open it if flathub doesn't accept it.
