### ISSUE TITLE
Fancy Skin Background is full of compression artifacts

### ISSUE THREAD

**Issue by passing** [jamulussoftware/jamulus#970]
**Describe the bug**
The background picture of the fancy skin looks quite bad and when increasing the window size that gets even worse

**To Reproduce**
Open Jamulus

**Expected behavior**
Shiny look

**Operating system**
Linux

**Version of Jamulus**
Built from latest github source

**Screenshots**
![Screenshot_2021-02-08_22-05-40](https://user-images.githubusercontent.com/8142186/107282298-1281d980-6a5b-11eb-9445-667b9d467cf9.png)

I have already created a new background which takes over the basic design and just gives the panel a nice finish. The new image also has a higher vertical resolution which makes it look much better when increasing the window size:
![Screenshot_2021-02-08_22-09-04](https://user-images.githubusercontent.com/8142186/107282303-157cca00-6a5b-11eb-9192-66d856ff65b0.png)

**Comment by DominikSchaller** [comment]
Thank you! This has been bothering me for a long time now.

**Comment by AndyMcProducer** [comment]
Would be awesome if peeps could just load up their own image, textured background etc. People love to customize, makes it more their own.
Also the HQ background is much nicer looking, looks less cheap now.
Maybe an option to tile or stretch if you did allow any background in the future.
