### ISSUE TITLE
Move ASIO-Setup button above Driver selection 

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#973]
Just had a thought about the ASIO Setup button. The current placement might not be obvious for the user. Therefore I think we should move (and maybe rename it to ASIO device Setup). This might make setting devices up more obvious.

**Comment by pljones** [comment]
The action of the button is dependent upon selection of the device.  I've six ASIO drivers, each with their own set up.  I'd move it above the "Input Channel Mapping", perhaps, but still below the device selection.

**Comment by ann0see** [comment]
Ok. I agree. That's probably a better position. I'll look into it now.

**Comment by ann0see** [comment]
There's still the question about renaming the button. 

> The action of the button is dependent upon selection of the device

Do you have an idea about something generic which clearly tells the (new) user that in order to configure his in/outputs in ASIO4ALL he needs to click on this button?

**Comment by mulyaj** [comment]
I think "ASIO Device Setup" works.  Maybe you could also box the device dropdown and setup together, under the label device? 

Something like this?
![image](https://user-images.githubusercontent.com/63881221/107885015-d8369300-6ec5-11eb-9c34-03c5601b0de4.png)

**Comment by ann0see** [comment]
Yes. This looks logical. Can you open a PR to this branch with these changes?
