### ISSUE TITLE
Mac keyboard controls for window switching not working

### ISSUE THREAD

**Issue by chrisrimple** [jamulussoftware/jamulus#981]
**Describe the bug**
Standard MacOS keyboard shortcuts for window/tab switching don't work in Jamulus

**To Reproduce**
1. Run Mac Jamulus client
2. Open Settings and Chat windows (with or without MacOS Always Tabs enabled)
3. Press standard keyboard shortcuts to switch windows/tabs

**Expected behavior**
Should be able to switch window/tab focus with keyboard shortcuts

**Screenshots**
N/A

**Operating system**
MacOS 10.14.6 Mojave (but likely applies to all)

**Version of Jamulus**
3.6.2

**Additional context**
See Forum discussion @ https://sourceforge.net/p/llcon/discussion/software/thread/7ba976c051/

**Comment by ann0see** [comment]
Not sure, but I think this might be a Qt bug? Just a wild guess: we could try to compile it with a new version of Qt and check if this bug is still there.

**Comment by genesisproject2020** [comment]
What languages are used? When translating there is signs for enabling short cuts.

**Comment by chrisrimple** [comment]
I'm running MacOS and Jamulus in English only, and seeing the problem there.  It may also be a problem in other languages.

**Comment by pljones** [comment]
> When translating there is signs for enabling short cuts.

Just to be clear, if I've understood @chrisrimple, this isn't about application menu shortcuts or hot keys.  This is about standard operating system windowing shortcuts for window navigation - like Command+Tab to switch windows, which aren't part of the application.

@chrisrimple - does this mean _all_ such shortcuts are unavailable or only some?  Are _any_ Command keyboard accelerators available?

**Comment by chrisrimple** [comment]
Keyboard accelerators for menu items are available and working.  Note all menu items have accelerators.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/47258736/108427165-9d986780-71f1-11eb-8533-b4f819c072da.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/47258736/108427190-a6893900-71f1-11eb-91e5-9a9798ef03eb.png">
<img width="176" alt="image" src="https://user-images.githubusercontent.com/47258736/108427217-b012a100-71f1-11eb-8769-d8bdf34fe3be.png">
<img width="306" alt="image" src="https://user-images.githubusercontent.com/47258736/108427251-b99c0900-71f1-11eb-8ccd-3ddc53e6937b.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/47258736/108427278-c28cda80-71f1-11eb-8cd5-697d2a3365c4.png">

And yes, the problem is that Command+Tab will bring up the main Jamulus window, but not others, and Shift+Tab should move among Jamulus windows but does not, etc.

**Comment by pljones** [comment]
Hm.  On Windows, Linux and Android (last time I used it) all the windows were "main" windows: there isn't a master application window with child windows.  Perhaps that's the problem on MacOS.

**Comment by ann0see** [comment]
@chrisrimple Is this fixed now by https://github.com/jamulussoftware/jamulus/pull/1873 ? Could you please re-test and close this issue if it's fixed?

Note: I will unsubscribe from this issue and won’t receive responses from any new comments. If you have any questions concerning maintenance, feel free to ping me.

**Comment by pljones** [comment]
Over a year with no further comments.  Please ping jamulussoftware/maindevelopers if this is still happening.  Closing.

**Comment by chrisrimple** [comment]
@pljones Sorry, I missed this.  Shift+Tab on macOS Monterey (and likely all) is not changing window focus "within" Jamulus, so it's impossible to shift focus between Main, Chat, and Settings with just keyboard.  Not sure that it's worth attempting to fix if no one else has reported it in the last year.

**Comment by pljones** [comment]
@chrisrimple Does Shift+Tab _normally_ switch between separate _application_ windows (not windows within the same application)?  (The Main, Chat and Settings windows are separate in the sense they do not share a parent, I believe.)
