### ISSUE TITLE
submodule checkout broken

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulus#984]
**Describe the bug**
 PR #934 breaks git checkout

**reproduce**
git clone --recurse-submodules https://github.com/jamulussoftware/jamulus >>> FAIL
git clone --recurse-submodules git@github.com:jamulussoftware/jamulus.git >>> FAIL

This is mandatory for github autobuilds (#978), but slipped in Auto-Checks because those do not yet use submodules.

@pljones
What command is your PR aiming for? Can it be improved to fit your needs and have the above still work?

**Comment by hoffie** [comment]
Thanks for the report. I can confirm. I think the `github.com/` part doesn't belong there. Gonna open a PR in a minute.

**Comment by ann0see** [comment]
Thanks @hoffie!

**Comment by pljones** [comment]
I shouldn't try to rush things so much...
