### ISSUE TITLE
Rename pan to balance

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#987]
The Pan slider next to the mixer board in fact isn't one (see the "what's that explanation" and test it). It doesn't move the sound around you as PAN would suggest!

It's more of a slider which balances the left/right input. 

I think now I understand what @drummer1154 ment https://github.com/jamulussoftware/jamuluswebsite/issues/174

**Comment by pljones** [comment]
Pan and Balance refer two different things.  Pan is for positioning a mono signal within a stereo field.  Balance is for mixing Left and Right (or any other two) signals to achieve a stereo position from a stereo source.

**Comment by ann0see** [comment]
I'm not yet used to audio terms but I don't think that this slider moves a mono source in a stereo field like the pan pots do in the mixer board.

**Comment by pljones** [comment]
Most audio engineers would be happy with pan, regardless.  They understand the differences.

**Comment by ann0see** [comment]
The problem is that it did cause confusion: https://github.com/jamulussoftware/jamuluswebsite/issues/174

So it doesn't seem to be clear.

**Comment by pljones** [comment]
The issue appears to start by confusing inputs with outputs, then the input control with the server mix control.  I'd rather that were addressed.  I don't believe changing the word "pan" on the input will address this.

**Comment by ann0see** [comment]
Ok. Will close this and this should probably discussed in an UI related thread.
