### ISSUE TITLE
Do not automatically open Jamulus after install with new installer

### ISSUE THREAD

**Issue by ann0see** [jamulussoftware/jamulus#995]
**Is your feature request related to a problem? Please describe.**
Once a new user without admin privileges installs Jamulus and the installer opens the app, it might run as administrator and therefore not as the person who is currently logged in. This means that the user might think that settings are not saved once he re-opens Jamulus with his user privileges. 
**Describe the solution you'd like**
I suggest not to automatically open Jamulus after the installer ran, although it might be a bit more inconvinient for the user. It would not cause confusion.

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by pljones** [comment]
It should be possible to run without Administrator privs.

**Comment by ann0see** [comment]
Of course it is. But if you tick the run app checkbox since the installer ran as admin, Jamulus will also run as admin.

**Comment by pljones** [comment]
It's possible to _drop Administrator privs_ when spawning another application, as far as I remember.

**Comment by ann0see** [comment]
That would be great! Do you know how to do do it with NSIS?

**Comment by pljones** [comment]
No - but I know Reaper does it and it uses NSIS, AFAIK.

**Comment by ann0see** [comment]
Ok. See my PR. I found a workaround.
