### ISSUE TITLE
Need Indication On Fader Panel That Someone Has Muted Themselves

### ISSUE THREAD

**Issue by maallyn** [jamulussoftware/jamulus#996]
Currently there is an indication that a user has muted you. That is the small light above a fader in your panel.

What I am suggesting is to have an indicator above someone's fader that that person has muted themself. This would be good for the sound engineer or the stage manager or the director or the producer to know that someone has muted themself  and their band is about to go onto the studio. 

With such an indicator, someone can message that person (or tell them verbally in the backstage) to please un-mute themselve before going onto the stage.

Currently, the sound engineer would have to ask the stage manager go into the studio, then un-mute the stage manager and then ask the stage manager to ask the musician to un-mute, which is really hard during a live performance and it may result in the band to have to re-start their piece, which can be frustrating to the overall operation/timing to that evening's show.

For matters of screen/panel real estate, could this be done by re-purposing the current mute light that indicates  that that person is muting you and is not hearing you? I would think that it would be more important for me to know if someone is muted themselves rather than muting me as the sound engineer. A performer can mute the sound engineer and it does not make any difference on the show as the sound engineer is not supposed to be heard on the stage.

**Comment by pljones** [comment]
Muting myself in most jams is personal to me.  No one else is interested in it.  It allows me to play along without them having to be aware of me.  That's its purpose.

**Comment by dcorson-ticino-com** [comment]
Just to be sure I am understanding you correctly, you are talking about the "Mute Myself" feature which stops the stream to the server.  You are not talking about the "Mute" feature which means that a musician will not be heard in your personal mix.
Is that correct ?

**Comment by jugo6** [comment]
Its a balance between privacy (pljones) and being helpful to each other. In a good jam or rehearsal or won't hurt to be open on this, i think.

A "muted myself" indicator would also be helpful in my daily choir rehearsals, as i encourage people to mute themselves if they are adjusting headsets, or want to practice silently. But they forget to unmute :-)

**Comment by pljones** [comment]
Another point I thought of.  It requires both clients - the "self-muted" and the "observer" - _and_ the server to support a new protocol indicator.  If any one of those three doesn't provide support, then the information won't be available.  So not seeing that someone is muted is no indication that they are not muted.  It's simply an indication that you don't know they're not muted.

**Comment by maallyn** [comment]
Folks: To answer Don, this is for Mute Myself, not the one that prevents you from hearing someone else. The current little red lights above the faders on your panel mean that that person is muting you. What I am suggesing is another light above somoene's fader that indicates that they are self muting. This, I feel, is important to the sound engineer and the manager. When you, the performer, is called by the manager to go back stage (from the waiting room); the manager can make sure that you have not muted yourself. While you are in the Backstage, the manager can tell you to please unmute yourself before you are called onto the studio stage itself. I had an incident while I was the sound engineer. I had noticed no sound coming from one of the guitarists. I heard no sound and their VU lights next to their fader on the sound engineer's Jamulus client panel were not flashing, which suggested to me that they were muted. I ended up having to ask the manager to go into the sudio, then I had to mute the manager on the sound engineer's console so they would not be heard on the live stream, and then the manager would ask the person to please un-mute. This is very disruptive during a live performance it was nerve racking to me as the sound engineer. If there is a visual indication that the person is muted prior to them being in the studio (while they are in the waiting room), it would save the sound engineer some grief as the sound engineer already has enough to contend with. This is all about improving the quality of the show and reducing the un-needed stress level of the sound engineer and the other players.

**Comment by nefarius2001** [comment]
I see it also as a balance of privacy, but useful in groups that trust each other. 

How about: new indicator as proposed, and a checkbox in the settings „do not indicate I am muting my stream“ (default unchecked)

**Comment by gilgongo** [comment]
Incognito mode :-)

**Comment by pljones** [comment]
Mark, you have to realise that the vast majority of users on Jamulus _are not in Worldjam_.  They're just using random servers around the internet and have no desire to have - be default - their status shown.

So I'd also be against it being shown by default.

**Comment by DavidSavinkoff** [comment]
Hi,
I would be in favor of this "I've muted myself" indicator if it is a trivial addition (maybe server can detect it by noticing no audio stream).
I do not think there is much of a privacy concern on the part of the person who has muted themself because their slider gives them away.
However, the others have a privacy concern because they don't know if they are being spied on.

**Comment by pljones** [comment]
I still haven't checked how "Mute myself" actually works.  I'd expect the client simply to send silence, whilst mixing its local audio with the received stream, rather than sending the audio and having it mix at the server.  So the server doesn't really know that anything's different - you might have muted in your hardware, in your DAW before getting to Jamulus or in Jamulus - it's still just silence.

**Comment by pljones** [comment]
@DavidSavinkoff 
> I do not think there is much of a privacy concern on the part of the person who has muted themself because their slider gives them away.

I'm not sure what you mean by this.  Can you show it?

**Comment by DominikSchaller** [comment]
I'm also in favor of it, as every chorus director has that problem (is my singer muted, are they just not singing etc.). Actually that happened twice tonight, so would be helpful to be able to give direct feedback to the singer.

I also really don't understand the privacy argument here. What's private about if I press the "mute myself" button or not?

**Comment by DavidSavinkoff** [comment]
> @DavidSavinkoff
> 
> > I do not think there is much of a privacy concern on the part of the person who has muted themself because their slider gives them away.
> 
> I'm not sure what you mean by this. Can you show it?
>
Every person that has joined a given Jamulus session will have a mixer panel slider associated with them. This lets everyone else know that you are there and satisfies privacy laws of all parties (I would expect - IANAL). Furthermore, someone who is listening without their microphone turned on is not part of a conversation (maybe the mixer panel slider associated with them legally makes them part of the conversation because others can see them). Oh, the privacy (<:

**Comment by houbsta** [comment]
> Mark, you have to realise that the vast majority of users on Jamulus _are not in Worldjam_. They're just using random servers around the internet and have no desire to have - be default - their status shown. There are seven days in a week of twenty four hours. Worldjam has this problem with only its users for two and a half hours.
> 
> So I'd also be against it being shown by default.

Fair point, unless in other contexts this is useful. If somebody hits "mute myself" they can then move away from the UI and be playing along and not be heard by everyone else, without realising it. In choirs, big bands, or many other use cases this can be frustrating. Other members of the same jam cannot tell and advise their friend to unmute themselves, because they could have muted themselves by switching off their mic, using a mute on their interface or in a DAW etc.

From a privacy perspective, you can always mute yourself elsewhere than in Jamulus and everyone would be none the wiser. I don't know that it's a privacy concern.

As far as needing new client and server versions, yes that's a given.

**Comment by DominikSchaller** [comment]
FWIW this is also a feature in Zoom and MS Teams where you can see if
someone else is muted or not. In Zoom you actually see four possible states:
- Not connected with sound
- Muted
- Unmuted
- Connected by phone

Obviously the last one is not needed, but the other are helpful. Unrelated,
but it would be amazing to also see the delay of everybody.

**Comment by pljones** [comment]
> Connected by phone

Ah, the days of dial-up IP.  At least it was 56Kb/s by then.  Watch that OPUS codec cry...

OK, so if it's accepted that:
* only clients that have implemented the new feature
* only when connected to servers that have implemented the new feature
* and only for other connected clients that have implemented the new feature
* and not when muted outside Jamulus
* and not when simply not making any sound

then a solution is possible.

Now, if I already have Mute Myself enabled when I join a server, I assume this needs to immediately tell everyone my status?  And it should then only send updates to status?  (Same way "has me muted" does, I guess.)

**Comment by gene96817** [comment]
I'm catching up with the last 12 hours on this thread. I think we are trying too hard and making privacy complicated. Anyone joining a jam session should not expect privacy EXCEPT when it is a closed jam session that they control. If you allow any visitors, then your jam session is not closed.

**Comment by DavidSavinkoff** [comment]
I guess the best mute detector is not hearing someone, or not seeing activity on their Vu meter. Maybe the client Vu meter could indicate a muted status if it was below a certain level for longer that a certain period.

The next thing would be Chat. Maybe Chat (with to:username) could be activated by right-clicking their slider and, selecting a Chat option, tell them to be online (unmute). Maybe the Chat client can highlight* a directed chat message; *or partition it. Chat could be used to send all kinds of status. Chat clients could also not display chats not addressed to them. (more for convenience, not absolute privacy, this is not any more or less private than now)

**Comment by gilgongo** [comment]
Hi all - I'm moving this to a Discussion until such time as we can agree a spec for this to add to the backlog or not (and it also seems like a consideration as part of the ongoing UI discussions too).
