### ISSUE TITLE
Question: Can I have two configurations stored in parallel?

### ISSUE THREAD

**Issue by nefarius2001** [jamulussoftware/jamulus#997]
Hi,

I want to start 
- a first client with normal access to my USB-Audio-Interface
- a second client connected to a "virtual audio cable" (so i can play a virtual keyboard/metronome)

1) I know there is a --inifile-parameter, but have a hard time to find how to use it.
2) Can I give Profile-name & target audio-interface in a parameter/inifile for the "Jamulus"-call?

**Comment by chrisrimple** [comment]
I list the INI file locations for Windows and Mac in my [Remote Band Rehearsals](https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/edit#heading=h.szc2tix6oj9l) doc.  On Windows, you can run multiple instances of Jamulus by changing the Shortcut parameters to use different INI files.  On Mac, you'll need to make a copy of the application, then run each copy from Terminal to specify the INI file that you want.
